### ISSUE TITLE
Add ability to set "service.name" when the telemetry is created from within the Gloo gateway proxy

### ISSUE THREAD

**Issue by htech7x** [solo-io/gloo#10196]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.17.x

### Is your feature request related to a problem? Please describe.

Currently is no way to set the "service.name" when telemetry is created from within the Gloo gateway proxy

One way to change "service.name" is using OTel attributes in the "otel-collector-conf" config map:
```
...
apiVersion: v1
data:
  otel-collector-config: |
...
  processors:
    resource/update-gloo-gateway-service-name:
      attributes:
        - key: "service.name"
           value: "new-name"
           action: update
...
```
But in case if OTel collector is not used "service.name"  can't be changed

It would be nice to be able to specify "service.name" from within the Gloo gateway proxy.
