### ISSUE TITLE
Making possible to override primary hostname in upstream health checks when multiple primaries are defined

### ISSUE THREAD

**Issue by sadieleob** [solo-io/gloo#10203]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.3

### Is your feature request related to a problem? Please describe.

A customer must override the primary host in the upstream **primary** health check. Specifically, the actual requirement is to perform health checks in different hostnames (**static.hosts.healthCheckConfig**) than the ones in the upstream (**static.hosts.addr**). 
As of now, we are able to override the hostname by using the global health check but overriding multiple primary hostnames is not possible. 

Here is an example of what they have:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: us-example-failover
  namespace: app-namespace
spec:
  connectionConfig:
    commonHttpProtocolOptions:
      idleTimeout: 50s
    connectTimeout: 5s
    tcpKeepalive:
      keepaliveProbes: 3
      keepaliveTime: 30s
  failover:
    policy:
      overprovisioningFactor: 600
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: failover.example.com
          port: 443
          upstreamSslConfig:
            secretRef:
              name: tls-secret
              namespace: app-namespace
            sni: failover.example.com
          healthCheckConfig:
            **hostname: failover-hc.example.com**
            portValue: 443
            path: /actuator/health    
        locality:
          region: west
          zone: alpha
  healthChecks:
  - healthyThreshold: 2
    httpHealthCheck:
      expectedStatuses:
      - end: 227
        start: 200
      path: /my/healthz
    interval: 20s
    timeout: 10s
    unhealthyThreshold: 3
  loadBalancerConfig:
    healthyPanicThreshold: 10
  static:
    hosts:
    - addr: primary.example.com
      port: 443
      healthCheckConfig: 
        method: GET
        path: /my/healthz  
    useTls: true
```

Currently, it is possible to override the hostname where the Health Checks are performed for the primary by defining a different hostname in the global health check but when multiple static.host it is not possible:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: example-failover
  namespace: app-namespace
spec:
  connectionConfig:
    commonHttpProtocolOptions:
      idleTimeout: 50s
    connectTimeout: 5s
    tcpKeepalive:
      keepaliveProbes: 3
      keepaliveTime: 30s
  failover:
    policy:
      overprovisioningFactor: 600
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: failover.example.com
          port: 443
          upstreamSslConfig:
            secretRef:
              name: tls-secret
              namespace: app-namespace
            sni: failover.example.com
          healthCheckConfig:
            **hostname: failover-hc.example.com**
            portValue: 443
            path: /actuator/health    
        locality:
          region: west
          zone: alpha
  healthChecks:
  - healthyThreshold: 2
    httpHealthCheck:
      expectedStatuses:
      - end: 227
        start: 200
      path: /my/healthz
      **host: primary-hc.example.com**
    interval: 20s
    timeout: 10s
    unhealthyThreshold: 3
  loadBalancerConfig:
    healthyPanicThreshold: 10
  static:
    hosts:
    - addr: primary.example.com
      port: 443
      healthCheckConfig: 
        method: GET
        path: /my/healthz  
    useTls: true
```

### Describe the solution you'd like

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: example-failover
  namespace: app-namespace
spec:
  connectionConfig:
    commonHttpProtocolOptions:
      idleTimeout: 50s
    connectTimeout: 5s
    tcpKeepalive:
      keepaliveProbes: 3
      keepaliveTime: 30s
  failover:
    policy:
      overprovisioningFactor: 600
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: failover.example.com
          port: 443
          upstreamSslConfig:
            secretRef:
              name: tls-secret
              namespace: app-namespace
            sni: failover.example.com
          healthCheckConfig:
            **hostname: failover-hc.example.com**
            portValue: 443
            path: /actuator/health    
        locality:
          region: west
          zone: alpha
  loadBalancerConfig:
    healthyPanicThreshold: 10
  static:
    hosts:
      - addr: **primary1.example.com**
      port: 443
      healthCheckConfig: 
        method: GET
        path: /my/healthz  
        **host**: **primary1-hc.example.com**
    - addr: **primary2.example.com**
      port: 443
      healthCheckConfig: 
        method: GET
        path: /my/healthz  
        **host**: **primary2-hc.example.com**
    useTls: true

```

### Describe alternatives you've considered

When multiple primaries are defined, the global health check is not possible, so there are no workarounds for this I am afraid.
