### ISSUE TITLE
Health checks for Envoy listeners over TLS and proxy protocol

### ISSUE THREAD

**Issue by sadieleob** [solo-io/gloo#10220]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.17.3

### Is your feature request related to a problem? Please describe.

**Issue**: As of now, it is not possible to configure Kubernetes probes that check the readiness of envoy listeners over TLS and using the proxy protocol. The gateway-proxy image is shipped with wget not curl, and wget does not have the option to send requests with proxy protocol. 

### Describe the solution you'd like

Include in the gateway-proxy image a version of cURL that supports the haproxy proxy protocol.
Example of gateway and gateway-proxy deployment: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  name: gateway-proxy
  namespace: gloo-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      gateway-proxy-id: gateway-proxy
      gloo: gateway-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/gateway-proxy-envoy-config: 27068cd033014d38f6c77522484e957ab25fa1be34a900a1f5241b8f7d62f525
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        gateway-proxy: live
        gateway-proxy-id: gateway-proxy
        gloo: gateway-proxy
    spec:
      containers:
      - args:
        - --disable-hot-restart
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: DISABLE_CORE_DUMPS
          value: "false"
        image: quay.io/solo-io/gloo-ee-envoy-wrapper:1.17.0@sha256:dc0b791aee33eb6b55d78c8a1a015a4fba8a4e576955508f68861c397c05dc54
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - wget --post-data "" -O /dev/null 127.0.0.1:19000/healthcheck/fail;
                sleep 15
        livenessProbe:
          exec:
            command:
            - curl
            - --haproxy-protocol
            - 127.0.0.1:8443/envoy-hc
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        name: gateway-proxy
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - --haproxy-procotol
            - /dev/null
            - 127.0.0.1:8443/envoy-hc
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/envoy
          name: envoy-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10101
        runAsUser: 10101
      serviceAccount: gateway-proxy
      serviceAccountName: gateway-proxy
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: gateway-proxy-envoy-config
        name: envoy-config
---
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8443
  httpGateway:
    options:
      healthCheck:
        path: /envoy-hc
  proxyNames:
  - gateway-proxy
  ssl: true
  useProxyProto: true
```
