### ISSUE TITLE
Support UpstreamGroup  as a backendRefs in the K8s Gateway API

### ISSUE THREAD

**Issue by AkshayAdsul** [solo-io/gloo#10261]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.17 onwards

### Is your feature request related to a problem? Please describe.

Currently we do not support UpstreamGroup  as a backendRefs.
For example if we try below we get a `invalid backend type provided` error.
```
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: gloo-system
spec:
  parentRefs:
    - name: http
      namespace: gloo-system
      sectionName: http
  hostnames:
    - "httpbin.example.com"
  rules:
    - backendRefs:
        - name: my-http-group
          kind: UpstreamGroup
          group: gloo.solo.io
```

### Describe the solution you'd like

Support UpstreamGroup  as a backendRefs.

### Additional Context

UpstreamGroup is used extensively by Gloo Edge customers.
Among other things it make canary releases easier for services that are referenced by multiple routes.
Currently only Xero has asked for it but I am sure other customers will too.
