### ISSUE TITLE
Incorrect propagation of transport socket matches - when a custom SNI is specified in Upstream SSL Config

### ISSUE THREAD

**Issue by DreyfussDaena** [solo-io/gloo#10266]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

gloo-ee-1.17.x

### Kubernetes Version

v1.28.6

### Describe the bug

When a custom SNI is specified in Upstream SSL Config, it is not propagated correctly to transport socket matches.
See example below.
 

### Expected Behavior

sni should be propagated under transport_socket.
as well as the match that is used by the endpoint
transport_socket_matches[i] -> transport_socket

### Steps to reproduce the bug

Steps to reproduce:
 
Apply config:
 
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: httpbin-us
  namespace: gloo-system
spec:
  sslConfig:
    sni: custom.sni.com
  static:
    useTls: true
    hosts:
      - addr: httpbin.org
        port: 443
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: httpbin-us
              namespace: gloo-system
```
 
 
Inspect config dump and see that the sni customization is only applied to the default transport socket config but not to the match that is used by the endpoint.
 
```
cluster:
  "@type": type.googleapis.com/envoy.config.cluster.v3.Cluster
  name: httpbin-us_gloo-system
  type: STRICT_DNS
  connect_timeout: 5s
  dns_lookup_family: V4_ONLY
  transport_socket:
    name: envoy.transport_sockets.tls
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
      common_tls_context: {}
      !! sni: custom.sni.com !! (OK)
  metadata: {}
  load_assignment:
    cluster_name: httpbin-us_gloo-system
    endpoints:
    - lb_endpoints:
      - endpoint:
          address:
            socket_address:
              address: httpbin.org
              port_value: 443
          health_check_config:
            hostname: httpbin.org
          hostname: httpbin.org
        metadata:
          filter_metadata:
            envoy.transport_socket_match:
              httpbin.org;httpbin.org:443: true
  transport_socket_matches:
  - name: httpbin.org;httpbin.org:443
    match:
      httpbin.org;httpbin.org:443: true
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        common_tls_context: {}
        !! sni: httpbin.org !!(DOESN'T APPEAR)
```
