### ISSUE TITLE
Gloo Gateway API CRs should report when they are orphans

### ISSUE THREAD

**Issue by nmnellis** [solo-io/gloo#10276]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.17.x

### Is your feature request related to a problem? Please describe.

When following the hello world example https://docs.solo.io/gateway/latest/quickstart/ i misconfigured the parent reference on the HTTPRoute so that the name did not match the gateway. All logging and statuses or lack there of made it seem like Gloo was happy with the configuration but in reality it did nothing. We should report when you have orphaned objects or bad references.

```yaml
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http
spec:
  gatewayClassName: gloo-gateway
  listeners:
  - protocol: HTTP
    port: 8080
    name: http
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    example: httpbin-route
spec:
  parentRefs:
    - name: http-does-not-exist
      namespace: gloo-system
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - name: httpbin
          port: 8000
```

This was caught by `gwctl`
```
	- HTTPRoute.gateway.networking.k8s.io/httpbin/httpbin: HTTPRoute(.gateway.networking.k8s.io) "httpbin/httpbin" references a non-existent Gateway(.gateway.networking.k8s.io) "gloo-system/http-does-not-exist":
```

### Describe the solution you'd like

Adding a status to Gloo objects that are clearly not being used or have mis configurations. You should know that the parent reference you are making selects nothing.
