### ISSUE TITLE
Easier way to reference Knative services as upstreams for Gloo Gateway

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#1037]
Currently Knative deployed services has a randomly generated k8s service name that makes it hard to predicable reference them from Virtual Services. For example if you deploy `foo` Knative Service you need to reference `foo-xxxxxx` k8s service in virtual service.

Also would be good to simplify destination syntax for knative service destinations from

```shell
SVC_NAME=$(kubectl get svc -l serving.knative.dev/service -o=jsonpath='{.items[0].metadata.name}')
```

```yaml
- matcher:
        prefix: /
      routeAction:
        multi:
          destinations:
          - destination:
              kube:
                port: 80
                ref:
                  name: ${SVC_NAME}
                  namespace: default
            weight: 100
            weighedDestinationPlugins:
              headerManipulation:
                requestHeadersToAdd:
                - header:
                    key: Knative-Serving-Revision
                    value: ${SVC_NAME}
                - header:
                    key: Knative-Serving-Namespace
                    value: default
```
