### ISSUE TITLE
decouple ServiceSpec from Upstreams

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1038]
currently [`ServiceSpec`s](https://gloo.solo.io/v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/service_spec.proto.sk/#servicespec) can only live inside an `Upstream`. that prevents users from being able to route to functions with the `consul` and `kube` destination types.

i propose we extract the service spec into its own crd, with a `selector` or `ref` pointing to the service(s) it describes. for example, the Petstore upstream:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-petstore-8080
  namespace: gloo-system
spec:
  upstreamSpec:
    kube:
      selector:
        app: petstore
      serviceName: petstore
      serviceNamespace: default
      servicePort: 8080
      serviceSpec:
        rest:
          swaggerInfo:
            url: http://petstore.default.svc.cluster.local:8080/swagger.json
          transformations:
            addPet:
              body:
                text: '{"id": {{ default(id, "") }},"name": "{{ default(name, "")}}","tag":
                  "{{ default(tag, "")}}"}'
...
```

would become two objects:

```
# the upstream itself
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-petstore-8080
  namespace: gloo-system
spec:
  upstreamSpec:
    kube:
      selector:
        app: petstore
      serviceName: petstore
      serviceNamespace: default
      servicePort: 8080
...
```

```
# the ServiceSpec attaching itself to the upstream
apiVersion: gloo.solo.io/v1
kind: ServiceSpec
metadata:
  name: default-petstore-8080
  namespace: gloo-system
spec:
  # service is a oneOf which could be type `upstream`, `kube`,  or`consul`
  service:
    upstream:
      name: default-petstore-8080
      namespace: gloo-system
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://petstore.default.svc.cluster.local:8080/swagger.json
        transformations:
          addPet:
            body:
              text: '{"id": {{ default(id, "") }},"name": "{{ default(name, "")}}","tag":
                "{{ default(tag, "")}}"}'
...
```
