### ISSUE TITLE
Upstreams incorrectly report Accepted when no translation has occurred

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#10401]
### Gloo Edge Product

Open Source

### Gloo Edge Version

n/a

### Kubernetes Version

n/a

### Describe the bug

`Upstreams` (and `UpstreamGroups`) will get a status of `Accepted` even if the resource is misconfigured when no translation occurs.

Only when translation happens, by creating the presence of a Proxy, will the status correctly reflect the state of the resource.

### Expected Behavior

Upstreams should not report Accepted status when it has not gone through translation

### Steps to reproduce the bug

Default gloo installation
```
helm install gloo gloo/gloo --namespace gloo-system --create-namespace
```

Create upstream point to incorrect service
```
kubectl apply -f - <<EOF
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: petstore
spec:
  kube:
    serviceName: example-svca-missing
    serviceNamespace: default
    servicePort: 8080
EOF
```

Check the upstream
```
kubectl get us petstore -o yaml
```

See status Accepted:
```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
```

Now create any VS to create a Proxy, which causes Upstream to go through translation
```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: missing-upstream
            namespace: gloo-system
EOF
```

Check upstream status again
```
kubectl get us petstore -o yaml
```

Now it is in a warning state
```
status:
  statuses:
    gloo-system:
      reason: "warning: \n  1 error occurred:\n\t* Upstream name:\"petstore\"  namespace:\"default\"
        references the service \"example-svca-missing\" which does not exist in namespace
        \"default\"\n\n"
      reportedBy: gloo
      state: Warning
```
