### ISSUE TITLE
Allow the setting of disable_shadow_host_suffix_append RequestMirrorPolicy.

### ISSUE THREAD

**Issue by chris530** [solo-io/gloo#10584]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.17

### Is your feature request related to a problem? Please describe.

Customer asked if we can add the ability to set disable_shadow_host_suffix_append  when shadowing traffic. 

### Describe the solution you'd like

 The appending of -shadow to the host header is a issue for them.    They would like the prevention of adding -shadow. 

Using this upstream section to test.

```
      options:
        shadowing:
          upstream:
            name: web-shadow-80
            namespace: gloo-system
          percentage: 100
```

### Describe alternatives you've considered

Tried to remove the -shadow part with a transformation but it does not work.  It looks like the adding of -shadow happens after the transformation filter in envoy. 

### Additional Context

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto
https://docs.solo.io/gateway/latest/resiliency/shadowing/
