### ISSUE TITLE
Routes CRD

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1062]
At present, I have to instantiate the same set of routes in three different virtual services:

1. http - externally accessible
1. https - externally accessible
1. http - internally accessible

Now, I could combine the first and the last, but due to the way in which I generate virtual service definitions, this in inconvenient.

However, the first and second cannot be combined into a single virtual service because they use different protocols.

Your `VirtualService` embeds  one `VirtualHost` which embeds a `[]Route`. 

This means that to provide  **both** http and https access, then one must replicate the `[]Route` definitions in each `VirtualHost`.

Instead of replication, I would suggest allowing a `Route` to be defined as a separate CRD with labels.  Similarly to the way pods are selected for deployments, I would suggest that `Route`s be selected by `VirtualHost`.

Then the `VirtualHost` could use a level of indirection to select all the routes, using the labels.

To be concrete, I suggest adding `routeSelector` field to the `VirtualHost`.  This selector is an object with a set of zero of more key/value pairs, where zero pairs means all routes in the current namespace.

**Comment by ilackarms** [comment]
hey @derrickburns 
the Solo-io team is currently looking at expanding Gloo's Routing API (VirtualService) to better support a self-service model. we believe the solution we're considering right now will handle this use case as well. we are taking a similar approach (i.e. allow users to attach routes from an external crd to a virtual service).  

We'd like to use this thread to discuss the idea in more detail and get feedback from Gloo users.

**Comment by rickducott** [comment]
We've been discussing a few use cases:
* Sharing the same set of routes across virtual services. If the routes are defined in a separate CRD, we can ref that CRD in multiple places. 
* Distributing the ownership of a domain, with guard rails. Admins could be responsible for the virtual service CRDs, but teams can create CRDs that contain a set of routes relative to a particular virtual service route (domain + path). 
  * By locking down virtual services, we could protect against teams contributing invalid virtual services (for instance, bad yaml, remapping paths on a domain, or conflicting plugin configuration); could have simple semantics around rejecting those team-contributed route list and not the overall proxy config.

**Comment by ilackarms** [comment]
The API We are considering will split Routing configuration between two object types: 
- The **VirtualService**, the root Routing object. defines the root RouteTable as well as the domains, SSL configuration, and VirtualHostPlugins that will live on all routes that live on the VirtualService.
- The **RouteTable**, always a child of a VirtualService or another RouteTable. RouteTables are stripped down virtual services which only have access to `Routes`, inheriting configuration from the VirtualService(s) they are imported into.

Using this new model, it will be possible to assemble Routing configurations from modular components. 

This model enables these cases we're targeting:
- the ability to share common route configurations across virtualservices
- the ability to enable self-service for users without access to the full virtualservice in multi-tenant environments

For example, to enable the use case @derrickburns describes above, a single `RouteTable` could be shared between  HTTP and HTTPS VirtualServices. 

An example of such a configuration would look as follows:

```yaml
# HTTP v2 VirtualService:
apiVersion: gateway.solo.io.v2/v2
kind: VirtualService
metadata:
  name: 'http'
  namespace: 'usernamespace'
spec:
  virtualHost:
    domains:
    - '*.mydomain.com'
    - 'mydomain.com'
    routes: 
    - matcher:
        prefix: '/'
      # delegate all traffic to the `shared-routes` RouteTable
      delegateAction:
        name: 'shared-routes'
        namespace: 'usernamespace' 

```
```yaml
# HTTPS v2 VirtualService:
apiVersion: gateway.solo.io.v2/v2
kind: VirtualService
metadata:
  name: 'https'
  namespace: 'usernamespace'
spec:
  virtualHost:
    domains:
    - '*.mydomain.com'
    - 'mydomain.com'
    routes: 
    - matcher:
        prefix: '/'
      # delegate all traffic to the `shared-routes` RouteTable
      delegateAction:
        name: 'shared-routes'
        namespace: 'usernamespace' 
  sslConfig:
    secretRef:
      name: gateway-tls
      namespace: gloo-system

```

```yaml
# the RouteTable shared by both VirtualServices:
apiVersion: gateway.solo.io.v2/v2
kind: RouteTable
metadata:
  name: 'shared-routes'
  namespace: 'usernamespace'
spec:
  routes: 
    - matcher:
        prefix: '/some-route'
      routeAction:
        single:
          upstream:
            name: 'some-upstream'
     ...
```

In the above example, we *delegated* the path `/` to the `shared-routes` **RouteTable**. All traffic handled by the VS with prefix `/` (all traffic) will be routed according to the routes defined in `shared-routes`.

RouteTables can delegate to other RouteTables, allowing a tree of configuration to be constructed. Delegated routes can easily be switched between RouteTables, enabling blue-green control of routing configuration.

Access to Route tables can be restricted using RBAC. For example, a route table placed in a `admin` namespace could hold the root prefixes which delegate to a `dev` and `prod` namespace. RouteTables in the `dev` and `prod` namespaces can further delegate their own path prefixes. 

When a RouteTable is delegated by a VirtualService (or another RouteTable), its routes are added as children to the provided prefix.

For example, the following 1 VirtualService and 3 RouteTables:

```
virtualService: mydomain.com
match: /a
delegate: a-routes 
---
routeTable: a-routes
match: /1
delegate: 1-routes
match: /2
delegate: 2-routes
---
routeTable: 1-routes
match: /foo
destination: foo-svc
match: /bar
destination: bar-svc
----
routeTable: 2-routes
match: /baz
destination: baz-svc
match: /qux
destination: qux-svc

```

Would produce the following route config for `mydomain.com`:

```
/a/1/foo -> foo-svc
/a/1/bar -> bar-svc
/a/2/baz -> baz-svc
/a/2/qux -> qux-svc

```

In our initial release of this API, we are planning on applying the following restrictions to **delegated routes**, though these may be relaxed in the future:

- delegate routes must use `prefix` path matchers
- delegated routes cannot specify header, query, or methods portion of the normal route matcher.
- routePlugin configuration will be inherited from the parent but can be overridden by the child

In particular we are still working out:
- how to name the `RouteTable` object (this is the best name we've got so far, have also considered `Delegate`, `VirtualRouter`, and `RouteList`)
- whether it's important to allow delegate routes to specify matcher config other than `prefix`. 
    - our concern here is error-prone / unexpected behavior when a child route specifies a conflicting matcher (such as header, query param, or method) with a parent

the Solo team is excited about the new features that will be possible via this API. we're looking for feedback about this proposal, so please comment if you have an opinion to share!
