### ISSUE TITLE
prefixRewrite.prefixRewrite is confusing

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1083]
currently, in the YAML form of the `RoutePlugin` API, `prefixRewrite` is the name of the plugin, as well as the key in the plugin config.

What this means is that, to configure the PrefixRewrite plugin, I need to provide the config:

```yaml
routePlugins:
  prefixRewrite:
    prefixRewrite: asdf 
```

This is confusing and has led to easy mistakes. We should refactor this API to:

```yaml
routePlugins:
  prefixRewrite: asdf 

```

*note*: this will be a breaking change, and require updates to Gloo docs as well
