### ISSUE TITLE
usign root to access default user installation (Error checking for existing knative installation namespaces is forbidden)

### ISSUE THREAD

**Issue by amir3code** [solo-io/gloo#1106]
I've installed `k3s` as a sudo user and then I switched to root user and tried to install gloo knative using:

    glooctl install knative

But it gives me this error:

    Error: checking for existing knative installation: namespaces is forbidden: User "system:serviceaccount:default:svcs-acct-dply" cannot list resource "namespaces" in API group "" at the cluster scope

How can I make it correct?

**Comment by ilackarms** [comment]
@amir3code the error you are seeing is an authorization error.

`glooctl` uses your default kubeconfig and current `context` to run `kubectl` commands. it looks like you've authenticated as the `system:serviceaccount:default:svcs-acct-dply` User.

There are 3 ways to fix this error:
- add the relevant permissions (essentially `cluster-admin` here) to the `system:serviceaccount:default:svcs-acct-dply` service account.
- use a `kubeconfig` with a cluster-admin user 
- create your cluster with RBAC disabled

**Comment by amir3code** [comment]
Thanks, but please, can you tell me which files I need to edit (cause I dont understand much about kubernetes terminology!).

I created a `config` file using the [this tutorial](http://docs.shippable.com/deploy/tutorial/create-kubeconfig-for-self-hosted-kubernetes-cluster/) and the resulting file is this:

```
root@ubuntu-bionic:~# cat $HOME/.kube/config
apiVersion: v1
kind: Config
users:
- name: svcs-acct-dply
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InN2Y3MtYWNjdC1kcGx5LXRva2VuLTdzZ2N3Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InN2Y3MtYWNjdC1kcGx5Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMGQ3MzI4MWItY2UxMi0xMWU5LTgzMTctMDIxOWQ2M2M5NGM4Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6c3Zjcy1hY2N0LWRwbHkifQ.b7Y4vCJ8YL-FiY-QB-er0IXFEMZzrz1tTY9UkWW_Ft8C6er_fquWOHmfMq6h1uX4FkEvPEq6N8d_o4b8pYfP83oDLv6vulETFy5yKnEE5UFAwTNmLy1bhQW8R-3MI4OSKrXj5-4VikFni76mSoCiRKzqZEO89SUkpAxL9YYJMGhoH7tvGV4rx28UTWuHix3P1zQmBNra4Z-5hcHihonLvsvvWZxiARla-o9z8MaADPd_KDzIR14k8-4OTd59NSaIhBRib2qBykfDeWIJHFNzZJS3_rMzr_c_S99nMU8kwltPiZrgzPYESFCZ_-mTKsHum-HV_nfqxZNpSX0TD613Lw
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWekNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFUyTnpBNU5EUXlNREFlRncweE9UQTRNamt4TmpBd01qQmFGdzB5T1RBNE1qWXhOakF3TWpCYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFUyTnpBNU5EUXlNREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk1ka2IxSkR4TFRpbW1uQ3lsTGUyakR5MVZ2WGxucnEwc0YrcnBlTndFRXEKbWNpc0VlaExrckJ0dnA4VzRQYnRSTENNcWd4bzBQNFVyQ0MrdHlEYi9jK2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSURTd1lFZUFkY0x1CjU5OWoxcENZRjBTUm82MUhJQmpyelRNc2FJV00wT08xQWlFQWhoR0hGM0xCYlRmRWdqRmdodkRMenZRcE9VcDYKZHZQSHl1MGRIOVpMQlQ4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://localhost:6443
  name: self-hosted-cluster
contexts:
- context:
    cluster: self-hosted-cluster
    user: svcs-acct-dply
  name: svcs-acct-context
current-context: svcs-acct-context
```
Which part should I edit? and what to add? :)
Thanks again!
