### ISSUE TITLE
Aws Secret is structured awkwardly

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1136]
Proposing a breaking change:

Right now aws secrets created by `glooctl` and read by gloo have this form:
```yaml
aws:
  accessKey: key
  secretKey: secret
```

I would like to remove the unnecessary aws outer nesting, as it prevents us from leveraging these secrets idiomatically in our helm charts, i.e. by either:

```yaml
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: secretKey
```
if we flattened our secret (removed the outer aws nesting)

or, even better:
```yaml
    envFrom:
    - secretRef:
        name: test-secret
```
if we used my preferred secret structure:
```yaml
awsAccessKeyId: key
awsSecretAccessKey: secret
```
