### ISSUE TITLE
A virtual service is still accessible (using curl as an example) even if it has been deleted

### ISSUE THREAD

**Issue by fmedery** [solo-io/gloo#1245]
When deleting an virtualservice `curl $(glooctl proxy url)/path` still works

How to reproduce:
* create a virtualservice
* create a route
* curl will successfully access upstream 
* delete the virtualservice
* curl will still successfully access vs even if it has been deleted 

Environment:
* EKS 1.13
* App mesh
* glooctl version  {"version":"0.19.1"}                                                                                                                              

gloo check:
```
glooctl check

Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
No problems detected
```

**Comment by fmedery** [comment]
It seems to work now. It took a long time before updating the config.

**Comment by rickducott** [comment]
I'm able to reproduce this. Some steps:

```
  - apply: https://raw.githubusercontent.com/solo-io/solo-docs/master/gloo/docs/static/content/upstream.yaml
  - apply: https://raw.githubusercontent.com/solo-io/solo-docs/master/gloo/docs/gloo_routing/virtual_services/routes/matching_rules/path_matching/prefix_vs.yaml
  - curl:
      path: /posts/1
      statusCode: 200
      host: foo
  - delete: https://raw.githubusercontent.com/solo-io/solo-docs/master/gloo/docs/gloo_routing/virtual_services/routes/matching_rules/path_matching/prefix_vs.yaml
```

At this point, there are no virtual services in the system, so you would expect retrying that curl would fail with a 404. However, it continues returning 200. Even after restarting Envoy, it continues returning 200. 

Looking at the crds, there are no proxy CRDs. In this case, it seemed like Gloo continues serving the last XDS config with the route. To have envoy stop serving the route that was deleted, Gloo needs to be restarted after the last virtual service is deleted, and then Envoy needs to be restarted. At this point, the curl returns a connection refused.
