### ISSUE TITLE
use shortcodes to identify api links for better docs version management

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1248]
https://github.com/solo-io/gloo/pull/1223 introduced a `protobuf` shortcode

- [x] expand its use to replace all `Rel` links to api docs

- [x] update solo-kit to produce an optional data/ProtoMap.yaml file for use in mapping links to protos by the protos name

`ProtoMap.yaml` format
```yaml
Apis:
  cors.plugins.gloo.solo.io:
    links: # we may want to link to old versions of the apis, so provide these as a map
      latest: "api/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/cors/cors.proto.sk/"
      v0: "api/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/cors/cors.proto.sk/v0"
    group: gloo # may be useful for product-specific styling, link, or mouse-over
```
