### ISSUE TITLE
Helm install fails

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1287]
```
helm install solo/gloo --dry-run
```

produces deployments  with `securityContext` like:

```
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: %!!(MISSING)f(json.Number=)
          capabilities:
            drop:
            - ALL
```

However, this:

```
helm fetch solo/gloo
tar -xvf gloo-0.20.1.tgz
helm template  gloo
```

produces deployments  with `securityContext` like:
```
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10101
          capabilities:
            drop:
            - ALL
```

What am I missing here?
