### ISSUE TITLE
Setting static nodePort in helm chart

### ISSUE THREAD

**Issue by george-oakling** [solo-io/gloo#1365]
Hi, we are using gloo as NodePort behind GLBC (google load balancer) as its the only way how to have it correctly set up in GKE with global anycast IP. For testing development we use kind (https://kind.sigs.k8s.io/) cluster which have a possibility to expose nodePort services on localhost. For that case, it would be useful to have a possibility to setup a static nodePort for the service, which will match the one in kind configuration. Would you mind adding this to the helm chart? Would be much appreciated :)

**Comment by marcogschmidt** [comment]
Hi @george-oakling, I assume are referring to the `gateway-proxy-v2` service (i.e. the Gloo Gateway service). In that case we already expose a Helm value to determine the service type (see the `gatewayProxies.NAME.service.type` Helm variable documented [in this section of our docs](https://gloo.solo.io/installation/gateway/kubernetes/#list-of-gloo-helm-chart-values)). 

If you are using the default gateway-proxy name (i.e. you are not overwriting it), you can use these Helm value overrides to make `gateway-proxy-v2` a `NodePort` service: 

```yaml
gatewayProxies:
  gatewayProxyV2:
    service:
      type: NodePort
      httpPort: 80 # set this to the port you want Gloo to listen for HTTP traffic on
      httpsPort: 443 # set this to the port you want Gloo to listen for HTTPS traffic on
```

According to the [Kubernetes docs](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) the service should then be visible as `<NodeIP>:httpPort` and `<NodeIP>:httpsPort` (e.g. `<NodeIP>:80` and `<NodeIP>:443` given the example above).

Can you check if this is what you are looking for?
