### ISSUE TITLE
Minimize and document required permissions for glooctl

### ISSUE THREAD

**Issue by joekelley** [solo-io/gloo#1418]
We should document and validate a minimal role for glooctl users. There might be tiers of user, such as admin (who may (un)install glooctl), developer (who may add virtual services), etc.

Docs issue: https://github.com/solo-io/solo-docs/issues/631

**Comment by joekelley** [comment]
starter role that seems to work for many common actions (barring installation, uninstall):

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glooctl-clusterrole
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "namespaces", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward", "pods/log"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get"]
  - apiGroups: ["gloo.solo.io"]
    resources: ["artifacts", "upstreams", "upstreamgroups", "proxies", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["gloo.solo.io"]
    resources: ["settings"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["gateway.solo.io.v2"]
    resources: ["gateways"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["gateway.solo.io"]
    resources: ["virtualservices", "routetables"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "delete"]
```
