### ISSUE TITLE
controller pods crash when settings is missing `refreshRate`

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1498]
# the bug

when settings is missing `refreshRate`, controller pods fail with `"error in setup: duration: nil Duration"`

**To Reproduce**
1. install gloo
2. 
```
kubectl apply -f - <<EOF
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  devMode: true
  discoveryNamespace: gloo-system
  gloo:
    xdsBindAddr: 0.0.0.0:9977
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}

EOF
```

3. observe crash:

```
NAME                                      READY   STATUS             RESTARTS   AGE
discovery-84c957ddb8-xdzxg                0/1     CrashLoopBackOff   6          6h30m
gloo-66cb5564db-nvcdn                     0/1     CrashLoopBackOff   6          10m
```

## the fix

check for `nil` duration in main setup loop
