### ISSUE TITLE
Knative VirtualService stays in state "Pending"

### ISSUE THREAD

**Issue by TheEvilCoder42** [solo-io/gloo#1544]
Hello

I'm trying to setup a VirtualService to rewrite the Host/authorization field of an incoming request.
Goal is to use sub-domains to route to their respective namespace (a.foo.bar -> app.a.foo.bar) to avoid the need to set a host header.

I installed Knative with Gloo with this command: 
`glooctl install knative --install-knative=true --install-knative-version=0.9.0` 

I then tried to setup the following VirtualService:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: domain
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'a.foo.bar'
    routes:
      - matcher:
          prefix: /
        routeAction:
          single:
            upstream:
              name: gloo-system-knative-external-proxy-80
              namespace: gloo-system
        routePlugins:
          hostRewrite:
            hostRewrite: app.a.foo.bar
```

But the VirtualService never changes it's status from "Pending", so the `knative-external-proxy` never gets any other address than the local and domain address from the Knative Services and is therefore not reachable.

Thanks for any help.
