### ISSUE TITLE
Package global default image tag and repo into values.yaml

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1571]
The current contents of `global` in our `values.yaml`:

```yaml
global:
  glooRbac:
    Namespaced: false
    create: true
  image:
    pullPolicy: IfNotPresent
    registry: quay.io/solo-io
```

We could do better by packaging the tag and repository into the global values so users can selectively override parts of the image chart (e.g., image name) without specifying the same tag over and over again.

This will allow users to render helm charts with multiple gateway proxies without re-defining the `image` tag identically in each gateway proxy
