### ISSUE TITLE
RateLimitBeforeAuth not handled by deprecated config format

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1572]
### Describe the bug
The [recently added](https://github.com/solo-io/gloo/issues/1445) `RateLimitBeforeAuth` setting, which allows performing rate limit check before external auth, does not work for the deprecated rate limiting settings format. For example, this works as expected:

```yaml
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  # [...]
  ratelimit_server:
    rate_limit_before_auth: true
    ratelimit_server_ref:
      name: rate-limit
      namespace: gloo-system
  ratelimit:
    descriptors:
    - key: generic_key
      rateLimit:
        requestsPerUnit: 1
        unit: MINUTE
  # [...]
```

while the following deprecated (`extensions`-based) format does not:

```yaml
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  # [...]
  extensions:
    configs:
      rate-limit:
        rate_limit_before_auth: true
        ratelimit_server_ref:
          name: rate-limit
          namespace: gloo-system
      envoy-rate-limit:
        customConfig:
          descriptors:
          - key: generic_key
            rateLimit:
              requestsPerUnit: 1
              unit: MINUTE
  # [...]
```

### Expected behavior
Both variants should works.
