### ISSUE TITLE
DLP standard regex is broken

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1591]
For example, run through docs written up here https://github.com/solo-io/gloo/pull/1574/files

Notice that this: 
```json
{
   "fakevisa": "4397945340344828",
   "ssn": "123-45-6789"
}
```

gets transformed into this:
```json
{
   "fakevisa": XXXXXXXXXXXXXX828",
   "ssn": XXXX-XX-XX89"
}
```

by this config:

```yaml
    virtualHostPlugins:
      dlp:
        actions:
        - actionType: SSN
        - actionType: ALL_CREDIT_CARDS
```

The standard regex shouldn't be including the opening `"` in the match
