### ISSUE TITLE
UpstreamRef not validated in remote JWKS config

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#1656]
**Describe the bug**
The Gloo remote JWKS configuration requires an upstream reference. If a non existing Upstream is referenced, the Virtual Service and Proxy resources are still accepted. When sending a valid request you get a `Jwks remote fetch is failed` error.

**To Reproduce**
Create a Virtual Service with a remote JWKS configuration that points to a non existing Upstream:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matcher:
        prefix: /
      routeAction:
        single:
          kube:
            port: 8080
            ref:
              name: petstore
              namespace: default
    virtualHostPlugins:
      jwt:
        providers:
          solo-provider:
            issuer: solo.io
            jwks:
              remote:
                upstreamRef:
                  name: foo
                  namespace: gloo-system
                url: http://jwks-server/jwks.json
```

**Expected behavior**
Virtual Service should be rejected. Instead it is accepted:

```

status:
  reported_by: gateway
  state: 1
  subresource_statuses:
    '*v1.Proxy.gloo-system.gateway-proxy-v2':
      reported_by: gloo
      state: 1
```
