### ISSUE TITLE
useProxyProto not working?

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1668]
**Describe the bug**
My envoy proxy fails to forward traffic properly when I enable `useProxyProto` in my Gloo gateways and set the corresponding field for AWS
```
service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

I get `unexpected response status code 502` when accessing the proxy.

Have you seen this before?  

This bug does NOT occur if `useProxyProto` is true and the annotation is NOT applied.  

Version 0.20.8

**Comment by derrickburns** [comment]
@rickducott Has anyone actually used this feature with an AWS nlb or elb? Has it been tested internally?

**Comment by yuval-k** [comment]
Hi @derrickburns I just confirm that this is working as expected.
I added the annotation to the gateway service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
...
  name: gateway-proxy-v2
  namespace: gloo-system
```

I edited the gateway to contain use_remote_address and proxy proto:
```
apiVersion: gateway.solo.io.v2/v2
kind: Gateway
metadata:
...
  name: gateway-proxy-v2
  namespace: gloo-system
spec:
...
  httpGateway:
    plugins:
      http_connection_manager_settings:
        use_remote_address: true
  useProxyProto: true
```
and i can see the correct remote address set in the XFF header and `x-envoy-external-address` header,
