### ISSUE TITLE
ResponseTransformation is not applied on gRPC Services

### ISSUE THREAD

**Issue by CelsoSantos** [solo-io/gloo#1700]
**Describe the bug**

Response Transformations DO NOT apply on gRPC services.

Taking as an example the following response transformation, it will only be applied/executed when the `Upstream` service is a HTTP (1) service. It does not apply/execute on gRPC `Upstream`s:

```
(...)
routePlugins:
  transformations:
    responseTransformation:
      transformationTemplate:
        headers:
          ":status":
            text: "301"
          location:
            text: "https://www.google.com/"
```

**To Reproduce**
(All the code for a reproduction of the issue is available at https://github.com/CelsoSantos/http-grpc-mux)

1. Deploy the Knative `Service` (`kubectl apply -f k8s/service.yaml`)
2. Modify and deploy the `VirtualService` (`kubectl apply -f k8s/virtualservice.yaml`) -- **Don't forget to modify the `Upstream`s names**.
3. Use the sample REST Client code (`rest-client.http`), Postman or `curl` to request both exposed endpoints.
3.1. gRPC will NOT redirect the user to Google
3.2. HTTP, on the other hand, DOES redirect to Google

**Expected behavior**
`responseTransformation`s are applied to both HTTP and gRPC services

**Comment by srenatus** [comment]
I have a strong suspicion that the same applies to `requestTransformations`.

A virtualservice pointing at postman-echo (like in the docs) that massages headers successfully before sending the request to the upstream **does not do that when the upstream is replaced by a gRPC function**. The added headers don't show up in the gRPC call's metadata.

**Comment by srenatus** [comment]
Dug a bit through the code. I believe this could be what happens:

- The gRPC plugin [process the route by emitting a filter config with **name** `io.solo.transformation`](https://github.com/solo-io/gloo/blob/d909a9429324719220b3a7456e1de02b51086391/projects/gloo/pkg/plugins/grpc/plugin.go#L137-L138).
- That name is used as [a key to store its config](https://github.com/solo-io/gloo/blob/d909a9429324719220b3a7456e1de02b51086391/projects/gloo/pkg/plugins/pluginutils/per_filter_config.go#L110).

Now, it could be that this overwrites an existing config from the transformation option (which uses the same key). I haven't verified the order of operations here, so, it's a bit guesswork. Maybe someone who knows better can chime in.

I'd think we could change the key of the gRPC plugin's transformations to, say, `io.solo.transformation.grpc`? Or we attempt to merge the transformation configs when there already is one present under the key in question.

**Comment by stevendanna** [comment]
This is a bit more of a detailed reproduction showing that both requestTransformation and responseTransformations do not work with gRPC upstreams. I have uploaded what I hope is a complete YAML file that you can kubectl apply here:

https://gist.github.com/stevendanna/01bb846698420c1ea7ff5bb1bb3b244d

This uses two echo services, one for HTTP and one for GRPC and each route it both headerManipulation and transformations options set (note, the bug isn't related to the interaction of these two options, I've only include headerManipulation to show that _other_ options work with both HTTP and gRPC as expected):

```
      options:
        headerManipulation:
          requestHeadersToAdd:
            - header:
                key: "req-header-added-by-header-manipulation"
                value: "req-header-1"
          responseHeadersToAdd:
            - header:
                key: "resp-header-added-by-header-manipulation"
                value: "resp-header-1"
        transformations:
          requestTransformation:
            transformationTemplate:
              headers:
                "req-header-added-by-transform":
                  text: "req-header-2"
          responseTransformation:
            transformationTemplate:
              headers:
                "resp-header-added-by-transform":
                  text: "resp-header-2"
```

In the case of HTTP, when we make an echo request, we can see
both the 2 request headers added and 2 response headers added, as expected:

```
> curl -v $(glooctl proxy url)/http-echo | jq .Header
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET /http-echo HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< date: Thu, 11 Jun 2020 11:02:44 GMT
< content-length: 669
< content-type: text/plain; charset=utf-8
< x-envoy-upstream-service-time: 0
< resp-header-added-by-header-manipulation: resp-header-1
< resp-header-added-by-transform: resp-header-2
< server: envoy
<
{ [669 bytes data]
100   669  100   669    0     0   163k      0 --:--:-- --:--:-- --:--:--  163k
* Connection #0 to host localhost left intact
* Closing connection 0
{
  "Accept": [
    "*/*"
  ],
  "Content-Length": [
    "0"
  ],
  "Req-Header-Added-By-Header-Manipulation": [
    "req-header-1"
  ],
  "Req-Header-Added-By-Transform": [
    "req-header-2"
  ],
  "User-Agent": [
    "curl/7.64.1"
  ],
  "X-Envoy-Expected-Rq-Timeout-Ms": [
    "15000"
  ],
  "X-Forwarded-Proto": [
    "http"
  ],
  "X-Request-Id": [
    "1a3f27f1-db5c-42c5-a880-adc546a822ff"
  ]
}
```

For gRPC, however, we only get the headers added via Header manipulation, and are missing the headers that should have been added via the transformation options:

```
$ curl -d '{"msg":"foo"}' -v $(glooctl proxy url)/grpc-echo 
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> POST /grpc-echo HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 13 out of 13 bytes
< HTTP/1.1 200 OK
< content-type: application/json
< x-envoy-upstream-service-time: 6
< resp-header-added-by-header-manipulation: resp-header-1
< grpc-status: 0
< grpc-message: 
< content-length: 2
< date: Thu, 11 Jun 2020 11:04:22 GMT
< server: envoy
<
$ kubectl logs svc/sample-api-grpc | tail -3
--- UnaryEcho ---
metadata: map[:authority:[localhost] accept:[*/*] content-type:[application/grpc] req-header-added-by-header-manipulation:[req-header-1] user-agent:[curl/7.64.1] x-envoy-expected-rq-timeout-ms:[15000] x-envoy-original-path:[/df733aa1/default-sample-api-grpc-50051/chef.sample.more.echo.Echo/UnaryEcho?] x-forwarded-proto:[http] x-request-id:[44a4158d-0598-4d6f-b8db-29bd289829bf]]
request received: message:"foo", sending echo
```

As @srenatus mentions, we think this is because the transformations that get installed by default for the gRPC upstream overwrite the user-supplied transformations.  Looking at `glooctl proxy dump` for the http-echo route we see:

```
                  "per_filter_config": {
                    "io.solo.transformation": {
                      "response_transformation": {
                        "transformation_template": {
                          "headers": {
                            "resp-header-added-by-transform": {
                              "text": "resp-header-2"
                            }
                          }
                        }
                      },
                      "request_transformation": {
                        "transformation_template": {
                          "headers": {
                            "req-header-added-by-transform": {
                              "text": "req-header-2"
                            }
                          }
                        }
                      }
                    }
                   },
```

but for the grpc-echo route:

```
                  "per_filter_config": {
                    "io.solo.transformation": {
                      "request_transformation": {
                        "transformation_template": {
                          "extractors": {
                            "method": {
                              "regex": "([\\-._[:alnum:]]+)",
                              "subgroup": 1,
                              "header": ":method"
                            },
                            "query_string": {
                              "subgroup": 1,
                              "header": ":path",
                              "regex": "/grpc-echo\\?([\\-._[:alnum:]]+)"
                            },
                            "path": {
                              "header": ":path",
                              "regex": "([\\-._[:alnum:]]+)",
                              "subgroup": 1
                            }
                          },
                          "headers": {
                            ":path": {
                              "text": "/df733aa1/default-sample-api-grpc-50051/chef.sample.more.echo.Echo/UnaryEcho?{{ default(query_string, \"\")}}"
                            },
                            ":method": {
                              "text": "POST"
                            }
                          },
                          "merge_extractors_to_body": {}
                        }
                      }
                    }
},
````

**Comment by bdecoste** [comment]
Following doc here: https://docs.solo.io/gloo/latest/guides/traffic_management/destination_types/grpc/

Using this vs:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: grpc
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - store.example.com
    routes:
    - matchers:
      - prefix: /
      options:
        headerManipulation:
          responseHeadersToAdd:
          - header:
              key: added-header
              value: added-value
        transformations:
          responseTransformation:
            transformationTemplate:
              headers:
                foobar:
                  text: fubar
              parseBodyBehavior: DontParse
      routeAction:
        single:
          upstream:
            name: default-grpcstore-demo-80
            namespace: gloo-system
```

And this request:
`grpcurl -plaintext -authority store.example.com $(glooctl proxy address --port http) solo.examples.v1.StoreService/ListItems`

Causes the request to hang. Removing the requestTransformation results in a successful request with the responseHeader added as expected,
