### ISSUE TITLE
Rate Limit Enhancements - Rule Priority and Concurrent Rules

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#1724]
Ticket is to add the following features to Rate Limiting:
* rule priority. I like to think of this as having weighted descriptors
* "concurrent-rules". I like to think of this as `alwaysApply: true` or `weight: infinity`
 
A sample descriptor might look like:
```yaml
descriptors:
 # Rule 1, limit all Instagram requests to 2/min
 - key: type
   rateLimit:
     requestsPerUnit: 2
     unit: MINUTE
   value: Instagram
 # Rule 2, limit all Facebook requests to 8/min
 - key: type
   rateLimit:
     requestsPerUnit: 8
     unit: MINUTE
   value: Facebook
```

With our additions, it may look like:
```yaml
descriptors:
 # Rule 1, limit all Instagram requests to 2/min
 - key: type
   rateLimit:
     requestsPerUnit: 2
     unit: MINUTE
   value: Instagram
   weight: 5           # defaults to 0
   alwaysApply: true   # defaults to false
 # Rule 2, limit all Facebook requests to 8/min
 - key: type
   rateLimit:
     requestsPerUnit: 8
     unit: MINUTE
   value: Facebook
```

When envoy makes a request to the rate limit server it sends a list of `Descriptor`s. If any of the descriptors results in a 429 Too Many Requests, then the entire request results in a 429.

By adding weights to descriptors, we allow for rule priority. For example, if a request were made that matched both of the above rules, only the rate limit response from the largest weight would matter in determining if the entire request is a 429. (in this case, the Instagram rule)

If weights are tied, evaluate all rules with the highest weight (this does not change the current behavior, as omitting the weight in every case means we still evaluate all rules).

---
`alwaysApply` functions as a special kind of override for weights. If `alwaysApply` is set to true, evaluate the rate limit rule regardless of whether or not it has the largest weight. Again, by defaulting to false, we do not change the default behavior.

A rule that has `alwaysApply: true` can have the largest weight (i.e., may be the only rule checked).

---
If a rule is not being considered for rate limiting (i.e. not the largest weight and `alwaysApply: false`) we shouldn't hit the rate limit cache (do not increment count) in Gloo Enterprise's rate limit server code.

---

Implementing these changes requires changes to Gloo Enterprise's rate limit server code, Gloo, and Gloo Enterprise code.

In Gloo, we need to update our public-facing API to support the new fields.

In Gloo Enterprise, we need to translate our new API into Envoy `Descriptor`s to put in the Envoy `RateLimitRequest` struct. We may need to special-case some `generic_keys` for this to work (and handle them in our server code).

In the rate limit server code we need to handle descriptors appropriately (with these special keys), and only make requests to the rate limit cache when required.
