### ISSUE TITLE
Helm chart doesn't gracefully handle gateway proxies without a configmap specified

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#1746]
values override of 
```yaml
gatewayProxies:
  gatewayProxyV2:
    service:
      type: NodePort
      # clusterIP: None
      httpPort: 30123
      httpsPort: 30124
```
produces 
```
Error: render error in "gloo/templates/9-gateway-proxy-configmap.yaml": template: gloo/templates/9-gateway-proxy-configmap.yaml:16:18: executing "gloo/templates/9-gateway-proxy-configmap.yaml" at <$spec.configMap.data>: nil pointer evaluating interface {}.data
```
we should probably check whether `configMap` exists THEN whether `configMap.data` exists, rather than assuming `configMap` is always going to be present
