### ISSUE TITLE
Phantom issue

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1757]
I see this:
```
  gloo:
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404
    xdsBindAddr: 0.0.0.0:9977
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}
  linkerd: true
  refreshRate: 60s
 ```
But when I run `glooctl check`
```
$glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
No problems detected.
```

I believe this error in my Gateway resource was the absence of the `ssl` field.
