### ISSUE TITLE
Single Namespaced Gloo Enterprise docs

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo#1764]
Now that the Grafana and Prometheus charts have been updated to contain RBACs,  there is a new field `grafana.rbac.namespaced` that needs to be set to either `true` or `false` to enable single-namespaced gloo enterprise. This should be reflected in the docs.

**Comment by ashleywang1** [comment]
The gloo page this information should go on is: https://docs.solo.io/gloo-edge/latest/installation/advanced_configuration/multiple-gloo-installs/

There should be a section for Gloo Enterprise users, saying:

For Gloo Enterprise users, the helm chart should look like:
```
settings:
  create: true
  writeNamespace: gloo2
  watchNamespaces:
  - default
  - gloo2
grafana:
  rbac:
    namespaced: true
```
