### ISSUE TITLE
Support for Prometheus Operator using ServiceMonitor resources

### ISSUE THREAD

**Issue by keiransteele** [solo-io/gloo#1773]
**Is your feature request related to a problem? Please describe.**
The Prometheus Operator doesn't take notice of prometheus.io annotations and instead configures scraping by ServiceMonitor resources and in some cases, custom services.

**Describe the solution you'd like**
It would be good if the Helm install had the ability to create ServiceMonitor resources for individual components of Gloo and if the Gloo services had the necessary changes to work with the ServiceMonitor resources.

This is the example config from the Prometheus Operator values.yaml which creates the ServiceMonitor resource:

```yaml
    - name: "gloo-proxy"
      # Service label for use in assembling a job name of the form <label value>-<port>
      # If no label is specified, the service name is used.
      jobLabel: gloo-proxy
      # Label selector for services to which this ServiceMonitor applies
      selector:
        k8s-app: gloo-proxy
      # Namespaces from which services are selected
      namespaceSelector:
        # Match any namespace
        any: false
        # Explicit list of namespace names to select
        matchNames: 
          - gloo-system
      # Endpoints of the selected service to be monitored
      #
      endpoints:
        # Name of the endpoint's service port
        # Mutually exclusive with targetPort
        - port: "http-metrics"
        # Name or number of the endpoint's target port
        # Mutually exclusive with port
        - targetPort: 8081
        # Interval at which metrics should be scraped
          interval: 30s
        # HTTP path to scrape for metrics
          path: /metrics
        # HTTP scheme to use for scraping
          scheme: http
```

This is the service manifest that creates a new service for the Gloo Envoy Proxy. This was the easiest way I found to get it working, I couldn't get it working with the existing service.

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo-proxy
    k8s-app: gloo-proxy
  name: gloo-proxy-metrics
  namespace: gloo-system
spec:
  ports:
    - name: http-metrics
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy-v2
    gloo: gateway-proxy
```
