### ISSUE TITLE
Valid custom logging in virtual service breaks apiserver ui

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#1774]
**Describe the bug**
If you add valid custom logging to a virtual service (see steps below) then then the api server ui becomes unusable because of a popup loop "There was an error retrieving the routes tables list". The only way to get the ui back to functional is to delete the config from the cirtual service. 

Have also seen this popup loop when adding invalid config. 

If you try to add this config to the virtual service via the ui then you get an error stating:
There was an error updating the virtual service.
Failed to parse virtual service gloo-system.petstore from YAML: Failed to parse the edited YAML for resource petstore in namespace gloo-system: error converting YAML to JSON: yaml: line 21: mapping values are not allowed in this context

**To Reproduce**
1. Deploy Glooe 0.21.0
2. Create a simple virtual service with a route (e.g. to petstore)
3. Enabled logging at the gateway:
```yaml
    plugins:
      accessLoggingService:
        accessLog:
        - fileSink:
            jsonFormat:
              clientDuration: '%DURATION%'
              correlationId: '%REQ(X-CORRELATION-ID)%'
              gateway_pod_name: '%DYNAMIC_METADATA(io.solo.transformation:gateway_pod_name)%'
              httpMethod: '%REQ(:METHOD)%'
              path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
              protocol: '%PROTOCOL%'
              requestId: '%REQ(X-REQUEST-ID)%'
              responseCode: '%RESPONSE_CODE%'
              systemTime: '%START_TIME%'
              targetDuration: '%RESPONSE_DURATION%'
              upstreamName: '%UPSTREAM_CLUSTER%'
            path: /dev/stdout
```
4. Add custom logging to the virtual service
```yaml
   virtualHostPlugins:
      transformations:
        responseTransformation:
          transformationTemplate:
            dynamicMetadataValues:
            - key: gateway_pod_name
              value:
                text: '{{ env("POD_NAME") }}'
```
**Expected behavior**
Valid (and invalid) config is handled by the api server ui
