### ISSUE TITLE
Merging VirtualServices prevents Gateway from writing proxy

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#1794]
**Describe the bug**

When the Gateway is about to write a proxy, it checks the resource report for each gateway.solo.io resource (gateways, vs, route table) in order to strip invalid objects from the proxy. 

When VS are merged, a vs is added to the proxy that has no resource report. This causes the above check to fail with an internal error. This prevents the proxy from being written, effectively making virtual service merging unavailable (and breaking to Gloo).

**To Reproduce**

```
glooctl install gateway

kubectl apply -f - <<EOF
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: merge-1
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'

---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: merge2-2
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
EOF
```

See that no proxy is created and `gateway` pod logs:

```
{"level":"error","ts":1575314113.9309113,"logger":"gateway.v1.event_loop.gateway","caller":"syncer/setup_syncer.go:266","msg":"error: event_loop: 1 error occurred:\n\t* failed to add proxy validation results to reports: internal err: missing resource report for source resource\n\n","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gopath/src/github.com/solo-io/gloo/projects/gateway/pkg/syncer/setup_syncer.go:266"}
```

**Expected behavior**

- Having a merged virtual service will not prevent writing the proxy
- The merged virtual service will be validated

**Additional context**

Relevant code:

where we call the proxy reconciler:

https://github.com/solo-io/gloo/blob/feature-rc1/projects/gateway/pkg/syncer/translator_syncer.go#L83

where we return an error (because there is no `resourceReport` for the merged virtual service):

https://github.com/solo-io/gloo/blob/feature-rc1/projects/gateway/pkg/reporting/add_proxy_validation_result.go#L78
