### ISSUE TITLE
Fix Gateway on Health Checks docs page

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/gloo#1818]
https://docs.solo.io/gloo/latest/gloo_routing/gateway_configuration/health_checks/

Health check options are under the `httpGateway` object:

```
spec:
  httpGateway:
    options:
      healthCheck: ...
```
