### ISSUE TITLE
Ingress upstream discovery issue

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1839]
**Describe the bug**
I have a basic Ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    flux.weave.works/antecedent: pomerium:helmrelease/pomerium
    kubernetes.io/ingress.class: gloo
  generation: 1
  labels:
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: pomerium
    helm.sh/chart: pomerium-4.1.1
  name: pomerium
  namespace: pomerium
spec:
  rules:
  - host: linkerd-dashboard-qa1.development.tidepool.org
    http:
      paths:
      - backend:
          serviceName: pomerium-proxy
          servicePort: https
  - host: authenticate.sso.tidepool.org
    http:
      paths:
      - backend:
          serviceName: pomerium-authenticate
          servicePort: https
  tls:
  - hosts:
    - authorize.sso.tidepool.org
    - authenticate.sso.tidepool.org
    - linkerd-dashboard-qa1.development.tidepool.org
    secretName: pomerium-tls
```

`glooctl get upstreams` shows several upstreams, including:

```
| pomerium-pomerium-proxy-443                                     | Kubernetes | Accepted | svc name:      pomerium-proxy                           |
|                                                                 |            |          | svc namespace: pomerium                                 |
|                                                                 |            |          | port:          443                                      |
```

But I get this in the `ingress` log:

```
│ {"level":"warn","ts":"2019-12-08T00:04:33.441Z","logger":"ingress.v1.event_loop.ingress.v1.event_loop.translatorSyncer","caller":"translator/translator_syncer.go:5 │
│ 3","msg":"snapshot 1531226928364265285 was rejected due to invalid config: computing virtual hosts: lookup upstream for ingress pomerium: discovery failure: upstream not found for kube service pomerium-proxy with port {1 0 https}\ningress proxy will not be updated."}
```

What am I doing wrong?
