### ISSUE TITLE
docs: https redirect example

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/gloo#1908]
A common use case is https redirection, add a practical example of how to do it.

put it here: https://docs.solo.io/gloo/latest/gloo_routing/virtual_services/https_redirect/

(Using the docs virtual service as an example)
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: docsmgmt-http
  namespace: docs
spec:
  virtualHost:
    domains:
    - docs.solo.io
    routes:
# use a single route to forward everything to https
    - matcher:
        prefix: /
      redirectAction:
        hostRedirect: docs.solo.io
        httpsRedirect: true
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: docsmgmt
  namespace: docs
spec:
  sslConfig:
    secretRef:
      name: docs.solo.io
      namespace: gloo-system
    sniDomains:
    - docs.solo.io
  virtualHost:
    domains:
    - 'docs.solo.io'
    routes:
    - matcher:
# etc. ( put the real routes here)
```
