### ISSUE TITLE
glooctl install gateway enterprise (1.2.10) creates gateway v2 resources 

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#1972]
I tried once again to migrate from Gloo open source to Gloo enterprise.  No dice.

This time I made sure that I have the correct version of glooctl:
```
glooctl version
Client: {"version":"1.2.10"}
```
When I run 
```
glooctl install gateway enterprise --license-key .....  --values /tmp/gloo-values.yaml  --dry-run >xxxx
```
I get (abbreviated) numerous references to gateway v2, e.g.
```
---
apiVersion: gateway.solo.io.v2/v2
kind: Gateway
metadata:
  name: gateway-proxy-ssl
  namespace: gloo-system
  labels:
    app: gloo
    installationId: 6InF06NgcnfPKPdZKSRY
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "5"
spec:
  bindAddress: "::"
  bindPort: 8443
  httpGateway: {}
  useProxyProto: false
  ssl: true
  proxyNames:
  - gateway-proxy
```

Am I missing something here? I expected to get something compatible with Gloo OSS 1.X.

This is my second attempt and, I must say, I am getting a bit frustrated.

My guess is that `glooctl` is using `helm` under the covers and that helm is attempting to install the wrong version of the helm chart.
