### ISSUE TITLE
ingress returns "Connection refused" for rc7

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#1992]
**Describe the bug**
Accessing service through ingress fails with "Connection refused" for rc7

**To Reproduce**
1. Deploy glooe via helm install glooe glooe/gloo-ee --namespace gloo-system   --set-string license-key=XXX--version 1.0.0-rc7 -f ingress-overrides.yaml
2. Deploy petstore in default namespace and add ingress (per our [docs](https://docs.solo.io/gloo/latest/gloo_integrations/ingress))
3. INGRESS_URL=$(glooctl proxy url --name ingress-proxy)
4. $ curl ${INGRESS_URL}/api/pets
curl: (7) Failed to connect to 10.100.206.41 port 80: Connection refused

**Expected behavior**
Should return petstore result

**Comment by bdecoste** [comment]
$ cat ingress-overrides.yaml 
gloo:
  ingress:
    deployment:
      replicas: 1
    enabled: true
    requireIngressClass: null
  ingressProxy:
    deployment:
      replicas: 1
  gateway:
    enabled: true
  gatewayProxies:
    gatewayProxy:
      service:
        type: ClusterIP
grafana:
  defaultInstallationEnabled: false
prometheus:
  enabled: false
rateLimit:
  enabled: false

**Comment by bdecoste** [comment]
Minikube w/tunnel for LoadBalancer. This works with 1.1.0.

**Comment by kdorosh** [comment]
Reproduced locally, possibly related to envoy error configuration:
```
  ...
   },
      "details": "Didn't find a registered implementation for name: 'io.solo.filters.http.transformation_ee'"
     }
    }
  ...
```

**Comment by kdorosh** [comment]
Tested and confirmed the cause is that the ingress-proxy deployment image is being rendered with `quay.io/solo-io/gloo-envoy-wrapper:1.2.10` instead of `quay.io/solo-io/gloo-ee-envoy-wrapper:1.0.0-rc7`. We need to fix the helm chart to render with the proper image.

**Comment by kdorosh** [comment]
These helm values would work with rc7:
```
gloo:
  ingress:
    deployment:
      replicas: 1
    enabled: true
    requireIngressClass: null
  ingressProxy:
    deployment:
      replicas: 1
      image:                # this is the new block
        tag: 1.0.0-rc7
        repository: gloo-ee-envoy-wrapper
  gateway:
    enabled: true
  gatewayProxies:
    gatewayProxy:
      service:
        type: ClusterIP
grafana:
  defaultInstallationEnabled: false
prometheus:
  enabled: false
rateLimit:
  enabled: false
```

**Comment by kdorosh** [comment]
Same problem also exists for knative on rc7, these helm values will make knative example work on rc7:
```
gloo:
  settings:
    integrations:
      knative:
        enabled: true
        version: 0.10.0
        proxy:
          image:
            tag: 1.0.0-rc7
            repository: gloo-ee-envoy-wrapper
  ingress:
    deployment:
      replicas: 1
    enabled: false
    requireIngressClass: null
  ingressProxy:
    deployment:
      replicas: 1
      image:                # this is the new block
        tag: 1.0.0-rc7
        repository: gloo-ee-envoy-wrapper
  gateway:
    enabled: true
  gatewayProxies:
    gatewayProxy:
      service:
        type: ClusterIP
grafana:
  defaultInstallationEnabled: false
prometheus:
  enabled: false
rateLimit:
  enabled: false
```
The PR to fix will address both the knative and ingress cases
