### ISSUE TITLE
Rate Limiting Gloo API (Enterprise) doc has incorrect yaml 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2065]
Is:

```
rate-limit:
  anonymous_limits:
    requests_per_unit: 1000
    unit: HOUR
  authorized_limits:
    requests_per_unit: 200
    unit: MINUTE
```

Should be:

```
      ratelimitBasic:
        anonymousLimits:
          requestsPerUnit: 1000
          unit: HOUR
        authorizedLimits:
          requestsPerUnit: 200
          unit: MINUTE
```
