### ISSUE TITLE
grpc web doc is incorrect

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2079]
https://docs.solo.io/gloo/0-20/gloo_routing/gateway_configuration/grpc_web/

```
  options:
    grpcWeb:
      disable: true
```

should be

```
    httpGateway:
      options:
        grpcWeb: 
          disable: true
```

Also, the other options use "disabled" instead of "disable"
