### ISSUE TITLE
Documentation for TLS outside of k8s secrets

### ISSUE THREAD

**Issue by CarpathianUA** [solo-io/gloo#2128]
It will be very useful to have clear documentation on how to configure Gloo components together, to be able to use TLS certificates entities (e.g. AWS ACM issued certs) outside of k8s secrets (like for Let's Encrypt ones).

Recently I was able to configure Gloo Gateway Proxy and VirtualService to use HTTPS only listener and AWS ACM issued TLS certificate - thanks to the community for the help!

So here is my case, it can be used as a base for the separate article in Gloo docs for enabling AWS ACM certificates:

1. Set a a needed annotations for Gloo gateway-proxy k8s svc:
```
service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <aws_acm_arn>
service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
```

2. Remove `sslConfig` from VirtualService and Proxy CRDs - it was used for Let's Encrypt certificates previously, and I expected that sslConfig directive is not required anymore for VirtualService and Proxy CRDs. The *major* point here that if you delete a `sslConfig` directive, you also need to change *gateway-proxy k8s svc* to forward traffic from NodePort to `8080` port instead of `8443` since after deletion of `sslConfig` gateway-proxy fallback to listen on `8080` port
3. Check AWS classic LB - it should have has single TLS listener with AWS ACM cert attached and health check set for checking  gateway-proxy service NodePort. 
No HTTP and HTTP listener is not required in my case.
4. LB health check is successful

Thank in advance!

**Comment by marcoferrer** [comment]
I ran into this same issue and found this explanation immensely helpful. 

For anyone else coming across this, as mentioned in step 2, you need to change the backing port for `443` to `8080`. At the official helm chart doesn't let you configure the service backing ports independently of the pod ports (shares same variable). 

There is an ugly workaround you can use in the meantime though.
```yaml
gatewayProxies:
  gatewayProxy:
    service:
      # We are setting the http port to 443 (instead of 80) because since we are terminating tls at the proxy and are
      # not performing a tls pass through, we need the backing port be http 8080
      httpPort: 443       # Backing port is 8080
      # To prevent conflicts with the above change we are making the https port match its default backing port
      httpsPort: 8443     # Backing port is 8443
```
