### ISSUE TITLE
Gloo's Helm chart gateway proxy service template and fixed listeneres

### ISSUE THREAD

**Issue by CarpathianUA** [solo-io/gloo#2129]
Hi, 

What do you think about modifying a Gloo's Helm chart to be able to set needed listeners for gateway proxy LB k8s service via Helm values? My case here that usually users don't need an HTTP listener on internet-facing LBs.

In [8-gateway-proxy-service.yaml](https://github.com/solo-io/gloo/blob/acdccf554dc144d62f7b92c7168bdec46db8bd21/install/helm/gloo/templates/8-gateway-proxy-service.yaml#L24) there is fixed values for HTTP port:

```  
ports:
  - port: {{ $spec.service.httpPort }}
    targetPort: {{ $spec.podTemplate.httpPort }}
    protocol: TCP
    name: http
  - port: {{ $spec.service.httpsPort }}
    targetPort: {{ $spec.podTemplate.httpsPort }}
    protocol: TCP
    name: https
```

It can be templated for an ability to specify via HElm values do we need an HTTP port at all.

I can contribute to the chart, of course. Just want to be sure that my case is relevant.
