### ISSUE TITLE
current helm chart generates bad manifests

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2159]
@kdorosh  There are two bugs in your helm templates that result in bad manifests.

https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml

This file will not work if there is more than one gateway proxy defined with helm2. I did not try it with helm3.

Here is part of the generated output. Notice that the separator `---` is appended to the line `name: envoy-config`.

```
      volumes:
      - configMap:
          name: external-gateway-proxy-envoy-config
        name: envoy-config---
apiVersion: apps/v1
```

You have *another* instance of the same bug at the end of the gateway proxy config map template:
```
          port_value: 19000 # if (empty $spec.configMap.data) ## allows full custom---
# config_map
apiVersion: v1
kind: ConfigMap
```
