### ISSUE TITLE
Add virtual services to Gateway status

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2166]
It would be helpful to see the actual set of VirtualServices that are selected by the Gateway resource.  Perhaps these can be added to the `status` of the Gateway Custom Resource?

**Comment by rickducott** [comment]
Hey @derrickburns I think we can do this today with the route metadata on the proxy CRD:

Here's an example:

```yaml
...
    listeners:
    - bindAddress: '::'
      bindPort: 8080
      httpListener:
        virtualHosts:
        - domains:
          - '*'
          metadata:
            sources:
            - kind: '*v1.VirtualService'
              name: petclinic
              namespace: gloo-system
              observedGeneration: 11
```
