### ISSUE TITLE
Helm Chart nil data bug

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2170]
Gloo OS 1.2.12

create a helm values file with the following overrides:
```
gatewayProxies:
  gateway-proxy:
    gatewaySettings:
      customHttpGateway:
        virtualServiceNamespaces: 
        - '*'
```
render a dry run using `helm`:
```
helm install --dry-run gloo gloo/gloo --namespace gloo-system -f gloo.values.yaml
```

get the following error:
```
Error: template: gloo/templates/9-gateway-proxy-configmap.yaml:15:18: executing "gloo/templates/9-gateway-proxy-configmap.yaml" at <$spec.configMap.data>: nil pointer evaluating interface {}.data
```
