### ISSUE TITLE
vs w/missing upstream causes previously Accepted vs to goto warning for missing upstream

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2228]
1) Create valid vs with existing upstream
2) Create second vs with a non-existent upstream

#2 vs goes to the expected status:

```
+-----------------+--------------+-----------------+------+--------------------------------------+-----------------+------------------------------------+
| VIRTUAL SERVICE | DISPLAY NAME |     DOMAINS     | SSL  |                STATUS                | LISTENERPLUGINS |               ROUTES               |
+-----------------+--------------+-----------------+------+--------------------------------------+-----------------+------------------------------------+
| default         |              | *               | none | *v1.Proxy.gloo-system.gateway-proxy |                 | /api ->                            |
|                 |              |                 |      | Warning: warning:    Route Warning:  |                 | gloo-system.static-pet            |
|                 |              |                 |      | InvalidDestinationWarning. Reason:   |                 | (upstream)                         |
|                 |              |                 |      | *v1.Upstream {missing gloo-system}  |                 |                                    |
|                 |              |                 |      | not found                            |                 |                                    |

```

However, #1 also goes to Warning state for missing upstream:

```
status:
  reason: "warning: \n  Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream
    {missing gloo-system} not found"
  reported_by: gateway
  state: 3
  subresource_statuses:
    '*v1.Proxy.gloo-system.gateway-proxy': {}
```
