### ISSUE TITLE
Gateway feature with Knative

### ISSUE THREAD

**Issue by jjangga0214** [solo-io/gloo#2231]
Hi!

The [official docs](https://docs.solo.io/gloo/latest/installation/knative/#installing-on-kubernetes-with-helm) shows an helm chart value example like this for Knative integration.

```yaml
gateway:
  enabled: false
settings:
  integrations:
    knative:
      enabled: true
      version: {{ . }}  # put installed knative version here!
```

Should the gateway feature be disabled? 
If not, can I use its gateway feature with Knative? 

Thanks.
