### ISSUE TITLE
invalid upstream healthchecks editing accepted with no warning

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2253]
Suspect this is a more general issue to upstream healthchecks.

1) healthChecks accepted via edit but not obvious there is a problem until upstream is inspected. This can happen for several types of invalid config. 

```
  healthChecks:
  - timeout: 10
```

```
$ glooctl get upstream
Error: converting output crd: reading crd spec on resource static-pet in namespace gloo-system into v1Upstream: json: cannot unmarshal number into Go value of type string
```

2) Edit can be accepted and fields are lost without warning:

```
spec:
  healthChecks:
  - httpHealthCheck:
    timeout: 10s
    unhealthyThreashold: 2
```
results in the following with no warning:

```
  healthChecks:
  - timeout: 10s
    unhealthyThreashold: 2
```
