### ISSUE TITLE
Envoy does not support multiple health checks per upstream - needs to be documented

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2267]
This config:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-pet
  namespace: gloo-system
spec:
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /api/pets
    interval: 30s
    timeout: 10s
    unhealthyThreshold: 1
  - healthyThreshold: 2
    httpHealthCheck:
      path: /api/pets
    interval: 20s
    timeout: 10s
    unhealthyThreshold: 2
  loadBalancerConfig:
    healthyPanicThreshold: 0
    roundRobin: {}
  static:
```

Results in:

`[2020-01-23 12:23:21.690][6][warning][config] [external/envoy/source/common/config/grpc_mux_subscription_impl.cc:82] gRPC config for type.googleapis.com/envoy.api.v2.Cluster rejected: Error adding/updating cluster(s) static-pet_gloo-system: Multiple health checks not supported`

https://github.com/envoyproxy/envoy/blob/master/source/common/upstream/cluster_factory_impl.cc#L111
