### ISSUE TITLE
Allow custom status codes to be passed through from upstream

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2270]
Workflow that should be possible

1. Install Gloo
2. Deploy upstream
```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: postman-echo
  namespace: gloo-system
spec:
  static:
    hosts:
    - addr: postman-echo.com
      port: 80
```
3. Deploy VirtualService
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: update-response-code
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
       - prefix: /
      routeAction:
        single:
          upstream:
            name: postman-echo
            namespace: gloo-system
      options:
        autoHostRewrite: true
```
4. Run `curl -v -H "Content-Type: application/json" "$(glooctl proxy url)/get?foo1=bar1&foo2=bar2= ="`

Note the status code:
```
< HTTP/1.1 400 Bad Request
```

This modified from the upstream, which for `curl -v --location --request GET 'https://postman-echo.com/get?foo1=bar1&foo2=bar2= ='` returns:

```
< HTTP/1.1 400 BAD_REQUEST
```

We should allow the original status codes to be passed through.
