### ISSUE TITLE
Enhancement: CRD for GatewayProxy

### ISSUE THREAD

**Issue by derrickburns** [solo-io/gloo#2285]
Have you considered having a CR that declares a gateway **proxy** resource?

```
kind: GatewayProxy
metadata:
   name: gateway-proxy
 spec:
    gatewaySettings: {}
    kind:
      deployment:
        replicas: 1
    podTemplate:
      probes: false
      image:
        repository: gloo-envoy-wrapper
      httpPort: 8080
      httpsPort: 8443
      runAsUser: 10101
    service:
      type: LoadBalancer
      # clusterIP: None
      httpPort: 80
      httpsPort: 443
    # Annotation example: setup ssl with aws cert when service.type is LoadBalancer
    # extraAnnotations:
    #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:EXAMPLE_CERT
    tracing:
    configMap:
      data:
```
