### ISSUE TITLE
Configuring Keep-Alive Duration/Timeout in Gloo

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2297]
Ability to configure the duration till when a connection to the upstream can be kept alive when there is no active traffic streams. We need a similar feature in Gloo.
Envoy seems to already have this feature - https://www.envoyproxy.io/docs/envoy/v1.9.0/intro/arch_overview/http_connection_management#timeouts

We need to expose this feature in Gloo. It is currently not available.

For reference, here is the v2 API (the one used by Gloo, original comment linked to v1 API): https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/core/protocol.proto#core-httpprotocoloptions

**Comment by marcogschmidt** [comment]
This already supported by Gloo. The idle timeout can be specified as an option on a `Gateway`:

```yaml
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      httpConnectionManagerSettings:
        idleTimeout: 10s # <--------------------------- HERE
  proxyNames:
  - gateway-proxy
  useProxyProto: false
```

I noticed, however, that we set the `idle_timeout` directly on the `HttpConnectionManager` itself, which is [deprecated](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/network/http_connection_manager/v2/http_connection_manager.proto#config-filter-network-http-connection-manager-v2-httpconnectionmanager). We should set it on `HttpConnectionManager.CommonHttpProtocolOptions`.
