### ISSUE TITLE
Dynamic Routes to Upstream Based on Request Data

### ISSUE THREAD

**Issue by gilday** [solo-io/gloo#2308]
Requesting a Gloo feature which allows users to define a Route that can choose an upstream based on information in the request data. For example, I would like to route traffic to a Consul service whose name is identified by some attribute of the request (e.g. the Host header or SNI).

It's an odd use case, so I'll elaborate on how I would use this. I am building an internal testing system which includes a dynamic set of short-lived (minutes) services registered in Consul. I would like to use Gloo as a API Gateway for exposing these services to the HTTP clients of this system. Instead of adding new Gloo routes whenever a new service is registered, or reaping old Gloo routes whenever a service is removed, I would like to define a dynamic Gloo route that allows the client to specify which service it wants to talk to in its request.

**Comment by ilackarms** [comment]
hi @gilday just to clarify here:

the desired behavior is that, given the existence of some Upstream (which is not known ahead of time), we would like to create a route (for example, something like this:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: dynamically-added-upstream
  namespace: gloo-system  
spec:
  virtualHost:
    domains:
    - 'dynamically-added-upstream.example.copm'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: dynamically-added-upstream
            namespace: dynamic
```


) for each upstream, when it appears during runtime?

this work would probably be handled by an operator built on top of Gloo to automate some of the routing behavior. we should discuss this further as we are currently discussing our roadmap for the *Gloo Operator*

**Comment by gilday** [comment]
Yes, that sounds right.

**Comment by gilday** [comment]
@ilackarms when you say _Gloo Operator_, are you referring to https://github.com/solo-io/envoy-operator ?

**Comment by ilackarms** [comment]
@gilday no, that is a now-defunct project which was originally designed to provide a standardized solution for deploying Envoy as a standalone proxy or sidecar.

the Gloo Operator I'm describing will automate installation and upgrade of Gloo components, as well as providing the ability to automate configuration changes such as the one you described

**Comment by ilackarms** [comment]
reference to the 'gloo operator' issue: #2295

**Comment by rickducott** [comment]
#430 <- another issue for tracking operator. I’ve been consolidating issues so I may merge these two

**Comment by bdecoste** [comment]
From #2400 ... requirement is for the user to not be required to create any virtual services or routes. When an upstream is dynamically created then the corresponding host/domain-based route is also created. Goal is for no Gloo configuration required as services are added (kube, consul, etc). 

New config would look something like this:

```
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  discovery:
    fdsMode: BLACKLIST
    dynamicVirtualService:
      enabled: true
```

For example, when this is dynamically created:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: petstore.example.com
  namespace: gloo-system
spec:
  consul:
    dataCenters:
    - dc1
    serviceName: petstore.example.com
```

Then this would also be created:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore.example.com
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - ‘petstore.example.com’
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: petstore.example.com
            namespace: gloo-system
```
