### ISSUE TITLE
Bug: HTTPS VirtualService is ignored until a HTTP is created

### ISSUE THREAD

**Issue by NelsonJeppesen** [solo-io/gloo#2311]
As far as I can tell, this is a bug. I created a VirtualService to listen on HTTPS. Unless I create a HTTP VirtualService on HTTP on the same gateway-proxy with the same domain, I get no response. This is reproducible if I then delete the HTTP virtualservice, it'll break again

The only thing that I feel is different about our environment is we're using a custom gateway-proxy, deployed with helm.

I created this:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
...
spec:
  sslConfig:
    secretRef:
      name: ********
      namespace: gloo-system
    sniDomains:
    - **********
  virtualHost:
    domains:
    - **********
    routes:
    - matchers:
      - prefix: /webhook
      routeAction:
        single:
          upstream:
            name: *******
````

With curl I get this:
```curl https://*******/webhook/ -iv
*   Trying ******...
* TCP_NODELAY set
* Connected to webhook-ops.k8s.production.apptentive.com (52.44.167.79) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to webhook-ops.k8s.production.apptentive.com:443
* Closing connection 0
```

But if I create a dumb redirect for the same hostname, it works

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
...
spec:
  virtualHost:
    domains:
    - ******
    routes:
    - matchers:
      - prefix: /webhook
      redirectAction:
        httpsRedirect: true
```

then I get what I expect
```
curl https://*****/webhook
HTTP/2 405
date: Wed, 29 Jan 2020 19:43:00 GMT
x-content-type-options: nosniff
content-type: text/plain;charset=utf-8
content-length: 6722
server: envoy
x-envoy-upstream-service-time: 2
....
```

gateway-proxy settings from helmchart

```
gatewayProxies
 public:
  gatewaySettings:
    disableGeneratedGateways: false
    useProxyProto: false

    # Watch all namespaces for virtual services, for both
    # http and https http gateways
    customHttpGateway:
      virtualServiceNamespaces:
        - '*'
      virtualServiceSelector:
        gateway: public
    customHttpsGateway:
      virtualServiceNamespaces:
        - '*'
      virtualServiceSelector:
        gateway: public

  # Spred the load over many kubernetes hosts
  antiAffinity: true

  kind:
    deployment:
      # Idle pods seem to use almost no resources
      replicas: 6

  # defaults from helm chart values `gatewayProxies.gatewayProxy`
  configMap:
    data: null
  extraInitContainersHelper: ""
  extraVolumeHelper: ""
  podTemplate:

    # Open up extra port for prometheus metrics
    extraPorts:
      -
        containerPort: 8081
        name: metrics
        protocol: TCP

    # defaults from helm chart values `gatewayProxies.gatewayProxy`
    disableNetBind: false
    floatingUserId: false
    httpPort: 8080
    httpsPort: 8443
    image:
      pullPolicy: Always
      repository: gloo-envoy-wrapper
      tag: 1.3.2
    probes: false
    runAsUser: 10101
    runUnprivileged: false
    tolerations: null
  readConfig: false
  service:
    httpPort: 80
    httpsPort: 443
    type: LoadBalancer
    extraAnnotations:
      external-dns.alpha.kubernetes.io/hostname: ***************
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
```

**Comment by CamelCaseNotation** [comment]
Are you running this on AWS?

By default, the svc created for the gateway-proxy has `http` as the first port-->targetPort option. If the `externalTrafficPolicy` of this LoadBalancer-type Service is `Cluster`, then the AWS ELB will have its health check configured to make TCP connections to the nodeport of the http listener.

Since Gloo doesn't start a listener if there are no VirtualServices, not having any HTTP VSs could mean the envoy listener on port 8080 (which serves HTTP traffic and is where the AWS ELB health check is sending its TCP probes to) may not be started.

@ilackarms is this correct? If you're not on AWS, then I'm not sure

**Comment by CamelCaseNotation** [comment]
I just saw your AWS-specific svc annotation. Yup, I can confirm that this is exactly what you're facing.

The way you can fix this is by re-creating your gateway-proxy service. Just make sure the HTTPS port is first, and that will cause the ELB health check to send TCP probes to the nodePort which eventually routes to the envoy listener in the gateway-proxy Pod on port 8443

**Comment by CamelCaseNotation** [comment]
https://docs.solo.io/gloo/latest/installation/gateway/kubernetes#looking-for-opened-ports

> NOT opening the listener ports when there are no listeners (routes) is by design with the intention of not over-exposing your cluster by accident (for security). **If you feel this behavior is not justified, please let us know.**

This behavior forces users like @NelsonJeppesen to create a fake HTTP service in order to have the listener respond to health checks and allow routing, so that's maybe a justification for not doing this

**Comment by CamelCaseNotation** [comment]
If you want a dummy HTTP service just to force the envoy listener on port 8080 to be listening so the AWS ELB health checks pass, you can use this:

```
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-http
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      redirectAction:
        httpsRedirect: true
```
