### ISSUE TITLE
Ignore opaque metadata to gloo when hashing snapshot

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2331]
without this, gateway & gloo can get in loop rewriting the status on objects because they wont hash to the same thing.

sample config:
```
	 - listeners:
  - ListenerType:
      http_listener:
        virtual_hosts:
        - domains:
          - petstore.com
          metadata:
            fields:
              sources:
                Kind:
                  list_value:
                    values:
                    - Kind:
                        struct_value:
                          fields:
                            kind:
                              Kind:
                                string_value: '*v1.VirtualService'
                            name:
                              Kind:
                                string_value: petstore
                            namespace:
                              Kind:
                                string_value: gateway-test-2372-1
                            observedGeneration:
                              Kind:
                                number_value: 685  # this was the one repeatedly being rewritten in our case
```
