### ISSUE TITLE
Helm chart does not render multiple plugins correctly

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2355]
To reproduce:
1. Extract the GlooE `1.2.3` Helm chart
2. Create `plugin-values.yaml` file:
```yaml
global:
  extensions:
    extAuth:
      plugins:
        my-plugin:
          image:
            repository: ext-auth-plugins
            registry: quay.io/solo-io
            pullPolicy: IfNotPresent
            tag: 1.2.3
        second-plugin:
          image:
            repository: foo
            registry: bar
            pullPolicy: IfNotPresent
            tag: 1.2.3
```
3. Run the following command: 
```
helm template . -x templates/21-extauth-deployment.yaml -f plugin-values.yaml
```

You will see that it renders it incorrectly:

```yaml
      initContainers:
      - image: quay.io/solo-io/ext-auth-plugins:1.2.3
        imagePullPolicy: IfNotPresent
        name: plugin-my-plugin
        volumeMounts:
          - name: auth-plugins
            mountPath: /auth-plugins- image: bar/foo:1.2.3
        imagePullPolicy: IfNotPresent
        name: plugin-second-plugin
        volumeMounts:
          - name: auth-plugins
            mountPath: /auth-plugins # $extAuth.plugins
```
