### ISSUE TITLE
Existing routes stop working when burst creating VirtualServices that use kubernetes services for routing

### ISSUE THREAD

**Issue by CamelCaseNotation** [solo-io/gloo#2368]
https://solo-io.slack.com/archives/C9L6VPAUW/p1580870371033200

I first create a `VirtualService`, and confirm I'm able to reach it via curl.
I then run
```
watch 'curl -sq https://test-soak.platform9.horse/kplane/v1/mgmtplanes'
```
This sends a curl request every 2 seconds. The output for this curl when it's able to reach the Upstream service is `null` (doesn't matter what the output is really, but it helps that this is a small string response so it's easy to watch in a separate tmux pane)

I then run a script called `soak.sh` which ultimately creates resources in a new Namespace. Prior to creating the Namespace, I apply a `VirtualService` to my cluster in the Namespace that Gloo is running in (I modified the default namespace via the helm chart to be `gloo` rather than `gloo-system`)

This `VirtualService` has 17 routes, all in a form similar to below:
```
    - matchers:
      - prefix: /qbert/
      options:
        prefixRewrite: /
      routeAction:
        single:
          kube:
            port: 443
            ref:
              name: qbert
              namespace: du-test-soak-10
```
Notice I chose to refer to the k8s service rather than the Upstream that the Discovery component creates for k8s services due to the Discovery component causing issues similar to what this issue is for. For this issue, please keep in mind I have scaled the Discovery deployment to 0 replicas, thus disabling it.

The behavior I'm observing is the route I'm continuously curling every 2 seconds begins to return `no healthy upstream` for varying periods of time. Sometimes it's over a minute, other times it is 5 seconds, sometimes it's only 2, other times it's 22 seconds, etc.

I will try to provide a cleaned up, more concise script which the Solo team can use to reproduce this issue in the next couple weeks. This issue is to track that, as well as provide a single place to discuss what the possible causes could be.

cc @christian-posta
