### ISSUE TITLE
enable dynamic creation of host-based route/virtualservice when upstream is dynmamically created

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2400]
Add a config option to enable the following: When an upstream is dynamically discovered and created then also create a / prefix route and virtualservice with a domain that matches the host in the upstream. This would remove the need for manual or external creation of routes/virtualservices for purely host-based routing.

**Comment by bdecoste** [comment]
New config would look something like this:

```
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  discovery:
    fdsMode: BLACKLIST
    dynamicVirtualService:
      enabled: true
      domainSuffix: example.com

```

Which would create this for every discovered upstream:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - ‘petstore.example.com’
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: petstore
            namespace: gloo-system
```
