### ISSUE TITLE
Add option for default namespace in glooctl-config

### ISSUE THREAD

**Issue by via-jordan-sokolic** [solo-io/gloo#2409]
It would be nice to have an option to configure the default namespace in `glooctl-config.yaml`, similar to how it's done for `kubectl` config. This would save some keystrokes for `glooctl` commands by allowing the user to omit the global `-n <namespace>` parameter for every `glooctl` command.

An alternative approach could be to parse this directly from the `kubectl` config itself. So if I have the following in `~/.kube/config`:
```yaml
contexts:
  - context:
      cluster: my-cluster
      namespace: my-namespace
    name: my-context
current-context: my-context
```
`glooctl` would know to do `-n my-namespace` for every command.
