### ISSUE TITLE
BUG: gloo does not respect named ports

### ISSUE THREAD

**Issue by joe-elliott** [solo-io/gloo#241]
I have this service/deployment combination in my clusters.  It's a very standard default backend for ingress.  Note that the service forwards from port 80 to the named port `http` on the pod.

```
kind: Service
apiVersion: v1
metadata:
  name: arch-default-backend
spec:
  ports:
  - port: 80
    targetPort: http
  selector:
    app: arch-default-backend
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: arch-default-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: arch-default-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
```

With this setup gloo is logging this every second:

```
{"level":"warn","ts":1546956254.3821619,"logger":"gloo.v1.event_loop.setup.kubernetes_eds","caller":"kubernetes/eds.go:133","msg":"upstream gloo-system.default-arch-default-backend-80: port 80 not found for service arch-default-backend"}
```
