### ISSUE TITLE
Add DataDog agent support to docs

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#2412]
Steps:

1. Install the DataDog agent in your Kubernetes cluster using their Helm chart
1. Install the Envoy integration in your DD account
1. Modify the 9-gateway-proxy-configmap.yaml (line 65) `/stats` instead of `/stats/prometheus`:
```
                            - match:
                                prefix: "/metrics"
                                headers:
                                - name: ":method"
                                  exact_match: GET
                              route:
                                prefix_rewrite: "/stats" #instead of /stats/prometheus
                                cluster: admin_port_cluster
```
(could add a new route to support both prometheus and DD, but this was the easiest change with minimal modifications to this yaml)
4. Add the following pod annotations to gateway-proxy deployment using the extraAnnotations key in values override:
```
gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        extraAnnotations:
          ad.datadoghq.com/gateway-proxy.check_names: '["envoy"]'
          ad.datadoghq.com/gateway-proxy.init_configs: '[{}]'
          ad.datadoghq.com/gateway-proxy.instances: '[{"stats_url": "http://%%host%%:8081/metrics"}]'
          ad.datadoghq.com/gateway-proxy.logs: '[{"source": "envoy", "service": "gloo",
          "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date",
          "pattern" : "^\\[[0-9]{4}-[0-9]{2}-[0-9]{2}"}]}]'
```

The integration in datadog will start pulling all the metrics and they are prepended with envoy.*

**Comment by kdorosh** [comment]
the only other thing you need to do to get the envoy logs to show up is set `logsEnabled: true` in the DataDog helm chart values file

**Comment by rickducott** [comment]
Input from another user:

> this is what we did instead of hostIP. We created a service specifically for envoy stats.

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  name: gateway-proxy-stats
  namespace: gloo-system
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    gateway-proxy: live
    gateway-proxy-id: gateway-proxy
```

> we install datadog via helm.. in the datadog values

```
  values:
    datadog:
      confd:
        envoy.yaml: |-
          init_config:
          instances:
            - stats_url: "http://gateway-proxy-stats.gloo-system:8082/stats"
```

(  datadog helm version version: 2.0.12)
