### ISSUE TITLE
nil pointer panic when watchNamespaces omits the settings own namespace

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2417]
reported by user on slack: https://solo-io.slack.com/archives/C9L6VPAUW/p1581536606299500?thread_ts=1581535139.285800&cid=C9L6VPAUW

settings crd:

```
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  labels:
    app: gloo
  name: default
  namespace: nas-gloo
spec:
  discovery:
    fdsMode: WHITELIST
  discoveryNamespace: nas-gloo
  gateway:
    readGatewaysFromAllNamespaces: false
    validation:
      alwaysAccept: true
      proxyValidationServerAddr: gloo:9988
  gloo:
    disableKubernetesDestinations: false
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404
    xdsBindAddr: 0.0.0.0:9977
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}
  refreshRate: 60s
  watchNamespaces:
  - hrzn01-dev-backoffice
```

logs from gloo pod:

```
 kctl logs pod/discovery-6ddc95b476-t42qb -n nas-gloo
{"level":"info","ts":1581536553.8353598,"logger":"fds.v1.event_loop","caller":"v1/setup_event_loop.sk.go:57","msg":"event loop started","version":"1.3.3"}
{"level":"info","ts":1581536553.8371043,"logger":"uds.v1.event_loop","caller":"v1/setup_event_loop.sk.go:57","msg":"event loop started","version":"1.3.3"}
{"level":"info","ts":1581536554.0633097,"logger":"fds.v1.event_loop.fds.v1.event_loop","caller":"v1/discovery_event_loop.sk.go:57","msg":"event loop started","version":"1.3.3"}
{"level":"info","ts":1581536554.0951815,"logger":"uds.v1.event_loop.uds.kube-uds","caller":"kubernetes/uds.go:31","msg":"started","version":"1.3.3","watchns":["hrzn01-dev-backoffice","nas-gloo"],"writens":"nas-gloo"}
{"level":"info","ts":1581536554.0952952,"logger":"uds.v1.event_loop.uds.v1.event_loop","caller":"v1/discovery_event_loop.sk.go:57","msg":"event loop started","version":"1.3.3"}
{"level":"info","ts":1581536554.095502,"logger":"uds.v1.event_loop.uds.kube-uds","caller":"runtime/panic.go:679","msg":"ended","version":"1.3.3"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2449934]
goroutine 230 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).DiscoverUpstreams.func1()
        /workspace/gloo/projects/gloo/pkg/plugins/kubernetes/uds.go:42 +0x234
github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).DiscoverUpstreams.func2(0xc000010310, 0xc000c69020, 0xc000aa3380, 0xc000aa33e0, 0xc000aa3440, 0xc0009a1080, 0x36ba8c0, 0xc000c69080)
        /workspace/gloo/projects/gloo/pkg/plugins/kubernetes/uds.go:66 +0x1e9
created by github.com/solo-io/gloo/projects/gloo/pkg/plugins/kubernetes.(*plugin).DiscoverUpstreams
        /workspace/gloo/projects/gloo/pkg/plugins/kubernetes/uds.go:60 +0x659

```

the user settings does not have the `nas-gloo` namespace in its watchNamespaces, even though the settings namespace itself is in `nas-gloo`. at some point, UDS starts a watch on the `nas-gloo` namespace, but no solo kit clients were initialized for it. this trickles down to a nil panic in UDS

the fix is to ensure the namespace of the settings itself gets added to the `watchNamespaces` automatically (or provide a validation error to the user)
