### ISSUE TITLE
Customize behavior of UDS

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#2423]
currently, Gloo UDS creates multiple upstreams from the mix of discovered pod labels, in addition to the "default" upstream per service. this means, given a the following service and 2 pods:

```
svc:
  selector:
    foo: bar
---
pod-1:
  labels:
    foo: bar
    a: b
---
pod-2:
  labels:
    foo: bar
    b: c

```

Gloo UDS will generate 3 upstreams:

```
svc-upstream:
  selector:
    foo: bar

---
svc-upstream-a-b:
   selector:
    foo: bar
    a: b
---
svc-upstream-a-b:
   selector:
    foo: bar
    b: c

```

this is done by sorting through the unique sets of volumes on pods. The *original* intention behind this behavior was to support subset routing. However it is no longer necessary, since the introduction of the `subset` field on the Virtual Service `route`.

We should disable this behavior, or provide a feature flag for it (in case anyone has a dependency on it, which i'm not aware exists).
