### ISSUE TITLE
Define static upstream hosts as separate resources

### ISSUE THREAD

**Issue by keiransteele** [solo-io/gloo#2438]
We could like to be able to define multiple hosts on a static upstream. The hosts in the upstream are unlikely to all be known at the time that the initial upstream is created.

We are provisioning VMs that are part of Gloo upstreams using Ansible. We want to dynamically add these to existing upstreams. Right now, we need to manually modify the upstream resource to include the hosts that are being provisioned.

My proposal is to have a separate "UpstreamHost" resource that an "Upstream" resource can reference rather than needing to have them statically defined in the Upstream resource. These could be referenced similar to NodeSelectors with tags etc. This method also allows for easy removal of hosts.

```yaml
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: dev-webservers
  namespace: gloo-system
spec:
  static:
    hosts:
    - ref:
        upstreamselector: dev-webservers
      port: 443
---
apiVersion: gloo.solo.io/v1
kind: UpstreamHost
metadata:
  name: webserver1
  namespace: gloo-system
  labels:
    upstreamselector: dev-webservers
spec:
  addr: webserver1
---
apiVersion: gloo.solo.io/v1
kind: UpstreamHost
metadata:
  name: webserver2
  namespace: gloo-system
  labels:
    upstreamselector: dev-webservers
spec:
  addr: webserver2
---
apiVersion: gloo.solo.io/v1
kind: UpstreamHost
metadata:
  name: dev-webservers
  namespace: gloo-system
  labels:
    upstreamselector: dev-webservers
spec:
  addr: webserver3
```

I have tried a Strategic Merge Patch as a workaround as it is supposed to be able to merge lists together but it doesn't work with CRDs and their generated resources.

https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/#use-a-strategic-merge-patch-to-update-a-deployment

https://github.com/kubernetes/kubernetes/issues/50037
