### ISSUE TITLE
Accepts vs with non-existent upstream when virtualServiceNamespaces does not include gloo-system

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#2474]
To reproduce:
- `glooctl install gateway`
- `k edit gateway -n gloo-system gateway-proxy` and add `virtualServiceNamespaces` to the `httpGateway` like this:
```
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    virtualServiceNamespaces:
    - default
```
- `k apply -f my-vs.yaml`
- `glooctl get vs` —> my-vs is "Accepted" even though the upstream doesn't exist

my-vs.yaml:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: my-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - foo
    routes:
    - routeAction:
        single:
          upstream:
            name: test-upstream
            namespace: gloo-system
      matchers:
      - prefix: /
```

I saw that the problem was fixed if `gloo-system` was added to `virtualServiceNamespaces` but that the problem still occurred if another namespace besides `default` was used instead or in addition.
