### ISSUE TITLE
Problems with JWT verification and / or unclarity of documentation

### ISSUE THREAD

**Issue by AntoninCamus** [solo-io/gloo#2495]
Hello,

I am working with the "petstore" demo app, following the tutorial but using google OpenID, and I am struggling to understand why my requests are passing without any errors to the backend.
The kubernetes template I apply looks like that :
```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: google-api
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: www.googleapis.com
        port: 80
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - 'gloo.example.com'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          kube:
            ref:
              name: petstore
              namespace: default
            port: 8080
    options:
      jwt:
        providers:
          google-account-provider:
            issuer: accounts.google.com
            audiences: # It does the same with or without audiences
            - "XXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com"
            jwks:
              remote:
                url: https://www.googleapis.com/oauth2/v3/certs
                upstream_ref:
                  name: google-api
                  namespace: gloo-system
```
And when I try to query it without any JWT it answers : 
```bash
curl gloo.example.com/api/pets
[{"id":1,"name":"Dog","status":"available"},{"id":2,"name":"Cat","status":"pending"}]
```
Am I doing something wrong ? 

While searching in the doc, I guessed it could be that JWT is an EE feature, since the field jwt is marked as is in the [protobuf definition ](https://docs.solo.io/gloo/latest/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk/#virtualhostoptions) : 
> Enterprise-only: Config for reading and verifying JWTs. Copy verifiable information from JWTs into other headers to make routing decisions or combine with RBAC for fine-grained access control

But on [the doc](https://docs.solo.io/gloo/latest/security/auth/jwt/access_control) it is not written anywhere, so even if this isn't the problem, it could benefit from clarification.

Thank you for your reading !
