### ISSUE TITLE
Support customization of UI base URL

### ISSUE THREAD

**Issue by ascampos** [solo-io/gloo#2545]
Users should be able to create a route that matches a custom domain and routes to the gloo UI upstream. (`example.com/gloo`)
```yaml  
- matchers:
        - prefix: /gloo/
      routeAction:
        single:
          upstream:
            name:  apiserver-ui-8080
            namespace: namespace
      options:
        prefixRewrite: /
```
Currently the UI will always issue requests relative to `/`. We need a way to customize this.
