### ISSUE TITLE
Don't deploy "gatewayProxy" resources when using alternative name

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2564]
If you don't use `gatewayProxy` in your map of `gatewayProxies` in your custom helm values, then the default `gatewayProxy` deployment, config, and service will still be created. You can scale the replicas to 0 in custom values, but that still leaves the service defined and leaves unused resources on the cluster.

**Comment by snuggie12** [comment]
@rickducott I have this same problem, but I think mine is specific to using gloo-ee as a subchart. A grandparent chart can't override settings for the gloo subchart because it's a subchart of gloo-ee.

I think global values would need to be setup to get around this.

**Comment by rickducott** [comment]
Interested, I thought values prefixes nested. Thanks for flagging.

**Comment by kdorosh** [comment]
I tested this and got a grandparent chart (gloo-ee as subchart) to override values in the gloo chart sucessfully: https://github.com/solo-io/gloo/pull/2577#issuecomment-597709070

closing as working as intended

**Comment by kdorosh** [comment]
the helm values
gloo-ee:
  gloo:
    gatewayProxies: []
override everything, nixing all envoy deployments from the grandparent chart.

which makes me think that if you explicitly provide the foo proxy map in the [] that it will work as written

**Comment by rickducott** [comment]
Here's an example values file: 
```
gatewayProxies:
  gatewayProxy:
    kind:
      deployment:
        replicas: 0
  internalProxy:
    antiAffinity: false
    configMap:
      data: null
    gatewaySettings:
      disableGeneratedGateways: false
      useProxyProto: false
    kind:
      deployment:
        replicas: 1
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 8080
      httpsPort: 8443
      image:
        repository: gloo-envoy-wrapper
        tag: 1.2.22
      probes: false
      runAsUser: 10101
      runUnprivileged: false
      tolerations: null
    readConfig: false
    service:
      type: LoadBalancer
      httpPort: 80
      httpsPort: 443
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    stats: true
  externalProxy:
    antiAffinity: false
    configMap:
      data: null
    gatewaySettings:
      disableGeneratedGateways: false
      useProxyProto: false
    kind:
      deployment:
        replicas: 1
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 8080
      httpsPort: 8443
      image:
        repository: gloo-envoy-wrapper
        tag: 1.2.22
      probes: false
      runAsUser: 10101
      runUnprivileged: false
      tolerations: null
    readConfig: false
    service:
      httpPort: 80
      httpsPort: 443
      type: LoadBalancer
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
    stats: true

```

Need something better to turn off the `gatewayProxy` resources.
