### ISSUE TITLE
Health check for gateway proxy fails on AWS

### ISSUE THREAD

**Issue by via-jordan-sokolic** [solo-io/gloo#2571]
When Gloo gateway is deployed on AWS, the default listener backend protocols are not set correctly. This can be fixed by adding the following service annotations to Helm values:
```yaml
gatewayProxies:
  gatewayProxy:
    service:
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "https"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
```

However, this causes the health check to fail since k8s >= 1.14: https://github.com/kubernetes/kubernetes/pull/70309

Until this issue is resolved, a [workaround](https://github.com/kubernetes/cloud-provider-aws/issues/49#issuecomment-556954918) is proposed to flip the order in which the ports are listed in `install/helm/gloo/templates/8-gateway-proxy-service.yaml`, placing `https` first.
