### ISSUE TITLE
grpc access logging documentation is incomplete

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2593]
In order to enable grpc access logging, you need the following values:

```
# prefix "gloo" since installing enterprise
gloo:
  accessLogger:
    enabled: true
```

And the following change to the gateway CRD:
```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  options:
    accessLoggingService:
      accessLog:
      - grpcService:
          logName: foo
          staticClusterName: access_log_cluster
  proxyNames:
  - gateway-proxy
  useProxyProto: false

```

The latter change is not mentioned anywhere in the docs. I had to look up the static cluster name directly in envoy.
