### ISSUE TITLE
Invalid gateways do not cause the proxy to be rejected

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2594]
~Just as we do with virtual services~(proxy errors bubble up onto the virtual services, not the other way), seems like we need to be marking the status as rejected on the proxy when the gateway is rejected. 

This is especially problematic when you consider the behavior of the UI: 

If you look in the admin page, there is a problem. But the envoy status is not red...
![image](https://user-images.githubusercontent.com/27434432/76575280-11d07400-6495-11ea-9fdd-819038b61478.png)

And the main page status isn't either: 

![image](https://user-images.githubusercontent.com/27434432/76575315-26147100-6495-11ea-9639-04fbb0379dc3.png)

**Comment by rickducott** [comment]
Here's an example config:
```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  proxyNames:
    - gateway-proxy
  useProxyProto: false
  options:
    accessLoggingService:
      accessLog:
        - grpcService:
            logName: example
            staticClusterName: nonexistent_cluster
```
