### ISSUE TITLE
Unable to get the Petstore example working

### ISSUE THREAD

**Issue by emaincourt** [solo-io/gloo#2604]
Hi,

I've been trying to deploy Gloo for a few hours and I can't make it work at all. I've followed the [Getting Started](https://docs.solo.io/gloo/1.0.0/gloo_routing/hello_world/) example and installed Gloo with `glooctl install gateway --namespace gloo-system --values values.yaml` and the following values:

```yaml
crds:
  create: true
settings:
  create: true
  watchNamespaces:
  - gloo-system
discovery:
  enabled: true
  fdsMode: WHITELIST
```

For now, I only want to create resources in the `gloo-system` namespace. After installing the control plane, watching the logs of the different services, I can clearly see there is something wrong with the `gateway-proxy`:

```bash
[2020-03-14 11:48:21.677][8][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamAggregatedResources gRPC config stream closed: 14, no healthy upstream
[2020-03-14 11:48:21.677][8][warning][config] [bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:54] Unable to establish new stream
```

All the other backends seem to be fine.

As far as I know, the `gloo` service is in charge of exposing the `StreamAggregatedResources` route. Therefore I've tried to reach it manually:

```bash
$ kubectl port-forward gloo-66fb8974c9-vxbnm 9977 &
$ grpc_cli call localhost:9977 envoy.service.discovery.v2.AggregatedDiscoveryService/StreamAggregatedResources

[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/core/grpc_service.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   udpa/annotations/sensitive.proto: Import "udpa/annotations/sensitive.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/core/config_source.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/core/grpc_service.proto: Import "envoy/api/v2/core/grpc_service.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.core.ApiConfigSource.grpc_services: ".envoy.api.v2.core.GrpcService" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/auth/cert.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/core/config_source.proto: Import "envoy/api/v2/core/config_source.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   udpa/annotations/sensitive.proto: Import "udpa/annotations/sensitive.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.auth.SdsSecretConfig.sds_config: ".envoy.api.v2.core.ConfigSource" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/cluster.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/auth/cert.proto: Import "envoy/api/v2/auth/cert.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/core/config_source.proto: Import "envoy/api/v2/core/config_source.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.Cluster.EdsClusterConfig.eds_config: ".envoy.api.v2.core.ConfigSource" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.Cluster.tls_context: ".envoy.api.v2.auth.UpstreamTlsContext" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.Cluster.lrs_server: ".envoy.api.v2.core.ConfigSource" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/cds.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/cluster.proto: Import "envoy/api/v2/cluster.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/core/grpc_service.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   udpa/annotations/sensitive.proto: Import "udpa/annotations/sensitive.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/core/config_source.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/core/grpc_service.proto: Import "envoy/api/v2/core/grpc_service.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.core.ApiConfigSource.grpc_services: ".envoy.api.v2.core.GrpcService" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/auth/cert.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/core/config_source.proto: Import "envoy/api/v2/core/config_source.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   udpa/annotations/sensitive.proto: Import "udpa/annotations/sensitive.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.auth.SdsSecretConfig.sds_config: ".envoy.api.v2.core.ConfigSource" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/listener/listener_components.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/auth/cert.proto: Import "envoy/api/v2/auth/cert.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.listener.FilterChain.tls_context: ".envoy.api.v2.auth.DownstreamTlsContext" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/listener.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/listener/listener_components.proto: Import "envoy/api/v2/listener/listener_components.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.Listener.filter_chains: ".envoy.api.v2.listener.FilterChain" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.Listener.listener_filters: ".envoy.api.v2.listener.ListenerFilter" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/lds.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/listener.proto: Import "envoy/api/v2/listener.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/core/grpc_service.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   udpa/annotations/sensitive.proto: Import "udpa/annotations/sensitive.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/core/config_source.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/core/grpc_service.proto: Import "envoy/api/v2/core/grpc_service.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.core.ApiConfigSource.grpc_services: ".envoy.api.v2.core.GrpcService" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/route.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/core/config_source.proto: Import "envoy/api/v2/core/config_source.proto" was not found or had errors.
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy.api.v2.Vhds.config_source: ".envoy.api.v2.core.ConfigSource" is not defined.
[libprotobuf ERROR google/protobuf/descriptor.cc:3603] Invalid proto descriptor for file "envoy/api/v2/rds.proto":
[libprotobuf ERROR google/protobuf/descriptor.cc:3606]   envoy/api/v2/route.proto: Import "envoy/api/v2/route.proto" was not found or had errors.
reading streaming request message from stdin...
```

In spite of the protobuf error (which do not occur if I downgrade the install to `1.3.5` btw) it looks like the gRPC server can be reached.

Then I tried to ignore the error and deploy the Petstore application. The application deploys properly. If we take a look at the created `Upstream`, we get:

```
$ glooctl get upstream gloo-system-petstore-8080

+---------------------------+------------+----------+----------------------------+
|         UPSTREAM          |    TYPE    |  STATUS  |          DETAILS           |
+---------------------------+------------+----------+----------------------------+
| gloo-system-petstore-8080 | Kubernetes | Accepted | svc name:      petstore    |
|                           |            |          | svc namespace: gloo-system |
|                           |            |          | port:          8080        |
|                           |            |          |                            |
+---------------------------+------------+----------+----------------------------+
```

As we can see, the discovery mechanism did not work with the API routes. See [expected output here](https://docs.solo.io/gloo/1.0.0/gloo_routing/hello_world/).

I still wanna know if I can reach the service:

```bash
$ kubectl port-forward svc/petstore 4000:8080 &
$ curl localhost:4000/api/pets | jq
[
  {
    "id": 1,
    "name": "Dog",
    "status": "available"
  },
  {
    "id": 2,
    "name": "Cat",
    "status": "pending"
  }
]
```

This seems to be ok. I've also created a `VirtualService` with the following parameters:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
        - prefix: /
        routeAction:
          single:
            upstream:
              name: gloo-system-petstore-8080
              namespace: gloo-system
```

Now, I guess I should be able to port-forward to the `gateway-proxy` to reach my service:

```
$ kubectl port-forward svc/gateway-proxy 4000:80
$ curl localhost:4000/api/pets | jq
curl: (52) Empty reply from server
```

And the port-forward also gives me the following error when querying:

```
E0314 13:02:27.140245     711 portforward.go:400] an error occurred forwarding 4000 -> 8080: error forwarding port 8080 to pod d06e1a65f042b7f52b73310a19082088e920148fb9085b31788ac794f52dbdf7, uid : exit status 1: 2020/03/14 12:02:27 socat[31476] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
```

So my guess is that Envoy, which is actually my `gateway-proxy` here I think, can not handle any requests for now because of some kind of a misconfiguration on my side. Please find below the configuration for Envoy:

```yaml
apiVersion: v1
data:
  envoy.yaml: |
    node:
      cluster: gateway
      id: "{{.PodName}}.{{.PodNamespace}}"
      metadata:
        # role's value is the key for the in-memory xds cache (projects/gloo/pkg/xds/envoy.go)
        role: "{{.PodNamespace}}~gateway-proxy"
    stats_sinks:
      - name: envoy.metrics_service
        config:
          grpc_service:
            envoy_grpc: {cluster_name: gloo.gloo-system.svc.cluster.local:9966}
    static_resources:
      listeners: # if or $statsConfig.enabled (or $spec.readConfig $spec.extraListenersHelper) # $spec.extraListenersHelper
        - name: prometheus_listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8081
          filter_chains:
            - filters:
                - name: envoy.http_connection_manager
                  config:
                    codec_type: auto
                    stat_prefix: prometheus
                    route_config:
                      name: prometheus_route
                      virtual_hosts:
                        - name: prometheus_host
                          domains:
                            - "*"
                          routes:
                            - match:
                                path: "/ready"
                                headers:
                                - name: ":method"
                                  exact_match: GET
                              route:
                                cluster: admin_port_cluster
                            - match:
                                prefix: "/metrics"
                                headers:
                                - name: ":method"
                                  exact_match: GET
                              route:
                                prefix_rewrite: "/stats/prometheus"
                                cluster: admin_port_cluster
                    http_filters:
                      - name: envoy.router
                        config: {} # if $statsConfig.enabled # if $spec.readConfig
      clusters:
      - name: gloo.gloo-system.svc.cluster.local:9977
        alt_stat_name: xds_cluster
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: gloo.gloo-system.svc.cluster.local:9977
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: gloo.gloo-system.svc.cluster.local
                    port_value: 9977
        http2_protocol_options: {}
        upstream_connection_options:
          tcp_keepalive: {}
        type: STRICT_DNS
        respect_dns_ttl: true
      - name: wasm-cache
        connect_timeout: 5.000s
        load_assignment:
          cluster_name: wasm-cache
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: gloo.gloo-system.svc.cluster.local
                    port_value: 9979
        upstream_connection_options:
          tcp_keepalive: {}
        type: STRICT_DNS
        respect_dns_ttl: true
      - name: gloo.gloo-system.svc.cluster.local:9966
        alt_stat_name: metrics_cluster
        connect_timeout: 5.000s
        load_assignment:
            cluster_name: gloo.gloo-system.svc.cluster.local:9966
            endpoints:
            - lb_endpoints:
              - endpoint:
                    address:
                        socket_address:
                            address: gloo.gloo-system.svc.cluster.local
                            port_value: 9966
        http2_protocol_options: {}
        type: STRICT_DNS # if .Values.accessLogger.enabled # if $spec.tracing
      - name: admin_port_cluster
        connect_timeout: 5.000s
        type: STATIC
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: admin_port_cluster
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 19000 # if or $statsConfig.enabled ($spec.readConfig) # if $spec.tracing
    dynamic_resources:
      ads_config:
        api_type: GRPC
        rate_limit_settings: {}
        grpc_services:
        - envoy_grpc: {cluster_name: gloo.gloo-system.svc.cluster.local:9977}
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 19000 # if (empty $spec.configMap.data) ## allows full custom # range $name, $spec := .Values.gatewayProxies# if .Values.gateway.enabled
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: gloo
    gateway-proxy-id: gateway-proxy
    gloo: gateway-proxy
  name: gateway-proxy-envoy-config
```

Could you please help me or give me any hints ?

Thanks a lot
