### ISSUE TITLE
Allow mapping gloo https port to map to http on gateway-proxy with helm

### ISSUE THREAD

**Issue by RichiCoder1** [solo-io/gloo#2608]
In short, it'd be nice to be able to map `service/gateway-proxy`'s https service port to the pod's http port for when the LoadBalancer is performing TLS termination. Currently there's no way (I can tell) to do this through helm as just mapping the `httpsPort` to `8080` seems to break things.

The use case is we're using existing certs with AWS NLB to do TLS termination.

**Comment by RichiCoder1** [comment]
Literally after posting this, it's suddenly working! (Mapping the podTemplate port that is). Closing this.

**Comment by RichiCoder1** [comment]
Update to the update. This works, but gloo will complain about having two bind ports

**Comment by rickducott** [comment]
Hey @RichiCoder1 can you provide your helm values? I'm wondering if it would be sufficient to also re-bind the http port to something else.

**Comment by RichiCoder1** [comment]
Values:
```
    gatewayProxies:
      gatewayProxy:
        podTemplate:
          httpsPort: 8080
        service:
          extraAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
```

I tried mapping the http pod port to a different place, but that seemed to break it in other ways.

**Comment by RichiCoder1** [comment]
Specifically it actually seems like it's the validating webhook that's rejecting it?

```
[March 20, 2020 at 3:35:45 PM GMT-5]
{"level":"error","ts":1584736545.700982,"logger":"gateway.v1.event_loop.gateway.gateway-validation-webhook.gateway-validator","caller":"validation/validator.go:156","msg":"validation is disabled due to an invalid resource which has been written to storage. Please correct any Rejected resources to re-enable validation.","version":"1.3.13","error":"3 errors occurred:\n\t* invalid resource gloo-system.gateway-proxy\n\t* bind-address :::8080 is not unique in a proxy. gateways: gloo-system.gateway-proxy,gloo-system.gateway-proxy-ssl\n\t* bind-address :::8080 is not unique in a proxy. gateways: gloo-system.gateway-proxy,gloo-system.gateway-proxy-ssl\n\n","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/validation.(*validator).validateSnapshot\n\t/workspace/gloo/projects/gateway/pkg/validation/validator.go:156\ngithub.com/solo-io/gloo/projects/gateway/pkg/validation.(*validator).ValidateGateway\n\t/workspace/gloo/projects/gateway/pkg/validation/validator.go:422\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).validateGateway\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:374\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).validate\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:348\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).makeAdmissionResponse\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:248\ngithub.com/solo-io/gloo/projects/gateway/pkg/services/k8sadmisssion.(*gatewayValidationWebhook).ServeHTTP\n\t/workspace/gloo/projects/gateway/pkg/services/k8sadmisssion/validating_admission_webhook.go:174\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2387\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2802\nnet/http.initNPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3365\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5713"}
```

Though tbh, per that suggestion being able to disable the HTTP port would also work.

**Comment by CarpathianUA** [comment]
I can confirm this.
The only way to that is to set 
```
podTemplate:
          httpsPort: 8080
```
However, Gloo complains about the non-unique port.
Moreover, Helm chart doesn't provide an ability to disable http listener at all (I've checked Helm templates), in most scenarios people don't need http listner when using TLS termination

**Comment by CarpathianUA** [comment]
@rickducott Rebinding port doesn't help as well

**Comment by RichiCoder1** [comment]
Update: remapping the httpsPort + httpsFirst seems to make things happy. However glooctl check will still be unhappy.

**Comment by z0lope0z** [comment]
In case someone tries the solution above and envoy doesn't register the 8080 listener because gateway opted to remove it. You can disable the duplicate 8080 gateway crd k8s object by setting disableHttpsGateway:true. Gloo v1.8 only.

```
Starting from Gloo v1.8 you can use the disableHttpsGateway helm value to disable https gateway generation and the disableHttpGateway helm value to disable http gateway generation.
```

ref:
https://github.com/solo-io/gloo/blob/9aa850c11cbc77b6d6ca159023e4b8917d727823/docs/content/guides/integrations/aws/_index.md#tls-certificates-entities

**Comment by sjortiz** [comment]
This is still happening with the following values:
````
settings:
  watchNamespaces:
    - default
gloo:
  logLevel: warn
discovery:
  logLevel: warn
gatewayProxies:
  gatewayProxy:
    gatewaySettings:
      ipv4Only: True
    podTemplate:
      httpsPort: 8080
    service:
      httpsFirst: True
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {valid-cm-arn}
````

**Comment by sjortiz** [comment]
an extra variable should be used to disable the httpsProxy and not the http gateway, because we do need the port open at the load balancer level, we just don't need both services pointing to the same host:port and gloo complaining about it.

in fact the ports should've been merged into one proxy and having two separate proxies should be reserved for advance cases where you need more custom definitions for each one (different selectors, etc) but for now I assuming having two different variables would be of help.

**Comment by sjortiz** [comment]
This is the combination that works on gloo > 1.10.x

as previously stated, disableHttpsGateway removes the gateway-ssl gateway but also removes the port from the svc, we the following config we override the final resource definition and force include the missing port.

```

gatewayProxies:
  gatewayProxy:
    gatewaySettings:
      disableHttpsGateway: true
    service:
      httpsFirst: true
      kubeResourceOverride:
        spec:
          ports:
            - name: http
              port: 80
              targetPort: 8080
            - name: https
              port: 443
              targetPort: 8080
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "external"
        service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing #
        service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:...." # the ARN of your x509 certificate
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
```
This should be reflected on the docs on method A) https://docs.solo.io/gloo-edge/master/guides/integrations/aws/#nlb-with-tls-offloading or be included as method C), as I figured this out in a sort of combination between tls offload and https redirect.

separating the two things on different variables would be the ideal solution
