### ISSUE TITLE
Need to add port to VS domains list for gRPC service

### ISSUE THREAD

**Issue by emaincourt** [solo-io/gloo#2610]
Hi,

I'm not exactly sure if this is a bug on Gloo's side, a feature, or a bug on gRPC's side but I would definitely appreciate to get more details on it.

**How to reproduce**

Let's say we do have a running upstream named `grpc-upstream`. We would like to create a new route to reach the gRPC service behind.

```bash
$ glooctl add route \
    --path-prefix / \
    --dest-name grpc-upstream
```

Then we try to connect to our server using `grpc_cli`:

```bash
$ grpc_cli ls $(glooctl proxy url --port http | sed 's/http:\/\///') 
grpc.health.v1.Health
grpc.reflection.v1alpha.ServerReflection 
```

It works well. Now I would like to make it accessible from only one domain, let’s say `grpc.example.com`:  

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
spec:
  virtualHost:
    domains:
    - grpc.example.com
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: grpc-upstream
            namespace: gloo-system 
```

  Now let’s try to reach the servier:  

```
$ grpc_cli ls grpc.example.com:80
 Received an error when querying services endpoint.
Reflection request not implemented; is the ServerReflection service enabled?
```

I spent a long time trying to figure out what was wrong here. As far as I know, this is not documented. So eventually I found a way to make it. I actually had to use `grpc.example.com:80` in the domains list instead of `grpc.example.com`:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
spec:
  virtualHost:
    domains:
    - grpc.example.com:80
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: grpc-upstream
            namespace: gloo-system 
```

`80` is only the port here, I did not expect the need to suffix the domain with that. Is it something that should be expected ?

Being able to use grpc-web is actually the reason why we're trying to migrate to Gloo and it's too bad there is no documentation for setting up a very basic gRPC Upstream as said in #2488 and #2372. If we eventually manage to migrate our services, I would be very glad to contribute to your documentation to add useful information.

Thank you in advance

**Comment by lgadban** [comment]
Hi @emaincourt -- I'm currently looking into this.

I suspect this has something to do with how `grpc_cli` sets the `authority` header, but I want to reproduce this myself to dig into it further.

Did you build `grpc_cli` from source? I plan on doing the same following [these gRPC docs](https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md), but if you used a different method please let me know.

**Comment by ned1313** [comment]
Hi @emaincourt and @lgadban. I was able to get the same setup working using grpcurl with the authority header set to the domain you want to use. Here's the breakdown:

VS configuration looks like this:
```yaml
spec:
  virtualHost:
    domains:
    - store.example.com
```

If I run the following:

```bash
grpcurl -plaintext store.example.com:80 solo.examples.v1.StoreService/ListItems
```

I get the error:

```bash
Error invoking method "solo.examples.v1.StoreService/ListItems": failed to query for service descriptor "solo.examples.v1.StoreService": server does not support the reflection API
```

I am guessing because Envoy is seeing a Host value of `store.example.com:80` which does not match `store.example.com`.  If you update the domain in the VS config to `store.example.com*` it will work, but that seems hacky.

If I run the grpcurl command like this:

```bash
grpcurl -plaintext -authority store.example.com store.example.com:80 solo.examples.v1.StoreService/ListItems
```

I do not get the error because I am explicitly setting the authority in the context of the request. Envoy is looking at that header and matching on the domain specified within.

Not sure which is the better solution, but I hope this helps.
