### ISSUE TITLE
Allow kube service labels and consul tags drive configuration of dynamic upstream configuration

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2631]
For example, given the following labels/tags :

```
healthcheck.1.healthyThreshold=1
healthcheck.1.httpHealthCheck.path=/api/pets
healthcheck.1.interval=30s
healthcheck.1.timeout=10s
healthcheck.1.unhealthyThreshold=2
healthcheck.1.healthyThreshold=1
```

create an upstream with the following

```
spec:
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /api/pets
    interval: 30s
    timeout: 10s
    unhealthyThreshold: 1
```
