### ISSUE TITLE
Subtle bug in gloo status reporting for virtual host issues

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2643]
This is a bit convoluted, but exposed a bug in how we're updating status. 

I have an app template that includes a namespace, service, and deployment, and then also a virtual service an upstream. For instance, I might deploy an app called "echo 1":

* Create NS "echo-1"
* Create service and deployment called "echo-1" in namespace "echo-1"
* Create upstream for echo-1
* Create virtual service in namespace echo-1 using "echo-1.example.com" as the host

Repeat this for "echo-2" and "echo-3". So far so good, this is a standard way you might onboard a new service with a new Gloo virtual service. 

Now I wanted to simulate a problem. I create a namespace called "echo-4", and save all my resources there, but I accidentally re-used "echo-3" as the name. This results in two virtual services called "echo-3", one in each namespace, each with the domain "echo-3.example.com". 

First, gateway propagates the error correctly:
```
reason: "2 errors occurred:\n\t* domain conflict: the [echo-3.example.com] domain
      is present in other virtual services that belong to the same Gateway as this
      one: [echo-4.echo-3]\n\t* VirtualHost Error: DomainsNotUniqueError. Reason:
      domain echo-3.example.com is shared by the following virtual hosts: [echo-3.echo-3
      echo-4.echo-3]\n\n"
    reported_by: gateway
    state: 2
    subresource_statuses:
      '*v1.Proxy.gloo-system.gateway-proxy':
        reported_by: gloo
        state: 1
```

Eventually, gloo starts reporting an error, but it loses "echo-4.echo-3" making the message not meaningful. 

```
  status:
    reported_by: gateway
    state: 1
    subresource_statuses:
      '*v1.Proxy.gloo-system.gateway-proxy':
        reason: "1 error occurred:\n\t* VirtualHost Error: DomainsNotUniqueError.
          Reason: domain echo-3.example.com is shared by the following virtual hosts:
          [echo-3.echo-3 echo-3.echo-3]; VirtualHost Error: DomainsNotUniqueError.
          Reason: domain echo-3.example.com is shared by the following virtual hosts:
          [echo-3.echo-3 echo-3.echo-3]\n\n"
        reported_by: gloo
        state: 2
```
