### ISSUE TITLE
virtual service with inja template confuses helm

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2648]
If you put a virtual service with inja templates into a helm chart, it can get confused by the syntax and fail to process:

```
Error: UPGRADE FAILED: parse error at (mdb-test-gw/templates/mdb-test-vs.yaml:90): function "header" not defined
```

This happens when trying our standard response transformations example:
```
...
      transformations:
        responseTransformation:
          transformationTemplate:
            headers:
              # We set the response status via the :status pseudo-header based on the response code
              ":status":
                text: '{% if default(data.error.message, "") != "" %}400{% else %}{{ header(":status") }}{% endif %}'
```
