### ISSUE TITLE
options.jwks.remote.cacheDuration has no effect on envoy config

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2677]
Regardless of the gloo setting options.jwks.remote.cacheDuration there is no chnage in the envoy setting. The latter always looks like:

 ```
     jwt:
        providers:
          bogus:
            issuer: http://bogus2.foo.com/auth/realms/solo
            jwks:
              remote:
                cacheDuration: 300s
                upstreamRef:
                  name: default-keycloak-8080
                  namespace: gloo-system
                url: http://jwt.example.com/auth/realms/solo/protocol/openid-connect/certs
          valid:
            audiences:
            - account1
            claimsToHeaders:
            - claim: email
              header: email-header
            - claim: sub
              header: sub-header
            issuer: http://34.82.251.0/auth/realms/solo
            jwks:
              remote:
                cacheDuration: 3000s
                upstreamRef:
                  name: default-keycloak-8080
                  namespace: gloo-system
                url: http://jwt.example.com/auth/realms/solo/protocol/openid-connect/certs
            keepToken: true
```

```
               },
               "providers": {
                "gloo-system_default_valid": {
                 "payloadInMetadata": "gloo-system_default_valid",
                 "remoteJwks": {
                  "httpUri": {
                   "timeout": "5s",
                   "uri": "http://jwt.example.com/auth/realms/solo/protocol/openid-connect/certs",
                   "cluster": "default-keycloak-8080_gloo-system"
                  }
                 },
                 "forward": true,
                 "audiences": [
                  "account1"
                 ],
                 "issuer": "http://34.82.251.0/auth/realms/solo"
                },
                "gloo-system_default_bogus": {
                 "payloadInMetadata": "gloo-system_default_bogus",
                 "remoteJwks": {
                  "httpUri": {
                   "cluster": "default-keycloak-8080_gloo-system",
                   "timeout": "5s",
                   "uri": "http://jwt.example.com/auth/realms/solo/protocol/openid-connect/certs"
                  }
                 },
                 "issuer": "http://bogus2.foo.com/auth/realms/solo"
                }
```
