### ISSUE TITLE
Gateway Pod is not running

### ISSUE THREAD

**Issue by debjitk** [solo-io/gloo#2689]
I am using the following configuration

```
# Metadata
metadata:
  name: default
  namespace: gloo-system

# Namespace
namespace:
  create: false

# CRDs
crds:
  create: false

# Settings
settings:
  create: true
  watchNamespaces: null
  writeNamespace: gloo-system
  integrations:
    knative:
      enabled: false
      version: 0.10.0
      proxy:
        image:
          repository: gloo-envoy-wrapper
          tag: 1.3.12
        httpPort: 80
        httpsPort: 443
        # tracing: ""
        replicas: 1
        resources:
          limits:
            cpu: 500m
            memory: 768m
          requests:
            cpu: 500m
            memory: 768m
      requireIngressClass: null
  extensions: null
  singleNamespace: false
  invalidConfigPolicy:
    replaceInvalidRoutes: false
    invalidRouteResponseCode: 404
    invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators should run `glooctl check` to find and fix config errors.
  linkerd: false
  disableProxyGarbageCollection: false
  disableKubernetesDestinations: false

# Gloo
gloo:
  deployment:
    image:
      repository: gloo
      tag: 1.3.12
    xdsPort: 9977
    validationPort: 9988
    stats: 
      enabled: true
    floatingUserId: false
    runAsUser: 10101
    # externalTrafficPolicy: "Cluster"
    disableUsageStatistics: false
    replicas: 1
    # resources:
    #   limits:
    #     cpu: 500m
    #     memory: 768m
    #   requests:
    #     cpu: 500m

# Discovery
discovery:
  enabled: true
  deployment:
    image:
      repository: discovery
      tag: 1.3.12
    # stats:
    #   enable: true
    floatingUserId: false
    runAsUser: 10101
    replicas: 1
    # resources:
    #   limits:
    #     cpu: 500m
    #     memory: 768m
    #   requests:
    #     cpu: 500m
  fdsMode: "WHITELIST"

# Gateway
gateway:
  enabled: true
  deployment:
    image:
      repository: gateway
      tag: 1.3.12
  validation:
    enabled: true
    alwaysAcceptResources: true
    secretName: gateway-validation-certs
    failurePolicy: Ignore
    # stats:
    #   enabled: true
    floatingUserId: false
    runAsUser: 10101
    replicas: 1
    # resources:
    #   limits:
    #     cpu: 500m
    #     memory: 768m
    #   requests:
    #     cpu: 500m
    #     memory: 768m
    certGenJob:
      enabled: false
      image:
        repository: certgen
        tag: 1.3.12
      restartPolicy: OnFailure
      setTtlAfterFinished: true
      ttlSecondsAfterFinished: 60
  updateValues: false
  proxyServiceAccount:
    disableAutomount: false
  readGatewaysFromAllNamespaces: false

# Gateway proxies
gatewayProxies:
  gatewayProxy:
    kind:
      deployment:
        replicas: 1
        # resources:
        #   cpu: 500m
        #   memory: 768m
        # requests:
        #   cpu: 500m
        #   memory: 768m
        antiAffinity: false
    daemonSet:
      hostPort: true
    podTemplate:
      image:
        repository: gloo-envoy-wrapper
        tag: 1.3.12
      httpPort: 8080
      httpsPort: 8443
      # extraPorts: []
      # nodeName: ""
      # nodeSelector: ""
      # tolerations: []
      probes: false
      resources:
        # limits:
        #   cpu: 500m
        #   memory: 768m
        # requests:
        #   cpu: 500m
        #   memory: 768m
      disableNetBind: true
      runUnprivileged: false
      floatingUserId: false
      runAsUser: 10101
      configMap:
        data: null
    service:
      type: LoadBalancer
      # name: "gloo-service"
      httpPort: 80
      httpsPort: 443
      # clusterIP: 
      extraAnnotations:
        "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
        "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
        "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp"
        "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
        "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"
      # externalTrafficPolicy: LoadBalancer
      # httpsFirst: false
      # tracing:
      #   provider: ""
      #   cluster: ""
    gatewaySettings:
      ipv4Only: true
      useProxyProto: false
      # customHttpGateway: ""
      # customHttpsGateway: ""
      options:
        read_gateways_from_all_namespaces: false
        always_sort_route_table_routes: false
      disableGeneratedGateways: false
    extraEnvoyArgs: []
    extraContainersHelper: ""
    extraInitContainersHelper: ""
    extraVolumeHelper: ""
    extraListenersHelper: ""
    stats:
      enabled: true
    readConfig: false
    extraProxyVolumeMountHelper: ""

# Ingress
ingress:
  enabled: false
  deployment:
    image:
      repository: ingress
      tag: 1.3.12
    replicas: 1
  requireIngressClass: gloo

# Ingress proxy
ingressProxy:
  configMap: {}
  deployment:
    httpPort: 80
    httpsPort: 443
    image:
      repository: gloo-envoy-wrapper
      tag: 1.3.12
    replicas: 1

# K8S
k8s:
  clusterName: cluster2.dc1.domain.internal

# Access logger
accessLogger:
  enabled: false
  image:
    repository: access-logger
    tag: 1.3.12
  port: 8083
  replicas: 1
  serviceName: AccessLog

# Global
global:
  image:
    registry: quay.io/solo-io
    pullPolicy: IfNotPresent
  extensions: null
  glooRbac:
    create: true
    namespaced: false
    # nameSuffix: ""
  wasm:
    enabled: false
  glooStats:
    enabled: true
  glooMtls:
    enabled: true
    sds:
      image:
        repository: sds
        tag: 1.3.12
    envoy:
      image:
        repository: gloo-envoy-wrapper
        tag: 1.3.12
```

**Comment by rickducott** [comment]
Hey @debjitk you can do multi-line code blocks with 
<pre>
```
content...
```
</pre>

**Comment by debjitk** [comment]
@rickducott Edited

**Comment by rickducott** [comment]
Hey @debjitk thanks for the values file, I was able to reproduce. It looks like there's a bug in our helm chart. Sharing some notes about my investigation, and describing the bug at the end, with some possible workarounds. 

First, I saw this log line in the crashed gateway pod:

```
{"level":"fatal","ts":1585669389.195996,"logger":"gateway","caller":"setuputils/main_setup.go:89","msg":"error in setup: starting snapshot watch: initial Gateway list: converting output crd: reading crd spec on resource gateway-proxy in namespace gloo-system into v1Gateway: unknown field \"always_sort_route_table_routes\" in v1.ListenerOptions","version":"1.3.12","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:89\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

I took a look at the API for `GatewayOptions`, I would use this as a reference: https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/#gatewayoptions. If you read simply from the proto, it looks like it should be snake cased as you did. But in the docs and in Kubernetes, it expects camel casing - sorry for the confusion. I updated your `gatewaySettings` like so:

```
...
    gatewaySettings:
      ipv4Only: true
      useProxyProto: false
      # customHttpGateway: ""
      # customHttpsGateway: ""
      options:
        readGatewaysFromAllNamespaces: false
        alwaysSortRouteTableRoutes: false
      disableGeneratedGateways: false
...
```

Now, we're getting an error that is slightly different:

```
{"level":"fatal","ts":1585671758.393627,"logger":"gateway","caller":"setuputils/main_setup.go:89","msg":"error in setup: starting snapshot watch: initial Gateway list: converting output crd: reading crd spec on resource gateway-proxy in namespace gloo-system into v1Gateway: unknown field \"alwaysSortRouteTableRoutes\" in v1.ListenerOptions","version":"1.3.12","stacktrace":"github.com/solo-io/gloo/pkg/utils/setuputils.Main\n\t/workspace/gloo/pkg/utils/setuputils/main_setup.go:89\ngithub.com/solo-io/gloo/projects/gateway/pkg/setup.Main\n\t/workspace/gloo/projects/gateway/pkg/setup/setup.go:13\nmain.main\n\t/workspace/gloo/projects/gateway/cmd/main.go:11\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

It appears we are using the same options blob both as the `ListenerOptions` in the generated `Gateway` CRDs, and in the `GatewayOptions` in the generated `Settings` CRD. We should fix this in the chart. 

Two possible workarounds:
1) Skip specifying those options in the helm values
2) Set `disableGeneratedGateways: true` and manually create your `Gateway` CRDs after install. For reference, here are the default gateways that are normally created:

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  creationTimestamp: "2020-03-31T16:37:08Z"
  generation: 1
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
  resourceVersion: "9009373"
  selfLink: /apis/gateway.solo.io/v1/namespaces/gloo-system/gateways/gateway-proxy
  uid: 44625bde-2c86-42af-a1c5-a926f9b42c5c
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  proxyNames:
  - gateway-proxy
  ssl: false
  useProxyProto: false
---
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  creationTimestamp: "2020-03-31T16:37:08Z"
  generation: 1
  labels:
    app: gloo
  name: gateway-proxy-ssl
  namespace: gloo-system
  resourceVersion: "9009372"
  selfLink: /apis/gateway.solo.io/v1/namespaces/gloo-system/gateways/gateway-proxy-ssl
  uid: 32211aa7-168c-4ca9-b560-3109fdb2c57b
spec:
  bindAddress: '::'
  bindPort: 8443
  httpGateway: {}
  proxyNames:
  - gateway-proxy
  ssl: true
  useProxyProto: false
```
