### ISSUE TITLE
VS with Consul RouteDestination is unable to find consul upstreams in non-default namespace

### ISSUE THREAD

**Issue by mattchrist** [solo-io/gloo#2693]
When using a Consul RouteDestination for a Consul Upstream in a namespace other than gloo-system, Gloo is not able to find the upstream and gives the following warning:
```
warning: \n  Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream
    {consul-svc:service gloo-system} not found
```
It appears that Gloo is hard coded to check in `gloo-system` for Consul upstreams.
- https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/upstreams/consul/conversions.go#L23
- https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/defaults/namespace.go#L3 

Settings:
```
---
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  labels:
    app: gloo
  name: default
  namespace: gloo-custom
spec:
  consul:
    address: consul:8500
    serviceDiscovery: {}
  discovery:
    fdsMode: WHITELIST
  discoveryNamespace: gloo-custom
  gateway:
    readGatewaysFromAllNamespaces: true
    validation:
      alwaysAccept: true
      proxyValidationServerAddr: gloo:9988
  gloo:
    disableKubernetesDestinations: false
    disableProxyGarbageCollection: false
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404
    xdsBindAddr: 0.0.0.0:9977
  kubernetesArtifactSource: {}
  kubernetesConfigSource: {}
  kubernetesSecretSource: {}
  refreshRate: 60s
  watchNamespaces:
  - gloo-custom
  - default
```

Virtual Service:
```
---
metadata:
  name: gloo-custom-service
  namespace: gloo-custom
status:
  reason: "warning: \n  Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream
    {consul-svc:service gloo-system} not found"
  reportedBy: gateway
  state: Warning
  subresourceStatuses:
    '*v1.Proxy.gloo-custom.gateway-proxy':
      reason: "warning: \n  Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream
        {consul-svc:service gloo-system} not found"
      reportedBy: gloo
      state: Warning
virtualHost:
  domains:
  - service.redacted
  routes:
  - matchers:
    - prefix: /
    routeAction:
      single:
        consul:
          dataCenters:
          - a
          - b
          serviceName: service
```

Consul Upstreams are discovered and accepted:
```
...
| service                               | Consul     | Accepted | svc name: service                |
...
```

Gloo pod is crashlooping with the following logs:
```
{"level":"warn","ts":1585660389.5201235,"logger":"gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:141","msg":"proxy gloo-custom.gateway-proxy was rejected due to invalid config: 2 errors occurred:\n\t* invalid resource gloo-custom.gateway-proxy\n\t* WARN: \n  [Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {consul-svc:service gloo-system} not found]\n\n\nAttempting to update only EDS information","version":"1.3.15"}
{"level":"warn","ts":1585660389.520154,"logger":"gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:148","msg":"endpoint update failed. xDS snapshot for proxy gloo-custom.gateway-proxy will not be updated. Error is: no snapshot found for node gloo-custom~gateway-proxy","version":"1.3.15"}
{"level":"info","ts":1585660390.1958942,"logger":"gloo.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/run.go:35","msg":"begin sync 2817760403409001946 (106 upstreams)","version":"1.3.15"}
panic: send on closed channel
goroutine 3861 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.refreshSpecs(0x3579d20, 0xc001e564c0, 0x35824a0, 0xc00067de30, 0xc000af6000, 0x52, 0x80, 0xc001d80d80, 0x0, 0x0, ...)
        /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:168 +0x48d
github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints.func2(0xc001d80de0, 0x3579de0, 0xc001ab8270, 0x0, 0xdf8475800, 0x0, 0x0, 0xc001d80480, 0xc000ece9f0, 0xc001d80d80, ...)
        /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:99 +0x4a8
created by github.com/solo-io/gloo/projects/gloo/pkg/plugins/consul.(*plugin).WatchEndpoints
        /workspace/gloo/projects/gloo/pkg/plugins/consul/eds.go:63 +0x5ea
```

Routing direct to the upstream in the specified namespace works as expected.
