### ISSUE TITLE
routetable with missing upstream is not flagged as invalid

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2730]
1) Deploy Gloo(E) normally
2) Deploy petstore to default
3) Create and test simple route
`
glooctl add route --name default --path-prefix /api --dest-name default-petstore-8080`

4) Create static upstream

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-pet
spec:
  static:
    hosts:
    - addr: petstore.default.svc.cluster.local
      port: 8080
```

5) Create routetable with missing namespace

```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: routetabletest
spec:
  routes:
  - matchers:
      - prefix: "/2730"
    options:
      prefixRewrite: /api/pets
    routeAction:
      single:
        upstream:
          name: static-pet
```

6) add routetable to vs

```
    - delegateAction:
        ref:
          name: routetabletest
          namespace: gloo-system
```

```
7) Test routetable

$ curl $(glooctl proxy url)/2730 -v
*   Trying 34.106.135.152...
* TCP_NODELAY set
* Connected to 34.106.135.152 (34.106.135.152) port 80 (#0)
> GET /2730 HTTP/1.1
> Host: 34.106.135.152
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< date: Thu, 23 Apr 2020 21:15:25 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host 34.106.135.152 left intact
* Closing connection 0
william-decostes-macbook-pro-2:solo bdecoste$ curl $(glooctl proxy url)/2730 -v
*   Trying 34.106.135.152...
* TCP_NODELAY set
* Connected to 34.106.135.152 (34.106.135.152) port 80 (#0)
> GET /2730 HTTP/1.1
> Host: 34.106.135.152
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 503 Service Unavailable
< date: Thu, 23 Apr 2020 21:16:15 GMT
< server: envoy
< content-length: 0
< 
* Connection #0 to host 34.106.135.152 left intact
* Closing connection 0
```

You end up with a vague 503 response, an envoy route referencing a cluster without a namespace (aka a nonexistant cluster):

```
{
          "match": {
           "path": "/static-pets"
          },
          "route": {
           "cluster": "static-pet",
           "prefix_rewrite": "/api/pets"
          }
         },
```

`: [debug][router] [external/envoy/source/common/router/router.cc:427] [C26600][S6855157425658974289] unknown cluster`

The problem is that this is accepted by Gloo but ends up with a bad Envoy config.

**Comment by corporealshift** [comment]
As far as I can tell this only happens with static upstreams. When I use a kube service upstream it does complain about the upstream being invalid.

**Comment by arianaw66** [comment]
Reproduced with:

1. `glooctl install gateway` (version 1.3.22)
2. `kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml`
3. `kubectl apply -f myManifest.yaml`
where 
`cat myManifest.yaml` gives:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-pet
  namespace: gloo-system
spec:
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /api/pets
    interval: 30s
    timeout: 10s
    unhealthyThreshold: 1
  loadBalancerConfig:
    healthyPanicThreshold: 0
    roundRobin: {}
  static:
    hosts:
    - addr: petstore.default.svc.cluster.local
      port: 8080
    serviceSpec:
      rest:
        swaggerInfo:
          url: http://petstore.default.svc.cluster.local:8080/swagger.json
        transformations:
          addPet:
            body:
              text: '{"id": {{ default(id, "") }},"name": "{{ default(name, "")}}","tag":
                "{{ default(tag, "")}}"}'
            headers:
              :method:
                text: POST
              :path:
                text: /api/pets
              content-type:
                text: application/json
          deletePet:
            headers:
              :method:
                text: DELETE
              :path:
                text: /api/pets/{{ default(id, "") }}
              content-type:
                text: application/json
          findPetById:
            body: {}
            headers:
              :method:
                text: GET
              :path:
                text: /api/pets/{{ default(id, "") }}
              content-length:
                text: "0"
              content-type: {}
              transfer-encoding: {}
          findPets:
            body: {}
            headers:
              :method:
                text: GET
              :path:
                text: /api/pets?tags={{default(tags, "")}}&limit={{default(limit,
                  "")}}
              content-length:
                text: "0"
              content-type: {}
              transfer-encoding: {}
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: routetabletest
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - methods:
      - POST
      - GET
      prefix: /2730
    options:
      prefixRewrite: /api/pets
    routeAction:
      single:
        upstream:
          name: static-pet
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /api
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
    - matchers:
      - prefix: /api
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
    - delegateAction:
        ref:
          name: routetabletest
          namespace: gloo-system
```

**Comment by arianaw66** [comment]
Also reproduced without routetable, when `cat myManifest.yaml` gives:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-pet
  namespace: gloo-system
spec:
  static:
    hosts:
    - addr: petstore.default.svc.cluster.local
      port: 8080
---
#          namespace: gloo-system # this error shows up when the namespace is not specified here
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - routeAction:
        single:
          upstream:
            name: static-pet 
#            namespace: gloo-system # this error shows up when the namespace is not specified here
```

**Comment by arianaw66** [comment]
Manifest for testing multi case: 
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-pet
  namespace: gloo-system
spec:
  static:
    hosts:
    - addr: petstore.default.svc.cluster.local
      port: 8080
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - routeAction:
        multi:
          destinations:
          - weight: 1
            destination:
              upstream:
                name: static-pet
                #namespace: gloo-system # this error shows up when the namespace is not specified here
```

**Comment by arianaw66** [comment]
Manifest for testing upstreamGroup case:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-pet
  namespace: gloo-system
spec:
  static:
    hosts:
    - addr: petstore.default.svc.cluster.local
      port: 8080
---
apiVersion: gloo.solo.io/v1
kind: UpstreamGroup
metadata:
  name: us-group
  namespace: gloo-system
spec:
  destinations:
  - destination:
      upstream:
        name: static-pet
        #namespace: gloo-system # this error shows up when the namespace is not specified here
    weight: 1
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - routeAction:
        upstreamGroup:
          name: us-group
          namespace: gloo-system
```
