### ISSUE TITLE
Checking proxies is failing

### ISSUE THREAD

**Issue by debjitk** [solo-io/gloo#2771]
I am getting the following error while executing a 'glooctl check'

```
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... Problem while checking for out of sync proxies
Error!
timed out trying to connect to localhost during port-forward, errors: 12 errors occurred:
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
        * Get http://localhost:61309/stats/prometheus: dial tcp [::1]:61309: connect: connection refused
```

**Comment by debjitk** [comment]
Here is the configuration values

```
accessLogger:
  enabled: false
  image:
    repository: access-logger
    tag: 1.3.19
  port: 8083
  replicas: 1
  serviceName: AccessLog

crds:
  create: false

discovery:
  deployment:
    floatingUserId: false
    image:
      repository: discovery
      tag: 1.3.19
    replicas: 1
    runAsUser: 10101
  enabled: true
  fdsMode: WHITELIST

gateway:
  certGenJob:
    enabled: true
    image:
      repository: certgen
      tag: 1.3.19
    restartPolicy: OnFailure
    setTtlAfterFinished: true
    ttlSecondsAfterFinished: 60
  deployment:
    floatingUserId: false
    image:
      repository: gateway
      tag: 1.3.19
    replicas: 1
    runAsUser: 10101
  enabled: true
  proxyServiceAccount:
    disableAutomount: false
  readGatewaysFromAllNamespaces: false
  updateValues: false
  validation:
    alwaysAcceptResources: true
    enabled: true
    failurePolicy: Ignore
    secretName: gateway-validation-certs

gatewayProxies:
  gatewayProxy:
    antiAffinity: false
    configMap:
      data: null
    extraInitContainersHelper: ""
    extraListenersHelper: ""
    extraVolumeHelper: ""
    gatewaySettings:
      disableGeneratedGateways: false
      options: {}
      useProxyProto: false
    kind:
      deployment:
        replicas: 1
    podTemplate:
      disableNetBind: false
      floatingUserId: false
      httpPort: 8080
      httpsPort: 8443
      image:
        repository: gloo-envoy-wrapper
        tag: 1.3.19
      probes: false
      runAsUser: 10101
      runUnprivileged: false
      tolerations: null
    readConfig: false
    service:
      httpPort: 80
      httpsFirst: false
      httpsPort: 443
      type: LoadBalancer
      extraAnnotations:
        "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
        "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
        "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "tcp"
        "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"
        "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": "*"

global:
  glooMtls:
    enabled: false
    envoy:
      image:
        repository: gloo-envoy-wrapper
        tag: 1.3.19
    sds:
      image:
        repository: sds
        tag: 1.3.19
  glooRbac:
    create: true
    nameSuffix: ""
    namespaced: false
  glooStats:
    enabled: true
  image:
    pullPolicy: IfNotPresent
    registry: quay.io/solo-io
  wasm:
    enabled: false

gloo:
  deployment:
    disableUsageStatistics: false
    floatingUserId: false
    image:
      repository: gloo
      tag: 1.3.19
    replicas: 1
    runAsUser: 10101
    validationPort: 9988
    xdsPort: 9977

ingress:
  deployment:
    image:
      repository: ingress
      tag: 1.3.19
    replicas: 1
  enabled: false
  requireIngressClass: null

ingressProxy:
  configMap: {}
  deployment:
    httpPort: 80
    httpsPort: 443
    image:
      repository: gloo-envoy-wrapper
      tag: 1.3.19
    replicas: 1
  service:
    type: LoadBalancer

k8s:
  clusterName: cluster3.dc1.riverlab.internal

namespace:
  create: false

settings:
  create: true
  disableKubernetesDestinations: false
  disableProxyGarbageCollection: false
  integrations:
    knative:
      enabled: false
      proxy:
        httpPort: 80
        httpsPort: 443
        image:
          repository: gloo-envoy-wrapper
          tag: 1.3.19
        replicas: 1
        service:
          type: LoadBalancer
      requireIngressClass: null
      version: 0.10.0
  invalidConfigPolicy:
    invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators should run `glooctl check` to find and fix config errors.
    invalidRouteResponseCode: 404
  linkerd: false
  singleNamespace: false
```
