### ISSUE TITLE
Gloo admin UI hangs when proxied via Gloo (Response closed without grpc-status)

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#2788]
## Description
When exposing the Gloo UI through a Virtual Service, the UI display indefinitely displays the loading spinner.

## To reproduce
- Install GlooE 1.3.0
- Apply this virtual service 
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: glooui-devportal
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: gloo-system-apiserver-ui-8080
            namespace: gloo-system
```
- Run `glooctl proxy url` and navigate to that URL in your browser

You should see this:
![image](https://user-images.githubusercontent.com/16148461/79282015-14eac580-7e82-11ea-8524-39d7e491d8e1.png)

The console shows multiple occurrences of the same error:
![image](https://user-images.githubusercontent.com/16148461/79282457-40ba7b00-7e83-11ea-81df-910b6f8ff840.png)

## Cause
We are using gRPC web in our UI, so we rely on the `grpc_web` filter, which is enabled by default in Gloo. Envoy uses that filter to convert a `grpc-web+proto` request to `grpc`, but since the `apiserver` upstream is not marked as `http2`, the `grpc_web` filter ignores the trailers in the response (instead of adding them to the body of the response). This causes an error in the `grpc-web` client library we use in the UI, because the response does not contains the required `grpc-status` header (neither in the body, not in a HTTP/2 trailer).

## Fix
We need to add the `gloo.solo.io/h2_service: "true"` annotation to the `apiserver-ui` service, sp discovery will set `useHttp2` to `true` on the corresponding upstream.
