### ISSUE TITLE
support host rewrite for healthchecks for multiple endpoint hosts in static and consul upstreams

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2794]
The upstream envoy change has been made for this but we need to support either upstream.healthChecks.httppHealthCheck.host as an array or upstream.healthChecks.httpHealthCheck.autoHostRewrite. 

In the following scenario, if bar.example.com requires a host rewrite then that health check will always fail:

```
kind: Upstream
metadata:
  name: static-pet
  namespace: gloo-system
spec:
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      host: foo.example.com
      path: /api/pets
    interval: 30s
    timeout: 10s
    unhealthyThreshold: 1
  static:
    hosts:
    - addr: foo.example.com
      port: 8080
    - addr: bar.example.com
      port: 8080
```

**Comment by ashleywang1** [comment]
1) The upstream changes were made here: https://github.com/envoyproxy/envoy/issues/10408
The 'Hostname' field was added to the Endpoint struct and the Endpoint_HealthCheckConfig struct in envoy/api/v2/endpoint/endpoint_components.pb.go.

Setting this to a non-empty value allows overriding the cluster level configuration for a specific endpoint.

2) [ 'auto host rewriting' in Envoy](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-routeaction-auto-host-rewrite): 
During forwarding, the host header will be swapped with the hostname of the upstream host chosen by the cluster manager. This can be customized by setting the Hostname field in the Endpoint struct described in #1.

3) 'autoHostRewrite' on a Gloo's virtual service:
If the option 'autoHostRewrite' is set to true - Indicates that the host header will be swapped with the hostname of the upstream host. This is how Gloo's config version of the feature that already exists in envoy.

4) health checks in Gloo Upstreams, or the envoy HealthCheck_HttpHealthCheck 'host field': If
left empty (default value), the name of the cluster this health check is associated with will be used. This can be customized by setting the Hostname field in the Endpoint_HealthCheckConfig struct described in #1.

Ok, now that our terminology is clear, let's look at what the problem actually is:

**Comment by ashleywang1** [comment]
Introduction to healthchecks, using the following static upstream and vs:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: test-upstream
  namespace: gloo-system
spec:
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /
    interval: 30s
    timeout: 10s
    unhealthyThreshold: 100
  static:
    hosts:
    - addr: jsonplaceholder.typicode.com
      port: 80
    - addr: httpstat.us
      port: 80

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matchers:
        - prefix: /
        routeAction:
          single:
            upstream:
              name: test-upstream
              namespace: gloo-system
        options:
          autoHostRewrite: true
```

Run both `curl -H "Host: foo" $(glooctl proxy url)/200` and `curl -H "Host: foo" $(glooctl proxy url)/posts/1` several times to see that we _are_ hitting both static hosts.

Run `k port-forward -n gloo-system deploy/gateway-proxy 19000` and go to http://localhost:19000/clusters.

You should see the following lines:
```
test-upstream_gloo-system::104.28.28.222:80::hostname::jsonplaceholder.typicode.com
test-upstream_gloo-system::104.28.28.222:80::health_flags::/failed_active_hc
test-upstream_gloo-system::23.99.0.12:80::hostname::httpstat.us
test-upstream_gloo-system::23.99.0.12:80::health_flags::/failed_active_hc
```

This means that our healthchecks are messing up.
