### ISSUE TITLE
customizing shadow request

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2796]
In Gloo, we can integrate with linkerd with a setting or a request transformation, to tell Gloo to add a header that helps the linkerd sidecar with networking. 

This raises a question of how to take advantage of shadowing when integrating with linkerd, because there would be a different destination for the real upstream and the shadow upstream. 

EDIT: initial use case was transforming shadow header for linkerd integration. Another use case for transforming the body came up, so I generalized this issue.

**Comment by rickducott** [comment]
Spoke with @yuval-k, this would require an upstream envoy change to expose headers to add on the shadowing config.

**Comment by rickducott** [comment]
Another user requested transformations only for shadowed request with a VS like this:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: gateway
  namespace: zerodown-shadow-poc
spec:
  displayName: gateway-transformation
  virtualHost:
    domains:
    - foo.bar
    routes:
    - matchers:
      - prefix: '/api/http-test'
      routeAction:
        single:
          upstream:
            name: zerodown-shadow-poc-blue-http-test-80
            namespace: zerodown-shadow-poc
      options:
        transformations:
          requestTransformation:
            transformationTemplate:
              passthrough: {}
              headers:
                orgid: 
                  text: '{{ header("orgid") }}-shadow'
        shadowing:
          upstream:
            name: zerodown-shadow-poc-green-http-test-80
            namespace: zerodown-shadow-poc
          percentage: 100
```
