### ISSUE TITLE
cannot use helm settings values unique to gloo in glooe

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#2822]
If you install gloo then the following are valid, but cannot be configured using glooe. They are from the gloo 18-settings.yaml but not in the glooe 40-settings.yaml

```
settings:
  writeNamespace: gloo-system
  integrations:
    knative:
      enabled: true
      version: "1.0.0"
  linkerd: true
```
