### ISSUE TITLE
invalid rate limit settings silently not applied

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#2832]
Found two cases of invalid rate limiting config not being applied as expected, but not reporting errors:

Case 1:

```
spec:
  ratelimit:
    descriptors:
      - key: apikey
        rate_limit:
          requests_per_unit: 1
          unit: MINUTE
      - key: apikey
        descriptors:
          - key: plan
            value: BASIC
            rateLimit:
              requestsPerUnit: 1
              unit: MINUTE
          - key: plan
            value: PLUS
            rateLimit:
              requestsPerUnit: 20
              unit: MINUTE
```

Using the same key name twice in the toplevel descriptors caused only the first one to be picked up, the second one dropped. 

Case 2:
```
spec:
  ratelimit:
    descriptors:
      - key: apikey
        rate_limit:
          requests_per_unit: 1
          unit: MINUTE
        descriptors:
          - key: plan
            value: BASIC
            rateLimit:
              requestsPerUnit: 1
              unit: MINUTE
          - key: plan
            value: PLUS
            rateLimit:
              requestsPerUnit: 2
              unit: MINUTE
          - key: plan
            value: PLUS
            rateLimit:
              requestsPerUnit: 10
              unit: DAY
```

Using "plan" as a key twice in the nested descriptor causes the rate limiting config to be silently dropped altogether.

**Comment by yuval-k** [comment]
case 1 sounds like a bug; there should be two rate limits based on the value;

i'm not sure i'm seeing how case 2 is different? i don't see the nesting.. should the last block be indented?

**Comment by rickducott** [comment]
@yuval-k when I apply that 2nd config, I get nothing in my `rlconfig` when I go to the admin UI for the rate-limit service. I figured it was a distinct bug because I had a partial config in case 1.

**Comment by rickducott** [comment]
FWIW, I was trying to express this:

settings:
```yaml
spec:
  ratelimit:
    descriptors:
      - key: apikey
        rate_limit:
          requests_per_unit: 1
          unit: MINUTE
        descriptors:
          - key: plan-per-minute
            value: BASIC
            rateLimit:
              requestsPerUnit: 2
              unit: MINUTE
          - key: plan-per-minute
            value: PLUS
            rateLimit:
              requestsPerUnit: 5
              unit: MINUTE
          - key: plan-per-hour
            value: BASIC
            rateLimit:
              requestsPerUnit: 20
              unit: HOUR
          - key: plan-per-hour
            value: PLUS
            rateLimit:
              requestsPerUnit: 50
              unit: HOUR
```

virtual service:
```yaml
      - matchers:
          - prefix: /
        options:
          ratelimit:
            rateLimits:
              - actions:
                  - requestHeaders:
                      descriptorKey: apikey
                      headerName: x-api-key
                  - requestHeaders:
                      descriptorKey: plan-per-minute
                      headerName: x-api-plan
              - actions:
                  - requestHeaders:
                      descriptorKey: apikey
                      headerName: x-api-key
                  - requestHeaders:
                      descriptorKey: plan-per-hour
                      headerName: x-api-plan
```

The config in the description above was an earlier attempt, thinking I could maybe support this with a single rate limit action.
