### ISSUE TITLE
How can I route http traffic to a k8s service at L4 ?

### ISSUE THREAD

**Issue by debjitk** [solo-io/gloo#2891]
How can I route http traffic to a k8s service at L4 ? I do not wish to use L7. Also to note I have disabled discovery in my gloo installation.

**Comment by ilackarms** [comment]
have you seen https://docs.solo.io/gloo/latest/guides/traffic_management/listener_configuration/tcp_proxy/ ?

**Comment by debjitk** [comment]
@ilackarms Yes. I presume in the document it is assumed that discovery is enabled in gloo installation as there is no documentation on the mentioned document of how to create the upstream 'gloo-system-tcp-echo-1025'.

**Comment by rickducott** [comment]
Here's an example. Suppose I have a service like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: spelunker
  namespace: spelunker
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: spelunker
```

I'll create an upstream like this: 

```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: http
  namespace: spelunker
spec:
  discoveryMetadata: {}
  kube:
    selector:
      app: spelunker
    serviceName: spelunker
    serviceNamespace: spelunker
    servicePort: 80
```

And I can route to that upstream by configuring TCP on my gateway CRD:

```yaml

apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  tcpGateway:
    tcpHosts:
      - name: http
        destination:
          single:
            upstream:
              name: http
              namespace: spelunker
  useProxyProto: false
```

With L4 proxying the feature set is limited, but you can find this, as well as a TLS example, here: https://github.com/solo-io/gloo-ref-arch/tree/master/encryption/part2.

**Comment by rickducott** [comment]
Let us know if that doesn't address your questions @debjitk! Will mark this as closed until we hear from you.

**Comment by debjitk** [comment]
@rickducott I did exactly the same as suggested in the sample configuration. Also, what if the service protocol is HTTP instead of TCP? I presume the sample configuration would still be proxying at L4. Am i right?

**Comment by rickducott** [comment]
Yes, that's right.

**Comment by debjitk** [comment]
@rickducott How do update the gloo gate-proxy service to listen to my tcp gateway ?

**Comment by debjitk** [comment]
Here is my gateway configuration

```
---
# Upstream
# 
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: domain-elastic-cluster-1-9200
  namespace: gloo-system
spec:
  kube:
    serviceName: elastic-elasticsearch-cluster-1-coordinator
    serviceNamespace: domain-elastic-cluster-1
    servicePort: 9200
---
# Gateway
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-domain-elastic-cluster-1-9200
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 9200
  tcpGateway:
    tcpHosts:
    - name: tcp
      destination:
        single:
          upstream:
            name: domain-elastic-cluster-1-9200
            namespace: gloo-system
  ssl: false
  useProxyProto: false
```

Here is the output for `kubectl get proxies.gloo.solo.io -n gloo-system -oyaml`

```
apiVersion: v1
items:
- apiVersion: gloo.solo.io/v1
  kind: Proxy
  metadata:
    creationTimestamp: "2020-05-03T06:52:00Z"
    generation: 2
    labels:
      created_by: gateway
    name: gateway-proxy
    namespace: gloo-system
    resourceVersion: "55377"
    selfLink: /apis/gloo.solo.io/v1/namespaces/gloo-system/proxies/gateway-proxy
    uid: 09e1ebf2-2bd2-4981-bfa7-addd5f359544
  spec:
    listeners:
    - bindAddress: '::'
      bindPort: 9200
      metadata:
        sources:
        - kind: '*v1.Gateway'
          name: gateway-domain-elastic-cluster-1-9200
          namespace: gloo-system
          observedGeneration: 1
      name: listener-::-9200
      tcpListener:
        tcpHosts:
        - destination:
            single:
              upstream:
                name: domain-elastic-cluster-1-9200
                namespace: gloo-system
          name: tcp
      useProxyProto: false
  status:
    reported_by: gloo
    state: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

According to gloo documentation now i would have to update the `gloo-proxy` service configuration.

I am clueless now ??
