### ISSUE TITLE
Virtual service pending

### ISSUE THREAD

**Issue by debjitk** [solo-io/gloo#2907]
Virtual service is pending. Here is the yaml output

```
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.solo.io/v1","kind":"VirtualService","metadata":{"annotations":{},"name":"consul-server-8500","namespace":"gloo-resources"},"spec":{"virtualHost":{"domains":["consul.dc1.domain.internal"],"routes":[{"matchers":[{"prefix":"/"}],"name":"route","routeAction":{"single":{"upstream":{"name":"consul-server-8500","namespace":"gloo-resources"}}}}]}}}
  generation: "1"
  name: consul-server-8500
  namespace: gloo-resources
  ownerReferences: []
  resourceVersion: "520187"
status: {}
virtualHost:
  domains:
  - consul.dc1.domain.internal
  routes:
  - matchers:
    - prefix: /
    name: route
    routeAction:
      single:
        upstream:
          name: consul-server-8500
          namespace: gloo-resources
```

**Comment by rickducott** [comment]
Can you run `glooctl check`

**Comment by debjitk** [comment]
Here is the check result

```
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... Your gateway-proxy is out of sync with the Gloo control plane and is not receiving valid gloo config.
You may want to try using the `glooctl proxy logs` or `glooctl debug logs` commands.
```

**Comment by rickducott** [comment]
Hmm, ok. That doesn't really clarify what the issue is, let's try looking around the logs for errors in one of the control plane pods. You can run this command: `glooctl debug logs --errors-only`

**Comment by debjitk** [comment]
This is the only error and it is caused by the route table configuration

```
{
  "level": "error",
  "ts": "2020-04-29T22:13:27.407Z",
  "logger": "gateway.v1.event_loop.gateway",
  "caller": "syncer/setup_syncer.go:263",
  "msg": "error: event_loop: v1.emitter errors: -routeTables: converting output crd: reading crd spec on resource riverlab-consul-server-8500 in namespace gloo-resources into v1RouteTable: json: cannot unmarshal string into Go value of type map[string]json.RawMessage",
  "version": "1.3.23",
  "stacktrace": "github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gloo/projects/gateway/pkg/syncer/setup_syncer.go:263"
}
```

The route table configuration

```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: "riverlab-consul-server-8500"
  namespace: "gloo-resources"
spec:
  routes:
  - matchers:
    - "/"
    routeAction:
      single:
        upstream:
          name: riverlab-consul-server-8500
          namespace: gloo-resources
```

I am not using the route table in the virtual service.

Here is the entire configuration

```
---
# Upstream
# 
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: "mydomain-consul-server-8500"
  namespace: "gloo-resources"
spec:
  kube:
    serviceName: "consul-server"
    serviceNamespace: "mydomain-consul"
    servicePort: 8500
---
# Route table
# 
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: "mydomain-consul-server-8500"
  namespace: "gloo-resources"
spec:
  routes:
  - matchers:
    - "/"
    routeAction:
      single:
        upstream:
          name: mydomain-consul-server-8500
          namespace: gloo-resources
---
# Virtual service
# 
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: 'mydomain-consul-server-8500'
  namespace: 'gloo-resources'
spec:
  virtualHost:
    domains:
    - "consul.dc1.mydomain.internal"
    routes:
    - name: "route"
      matchers:
      - prefix: "/"
      routeAction:
        single:
          upstream:
            name: "mydomain-consul-server-8500"
            namespace: "gloo-resources"
```

**Comment by debjitk** [comment]
When the above configuration is applied to namespace "gloo-system" everything is working. But on a different namespace like "gloo-resources" is giving problem. Why is that so ?

**Comment by rickducott** [comment]
Ah, so the problem is your route table matcher is malformed - it should be `- prefix: "/"`:

```yaml
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: "mydomain-consul-server-8500"
  namespace: "gloo-resources"
spec:
  routes:
  - matchers:
    - prefix: "/"
    routeAction:
      single:
        upstream:
          name: mydomain-consul-server-8500
          namespace: gloo-resources
```

This configuration cleanly applied for me after this was fixed.
