### ISSUE TITLE
`glooctl get ug` shows unexpected and inconsistent behavior, implying race involving gloo pod

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#2954]
**Describe the bug**
`glooctl get ug` showed an inconsistent eventual state, implying a race condition involving the gloo pod. It also marked the upstreamGroup as Accepted despite looking for an upstream without a namespace specified.

**To Reproduce** (Also see "Additional unexpected behavior that may be relevant" comment for a more reliable way to reproduce what is likely but not definitely the same bug.)
1. Deploy petstore: `kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml `
2. Install gloo with local version of code as described in "Additional Context" section: `glooctl install gateway -f _test/gloo-1.4.0-beta7-10-g2d97d321-dirty.tgz`
3. Apply manifest shown in "Additional Context" section: `kubectl apply -f myManifest.yaml`
4. `glooctl get ug` until it is stable

This will sometimes show the upstream destination without the namespace filled in:
```
+----------------+----------+--------------+----------------------------+
| UPSTREAM GROUP |  STATUS  | TOTAL WEIGHT |          DETAILS           |
+----------------+----------+--------------+----------------------------+
| us-group       | Accepted | 1            | destination type: Upstream |
|                |          |              | namespace:                 |
|                |          |              | name: static-pet           |
|                |          |              | weight: 1   % total: 1.00  |
+----------------+----------+--------------+----------------------------+
```
and will sometimes show it with the namespace filled in:
```
+----------------+----------+--------------+----------------------------+
| UPSTREAM GROUP |  STATUS  | TOTAL WEIGHT |          DETAILS           |
+----------------+----------+--------------+----------------------------+
| us-group       | Accepted | 1            | destination type: Upstream |
|                |          |              | namespace: gloo-system     |
|                |          |              | name: static-pet           |
|                |          |              | weight: 1   % total: 1.00  |
+----------------+----------+--------------+----------------------------+
```

To see both versions, repeat these commands until you get what you're looking for:
5. `kubectl delete -f myManifest.yaml`
6. `kubectl apply -f myManifest.yaml`
7. `glooctl get ug` until it is stable

**Expected behavior**
I would expect the output of `glooctl get ug` to always eventually show the upstream destination with the namespace filled in:
```
➜ glooctl get ug
+----------------+----------+--------------+----------------------------+
| UPSTREAM GROUP |  STATUS  | TOTAL WEIGHT |          DETAILS           |
+----------------+----------+--------------+----------------------------+
| us-group       | Accepted | 1            | destination type: Upstream |
|                |          |              | namespace: gloo-system     |
|                |          |              | name: static-pet           |
|                |          |              | weight: 1   % total: 1.00  |
+----------------+----------+--------------+----------------------------+
```
and to never show the upstreamGroup as Accepted if the namespace on the upstream destination is empty.

My current understanding is that the destination upstream namespace is set here https://github.com/solo-io/gloo/blob/dbe90b58e550094027414056d3e8ad854ae06e00/projects/gloo/pkg/translator/upstream_groups.go#L24 before we write reports here https://github.com/solo-io/gloo/blob/dbe90b58e550094027414056d3e8ad854ae06e00/projects/gloo/pkg/syncer/envoy_translator_syncer.go#L184.
Therefore, by the time we write an Accepted status to the upstreamGroup resource, the namespace should always have been filled in.

**Additional context**

- Bug discovered while fixing https://github.com/solo-io/gloo/issues/2730

- Reproduced by installing gloo with code from gitish dbe90b58e550094027414056d3e8ad854ae06e00 in addition to another change removing `namespace == "" || ` from this line https://github.com/solo-io/gloo/blob/dbe90b58e550094027414056d3e8ad854ae06e00/projects/gloo/pkg/api/v1/upstream.sk.go#L52

- The version of solo-kit in the gloo repo is tag 0.13.6

- `myManifest.yaml` contains:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-pet
  namespace: gloo-system
spec:
  static:
    hosts:
    - addr: petstore.default.svc.cluster.local
      port: 8080
---
apiVersion: gloo.solo.io/v1
kind: UpstreamGroup
metadata:
  name: us-group 
  namespace: gloo-system
spec:
  destinations:
  - destination:
      upstream:
        name: static-pet 
        #namespace: gloo-system # this error shows up when the namespace is not specified here
    weight: 1
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - routeAction:
        upstreamGroup:
          name: us-group 
          namespace: gloo-system 
```

- The gloo version:
```
➜ glooctl version
Client: {"version":"1.3.22"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.4.0-beta7-10-g2d97d321-dirty","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.4.0-beta7-10-g2d97d321-dirty","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.4.0-beta7-10-g2d97d321-dirty","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.4.0-beta7-10-g2d97d321-dirty","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}
```

- The kubernetes version:
```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
