### ISSUE TITLE
Support empty SSL config via service annotations

### ISSUE THREAD

**Issue by via-jordan-sokolic** [solo-io/gloo#3011]
Auto-discovered kubernetes upstreams can be partially configured with service annotations, such as `sslConfig` per the [docs](https://docs.solo.io/gloo/latest/guides/security/tls/client_tls_service_annotations/).

Since #2874, it would be helpful to support configuring an empty `sslConfig` using service annotations, mitigating the need to manually edit the upstream after discovery.
I propose splitting the port specifier annotation out from the secret annotation, i.e.:
```
kind: Service
metadata:
  name: my-service
  namespace: default
  annotations:
    gloo.solo.io/sslService.tlsPort: "443"
```
which would result in an `Upstream` config like:
```
kind: Upstream
metadata:
  name: default-my-service-443
  namespace: gloo-system
...
spec:
  sslConfig: {}
```

Following some discussion with @kdorosh.

Thanks!
