### ISSUE TITLE
Unable to use Gloo transformations for Lambda upstreams

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3019]
**Describe the bug**
When utilizing a Gloo transformation to add a body for a request routed to an AWS Lambda upstream, the request will hang and envoy will not actually route the request to the upstream. Note that if a body (even empty) is specified, this bug will not occur

**To Reproduce**
Create a route to a Lambda upstream and use the following transformation:
```
      options:
        transformations:
          requestTransformation:
            transformationTemplate:
              extractors:
                pathArg:
                  header: arg
                  regex: .*
              mergeExtractorsToBody: {}
```

With a curl request (to the route/virtualHost this transformation is applied to):
```curl "$(glooctl proxy url)/route" -H 'arg: foo' -v```

**Expected behavior**
The body should be successfully created based off the transformations applied. Additionally, a log should be present and/or the request shouldn't hang indefinitely.

**Additional context**
Issue more than likely in upstream Envoy. Seems to be related to having 2 filters that do transformation (e.g. transformation filter and lambda filter).

Per @yuval-k --

> for reference, we hit this return:
> https://github.com/envoyproxy/envoy/blob/e71d1622d622ab19dd962538908f1baa6e0483b1/source/common/http/conn_manager_impl.cc#L1099
> instead of this continue decoding:
> https://github.com/envoyproxy/envoy/blob/e71d1622d622ab19dd962538908f1baa6e0483b1/source/common/http/conn_manager_impl.cc#L1116

>if the next filter that stops the iteration is the router filter, it will work. in our case it is the aws filter, so it doesn't work
