### ISSUE TITLE
Ingress objects that specify servicePort: serviceportname do not work

### ISSUE THREAD

**Issue by cweidinger** [solo-io/gloo#3050]
**Describe the bug**
Ingress objects that specify servicePort: serviceportname do not work

**To Reproduce**
0. Be using gloo as ingress controller
1. run
```
cat > service.yaml
apiVersion: v1
kind: Service
metadata:
  name: myservicename
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  type: ClusterIP

ctrl-D

cat > ingress.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  namespace: default
spec:
  rules:
  - host: myhost
    http:
      paths:
      - backend:
          serviceName: myservicename
          servicePort: http
Ctrl-D
kube apply -f *.yaml
``` 
2. See that it doesn't work
3. $ k logs ingress-6564685644-n6d5k -n gloo-admin | grep rejected
{"level":"warn","ts":"2020-05-21T16:26:01.518Z","logger":"ingress.v1.event_loop.ingress.v1.event_loop.translatorSyncer","caller":"translator/translator_syncer.go:55","msg":"snapshot 3469490729078001599 was rejected due to invalid config: computing virtual hosts: lookup upstream for ingress myingress: discovery failure: upstream not found for kube service myservicename with port {1 0 http}\ningress proxy will not be updated.","version":"1.3.27"}

3. change servicePort to be 8080 and see it work.

**Expected behavior**
https://kubernetes.io/docs/concepts/services-networking/ingress/ states "A backend is a combination of Service and port names as described in the Service doc. HTTP (and HTTPS) requests to the Ingress that matches the host and path of the rule are sent to the listed backend."
We're currently using Traefik as an ingress controller and it works using serviceportnames so converting all our ingress CRDs would be work we don't want to have to do.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version 1.3.27
- Kubernetes version 1.14
