### ISSUE TITLE
Observability dynamic dashboards incorrect for non-discovered upstreams 

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3061]
**Describe the bug**
The dynamic dashboards created by `observability` use the upstream/envoy cluster naming convention for discovered upstreams when creating dashboards for all upstreams, regardless of the actual name of the upstream.

**To Reproduce**
Create an upstream manually, e.g. --
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: petstore
  namespace: gloo-system
spec:
  kube:
    serviceName: petstore
    serviceNamespace: default
    servicePort: 8080
```

The generated dashboard will have a query similar to --
`irate(envoy_cluster_upstream_rq_total{ envoy_cluster_name="default-petstore-8080_gloo-system" }[1m])`

**Expected behavior**
The query should be created according to the actual name of the Upstream/the envoy cluster. For the above example it should be --
`irate(envoy_cluster_upstream_rq_total{ envoy_cluster_name="petstore_gloo-system" }[1m])`
