### ISSUE TITLE
Lambda Upstream status incorrect when secret is deleted

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3062]
**Describe the bug**
When using an AWS lambda upstream, if the secret containing the AWS credentials is deleted and then recreated, the `status` for that upstream will show as `Rejected` indefinitely even though the secret exists.

**To Reproduce**
1. Create a secret containing AWS credentials
2. Create a Lambda upstream referencing that secret
3. Delete secret (`VirtualService` routing to the lambda will stop working)
4. Recreate secret (`VirtualService` routing to the lambda works again)
5. Check status of upstream, should still show an error similar to below

```
status:
  reason: "1 error occurred:\n\t* retrieving aws secret: list did not find secret
    gloo-system.aws-creds\n\n"
  reportedBy: gloo
  state: Rejected
```

**Expected behavior**
The `Rejected` status should be cleared out if the `Upstream` is back to a functional state
