### ISSUE TITLE
delegated weighted routes are not sorted globally

### ISSUE THREAD

**Issue by oboukili** [solo-io/gloo#3085]
**Describe the bug**
A route of higher weight (10) can override a route of lesser weight (0-9) depending the routeDelegateAction ordering within the virtualservice.

**To Reproduce**
Create a virtual service with 2 delegations for the same prefix matcher, with different routeTableSelectors, example with simple different namespace selectors:

```yaml
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: foo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - foo.io
    routes:
      - matchers:
          - prefix: /
        delegateAction:
          selector:
            namespaces:
              - "ns1"
      - matchers:
          - prefix: /
        delegateAction:
          selector:
            namespaces:
              - "ns2"
```

Create the following routeTables:
```yaml
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: first
  namespace: ns1
spec:
  routes:
    - matchers:
        - prefix: /foo/a/
      routeAction:
        single:
          upstream:
            name: ns1-first-80
            namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: second
  namespace: ns2
spec:
  // also happens with default weight of 0
  weight: 5
  routes:
    - matchers:
        - prefix: /foo/b/
      routeAction:
        single:
          upstream:
            name: ns2-second-80
            namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: third
  namespace: ns1
spec:
 weight: 10
  routes:
    - matchers:
        - prefix: /
      routeAction:
        single:
          upstream:
            name: ns1-third-80
            namespace: gloo-system
```

Observe  the resulting route ordering in the proxy resource (first, third, second):
```
glooctl get proxy -o yaml 
```

**Expected behavior**

The ordering should be first, second, third

**Additional context**

- Gloo version 1.3.9
- Kubernetes version 1.16.8-gke.15

Unit tests that helped me confirm this behavior is done on purpose even on latest Gloo (master branch / 1.4.0-beta12 tag), add in `translator_test` package, in file `projects/gateway/pkg/translator/converter_test.go`) 

```go
Describe("route tables with weights and different label selectors", func() {

			var rt1a, rt1b, rt2 *v1.RouteTable

			buildVirtualServiceWithMultipleRoutes := func(routes []*v1.Route) *v1.VirtualService {
				return &v1.VirtualService{
					Metadata: core.Metadata{
						Name:      "vs-1",
						Namespace: "ns-1",
					},
					VirtualHost: &v1.VirtualHost{
						Routes: routes,
					},
				}
			}

			BeforeEach(func() {

				// Matches rt1a, rt1b, rt2
				vs = buildVirtualServiceWithMultipleRoutes([]*v1.Route{
					{
						Matchers: []*matchers.Matcher{{
							PathSpecifier: &matchers.Matcher_Prefix{
								Prefix: "/foo/",
							},
						}},
						Action: &v1.Route_DelegateAction{
							DelegateAction: &v1.DelegateAction{
								DelegationType: &v1.DelegateAction_Selector{
									Selector: &v1.RouteTableSelector{
										Labels:     map[string]string{"foo": "bar"},
										Namespaces: []string{"*"},
									},
								},
							},
						},
					},
					{
						Matchers: []*matchers.Matcher{{
							PathSpecifier: &matchers.Matcher_Prefix{
								Prefix: "/foo/",
							},
						}},
						Action: &v1.Route_DelegateAction{
							DelegateAction: &v1.DelegateAction{
								DelegationType: &v1.DelegateAction_Selector{
									Selector: &v1.RouteTableSelector{
										Labels:     map[string]string{"bar": "baz"},
										Namespaces: []string{"*"},
									},
								},
							},
						},
					},
				})

				// No weight
				rt1a = buildRouteTableWithSimpleAction("rt-1a", "ns-1", "/foo/a/", map[string]string{"foo": "bar"})

				// heavy weight
				rt1b = buildRouteTableWithSimpleAction("rt-1b", "ns-1", "/foo/", map[string]string{"foo": "bar"})
				rt1b.Weight = &types.Int32Value{Value: 10}

				// middle weight
				rt2 = buildRouteTableWithSimpleAction("rt-2", "ns-2", "/foo/b/", map[string]string{"bar": "baz"})
				rt2.Weight = &types.Int32Value{Value: 5}

				allRouteTables = v1.RouteTableList{rt1a, rt1b, rt2}
			})

			It("works as expected", func() {

				converted, err := visitor.ConvertVirtualService(vs)

				Expect(err).NotTo(HaveOccurred())
				Expect(converted).To(HaveLen(3))

				Expect(converted[0]).To(WithTransform(getFirstPrefixMatcher, Equal("/foo/a/")))
				Expect(converted[1]).To(WithTransform(getFirstPrefixMatcher, Equal("/foo/b/")))
				Expect(converted[2]).To(WithTransform(getFirstPrefixMatcher, Equal("/foo/")))
			})
		})
```

**Comment by marcogschmidt** [comment]
Hi @oboukili , thanks for the detailed issue. As you mentioned, this is indeed intended behavior. Weights are not global, they only determine how a `delegateAction` sorts the routes on its direct children. The process is recursive; please see [this comment](https://github.com/solo-io/gloo/pull/2370#discussion_r376148890) on the PR that introduced the feature for a more detailed explanation.

This behavior was chosen to enable our delegation model. A resource can delegate the action for a particular route, but children should not be able to impact other routes on the parent. If we allowed global weights, any table would be able to influence the order of routes on any of its parents, potentially breaking them.

In the example you provided, you could achieve the desired ordering by specifying both namespaces on the same selector:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: foo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - foo.io
    routes:
      - matchers:
          - prefix: /
        delegateAction:
          selector:
            namespaces:
              - "ns1"
              - "ns2"
```

Do you have a use case where this configuration would not work, or one for which our model results in awkward resources? If so, I'd be happy to work with you to figure out how we can solve the issue.

**Comment by oboukili** [comment]
Thanks for the reply, indeed I understand it better now. However while the namespace selector works well in that example, having multiple labelSelectors for a single matcher would actually solve my issue.

We are using weights on our development environment to setup 'ephemeral' environments that corresponds to a set of Kubernetes deployments, services, virtualservice, and routeTables. Basically it's a carbon copy of a the 'vanilla' dev environment, allowing a developer to test out their current PR work, with all the current services of the dev 'vanilla' environment.

The 'vanilla' routeTables may expose any combination of the following labels (simplified):
* `marketplace-endpoint: enabled`
* `backoffice-endpoint: enabled`

The 'ephemeral' routeTables expose different labels not to disturb the vanilla dev environment:
* `marketplace-endpoint-ephemeral: enabled`
* `backoffice-endpoint-ephemeral: enabled`
* `ephemeral: someid`

The resulting ephemeral virtualservice is as follows, and hence my issue with unfortunate 'catch-all' routes with high weights (such as `prefix: /api/ or /` :( ):

```yaml
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: backoffice-https-someid
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - someid.backoffice.corp
    # Matches both 'vanilla' and 'ephemeral' dev RouteTables
    # In case of a path / path prefix conflict between 'ephemeral' and 'vanilla' RouteTables,
    # 'ephemeral' have the highest priority.
    routes:
      - matchers:
          - prefix: /
        delegateAction:
          selector:
            labels:
              backoffice-endpoint-ephemeral: enabled
              ephemeral: someid
            namespaces:
              - "*"
      - matchers:
          - prefix: /
        delegateAction:
          selector:
            labels:
              # Vanilla dev RouteTables will also be selected
              backoffice-endpoint: enabled
            namespaces:
              - "*"
```

I guess to circumvent this issue at the present time, I would have to:
1. Deploy a new set of kv labels on existing routeTables such as `catchall: true` and `catchall: false` (apparently the existing RT labelSelector does not support [set-based selection](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#_set-based_-requirement) ?)
2. add new routes with delegateAction _after_ the first ones to ensure those do not eat the other ones, but there still might be the same issues between 'catchall' routes

**Comment by marcogschmidt** [comment]
@oboukili Sorry, found some time only now to look into this. Thanks for explaining your use case. I think that enhancing the current selector - like you suggested - is the way to go. 

Specifically, I think we should adopt the same API that Kubernetes uses for set-based selectors (see [this section](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#_set-based_-requirement ) of the doc you linked to) and add a new `expressions` field to our selector:

```yaml
delegateAction:
  selector:
    labels:
      foo: bar
    namespaces:
    - "*"
    expressions:
    - key: label-1
      operator: In
      values:
      - value-1
      - value-2
    - key: label-2
      operator: In
      values:
      - value-3
```

The semantics would be the same as the ones in the Kubernetes API, i.e. all requirements in the selector (`labels`, `namespaces`, `expressions`) are ANDed together. We could start by just implementing the `In` operator initially (since that should be enough for your use case) and add the other ones successively.

Let me know what you think. Also, you mentioned in the community Slack that you would be willing to contribute this feature yourself. Let me know if this is still the case; I'd be happy to discuss the changes in more detail and help you get started.
