### ISSUE TITLE
A single invalid `AuthConfig` can halt processing of other auth valid `AuthConfig`s

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3097]
**Describe the bug**

if a route table is incorrectly configured with a bad reference to another `AuthConfig` (e.g. one that doesnt exist) the ExtAuth pod does not receive any more configuration updates (tested in glooe 1.3.4).

In `projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go` in Gloo Enterprise, we make calls to `processAuthExtension` that return error for the entire `SyncAndSet` call, rather than just appending an error to the resource reports and continuing to process other `AuthConfig`s.

We also do the same thing in the rate limit translator syncer.

**To Reproduce**
1. Install Gloo Enterprise
2. Sample route table config
```
spec:
  routes:
    - matchers:
      - methods:
        - POST
        prefix: /v1/someapp/
      options:
        extauth:
          configRef:
            name: this-is-a-fake-plugin-ref
            namespace: gloo-system
      routeAction:
        single:
          upstream:
            name: someappapp-upstream
            namespace: gloo-system
```

**Expected behavior**
Add errors to report but also continue to process other auth configs

**Additional context**
Related issue https://github.com/solo-io/gloo/issues/2623
