### ISSUE TITLE
validation accepts route table without a route action

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3100]
**Describe the bug**
validation accepts route table without a route action

**To Reproduce**
1. Install Gloo Enterprise 1.3.9
2. Edit the validation settings to set `alwaysAccept` to false (`kubectl edit settings -n gloo-system`)
3. forward validation api so you can hit from your local machine, `kubectl port-forward -n gloo-system deploy/gateway 8443`
4. post the invalid route table to validation API: `curl -k -XPOST -d '{  "request": { "uid": "1234", "kind": {"group": "gateway.solo.io","version": "v1","kind": "RouteTable" }, "resource": {"group": "","version": "","resource": "" }, "name": " invalid-rt", "namespace": "gloo-system", "operation": "CREATE", "userInfo": {}, "object": {"apiVersion": "gateway.solo.io/v1","kind": "RouteTable","metadata": {  "name": "invalid-rt",  "namespace": "gloo-system"},"spec": {  "routes": [ {"matchers": [  { "prefix": "/"  }] }  ]} }  }}' -H 'Content-Type: application/json' https://localhost:8443/validation`

Returns:
```
{"response":{"uid":"1234","allowed":true}}
```

**Expected behavior**
Expected Result: Error stating the routetable is missing a route action

**Comment by kdorosh** [comment]
yaml to reproduce
```yaml
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: invalid-rt
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - prefix: "/"
```
this gets accepted without even a warning. should be an error
