### ISSUE TITLE
Support Nested Claims in JWTs claimToHeader setting

### ISSUE THREAD

**Issue by srenatus** [solo-io/gloo#3107]
**Is your feature request related to a problem? Please describe.**
Translating JWT claims to request headers only works for simple string claims, like `role: foobar`. It doesn't work for nested claims like

```
roles:
  tenant1: foobear
  tenant2: admin
```

**Describe the solution you'd like**
There's some ways this could work, maybe by injecting the JSON as header value, like
```
roles: { "tenant1": "foobear", "tenant2": "admin"}
```

**Describe alternatives you've considered**
Setting `keepToken: true` and having the upstream service deal with parsing the token claims.

**Additional context**
This is similar, but not exactly the same as #2744 (RBAC with nested claims).

**Comment by kdorosh** [comment]
note from @yuval-k , after cursory reading of filter code: underlying envoy filter uses a proto struct, the filter itself should already support nested claims. the `claimToHeader` functionality of the filter does not support nested claims, however

**Comment by npolshakova** [comment]
Translating nested JWT claims is now partially supported.

```
{
  test: {
    company: "foo",
    field2: "bar" 
  },
 tenant2: admin
}
```

You can do:

```

claimsToHeaders:
  - claim: test
    header: x-company

```

Currently only supports direct claims in the header, not nested claim path parsing i.e.


```
            claimsToHeaders:
            - claim: test.company
              header: x-company
```

**Comment by willowmck** [comment]
We have another prospect who is looking for this functionality.  Currently, they have a workaround but it's fairly complex to do with the transformation filter that could become error prone.

**Comment by DuncanDoyle** [comment]
This is now possible in kgateway using a combination of `TrafficPolicy` and a `JWTProvider` `GatewayExtension`.

This works for single as multi-level nesting.

Example `GatewayExtension`

```
apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayExtension
metadata:
  name: basic-jwt-provider
  namespace: default
spec:
  type: JWTProviders
  jwtProviders:
  - name: selfminted
    issuer: solo.io
    jwks:
        local:
          inline: '{"keys":[{"e":"AQAB","kid":"3161","kty":"RSA","n":"tmzcODUF5T9p-74QVtftjmB81bnRxvGcgbW1lNsIQSSzhbGLZ7_oqGNS4j6JSDFpjy0XqJnM11_MfZpU4HyeDEBad4tNzEZSprne9OfJoUxdvE8yAoO8Lm8Nz-7Ntp44xyqnqZaR-cz4tnRaBWjA4TEd3mGNfV-Zfnq8YcsQkfKwDDAPVPU9Rpk38cD4ZQqrMWi0Oap9598f1ycc4qFgRYxI95k1phUpcBr4L2wfwukUKgqz6geCIAnW1VEuCm4_axIFqwif9EaA3yjoUD9ByExwA6PkMuIOe192BgAXP8CbTAa3OkMameAeLpxNhg5nkkhYkYKKQuC5HG8QRh1J8w"}]}'
    claimsToHeaders:
    - name: org
      header: claimOrg
    - name: parent.child
      header: claimChild
    - name: parent.otherchild.grandchild
      header: claimGrandChild
```

Example `TrafficPolicy`:

```
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: extauth-httproute-policy
  namespace: default
spec:
  targetRefs:
    - name: api-example-com
      group: gateway.networking.k8s.io
      kind: HTTPRoute
  jwt:
    extensionRef:
      name: basic-jwt-provider
```

Example JWT:

```
[
  {
    "alg": "RS256",
    "kid": "3161",
    "typ": "JWT"
  },
  {
    "exp": 1764941025,
    "iss": "solo.io",
    "org": "solo.io",
    "parent": {
      "child": "value",
      "otherchild": {
        "grandchild": "test"
      }
    },
    "sub": "alice",
    "team": "dev"
  }
]
```
