### ISSUE TITLE
Race in GlooE and non-eventual consistency in GlooE 1.3.9

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#3115]
**Describe the bug**
By applying a bunch of resources at once, Gloo can get into a state where it marks a virtual service as invalid even though it is indeed valid.

**To Reproduce**
1. Install GlooE 1.3.9
2. Delete the default gateways from installation `krm gw -n gloo-system --all` 
3. Repeatedly apply and remove the following yaml until you can get the desired error from `glooctl check`:
```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy-a
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    virtualServiceSelector:
      tier: common
  proxyNames:
  - gateway-proxy
  useProxyProto: false
---
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy-b
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8081
  httpGateway:
    virtualServiceSelector:
      tier: bdp
  proxyNames:
  - gateway-proxy
  useProxyProto: false
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: 'example1'
  namespace: 'gloo-system'
  labels:
    tier: common
spec:
  virtualHost:
    domains:
    - 'example1.com'
    routes:
    - matchers:
       - prefix: '/a' # delegate ownership of routes for `example.com/a`
      delegateAction:
        ref:
          name: 'a-routes'
          namespace: 'gloo-system'
      options:
        autoHostRewrite: true
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: 'example2'
  namespace: 'gloo-system'
  labels:
    tier: bdp
spec:
  virtualHost:
    domains:
    - 'example2.com'
    routes:
    - matchers:
       - prefix: '/b' # delegate ownership of routes for `example.com/b`
      delegateAction:
        ref:
          name: 'b-routes'
          namespace: 'gloo-system'
      options:
        autoHostRewrite: true
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: 'a-routes'
  namespace: 'gloo-system'
spec:
  routes:
    - matchers:
        # the path matchers in this RouteTable must begin with the prefix `/a/`
       - prefix: '/a/1'
      routeAction:
        single:
          upstream:
            name: 'a'
      options:
        prefixRewrite: /
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: 'b-routes'
  namespace: 'gloo-system'
spec:
  routes:
    - matchers:
        # the path matchers in this RouteTable must begin with the prefix `/b/`
       - regex: '/b/2'
      routeAction:
        single:
          upstream:
            name: 'b'
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: a
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: b
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80
```
3. See error, `kg vs -A -oyaml`
```
  Route Warning: InvalidDestinationWarning. Reason: *v1.Upstream {a } not found
```
but not that the upstream does indeed exist:
```
kg us -n gloo-system
NAME                                                  AGE
a                                                     28s
b                                                     28s
default-kubernetes-443                                32m
extauth                                               32m
gloo-system-apiserver-ui-8080                         32m
...
```
And note that the virtual service status does not eventually sort itself out.

We can resolve the virtual service error by forcing a Gloo resync, for example, by applying a new, totally unrelated upstream:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: c
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80
```

**Expected behavior**
Gloo should be eventually consistent.

**Additional context**
Add any other context about the problem here, e.g.
- GlooE version 1.3.9
- Kubernetes version 1.17 on minikube
