### ISSUE TITLE
gRPC parameters' header doesn't allow for spaces

### ISSUE THREAD

**Issue by srenatus** [solo-io/gloo#3123]
**Describe the bug**

The gRPC header extraction settings
```
parameters:
  headers:
    foo: '{ bar }'
```

would fail with

```
reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *grpc.plugin:
   error processing parameter: { bar } is not valid syntax. {} braces must be
   closed and variable names must satisfy regex ([\\-._[:alnum:]]+)\n\n"
```
...while the docs suggest that spaces there are OK. **Actuall**, the error message is spot-on, the RE doesn't contain a space. However, it took me a while to see that. Also, in other places, I believe we allow for spaces in those positions.

ℹ️ I've created this issue post-hoc for the changelog of #3113 

**To Reproduce**
Create a virtual service like this one:
```
  virtualHost:
    routes:
    - matchers:
      - prefix: /
        methods:
        - POST
      routeAction:
        single:
          destinationSpec:
            grpc:
              function: UnaryEcho
              package: grpc.examples.echo
              service: Echo
              parameters:
                headers:
                  foo: '{ bar }'
          upstream:
            name: default-sample-api-grpc-50051
            namespace: gloo-system
```
Where default-sample-api-grpc-50051 is a service exposing the example gRPC Echo service.

**Expected behavior**

With the echo service, these headers will not matter much, but the virtualservice should be _accepted_.

**Additional context**
```
Client: {"version":"1.3.17"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.3.9","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.3.28","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.28","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.3.9","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```
