### ISSUE TITLE
Provide a way to inherit defaults when adding a custom proxy 

### ISSUE THREAD

**Issue by law10k** [solo-io/gloo#3142]
**Is your feature request related to a problem? Please describe.**
When using the helm charts to specify custom `Gateways`, the defaults that get applied to the standard `gateway-proxy` are not applied to any custom proxies. This means a full set of defaults must be explicitly defined in the provided `values.yaml` file.

**Describe the solution you'd like**
A way for `gloo.gatewayProxies.gatewayProxy` defaults to be propagated to other custom proxies.

**Describe alternatives you've considered**
Some of this can be accomplished with `.Values.global` but this still requires explicit duplication of some default values e.g. tag/version to use

**Additional context**
An example `values.yaml` for installing a custom gatewayProxy:
```
gloo:
  gatewayProxies:
    customProxy:
      configMap:
        data: null
      kind:
        deployment:
          replicas: 1
      podTemplate:
        probes: false
        httpPort: 8080
        httpsPort: 8443
        runAsUser: 10101
        image:
          pullPolicy: IfNotPresent
          repository: gloo-ee-envoy-wrapper
          tag: 1.4.0-beta7
      service:
        type: LoadBalancer
        httpPort: 80
        httpsPort: 443
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway: custom-gateway
```

Most of the are default values set for the standard gatewayProxy that must be duplicated for the chart to work as expected.

**Comment by via-jordan-sokolic** [comment]
This is a pain point for us too. With each deployment we deploy two gateways, one for internal services exposed with an internal load balancer and another with an external load balancer for public-facing services.

We're using YAML anchoring to minimize the amount of duplication. So for example:
```yaml
# values/gateway-base.yaml
gatewayProxies: # full gatewayProxy defaults go here, obtained from `helm get values $RELEASE --all`
  gatewayProxy: &gatewayProxyConfig
    service:
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
  internalProxy: 
    <<: *gatewayProxyConfig
```
```yaml
# values/gateway-internal.yaml
gatewayProxies: # custom gatewayProxy overrides go here
  internalProxy:
    service:
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: ssl
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

This way we can define the defaults once, and duplicate them for our custom internal proxy, overriding any values as necessary by passing multiple `--values` options to Helm.
