### ISSUE TITLE
Enrich event object for AWS Lambda integration

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3160]
**Is your feature request related to a problem? Please describe.**
The `event` object that an AWS Lambda receives when executing is the main way for the function to get contextual data from the incoming request. Currently, the Gloo integration only provides the request body as the received `event`.

**Describe the solution you'd like**
The `event` should additional information from the request (e.g. headers, query string, etc.).
For example:
[`event` format when Lambda called via ALB](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html)
[`event` format when Lambda called via AWS API Gateway](https://docs.aws.amazon.com/lambda/latest/dg/services-apigateway.html)

**Describe alternatives you've considered**
Transformations can get you most of the way, but become extremely cumbersome/verbose as the you try to reach parity with e.g. AWS API Gateway

**Comment by via-jordan-sokolic** [comment]
+1 for this. It would make transitioning from AWS API Gateway to Gloo super straightforward.

Something similar to how Kong handles AWS Lambda integration would be ideal IMO with feature flag `config.is_proxy_integration`: https://docs.konghq.com/hub/kong-inc/aws-lambda/ 
The AWS docs specify the [format](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-output-format) for integrating with their API gateway. 

From our testing it seems this is partially implemented in [`aws.responseTransformation`](https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk/), but that only handles the body and ignores the rest of the response (`statusCode`, `headers`, etc.).

For now, we're using the following transformation for `statusCode`:
```yaml
      transformations:
        responseTransformation:
          transformationTemplate:
            headers:
              ":status": 
                text: '{% if default(statusCode, "") != "" %}{{ statusCode }}{% else %}{{ header(":status") }}{% endif %}'
```

**Comment by RichiCoder1** [comment]
We're also looking for something pretty close to the AWS API Gateway event payload for invoked lambdas.

**Comment by ben-taussig-solo** [comment]
To resolve this issue, we have introduced a new field, `requestTransform` on the AWS destionationSpec, which can be used to configure a default set of request transformations which place all request headers, the request HTTP method, and the path and queryString of the request in the event payload received by the lambda. This field will be available as of Gloo OSS 1.9.0-beta18 and Gloo Enterprise 1.9.0-beta9. The PR introducing this change can be found here: https://github.com/solo-io/gloo/pull/5308

In the meantime, you can configure the following transformations on a route or virtualhost to achieve the same behavior:
```yaml
options:
  stagedTransformations:
    early:
      requestTransforms:
      - requestTransformation:
          headerBodyTransform: {}
    regular:
      requestTransforms:
      - requestTransformation:
          transformationTemplate:
            extractors:
              path:
                header: ':path'
                regex: '([^\?]+)(\?.*)?'
                subgroup: 1
              queryString:
                header: ':path'
                regex: '([^\?]+)(\?(.*))?'
                subgroup: 3
              httpMethod:
                header: ':method'
                regex: '(.*)'
                subgroup: 1
            mergeExtractorsToBody: {}
```

Event payload before transformation:
```json
"This is the request body"
```

Event payload after transformation:
```json
{
  "body": "\"This is the request body\"",
  "headers": {
    ":authority": "localhost:8080",
    ":method": "POST",
    ":path": "/path?parameter_a=value_a&parameter_b=value_b",
    ":scheme": "http",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "content-length": "24",
    "content-type": "text/plain",
    "postman-token": "125afd00-7c8f-4786-b4f8-5dddcf338553",
    "user-agent": "PostmanRuntime/7.28.4",
    "x-forwarded-proto": "http",
    "x-request-id": "07cf3461-38d9-427c-9735-837d031b439d"
  },
  "httpMethod": "POST",
  "path": "/path",
  "queryString": "parameter_a=value_a&parameter_b=value_b"
}
```
