### ISSUE TITLE
modifying healthcheck config while in unhealthy state stops future healthchecks

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3219]
**Describe the bug**
Toggling a healthcheck path config between valid to invalid to valid stops future healthchecks and leaves the upstream in a permanent unhealthy state

**To Reproduce**
1. Deploy simple petstore app and route. Add the following to the upstream:
```
spec:
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /api/pets
    interval: 30s
    timeout: 30s
    unhealthyInterval: 30s
    unhealthyThreshold: 1
  loadBalancerConfig:
    healthyPanicThreshold: 0
```
2. Send a request, 200 returned as expected. You will see the following increase as expected:
envoy_cluster_health_check_success{envoy_cluster_name="default-petstore-8080_gloo-system"}

3. modify the upstream config to be invalid: 
`path: /api/pets`

4. Send a request, 503 no healthy upstream returned as expected. You will see the following increase as expected:
envoy_cluster_health_check_failure{envoy_cluster_name="default-petstore-8080_gloo-system"}
envoy_cluster_upstream_cx_none_healthy{envoy_cluster_name="default-petstore-8080_gloo-system"}

5. Switch the healthcheck back to valid: 
`path: /api/pets`

6. Send a request. You will see 503 no healthy upstream and the following will not change:
envoy_cluster_health_check_failure{envoy_cluster_name="default-petstore-8080_gloo-system"}
envoy_cluster_health_check_success{envoy_cluster_name="default-petstore-8080_gloo-system"}

7. At this point envoy is stuck. Appears healthchecks are no longer being sent and the upstream remains unhealthy despite the valid config. 

**Expected behavior**
Envoy detects the healthy upstream with the valid config and healthchecks continue as expected.
