### ISSUE TITLE
Get an "Unimplemented" error when creating a virtual service with an SSL secret (as opposed to editing it after creation)

### ISSUE THREAD

**Issue by jwvictor** [solo-io/gloo#3234]
**Describe the bug**
Get an error code "Unimplemented" when I try to call a virtualservice that was created with a YAML file that declared explicitly the name of an SSL secret. When you instead create the virtualservice from that same YAML but _without_ referencing the SSL secret, and then edit the virtualservice to set the TLS secret, it works fine.

**To Reproduce**
1. kubectl apply -f virtualservice.yaml # this is the version that DOES reference an SSL secret
2. curl '....'
3. See error "Unimplemented"
4. Remove SSL secret from virtualservice.yaml
5. curl '...'
6. Works!

**Expected behavior**
Creating a VS from YAML referencing an SSL secret should be the same thing as creating it and then editing it to add that secret.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version: Client: {"version":"1.3.17"}
Server: {"type":"Gateway","kubernetes":{"containers":[{"Tag":"1.3.17","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.3.17","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.3.17","Name":"gloo-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.3.17","Name":"gloo","Registry":"quay.io/solo-io"}],"namespace":"gloo-system"}}
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.36", GitCommit:"34a615f32e9a0c9e97cdb9f749adb392758349a6", GitTreeState:"clean", BuildDate:"2020-04-06T16:33:17Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kdorosh** [comment]
apologies for the late reply

i was unable to reproduce on minikube using the following steps:

- `minikube start --memory=4096 --cpus=2 --kubernetes-version=v1.17.0`
- `glooctl install gateway --version 1.5.0-beta20`
- `kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml`
- `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=petstore.example.com"`
- `kubectl create secret tls upstream-tls --key tls.key --cert tls.crt --namespace gloo-system`
- applying the following yaml
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /sample-route-1
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```

`curl -kv $(glooctl proxy url --port https)/sample-route-1` worked as expected


closing as stale & unable to reproduce. feel free to reopen if you'd like to revisit this and can add more descriptive steps to reproduce. thanks!
