### ISSUE TITLE
Ingress controller does not add a rule that matches the host and the port

### ISSUE THREAD

**Issue by pbchekin** [solo-io/gloo#3244]
**Describe the bug**
Gloo in ingress mode adds an Envoy rule that matches a host specified in Ingress, but does not add a rule that matches a host and a port (80 or 443). This creates an issue for proxying GRPC services, because most of the standard GRPC clients (grpcurl, Go, Python) use GRPC endpoint for `:authority` header, if `authority` is not explicitly specified.

For example:
```
grpcurl -plaintext example.com:80 list
```

sends the corresponding request:
```
:method: POST
:scheme: http
:path: /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
:authority: example.com:80
content-type: application/grpc
user-agent: grpc-go/1.29.0
te: trailers
```

As a result, a GRPC request does not work with Gloo ingress-proxy (other methods fail with similar message):

```
Failed to list services: server does not support the reflection API
```

As a workaround, every client needs to explicitly specify `authority`:

```
grpcurl -plaintext -authority example.com example.com:80 list
```

sends the corresponding request:
```
:method: POST
:scheme: http
:path: /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
:authority: example.com
content-type: application/grpc
user-agent: grpc-go/1.29.0
te: trailers
```

Envoy has the following configuration:

```
      ...
      {
        "name": "example_com-http",
        "domains": [
         "example.com"
        ],
        ...
      },
      ...
```

**To Reproduce**
1. Create a deployment

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: books
  name: books
spec:
  selector:
    matchLabels:
      app: books
  template:
    metadata:
      labels:
        app: books
    spec:
      containers:
      - image: docker.io/soloio/example-store-grpc:v1
        args:
        - --service=books
```

2. Create a service

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: books
  name: books
spec:
  type: ClusterIP
  ports:
  - port: 9999
    targetPort: 8080
    name: grpc-port
  selector:
    app: books
```

3. Verify that the GRPC service works

```
kubectl port-forward svc/books 9999:9999 # run in a separate terminal
grpcurl -plaintext 127.0.0.1:9999 list
```

4. Create an ingress

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: books
  labels:
    app: books
  annotations:
    kubernetes.io/ingress.class: gloo
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: books
          servicePort: 9999
```

5. The same GRPC service does not work via Ingress

```
grpcurl -plaintext example.com:80 list
```

However it works when we specify `authority`:

```
grpcurl -plaintext -authority example.com example.com:80 list
```

**Expected behavior**
While explicitly specifying `authority` for a GRPC client is a potential workaround, sometimes it not possible to modify 3rd party GRPC applications or libraries. For such cases, Gloo in ingress mode should support their default behavior.

Gloo in ingress mode should add two Envoy rules: first for the Ingress host, second for the Ingress port and port.

The corresponding Envoy configuration must be:

```
      ...
      {
        "name": "example_com-http",
        "domains": [
         "example.com",
         "example.com:80"
        ],
        ...
      },
      ...
```

**Additional context**
- Gloo version: 1.4.1
