### ISSUE TITLE
support List in gateway validation API

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3261]
**Is your feature request related to a problem? Please describe.**
Unable to combine multiple resources into a single gateway validation request

**Describe the solution you'd like**
Support something like this:

```
{
        "request": {
                "uid": "1234",
                "kind": {
                        "version": "v1",
                        "kind": "List"
                },
                "resource": {
                        "group": "",
                        "version": "",
                        "resource": ""
                },
                "name": "invalid-vs-list",
                "namespace": "gloo-system",
                "operation": "CREATE",
                "userInfo": {},
                "object": {
                        "apiVersion": "v1",
                        "kind": "List",
                        "items": [{
                                "apiVersion": "gateway.solo.io/v1",
                                "kind": "VirtualService",
                                "metadata": {
                                        "name": "invalid-vs",
                                        "namespace": "gloo-system"
                                },
                                "spec": {
                                        "virtualHost": {
                                                "routes": [{
                                                        "matchers": [{
                                                                "prefix": "/"
                                                        }],
                                                        "delegateAction": {
                                                                "name": "i-dont-exist-rt",
                                                                "namespace": "gloo-system"
                                                        }
                                                }]
                                        }
                                }
                        }]
                }
        }
}
```

i.e. (should be accepted),
```
curl -k -XPOST -d '{"request":{"uid":"1234","kind":{"version":"v1","kind":"List"},"resource":{"group":"","version":"","resource":""},"name":"invalid-vs-list","namespace":"gloo-system","operation":"CREATE","userInfo":{},"object":{"apiVersion":"v1","kind":"List","items":[{"apiVersion":"gateway.solo.io/v1","kind":"VirtualService","metadata":{"name":"invalid-vs","namespace":"gloo-system"},"spec":{"virtualHost":{"routes":[{"matchers":[{"prefix":"/"}],"delegateAction":{"name":"i-dont-exist-rt","namespace":"gloo-system"}}]}}}]}}}' -H 'Content-Type: application/json' https://localhost:8443/validation
```

also nice test, two VS with overlapping domains (should be denied):
```
curl -k -XPOST -d '{"request":{"uid":"1234","kind":{"version":"v1","kind":"List"},"resource":{"group":"","version":"","resource":""},"name":"invalid-vs-list","namespace":"gloo-system","operation":"CREATE","userInfo":{},"object":{"apiVersion":"v1","kind":"List","items":[{"apiVersion":"gateway.solo.io/v1","kind":"VirtualService","metadata":{"name":"invalid-vs1","namespace":"gloo-system"},"spec":{"virtualHost":{"routes":[{"matchers":[{"prefix":"/"}],"delegateAction":{"name":"i-dont-exist-rt","namespace":"gloo-system"}}]}}},{"apiVersion":"gateway.solo.io/v1","kind":"VirtualService","metadata":{"name":"invalid-vs2","namespace":"gloo-system"},"spec":{"virtualHost":{"routes":[{"matchers":[{"prefix":"/"}],"delegateAction":{"name":"i-dont-exist-rt","namespace":"gloo-system"}}]}}}]}}}' -H 'Content-Type: application/json' https://localhost:8443/validation
```

**Comment by kdorosh** [comment]
A tricky nuance to this is that we need to update the webhook to process all the resources at once, rather than serially.

For example, from a clean install, both of these virtual services are individually valid (after applying the upstream):

```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: json-upstream
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80
```

```yaml

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-static1
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matchers:
         - prefix: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
        options:
          autoHostRewrite: true
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-static2
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matchers:
         - prefix: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
        options:
          autoHostRewrite: true
```

However, applying them together actually gets rejected (even with dry-run via `pbpaste | k apply -f - --server-dry-run`), likely due to some invalid caching in the webhook. Once that caching handles the dry-run properly, I expect these resources will be accepted in a dry run when applied at once, as `kubectl` attempts to apply resources one by one. These resources should be rejected, however.
