### ISSUE TITLE
VirtualHost extauth options are ignored when using Gateway level extauth

### ISSUE THREAD

**Issue by marcoferrer** [solo-io/gloo#3270]
**Describe the bug**

After moving our ext auth configuration out of the global `Settings` resource and into the `Gateway` options, (Introduce in https://github.com/solo-io/gloo/issues/2257 and https://github.com/solo-io/gloo/pull/3022) all virtual services have auth enabled by default. VirtualServices without any extauth options defined respond with 403 after the change was made.
```yaml
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      extauth:
        extauthzServerRef:
          name: my-auth-8080
          namespace: gloo-system
        httpService:
          response:
            allowedUpstreamHeaders: []
        requestTimeout: 0.500s
      httpConnectionManagerSettings:
        tracing:
          requestHeadersForTags:
          - path
          - origin
          verbose: true
    virtualServiceSelector:
      myselector: "true"
  proxyNames:
  - gateway-proxy
  useProxyProto: false
```

Also, we attempted to explicitly disable auth using the virtual host options but it had no effect.
```yaml

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  labels:
    myselector: "false"
  name: my-service
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    options:
      extauth:
        disable: true
    routes:
      - routeAction:
          single:
            upstream:
              name: my-service-8080
              namespace: gloo-system
```

**To Reproduce**
1. Create a gateway configured to use external auth with a customer server
2. Create a virtual service for any HTTP upstream with no virtual host or route options
3. Attempt to make a request to the domain defined in the newly created virtual service
4. A response with status 403 is returned

**Expected behavior**
The authentication should not have been asserted for the virtual service since there were no options defined in its virtual host or routes. This is the current behavior when defining the external auth configuration using the global `Settings` object. (Based on [this](https://docs.solo.io/gloo/latest/guides/security/auth/custom_auth/) guide) 

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version: v1.4.1
- Kubernetes version: v1.16.8
