### ISSUE TITLE
Knative translator stops propagating proxy status after 30 seconds or after first rejection

### ISSUE THREAD

**Issue by Sodman** [solo-io/gloo#3281]
**Describe the bug**
If the proxy gets rejected, and then subsequently the configuration is fixed, the accepted status is never propagated.

**To Reproduce**
,. Then create the secret, service never comes up.
1. Fresh install of gloo + knative: 
`glooctl install knative`
2. Spin up a service pointing to a non-existing secret. eg using a TLS key:
```
cat << EOF | kubectl apply -f -
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
  annotations:
    gloo.networking.knative.dev/ssl.sni_domains: helloworld-go.default.example.com
    gloo.networking.knative.dev/ssl.secret_name: my-knative-tls-secret
spec:
  template:
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: Go Sample v1
EOF
```

3. Generate TLS cert:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
   -keyout tls.key -out tls.crt -subj "/CN=helloworld-go.default.example.com"
```
4. Add cert as secret:
```
kubectl create secret tls my-knative-tls-secret \
      --key tls.key \
      --cert tls.crt \
      --namespace default
```

Note proxy never changes to ready status after this.

**Workarounds**
Changing the service deploy, eg tweaking an env var in the config, will cause a redeploy at which point the proxy will report as ready.

**Expected behavior**
Eventual consistency - if the key is added after the config, it should be picked up and the proxy should report as ready.

**Additional context**
- Gloo version 1.3.0+
The issue is in the method [here](https://github.com/solo-io/gloo/blob/master/projects/knative/pkg/translator/translator_syncer.go#L157-L187)
