### ISSUE TITLE
invalid child routetable is accepted if parent rt does not include an explicit matcher

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3291]
**Describe the bug**
With nested routetables, an invalid child routetable is accepted if parent rt does not include an explicit matcher

**To Reproduce**
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - delegateAction:
        ref:
          name: routetableparent
          namespace: gloo-system
      matchers:
      - prefix: /api
```

```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: routetableparent
  namespace: gloo-system
spec:
  routes:
  - delegateAction:
      ref:
        name: routetable1
        namespace: gloo-system
  weight: 0
```

apiVersion: gateway.solo.io/v1
```
kind: RouteTable
metadata:
  name: routetable1
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - prefix: /invalid/pets
    options:
      prefixRewrite: /api/pets
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system
  weight: 0
```

```
   "dynamic_route_configs": [
    {
     "version_info": "12426037149185603100",
     "route_config": {
      "@type": "type.googleapis.com/envoy.api.v2.RouteConfiguration",
      "name": "listener-::-8080-routes",
      "virtual_hosts": [
       {
        "name": "gloo-system_default",
        "domains": [
         "*"
        ],
        "routes": [
         {
          "match": {
           "prefix": "/invalid/pets"
          },
          "route": {
           "cluster": "default-petstore-8080_gloo-system",
           "prefix_rewrite": "/api/pets"
          }
         }
        ],
        "per_filter_config": {
         "envoy.ext_authz": {
          "disabled": true
         }
        }
       }
      ]
     },
     "last_updated": "2020-07-06T19:29:01.190Z"
    }
   ]
  },
```

```
$ glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
No problems detected.
```
