### ISSUE TITLE
Single OpenAPI endpoint for the API Gateway

### ISSUE THREAD

**Issue by wilmardo** [solo-io/gloo#3320]
**Is your feature request related to a problem? Please describe.**
Currently we have multiple microservices who expose their own OpenAPI spec at `172.20.1.12/docs/`. All these microservices are exposed by the API Gateway as `apigateway.com/<domain>/<enitity>` for example, `apigateway.com/finance/customer`, `apigateway.com/asset-management/device` and `apigateway.com/crm/company`.

So now we want to generate an SDK for the whole `apigateway.org` since for the end-user it does not matter that it are all microservices, he just connects to `apigateway.com` API. Normally we would just take the OpenAPI spec of the API and generate the SDK but this isn't possible now since the API is composed of multiple microservices.

**Describe the solution you'd like**
One endpoint like `apigateway.com/docs/` where a composed OpenAPI spec is available from all the APIs exposed by the API Gateway.

**Describe alternatives you've considered**
Merging and maintaining them ourselves but it is destined to fail when more and more microservices are added.

**Comment by marcogschmidt** [comment]
Hi @wilmardo, sorry for the late reply. I think that the enhancements to the [Gloo Developer Portal](https://docs.solo.io/gloo/latest/guides/dev_portal/) we are currently working on will be very close to delivering what you are looking for. The new API of the dev portal will be very similar to the one that is currently exposed by our Developer Portal for Istio](https://docs.solo.io/dev-portal/latest/), so I will base the following examples on that. 

With the new Gloo Dev Portal API you will be able to define multiple [`APIDocs`](https://docs.solo.io/dev-portal/latest/concepts/api_products/#api-docs), each one of which will be able to fetch the OpenAPI document of one of your services.

```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: APIDoc
metadata:
  name: api-doc-1
  namespace: default
spec:
  openApi:
    content:
      fetchUrl: http://svc-1.default:8080/swagger.json

---

apiVersion: devportal.solo.io/v1alpha1
kind: APIDoc
metadata:
  name: api-doc-2
  namespace: default
spec:
  openApi:
    content:
      fetchUrl: http://svc-2.default:8080/swagger.json
---

# ...
```

You will then be able to create an [`APIProduct`](https://docs.solo.io/dev-portal/latest/concepts/api_products/#api-products) that is composed of all of the above `APIDocs`:

```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: APIProduct
metadata:
  name: my-product
  namespace: default
spec:
  apis:
  - apiDoc:
      name: api-doc-1
      namespace: default
  - apiDoc:
      name: api-doc-2
      namespace: default
  # ....
```

The Dev Portal will then stitch together the required OpenAPI documents and write the result to the `status` of the `APIProduct`:

```yaml
apiVersion: devportal.solo.io/v1alpha1
kind: APIProduct
metadata:
  name: my-product
  namespace: default
spec: {} # omitted
status:
  state: Succeeded
  openApiSchema: {} # omitted
```

`status.openApiSchema` will contain the merged OpenAPI specs of all the services. 

We use this merged OpenAPI document to generate the interactive swagger doc for each `APIProduct` that is published to a portal (see examples [here](https://docs.solo.io/dev-portal/latest/guides/users_groups/#using-the-petstore-portal)). You could use that spec to generate the SDK you are looking for. Right now the merged document is only accessible on the `status` of the `APIProduct`. If that does not work for you, it should be pretty easy to add an endpoint to the portal UI from which you can GET it.

Would this solution work for you? Let me know what you think!
