### ISSUE TITLE
Support additional matchers for route delegation

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3327]
**Is your feature request related to a problem? Please describe.**
Currently only path prefix matching is supported for route delegation via `RouteTables`. This means that if you want to use delegation for separation of concerns (i.e. platform team and service teams), you can not use advanced routing techniques such as query parameter or header matching. This limits the ability to do e.g. blue/green deployments for routes that are delegated.

This would be alleviated if `RouteTable` delegation supported the other forms of matching.

**Describe the solution you'd like**
No restriction on `matchers` for routes that use delegation. Ideally this can be done at either the `VirtualService` or the `RouteTable` level.

**Describe alternatives you've considered**
No alternatives seem to work

**Additional context**
N/A

**Comment by lgadban** [comment]
The current implementation requires the matchers to be present on both the parent `VirtualService` and the selected `RouteTable`.

This may not be suitable for the use-case of a separate teams owning these different resources.

**Example**
A platform team owns the `VirtualService` and the service team owns various `RouteTables` and `Upstreams`.

The service teams configure app-specific routing rules (e.g. via `path` prefix) as well as various route-level options.

The platform team owns the the gateway and wants to perform a canary release by changing the matchers to select a different `RouteTable` corresponding to different versions of the service.

`RouteTable` version 1 owned by service team
```
kind: RouteTable
metadata:
  name: petstore-route-v1
  namespace: petstore-v1
spec:
  routes:
  - matchers:
    - prefix: /
    routeAction:
      single:
        upstream:
          name: petstore-v1-petstore-8080
          namespace: petstore-v1
```

`RouteTable` version 2 owned by service team
```
kind: RouteTable
metadata:
  name: petstore-route-v2
  namespace: petstore-v2
spec:
  routes:
  - matchers:
    - prefix: /
    routeAction:
      single:
        upstream:
          name: petstore-v2-petstore-8080
          namespace: petstore-v2
```

`VirtualService` owned by platform team
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
        headers:
        - name: version
          value: v2
      delegateAction:
        selector:
          namespaces:
          - petstore-v2
    - matchers:
      - prefix: /
      delegateAction:
        selector:
          namespaces:
          - petstore-v1
```

The desired behavior would be to result in a (condensed) routing config as follows, where the matchers from the `VirtualService` are additive with the `RouteTable` and no changes are required from the service team
```
routes:
- matchers:
  - prefix: /
     headers:
     - name: version
       value: v2
    routeAction:
      single:
        upstream:
          name: petstore-v2-petstore-8080
    - matchers:
  - prefix: /
    routeAction:
      single:
        upstream:
          name: petstore-v1-petstore-8080
```
