### ISSUE TITLE
wasm advanced config page references old example

### ISSUE THREAD

**Issue by rickducott** [solo-io/gloo#3348]
Wasm example references an image that doesn't seem to exist. I got it working with this config instead:

```
spec:
  httpGateway: 
    options:
      wasm:
        filters:
        - config: |
            {}
          image: webassemblyhub.io/solo.io/metrics:gloo-1.3.x
          name: metrics
          root_id: stats_root_id
```
