### ISSUE TITLE
api-server not supported in non-kubernetes environments

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3373]
**Describe the bug**
Trying to start the api-server with docker-compose results in the following error in the grpcserver-ee container:
```

{"level":"fatal","ts":1595278841.6811926,"logger":"gloo-grpcserver","caller":"setup/settings.go:54","msg":"Could not create settin
gs client","version":"1.4.4","error":"invalid configuration: no configuration has been provided","errorCauses":[{"error":"no confi
guration has been provided"}],"stacktrace":"github.com/solo-io/solo-projects/projects/grpcserver/server/setup.mustGetSettingsClien
t\n\t/workspace/solo-projects/projects/grpcserver/server/setup/settings.go:54\ngithub.com/solo-io/solo-projects/projects/grpcserve
r/server/setup.mustGetSettings\n\t/workspace/solo-projects/projects/grpcserver/server/setup/settings.go:22\ngithub.com/solo-io/sol
o-projects/projects/grpcserver/server/setup.MustSettings\n\t/workspace/solo-projects/projects/grpcserver/server/setup/initializers
.go:18\ngithub.com/solo-io/solo-projects/projects/grpcserver/server.InitializeServer\n\t/workspace/solo-projects/projects/grpcserv
er/server/wire_gen.go:44\nmain.main\n\t/workspace/solo-projects/projects/grpcserver/server/cmd/main.go:37\nruntime.main\n\t/usr/lo
cal/go/src/runtime/proc.go:203"}
```

Kubernetes is hardcoded here: https://github.com/solo-io/solo-projects/blob/v1.4.x/projects/grpcserver/server/setup/settings.go#L52

**To Reproduce**
Use the following docker-compose.yaml:

```
version: '3'
services:
  apiserver-ui:
    image: quay.io/solo-io/grpcserver-ui:1.4.4
    working_dir: /
    volumes:
    - ./empty-cache:/var/cache/nginx
    - ./empty-run:/var/run
    ports:
    - "8081:8080"
    restart: always

  apiserver:
    image: quay.io/solo-io/grpcserver-ee:1.4.4
    environment:
    - START_STATS_SERVER=true
    - GRPC_PORT=10101
    - NOAUTH=1
    - DEV_PORTAL_ENABLED=false
    - GLOO_LICENSE_KEY=$KEY_HERE
    - POD_NAMESPACE=gloo-system
    - RBAC_NAMESPACED=false
    working_dir: /
    ports:
    - "10101:10101"
    restart: always

  gloo-grpcserver-envoy:
    image: quay.io/solo-io/grpcserver-envoy:1.4.4
    working_dir: /
    restart: always
```

**Expected behavior**
api-server supported in non-kubernetes environments
