### ISSUE TITLE
set TLS default to supporting >=TLS1.2 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3417]
**Is your feature request related to a problem? Please describe.**
Gloo should not allow < TLS1.2 by default 

**Describe the solution you'd like**
set TLS default to supporting >=TLS1.2

**Comment by oboukili** [comment]
Related to that issue, it seems the defaults cannot be overriden through configuration:
Example virtualservice that still allows tls1.0 / 1.1.:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/instance: gloo
  name: vs-https
  namespace: gloo-system
spec:
  sslConfig:
    parameters:
      cipherSuites:
        - ECDHE-ECDSA-AES128-GCM-SHA256
        - ECDHE-RSA-AES128-GCM-SHA256
        - ECDHE-ECDSA-AES128-SHA
        - ECDHE-RSA-AES128-SHA
        - AES128-GCM-SHA256
        - AES128-SHA
        - ECDHE-ECDSA-AES256-GCM-SHA384
        - ECDHE-RSA-AES256-GCM-SHA384
        - ECDHE-ECDSA-AES256-SHA
        - ECDHE-RSA-AES256-SHA
        - AES256-GCM-SHA384
        - AES256-SHA
      minimumProtocolVersion: TLSv1_2
    secretRef:
      name: secret
      namespace: secret
    sniDomains:
      - some.domain.com
  virtualHost:
    domains:
      - some.domain.com
    options:
      cors:
        allowCredentials: true
        allowHeaders:
          - Authorization
          - Cache-Control
          - Content-Type
          - DNT
          - If-Modified-Since
          - Range
          - User-Agent
          - X-Requested-With
        allowMethods:
          - GET
          - OPTIONS
          - PATCH
          - POST
          - PUT
      headerManipulation:
        responseHeadersToAdd:
          - header:
              key: X-Robots-Tag
              value: 'noindex, nofollow'
          - header:
              key: X-Frame-Options
              value: SAMEORIGIN
    routes:
      - delegateAction:
          selector:
            labels:
              somelabel: enabled
            namespaces:
              - '*'
        matchers:
          - prefix: /
 ```
