### ISSUE TITLE
contextExtensions

### ISSUE THREAD

**Issue by sbvitok** [solo-io/gloo#3419]
I try to setup extauth for my custom auth server, and all works if setup global Settings, but I want to set 1 additional head per VirtualHost

is Settings.spec.extauth.httpService.request.headersToAdd and virtualHost.options.extauth.customAuth.contextExtensions are the same logic?

I try to move header from Settings.spec.extauth.httpService.request.headersToAdd to virtualHost.options.extauth.customAuth.contextExtensions but nothings happens.

**Comment by yuval-k** [comment]
the are not the same logic. 
context extensions adds metadata that's only available for a grpc server.

**Comment by sbvitok** [comment]
So I have no way to add header per VirtualHost?

**Comment by yuval-k** [comment]
I'm not aware of anything to add a header per vhost that would only go to the ext auth server (doing this would require a change in the upstream envoy ext-authz filter).
you can add a header but it will go to the upstream as well.

starting recent version of gloo, you can add early stage transformations. you can add a header that contains the hostname using this ability. but, unless removed, the header will also go upstream.
for example:
```
stagedTransformations:
  early:
    requestTransforms:
      requestTransformation:
        transformationTemplate:
          advancedTemplates: true
          passthrough: {}
          headers:
            x-custom-header: {text: "{{header(\":authority\")}}"}
```

see the stagedTransformations field in https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk/#virtualhostoptions .

Is there anything preventing you from using a gRPC ext auth service? you can then use the context extensions per vhost/route/weighted cluster.
