### ISSUE TITLE
Suppressing envoy http router added headers 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#3444]
Add an option on a vs/route option to suppress envoy http router added headers.
for example: https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#http-request-headers-set-on-upstream-calls

to suppress these header in envoy: 
```
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                  suppress_envoy_headers: true
```
