### ISSUE TITLE
Support helm install with no http gateways

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3450]
**Is your feature request related to a problem? Please describe.**
Unable to configure helm overrides which results in creation of only https gateways (i.e. always created http gateways). 

**Describe the solution you'd like**
Support helm install with no http gateways

The following config creates this:

```
$ kubectl -n gloo-system get gateway
NAME                AGE
custom-proxy        84s
custom-proxy-ssl    84s
gateway-proxy       84s
gateway-proxy-ssl   84s
```

```
global:
  glooStats:
    enabled: true
gloo:
  global:
    glooStats:
      enabled: true
  discovery:
    fdsMode: BLACKLIST
  gateway:
    validation:
      alwaysAcceptResources: false
      allowWarnings: false
      webhook:
        enabled: true
  gatewayProxies:
    gatewayProxy:
      stats:
        enabled: true
      loopBackAddress: 127.0.0.1
      readConfig: true
      gatewaySettings:
        customHttpsGateway:
          virtualServices:
          - name: standard-vs
            namespace: gloo-system
          options:
            httpConnectionManagerSettings:
              xffNumTrustedHops: 1
            proxyLatency:
              chargeClusterStat: true
              chargeListenerStat: true
              response: FIRST_INCOMING_FIRST_OUTGOING
      podTemplate:
        disableNetBind: false
        floatingUserId: false
        httpPort: 8080
        httpsPort: 8443
    customProxy:
      globalDownstreamMaxConnections: 250000
      loopBackAddress: 127.0.0.1
      stats:
        enabled: true
      gatewaySettings:
        customHttpsGateway:
          virtualServices:
          - name: custom-vs
            namespace: gloo-system
          options:
            httpConnectionManagerSettings:
              xffNumTrustedHops: 1
            proxyLatency:
              chargeClusterStat: true
              chargeListenerStat: true
              response: FIRST_INCOMING_FIRST_OUTGOING
      readConfig: true
      configMap:
        data: 
      kind:
        deployment:
          antiAffinity: false
          replicas: 1
      podTemplate:
        disableNetBind: false
        floatingUserId: false
        httpPort: 8180
        httpsPort: 8543
        image:
          repository: gloo-ee-envoy-wrapper
          tag: 1.4.0
        probes: false
        runUnprivileged: false
      service:
        httpPort: 80
        httpsPort: 1443
        type: LoadBalancer
        annotations:
          prometheus.io/path: "/metrics"
          prometheus.io/port: "8081"
          prometheus.io/scrape: "true"
```

Would like that config to create this:

```
$ kubectl -n gloo-system get gateway
NAME                AGE
custom-proxy-ssl    84s
gateway-proxy-ssl   84s
```
