### ISSUE TITLE
Be able to define upstreams based on selectors

### ISSUE THREAD

**Issue by wilmardo** [solo-io/gloo#3454]
**Is your feature request related to a problem? Please describe.**
The current cert-manager implementation leaves things desired and #2993 is tracking this. But before I found that issue I was trying to improve the HTTP challenge situation with an `Upstream` with a selector instead of the hardcoded serviceName as described in the docs:
https://docs.solo.io/gloo/latest/guides/integrations/cert_manager/#routing-to-the-cert-manager-pod
```yaml
# Create upstream for cert-manager to be able to route on selector instead of hardcoded servicename
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: cert-manager-upstream
  namespace: gloo-system
spec:
  kube:
    selector:
      acme.cert-manager.io/http01-solver: "true"
```

Currently this does not work (although you can apply it all fine) since `serviceName` is required and selecting a service just on labels currently isn't supported.

When selecting on labels is supported, the cert-manager setup could be just the above `Upstream` and something like this `virtualService` to handle only cert-manager requests:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: cert-manager
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matchers:
         - prefix: /.well-known/acme-challenge/
        routeAction:
          single:
            upstream:
              name: cert-manager-upstream
              namespace: gloo-system
        options:
          autoHostRewrite: true
```

This would make the HTTP challenge work without an `Ingress` resource and makes it work for each subsequent certificate renewal :)

**Describe the solution you'd like**
Make service selection for the `Upstream` possible by labels.

**Describe alternatives you've considered**
Hardcoding the serviceName but that required manual labor each time a certificate is requested/renewed.
