### ISSUE TITLE
LDS & validation failure with conflicting virtualservices

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3459]
**Describe the bug**
Conflicting virtualservices cause Envoy LDS failure and inconsistent validation state

```
[2020-08-04 15:38:01.258][7][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:100] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) listener-::-4443: error adding listener '[::]:4443': multiple filter chains with overlapping matching rules are defined
listener-::-8443: error adding listener '[::]:8443': multiple filter chains with overlapping matching rules are defined
```

```
$ glooctl get vs
+-----------------+--------------+-----------------+------------+-------------------------------------+-----------------+-----------------------------------+
| VIRTUAL SERVICE | DISPLAY NAME |     DOMAINS     |    SSL     |               STATUS                | LISTENERPLUGINS |              ROUTES               |
+-----------------+--------------+-----------------+------------+-------------------------------------+-----------------+-----------------------------------+
| conflict1       |              | *               | secret_ref | Accepted                            |                 | /api ->                           |
|                 |              |                 |            | *v1.Proxy.gloo-system.gateway-proxy |                 | gloo-system.default-petstore-8080 |
|                 |              |                 |            | is in a Pending state. Updates to   |                 | (upstream)                        |
|                 |              |                 |            | this resource may be blocked by     |                 |                                   |
|                 |              |                 |            | problems with another resource.     |                 |                                   |
| conflict2       |              | foo.example.com | secret_ref | Accepted                            |                 | /api ->                           |
|                 |              |                 |            |                                     |                 | gloo-system.default-petstore-8080 |
|                 |              |                 |            |                                     |                 | (upstream)                        |
+-----------------+--------------+-----------------+------------+-------------------------------------+-----------------+-----------------------------------+
```

```
$ glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... An update to your gateway-proxy deployment was rejected due to schema/validation errors. The envoy_listener_manager_lds_update_rejected{} metric increased.
You may want to try using the `glooctl proxy logs` or `glooctl debug logs` commands.
Problems detected!
```

**To Reproduce**

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
  name: gateway-proxy-ssl-2
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 4443
  httpGateway: {}
  proxyNames:
  - gateway-proxy
  ssl: true
  useProxyProto: false
```

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: conflict1
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: tls
      namespace: gloo-system
    sniDomains:
    - foo.example.com
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /api
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: conflict2
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: tls
      namespace: gloo-system
    sniDomains:
    - foo.example.com
  virtualHost:
    domains:
    - foo.example.com
    routes:
    - matchers:
      - prefix: /api
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```

**Expected behavior**
Gloo validation rejects the invalid listener state

**Comment by bdecoste** [comment]
If the virtualservices do not get assigned to the same gateway then there is no problem. If they are both assigned to the same gateway but have different sniDomains there is no conflict, both are accepted and Envoy is happy

**Comment by kdorosh** [comment]
The first question for @mlholland , does the `Proxy` generated in this scenario have matching SNI domains in it's `SSLConfig`?
```golang
// SslConfig contains the options necessary to configure a virtual host or listener to use TLS
type SslConfig struct {
	// Types that are valid to be assigned to SslSecrets:
	//	*SslConfig_SecretRef
	//	*SslConfig_SslFiles
	//	*SslConfig_Sds
	SslSecrets isSslConfig_SslSecrets `protobuf_oneof:"ssl_secrets"`
	// optional. the SNI domains that should be considered for TLS connections
	SniDomains []string `protobuf:"bytes,3,rep,name=sni_domains,json=sniDomains,proto3" json:"sni_domains,omitempty"`
	// Verify that the Subject Alternative Name in the peer certificate is one of the specified values.
	// note that a root_ca must be provided if this option is used.
	VerifySubjectAltName []string       `protobuf:"bytes,5,rep,name=verify_subject_alt_name,json=verifySubjectAltName,proto3" json:"verify_subject_alt_name,omitempty"`
	Parameters           *SslParameters `protobuf:"bytes,6,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// Set Application Level Protocol Negotiation
	// If empty, defaults to ["h2", "http/1.1"].
	AlpnProtocols        []string `protobuf:"bytes,7,rep,name=alpn_protocols,json=alpnProtocols,proto3" json:"alpn_protocols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```

If so, we should prevent the gateway from writing such a proxy (here https://github.com/solo-io/gloo/blob/v1.5.0-beta17/projects/gateway/pkg/translator/http.go#L199) by adding a check similar to the one here https://github.com/solo-io/gloo/blob/v1.5.0-beta17/projects/gateway/pkg/translator/http.go#L59. Additionally, it would be prudent to add such validation to gloo itself during the generation of envoy config (see here https://github.com/solo-io/gloo/blob/v1.5.0-beta17/projects/gloo/pkg/translator/listener.go#L146)

**Comment by RichiCoder1** [comment]
God bless. The embarrassing amount of times I've run into this without any visible errors aside from things not working.

**Comment by EItanya** [comment]
**Describe the bug**
Gloo currently translates Separate SSL configs into envoy `FilterChainMatches`. Gloo takes certain steps to ensure that equal `FilterChainMatches` are not sent to envoy, as that is a bug. If the Virtual Hosts have matching SslSecrets and `VerifySubjectAltName` than it combines the SNI domains and merges them. However, if separate SslSecrets are used, and no other match criteria are used, then the listener is sent to envoy, and subsequently rejected. However, this error is not propogated up to the resource. 

**To Reproduce**

1. `helm install gloo https://storage.googleapis.com/gloo-ee-helm/charts/gloo-ee-1.5.0-beta8.tgz -n gloo-system`

2. `openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
   -keyout tls.key -out tls.crt -subj "/CN=petstore.example.com"`

3. `kubectl create secret tls upstream-tls --key tls.key \
   --cert tls.crt --namespace gloo-system`

4. `kubectl create secret tls upstream-tls-2 --key tls.key \
   --cert tls.crt --namespace gloo-system`

5. 

```
cat << EOF | kubectl apply -f -
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: my-vs-1
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - 'my.domain.com'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: rate-limit
            namespace: gloo-system
  ssl_config:
    secret_ref:
      name: upstream-tls
      namespace: gloo-system

---

apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: my-vs-2
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - 'other.domain.com'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: rate-limit
            namespace: gloo-system
  ssl_config:
    secret_ref:
      name: upstream-tls-2
      namespace: gloo-system
EOF
```

**Expected behavior**
The applied VirtualService which would cause this bug should be rejected. This can be accomplished most simply by checking the equality of all `FilterChainMatches` to ensure that envoy will not reject the listener. Some extra logic can be added to determine the exact source of the problem as well.

**Additional context**

- gloo version: gloo-e v1.5.0-beta8
- kube version: 1.18.x
