### ISSUE TITLE
Simplify API key secret structure

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#3472]
## Problem
We currently expect API key Kubernetes secrets to be standard solo-kit secrets, which means that the secret payload is encoded in the secret data. Currently an API key secret has the following format:

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    resource_kind: '*v1.Secret'
  labels:
    team: infrastructure
  name: infra-apikey
  namespace: gloo-system
type: Opaque
data:
  apiKey: YXBpS2V5OiBOMll3TURJeFpURXROR1V6TlMxak56Z3pMVFJrWWpBdFlqRTJZelJrWkdWbU5qY3kKbGFiZWxzOgotIHRlYW09aW5mcmFzdHJ1Y3R1cmUK
``` 

Where the `data.apiKey` element is an encoded YAML document, in this case:

```yaml
config:
  api_key: N2YwMDIxZTEtNGUzNS1jNzgzLTRkYjAtYjE2YzRkZGVmNjcy
  labels:
  - team=infrastructure
```

This format makes it unnecessary hard to manage API key secrets: it is not possible to easily create a secret using `kubectl`, and extracting the API key requires an additional parsing operation.

## Proposed solution
The secret data element should just contain the API key and the secret type information should be expressed via the standard `type` secret attribute, e.g.

```yaml
apiVersion: v1
kind: Secret
type: extauth.solo.io/apikey
metadata:
  labels:
    team: infrastructure
  name: infra-apikey
  namespace: gloo-system
data:
  api-key: TjJZd01ESXhaVEV0TkdVek5TMWpOemd6TFRSa1lqQXRZakUyWXpSa1pHVm1OamN5
```

Where `TjJZd01ESXhaVEV0TkdVek5TMWpOemd6TFRSa1lqQXRZakUyWXpSa1pHVm1OamN5` is just the encoded API key.

Creating a secret via `kubectl` would then be very easy:

```
kubectl create secret generic infra-apikey --type extauth.solo.io/apikey --from-literal api-key=$MY_API_KEY
```
