### ISSUE TITLE
alternative to escaped double quote for dynamic metadata access log 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3482]
**Is your feature request related to a problem? Please describe.**
Access log DYNAMIC_METADATA entries are enclosed in escaped double quotes:

`{"responseCode":"200","podName":"\"gateway-proxy-66fc5954b7-sd2x4\"","responseDuration":"1","requestId":"37ac79a2-58fe-9f29-8b8a-b50114f5212b","matcher":"\"spl\"","downstreamRemoteAddress":"10.32.1.1:65351","access":"ACCESS","httpMethod":"GET","centralId":"\"test\"","host":"-","authority":"35.203.154.113","path":"/dynamic-metadata","protocol":"HTTP/2","requestDuration":"0","startTime":"2020-08-06T21:05:17.510Z","duration":"2","upstream":"default-petstore-8080_gloo-system","error":"-","pod":"-","wafLog":"-","clientId":"-"}`

```
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            access: ACCESS
            authority: '%REQ(:AUTHORITY)%'
            centralId: '%DYNAMIC_METADATA(io.solo.transformation:central-id)%'
            clientId: '%REQ(CUSTOM-CLIENT-ID)%'
            downstreamRemoteAddress: '%DOWNSTREAM_REMOTE_ADDRESS%'
            duration: '%DURATION%'
            error: '%DYNAMIC_METADATA(io.solo.transformation:error)%'
            host: '%REQ(:HOST)%'
            httpMethod: '%REQ(:METHOD)%'
            matcher: '%DYNAMIC_METADATA(io.solo.transformation:matchers)%'
            path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            pod: '%DYNAMIC_METADATA(io.solo.transformation:pod)%'
            podName: '%DYNAMIC_METADATA(io.solo.transformation:pod_name)%'
            protocol: '%PROTOCOL%'
            requestDuration: '%REQUEST_DURATION%'
            requestId: '%REQ(X-REQUEST-ID)%'
            responseCode: '%RESPONSE_CODE%'
            responseDuration: '%RESPONSE_DURATION%'
            startTime: '%START_TIME%'
            upstream: '%UPSTREAM_CLUSTER%'
            wafLog: '%FILTER_STATE(io.solo.modsecurity.audit_log)%'
          path: /dev/stdout
```
```

    routes:
    - matchers:
      - prefix: /dynamic-metadata
      options:
        autoHostRewrite: true
        extauth:
          disable: true
        jwt:
          disable: true
        prefixRewrite: /api/pets
        rbac:
          disable: true
        transformations:
          requestTransformation:
            transformationTemplate:
              dynamicMetadataValues:
              - key: matchers
                value:
                  text: '{% if "404" == "404" %}spl{% else %}spl{% endif %}'
              - key: central-id
                value:
                  text: test
              - key: pod_name
                value:
                  text: '{{ env("POD_NAME") }}'
```

**Describe the solution you'd like**

 I'd like to be able to either remove these or replace with non-escaped single quotes.
