### ISSUE TITLE
Rate Limits feature not working in the UI

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3484]
Kubernetes 1.18
Gloo Enterprise version v1.4.6

When creating a VirtualService with a rate limit as below, the rate limit isn't displayed in the UI :

```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: gloo-ui
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      ratelimitBasic:
        anonymous_limits:
          requestsPerUnit: 4
          unit: MINUTE
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: gloo-system-apiserver-ui-8080
            namespace: gloo-system
EOF
```

When creating a limit from the UI (by clicking on the `Update Rate Limits` link in the Virtual Service page), only for anonymous access, it creates it, but the menu isn't closed.
And the VirtualService is invalid:

```
status:
  reason: "1 error occurred:\n\t* VirtualHost Error: ProcessingError. Reason: invalid
    virtual host [gloo-system_gloo-ui]: unknown unit for authenticated config\n\n"
```

It's because it creates the rate limit with an empty authorizedLimits:

```
    options:
      ratelimitBasic:
        anonymousLimits:
          requestsPerUnit: 4
          unit: MINUTE
        authorizedLimits: {}
```

When creating a limit from the UI for both authorized and anonymous access, it creates the VirtualService correctly, but again, the menu isn't closed.

And in all the cases, the rate limits are never displayed in the UI.
