### ISSUE TITLE
unknown field "headerName" in v1.ApiKeyAuth

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3500]
The page https://docs.solo.io/gloo/latest/guides/security/auth/extauth/apikey_auth/ contains an example showing how to create and `AuthConfig` object like that:

```
kubectl apply -f - <<EOF
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: apikey-auth
  namespace: gloo-system
spec:
  configs:
  - apiKeyAuth:
      # This is the name of the header that is expected to contain the API key.
      # This field is optional and defaults to `api-key` if not present.
      headerName: api-key
      labelSelector:
        team: infrastructure
EOF
```

But then you get this error:

```
converting output crd: reading crd spec on resource apikey-auth in namespace gloo-system into v1AuthConfig: unknown field "headerName" in v1.ApiKeyAuth
```

Removing the `headerName` field fix the issue.

This field is also documented in this page: https://docs.solo.io/gloo/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#apikeyauth

But it looks like this field doesn't exist anymore, so both pages should be updated.

**Comment by djannot** [comment]
Also, the documentation on the first page (https://docs.solo.io/gloo/latest/guides/security/auth/extauth/apikey_auth/) indicated that the Secret should be like that:

```
apiVersion: v1
kind: Secret
type: extauth.solo.io/apikey
metadata:
  labels:
    team: infrastructure
  name: infra-apikey
  namespace: gloo-system
data:
  api-key: TjJZd01ESXhaVEV0TkdVek5TMWpOemd6TFRSa1lqQXRZakUyWXpSa1pHVm1OamN5
```

But the value of `type` should be `Opaque`
