### ISSUE TITLE
>= 1.4.7 create duplicate extauth&rate-limit Service&Deployment resources when global.extensions.dataplanePerProxy=false

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3516]
**Describe the bug**
>= 1.4.7 create duplicate extauth&rate-limit Service&Deployment resources when `global.extensions.dataplanePerProxy=false`

This causes the install to fail. 
**To Reproduce**
1. Deploy GlooE via Helm with multiple gatewayProxies

**Expected behavior**
No duplicate resources for shared dataplane

**Comment by kdorosh** [comment]
Helm values that can reproduce the problem:
```yaml
global:
  extensions:
    dataplanePerProxy: false
  glooStats:
    enabled: true
gloo:
  global:
    glooStats:
      enabled: true
  discovery:
    fdsMode: BLACKLIST
  gateway:
    validation:
      alwaysAcceptResources: false
      allowWarnings: false
      webhook:
        enabled: true
  gatewayProxies:
    gatewayProxy:
      stats:
        enabled: true
      loopBackAddress: 127.0.0.1
      readConfig: true
      gatewaySettings:
        customHttpGateway:
          virtualServices:
          - name: standard-vs
            namespace: gloo-system
          options:
            httpConnectionManagerSettings:
              xffNumTrustedHops: 1
            proxyLatency:
              chargeClusterStat: true
              chargeListenerStat: true
              response: FIRST_INCOMING_FIRST_OUTGOING
        customHttpsGateway:
          virtualServices:
          - name: standard-vs
            namespace: gloo-system
          options:
            httpConnectionManagerSettings:
              xffNumTrustedHops: 1
            proxyLatency:
              chargeClusterStat: true
              chargeListenerStat: true
              response: FIRST_INCOMING_FIRST_OUTGOING
      podTemplate:
        disableNetBind: false
        floatingUserId: false
        httpPort: 8080
        httpsPort: 8443
    customProxy:
      loopBackAddress: 127.0.0.1
      stats:
        enabled: true
      gatewaySettings:
        customHttpGateway: 
          virtualServices:
          - name: custom-vs
            namespace: gloo-system
          options:
            httpConnectionManagerSettings:
              xffNumTrustedHops: 1
            proxyLatency:
              chargeClusterStat: true
              chargeListenerStat: true
              response: FIRST_INCOMING_FIRST_OUTGOING
        customHttpsGateway:
          virtualServices:
          - name: custom-vs
            namespace: gloo-system
          options:
            httpConnectionManagerSettings:
              xffNumTrustedHops: 1
            proxyLatency:
              chargeClusterStat: true
              chargeListenerStat: true
              response: FIRST_INCOMING_FIRST_OUTGOING
      readConfig: true
      configMap:
        data: 
      kind:
        deployment:
          antiAffinity: false
          replicas: 1
      podTemplate:
        disableNetBind: false
        floatingUserId: false
        httpPort: 8180
        httpsPort: 8543
        image:
          repository: gloo-ee-envoy-wrapper
          tag: 1.4.0
        probes: false
        runUnprivileged: false
      service:
        httpPort: 80
        httpsPort: 1443
        type: LoadBalancer
        annotations:
          prometheus.io/path: "/metrics"
          prometheus.io/port: "8081"
          prometheus.io/scrape: "true"
```
