### ISSUE TITLE
Metrics driven routing

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3558]
Several customers are interested by having the ability to use metrics to influence routing decisions.

- one use case is for Gloo Fed, to allow a Traffic shift based on metrics (when the latency was higher than x ms during the last y minutes, start to send z % of the traffic to another site)
- another use case is for Gloo to stop routing traffic to a subset based on metrics

@scootweiss was thinking about something like that:

```
routes:
- name: low-throughput-route
  condition: job:request_latency_seconds:mean5m{job="myjob"} <= 0.5
  destination:
    single: local-upstream
- name: high-throughput-route
  condition: job:request_latency_seconds:mean5m{job="myjob"} > 0.5
  destination:
    multi:
    - local-upstream, 50%
    - remote-upstream, 50%
```

The number of potential use cases is nearly unlimited and the metrics could be Envoy metrics, but also application metrics.
