### ISSUE TITLE
Redirect to a different page when OPA reject a call

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3575]
**Is your feature request related to a problem? Please describe.**
Currently, it simply returns a 403, so there's no way to explain to the end use what's wrong

**Describe the solution you'd like**
Add an option to redirect to a different page

**Comment by srenatus** [comment]
https://github.com/solo-io/gloo/issues/3201 would allow something like this, I think.

**Comment by djannot** [comment]
We did some investigations with @lgadban and found that the following works:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      extauth:
        configRef:
          name: opa
          namespace: gloo-system
      stagedTransformations:
        early:
          responseTransforms:
          - responseTransformation:
              transformationTemplate:
                headers:
                  location:
                    text: '{% if header(":status") == "403" %}/api/pets/1{% else %}{{
                  header(":path") }}{% endif %}'
                  :status:
                    text: '{% if header(":status") == "403" %}301{% else %}{{ header(":status") }}{% endif %}'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```

In this example, we replace `403` by `200` and redirect to `/api/pets`
