### ISSUE TITLE
extractors are not passed from early to regular staged transformations

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3608]
**Describe the bug**
extractors are not passed from early to regular staged transformations

**To Reproduce**
```
    - matchers:
      - exact: /early-trans-auth
      options:
        extauth:
          disable: false
        jwt:
          disable: true
        prefixRewrite: /api/pets
        stagedTransformations:
          early:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    tempauth1:
                      header: authorization
                      regex: .*
                  headers:
                    authorization:
                      text: '{% if header("authorization") == "foo" %}basic dXNlcjpwYXNzd29yZA=={%
                        else %}{{ header("authorization") }}{% endif %}'
          regular:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    tempauth2:
                      header: authorization
                      regex: .*
                  headers:
                    authorization:
                      text: '{{ tempauth2 }}'
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```
`{{ tempauth2 }}` works as expected but `{{ tempauth1 }}` results in the following from curl 

`bad request: [inja.exception.render_error] variable 'tempauth1' not found* Closing connection 0`
