### ISSUE TITLE
Helm settings.invalidConfigPolicy.replaceInvalidRoutes value not working

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3619]
**Describe the bug**
When setting `settings.invalidConfigPolicy.replaceInvalidRoutes` to true, the `settings.invalidConfigPolicy` isn't used

Looking at the `charts/gloo/templates/18-settings.yaml` file, I think the check is wrong:

```
{{- if .Values.settings.invalidConfigPolicy }}
    invalidConfigPolicy:
{{ toYaml .Values.settings.invalidConfigPolicy | indent 6}}
{{- end }}
````

I think it should be as follow:

```
{{- if .Values.settings.replaceInvalidRoutes }}
    invalidConfigPolicy:
{{ toYaml .Values.settings.invalidConfigPolicy | indent 6}}
{{- end }}
```

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version: 1.4.12 and 1.5.0beta9

**Comment by djannot** [comment]
With the new implementation, someone needs to provide the following values:

```
settings:
  replaceInvalidRoutes: true
  invalidConfigPolicy:
    invalidRouteResponseBody: Gloo Edge has invalid configuration. Administrators
      should run `glooctl check` to find and fix config errors.
    invalidRouteResponseCode: 404
    replaceInvalidRoutes: true
```

Can we find a better way ?
