### ISSUE TITLE
unable to deploy gateway-proxy with runAsRoot: 0 without runAsNonRoot: true

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3627]
**Describe the bug**
https://github.com/solo-io/gloo/blob/v1.4.12/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L143-L148

Unable to configure gateway-proxy to run as root. runAsRoot: 0 with runAsNonRoot: true results in a gateway-proxy pod failure 

**To Reproduce**
```
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        disableNetBind: false
        runAsUser: 0
        runUnprivileged: true or false
        floatingUserId: false
      readConfig: true
```
