### ISSUE TITLE
Adding missing Helm values for resource requests and limits

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3629]
The resource requests and limits aren't available for all the Gloo Deployments.

For example, the following ones aren't available:

```
observability:
  deployment:
    resources:
      requests:
        cpu: 30m
        memory: 64Mi
      limits:
        cpu: 600m
        memory: 128Mi
rateLimit:
  deployment:
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
redis:
  deployment:
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 50m
        memory: 64Mi
global:
  extensions:
    extAuth:
      deployment:
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 600m
            memory: 128Mi
```
