### ISSUE TITLE
per host healthchecks still requires upstream global healthcheck config 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3638]
**Is your feature request related to a problem? Please describe.**
Per host healthchecks require unused httpHealthCheck. See config below. Global httpHealthCheck is required for validation but not used
```

apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: echo-postman
  namespace: gloo-system
spec:
  connectionConfig:
    connectTimeout: 10s
  healthChecks:
  - healthyThreshold: 10
    httpHealthCheck:
      path: /notused
    interval: 10s
    timeout: 5s
    unhealthyThreshold: 1
  static:
    hosts:
    - addr: postman-echo.com
      healthCheckConfig:
        path: /bogus?foo=bar
      port: 443
    - addr: postman-echo.com
      healthCheckConfig:
        path: /get?bar=foo
      port: 443
```
