### ISSUE TITLE
Response Transformation not working when upstream not available

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3649]
**Describe the bug**
When I create a basic transformation like that:
```
        transformations:
          responseTransformation:
            transformationTemplate:
              body:
                text: '{% if header(":status") == "404" %}{ "error": "Not found!" }{% else %}{{ body() }}{% endif %}'
```

And I scale the deployment corresponding to the upstream to 0, I get the following error:
```
bad request: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 'no'* Closing connection 0
```

The `no` is the beginning of the original response which is `no healthy upstream`

**Additional context**
- Gloo version: I had the same issue in 1.4.12 And 1.5.0beta9
