### ISSUE TITLE
Envoy doesn't update using new Oauth2 syntax

### ISSUE THREAD

**Issue by ned1313** [solo-io/gloo#3691]
**Describe the bug**
When creating an AuthConfig using the new oauth2 API syntax, the configuration is not successfully applied to Envoy. This was discovered when running through the Dex OAuth guide for an update: https://docs.solo.io/gloo/latest/guides/security/auth/extauth/oauth/dex/

**To Reproduce**
AuthConfig being created:

```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oidc-dex
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        app_url: http://localhost:8080/
        callback_path: /callback
        client_id: gloo
        client_secret_ref:
          name: oauth
          namespace: gloo-system
        issuer_url: http://dex.gloo-system.svc.cluster.local:32000/
        scopes:
        - email
```

1. Run through the guide
2. Apply the AuthConfig as shown above
3. Test the external auth against the petclinic virtualservice

**Expected behavior**
The http://localhost:8080 page should redirect to the Dex login page. Instead it goes straight to the petclinic homepage.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version - 1.4.15
- Kubernetes version - 1.18.8

After doing an Envoy config dump the following section was different than a successful deployment using the old oauth syntax:

```json
"envoy.filters.http.ext_authz": { 
  "disabled": true
}
```

**Comment by Sodman** [comment]
Hi @ned1313 I'm struggling to reproduce this one. I've tried it on both Gloo 1.15.1 and then on 1.4.15, both times in fresh kind clusters, and both times I get redirected to Dex as expected.

My exact steps were (following the guide, except for the AuthConfig you posted above), on a fresh new cluster:


```
# Install gloo enterprise
glooctl install gateway enterprise --license-key LICENSE_KEY_GOES_HERE

# Install Petstore
kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v0.8.4/example/petclinic/petclinic.yaml

# Set up VS to petstore
cat << EOF | k apply -f -
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petclinic
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          kube:
            ref:
              name: petclinic
              namespace: default
            port: 80
EOF

# Create Dex values file
cat > dex-values.yaml <<EOF
config:
  issuer: http://dex.gloo-system.svc.cluster.local:32000
  staticClients:
  - id: gloo
    redirectURIs:
    - 'http://localhost:8080/callback'
    name: 'GlooApp'
    secret: secretvalue
  staticPasswords:
  - email: "admin@example.com"
    hash: "\$2a\$10\$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
EOF

# Install Dex
helm install dex --namespace gloo-system stable/dex -f dex-values.yaml

# Create secret
glooctl create secret oauth --client-secret secretvalue oauth

# Create AuthConfig with oauth2
cat << EOF | k apply -f -
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oidc-dex
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        app_url: http://localhost:8080/
        callback_path: /callback
        client_id: gloo
        client_secret_ref:
          name: oauth
          namespace: gloo-system
        issuer_url: http://dex.gloo-system.svc.cluster.local:32000/
        scopes:
        - email
EOF
```

Then I added the following to the petclinic virtualservice's spec.virtualHost:
```
options:
  extauth:
    configRef:
      name: oidc-dex
      namespace: gloo-system
```

Finally, for testing I did the following:
```
# port-forward dex & store the pid so we can kill the process later
kubectl -n gloo-system port-forward svc/dex 32000:32000 & 
portForwardPid1=$!

# Port forward gateway-proxy and envoy admin + hold onto pid for killing later
kubectl port-forward -n gloo-system gateway-proxy-PODNAME_HERE 8080:8080 19000:19000 &
portForwardPid2=$!

# Add a local DNS entry
echo "127.0.0.1 dex.gloo-system.svc.cluster.local" | sudo tee -a /etc/hosts
```

Upon opening up `localhost:8080` in a browser I am redirected to the Dex login page.

Notably, I also see the extauth config in the envoy admin dump:

```
"typed_per_filter_config": {
         "envoy.filters.http.ext_authz": {
          "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute",
          "check_settings": {
           "context_extensions": {
            "config_id": "gloo-system.oidc-dex",
            "source_name": "gloo-system.gateway-proxy-listener-::-8080-gloo-system_petclinic",
            "source_type": "virtual_host"
           }
          }
         }
        }
```

Can you give it a shot with the steps above or let me know if I've missed a step to reproduce? Thanks!
