### ISSUE TITLE
Empty upstreams

### ISSUE THREAD

**Issue by sbvitok** [solo-io/gloo#3710]
**Describe the bug**
Gloo remove upstreams from envoy after editing upstream spec

**To Reproduce**
1. Create Upstream for example:
```
# Source: ingress/templates/upstream.yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-whoami-80-custom
  namespace: pfm-admins
  labels:
    app.kubernetes.io/instance: whoami
spec:
  connectionConfig:
    connectTimeout: 0.3s
  circuitBreakers:
    maxConnections: 10240
    maxPendingRequests: 10240
    maxRequests: 10240
  kube:
    selector:
      app.kubernetes.io/instance: whoami
    serviceName: whoami
    serviceNamespace: default
    servicePort: 80
```
2. kubectl edit  us -n pfm-admins default-whoami-80-custom
add
```
  loadBalancerConfig:
    leastRequest:
      choiceCount: 3

```
3. See new lb configuration in /config_dump
4. But in the /cluster all upstream ips is gone and envoy say no healthy upstream
5. And for them to appear again need to do
kubectl rollout restart deployment/whoami

**Expected behavior**
they were not expected to disappear

**Additional context**
- Gloo version 1.3.34
- Kubernetes version 1.18
