### ISSUE TITLE
support envoy_config_core_v3.Http2ProtocolOptions.connection_keepalive 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3740]
**Describe the bug**
Envoy init (GlooE 1.5.1) prevents use of this field

**To Reproduce**
```
clusters:
   - name: gloo.gloo-system.svc.cluster.local:9977
    alt_stat_name: xds_cluster
    connect_timeout: 5.000s
    load_assignment:
     cluster_name: gloo.gloo-system.svc.cluster.local:9977
     endpoints:
     - lb_endpoints:
      - endpoint:
        address:
         socket_address:
          address: gloo.gloo-system.svc.cluster.local
          port_value: 9977
    http2_protocol_options:
     connection_keepalive:
      interval: 5s
      timeout: 5s
    upstream_connection_options:
     tcp_keepalive: {}
    type: STRICT_DNS
    respect_dns_ttl: true
```

```
$ kubectl -n gloo-system logs gateway-proxy-6bdc947599-6jjlx
2020/10/13 13:32:41 initializer failed: unknown field "connection_keepalive" in envoy_config_core_v3.Http2ProtocolOptions
**Expected behavior**
supported envoy_config_core_v3.Http2ProtocolOptions.connection_keepalive 
```

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/protocol.proto#envoy-v3-api-msg-config-core-v3-http2protocoloptions
