### ISSUE TITLE
4-ratelimit-upstream.yaml  creates incorrect grpc service name which results in failing health checks 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#3745]
**Describe the bug**
Upstream for rate-limit needs to be 

```
spec:
  healthChecks:
  - grpcHealthCheck:
      serviceName: ratelimit
    healthyThreshold: 5
    interval: 60s
    timeout: 5s
    unhealthyThreshold: 5
```

not

```
spec:
  healthChecks:
  - grpcHealthCheck:
      serviceName: rate-limit
    healthyThreshold: 5
    interval: 60s
    timeout: 5s
    unhealthyThreshold: 5
```

This is the erroneous commit:
https://github.com/solo-io/solo-projects/commit/520af9273a64304237ef20cd9bcce311210bea83#diff-d864bab3908337eca5a53cbfa0f95bd4c3543243229ea37b037c22a66e238f8eL17-R22
