### ISSUE TITLE
Gloo and gloo-ee components still being created even with `gatewayProxies.gatewayProxy.disabled=true` set in our values file.

### ISSUE THREAD

**Issue by tmojlupo** [solo-io/gloo#3751]
**Describe the bug**
I are using the `global.extensions.dataplanePerProxy=true` option in the Helm values file and testing `gatewayProxies.gatewayProxy.disabled=true`.  This does properly remove the `gateway-proxy` deployment, but there are still a number of other objects that get created.

These are the objects (both gloo and gloo-ee) that get created that seem like they shouldn't exist without the relevant gateway-proxy.
configmap - gateway-proxy-envoy-config (gloo)
service - gateway-proxy (gloo), redis-gateway-proxy (gloo-ee), extauth-gateway-proxy (gloo-ee), rate-limit-gateway-proxy (gloo-ee)
deployment - redis-gateway-proxy (gloo-ee), rate-limit-gateway-proxy (gloo-ee), extauth-gateway-proxy (gloo-ee)
gateway - gateway-proxy (gloo)
upstream - extauth-gateway-proxy (gloo-ee), rate-limit-gateway-proxy (gloo-ee)

**To Reproduce**
1. Create a values.yaml file with the following:
```
gloo:
  gatewayProxies:
    gatewayProxy:
      disabled: true
    gatewayProxyInternal:
      antiAffinity: false
      failover:
        enabled: false
        secretName: ""
      kind:
        deployment:
          replicas: 1
      podTemplate:
        customReadinessProbe: {}
        disableNetBind: true
        floatingUserId: false
        fsGroup: 10101
        gracefulShutdown:
          enabled: false
          sleepTimeSeconds: 25
        httpPort: 8080
        httpsPort: 8443
        image:
          extended: false
          pullPolicy: IfNotPresent
          repository: gloo-ee-envoy-wrapper
          tag: 1.5.1
        probes: false
        runAsUser: 10101
        runUnprivileged: true
        terminationGracePeriodSeconds: 0
        tolerations: null
      readConfig: false
      service:
        extraAnnotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8081"
          prometheus.io/scrape: "true"
        httpPort: 80
        httpsFirst: false
        httpsPort: 443
        type: LoadBalancer
```
2. Run the helm command to install:
   `helm install gloo-ee glooe/gloo-ee --include-crds --namespace gloo-system --version 1.5.1 --set license_key=<your license> --values values.yml`
3. See the various components that show up that shouldn't exist without the appropriate gateway-proxy object.

**Expected behavior**
I would expect that disabling the default gatewayProxy object would also disable all related components.

**Additional context**
Testing with gloo-ee 1.5.1, helm 3.2.1 and kubernetes 1.15.5.
