### ISSUE TITLE
Expose tracing configuration through dynamic listeners (gateway)

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#3762]
Previously, envoy v2 allowed to configure tracing configuration at the bootstrap/global level. They changed it (as did we, see https://github.com/solo-io/gloo/commit/f82f098a442ae595c83a196ba433704043a3acc1#diff-cc111218d75d3fe2f38b3e0e5b67da77852da25dbaa566f98f87227303650891) to be at the listener level. We cannot config listeners tracing unless we expose that on the Gloo API.

**Comment by Hugome** [comment]
Just a quick question : Is this the reason why the tracing is not working ?
I don't have any tracing `provider` configuration in my `type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager` filter :
```yml
"tracing": {
 "client_sampling": {
  "value": 100
 },
 "random_sampling": {
  "value": 100
 },
 "overall_sampling": {
  "value": 100
 },
 "verbose": true,
 "custom_tags": [
  {
   "tag": "path",
   "request_header": {
    "name": "path"
   }
  },
  {
   "tag": "origin",
   "request_header": {
    "name": "origin"
   }
  }
 ]
},
```
I even add the `generate_request_id` at `true` and this is not working as well

The only working tracing listener/filter are the `prometheus` (As asked to configure in the docs)

Thanks
