### ISSUE TITLE
CORS broken when matchers include methods

### ISSUE THREAD

**Issue by ctomc** [solo-io/gloo#3774]
When you configure CORS and have path matchers that include method matching, OPTIONS pre flight request fail with 404 while it should return 200 or 204.
Workaround is to specify OPTIONS also as one of the matchers on the path, even if backend service doesn't support it.

**To Reproduce**
1. kube apply https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml
2. apply file

```yml
cat <<EOF | kubectl apply -f -
---
metadata:
  name: default
  namespace: gloo-system  
virtualHost:
  domains:
  - '*'
  options:
    cors:
      allowCredentials: true
      allowHeaders:
      - origin
      allowMethods:
      - GET
      - POST
      - OPTIONS
      allowOrigin:
      - https://solo.io
      allowOriginRegex:
      - https://[a-zA-Z0-9]*.gloo.dev
      exposeHeaders:
      - origin
      maxAge: 1d
  routes:
  - matchers:
    - methods:
      - GET
      - POST
      prefix: /httpbin
    options:
      prefixRewrite: /
    routeAction:
      single:
        upstream:
          name: default-httpbin-8000
          namespace: gloo-system

```
3. curl --location --request OPTIONS '<address-of-gloo>/httpbin/anything' \
--header 'Origin: https://www.solo.io' \
--header 'Access-Control-Request-Method: GET' \
--header 'Access-Control-Request-Headers: content-type'
4. it returns 404 not found, while it should return 200 with proper cors headers.
5. if you change the matchers to include also "OPTIONS" method, you get back proper 200 response, but CORS matching is not correct. For example it would return that also DELETE method is allowed

**Expected behavior**
No OPTIONS method should be specified in route matcher. As well as proper cors response should be always returned 

**Additional context**
Add any other context about the problem here, e.g.
- Gloo version: 1.5.2
- Kubernetes version: 1.16.1
