### ISSUE TITLE
Can't apply transformations at different levels

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3798]
**Describe the bug**
When applying transformations at different levels (one in the VirtualService, one in a RouteTable, for example), only the one in the lowest level is applied

**To Reproduce**

```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /messaging
      options:
        prefixRewrite: /get
        transformations:
          requestTransformation:
            transformationTemplate:
              headers:
                first:
                  text: 'level'
      delegateAction:
        ref:
          name: messaging
          namespace: gloo-system
    - matchers:
      - prefix: /sms
      delegateAction:
        ref:
          name: sms
          namespace: gloo-system
EOF

kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: messaging
  namespace: gloo-system
spec:
  routes:
    - matchers:
      - prefix: /messaging
      options:
        transformations:
          requestTransformation:
            transformationTemplate:
              headers:
                second:
                  text: 'level'
      delegateAction:
        ref:
          name: submessaging
          namespace: gloo-system
EOF

kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: submessaging
  namespace: gloo-system
spec:
  routes:
    - matchers:
      - prefix: /messaging
      options:
        transformations:
          requestTransformation:
            transformationTemplate:
              headers:
                third:
                  text: 'level'
      routeAction:
        single:
          upstream:
            name: default-httpbin-service-1-80
            namespace: gloo-system
EOF

kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: sms
  namespace: gloo-system
spec:
  routes:
    - matchers:
      - prefix: /sms
      routeAction:
        single:
          upstream:
            name: default-httpbin-service-2-80
            namespace: gloo-system
EOF
```

When executing the commands above and then a curl, only the header `third` is added.

Note that if we use `transformations` and `stagedTransformations`, one of each time is applied.

**Expected behavior**
The transformations should be combined

**Additional context**
- Gloo version: Same behavior in 1.4.5 and 1.5.3
