### ISSUE TITLE
Rate limit rule configuration doesn't distinguish between key a_b and key_value pair a_b

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#3801]
**Describe the bug**
Rate limit rule configuration does not distinguish between
```
key: a
value: b
```
and
```
key: a_b
```

**To Reproduce**
1. Deploy pet store sample application: `kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml`
2. Install glooE: `glooctl install gateway enterprise --license-key {licenseKey} --version 1.6.0-beta4`
3. Add vs routing to petstore application: `glooctl add route --name petstore --path-prefix / --dest-name default-petstore-8080`
4. Edit the vs: `k edit vs petstore -n gloo-system` to include this rate limit configuration under `virtualHost:`:
```
    options:
      ratelimit:
        rateLimits:
        - actions:
          - requestHeaders:
              descriptorKey: type
              headerName: x-type
```
5. Edit the settings: `k edit settings -n gloo-system` to include this rate limit configuration under `spec:`:
```
  ratelimit:
    descriptors:
    - key: type_example
      rateLimit:
        requestsPerUnit: 1
        unit: DAY
```
6. Send a request: `curl $(glooctl proxy url)/api/pets -v -H "x-type: example"`. Should give back a successful 200 response.
7. Send another request: `curl $(glooctl proxy url)/api/pets -v -H "x-type: example"`. _Should_ give back a successful 200 response but _will_ give back a 429 response indicating that the request was rate limited.

**Expected behavior**
The request should only be rate limited if you modify the settings to include the following configuration instead:
```
  ratelimit:
    descriptors:
    - key: type
      value: example
      rateLimit:
        requestsPerUnit: 1
        unit: DAY
```

**Additional context**
This bug can also easily be seen by modifying [this test](https://github.com/solo-io/rate-limiter/blob/v0.1.1/test/integration/kube/kube_test.go#L152) in the rate-limiter repo to use `Key: "key1_foo"` instead of `Key: "key1"` and seeing that the test still passes. In other words, the request with key/value pair `{"key1", "foo"}` is still rate limited.

Should also be tested for set rate limiting implementation once that's fully implemented. (https://github.com/solo-io/gloo/issues/2695)
See TODO in tests: https://github.com/solo-io/rate-limiter/blob/table-rate-limiting-2/pkg/config/domain_test.go#L293-L296
