### ISSUE TITLE
Improve TCP proxy routing via SNI

### ISSUE THREAD

**Issue by irozzo-1A** [solo-io/gloo#3823]
**Is your feature request related to a problem? Please describe.**
Today TCP proxy supports routing via SNI based on Envoy [SNI Cluster Filter](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/sni_cluster/v3/sni_cluster.proto.html?highlight=sni_cluster), with a configuration like:

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: passthrough-gateway
  namespace: gloo-system
  labels:
    app: gloo
spec:
  bindAddress: "::"
  bindPort: <port> 
  tcpGateway:
    tcpHosts:
    - name: sni_cluster
      destination:
        forwardSniClusterName: {}
  proxyNames:
  - gateway-proxy
```

The problem with this approach is that the matching with the upstream is implicit and requires the upstream cluster name to be the same as the SNI. As the Envoy docs point out:

> This extension has an unknown security posture and should only be used in deployments where both the downstream and upstream are trusted.

IMO a better alternative would be to match the upstream clusters explicitly with [Filter Chain Match](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto.html?highlight=filterchainmatch#config-listener-v3-filterchainmatch), based on:

> Server name (e.g. SNI for TLS protocol)

This solution also requires: https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/tls_inspector#config-listener-filters-tls-inspector

**Describe the solution you'd like**
I would like to be able to explicitly match an SNI and bind it to an upstream.

**Describe alternatives you've considered**
None

**Additional context**
None
