### ISSUE TITLE
Different JWT with TokenSource Behavior

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#3835]
**Describe the bug**
In GlooE 1.5.0-beta3 you can define a JWT provider which can handle JWTs in the `authorization` header in the "standard" location, i.e. `Authorization: Bearer $token`, as well as in another location, e.g. `Authorization: $token`

This same configuration doesn't work in GlooE 1.5.6

**To Reproduce**
In both versions, GlooE 1.5.0-beta3 and GlooE 1.5.6
1. Create a JWT secured VS with a `tokenSource` to match the scenario, e.g. --
```
spec:
  virtualHost:
    domains:
    - '*'
    options:
      jwt:
        providers:
          solo:
            audiences:
            - gloo
            issuer: solo.io
            jwks:
              local:
                key: |
                  -----BEGIN PUBLIC KEY-----
                  ...
                  -----END PUBLIC KEY-----
            tokenSource:
              headers:
              - header: authorization
              - header: authorization
                prefix: Bearer
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```

2. Send `curl` requests to both versions

GlooE 1.5.0-beta3
```
% curl localhost:8080/api/pets -H "authorization: Bearer ${TOKEN}"
[{"id":1,"name":"Dog","status":"available"},{"id":2,"name":"Cat","status":"pending"}]

% curl localhost:8080/api/pets -H "authorization: ${TOKEN}"
[{"id":1,"name":"Dog","status":"available"},{"id":2,"name":"Cat","status":"pending"}]
```

GlooE 1.5.6
```
% curl localhost:8080/api/pets -H "authorization: ${TOKEN_GOOD_USER}"
[{"id":1,"name":"Dog","status":"available"},{"id":2,"name":"Cat","status":"pending"}]

% curl localhost:8080/api/pets -H "authorization: Bearer ${TOKEN_GOOD_USER}"
Jwt header is an invalid JSON
```

**Expected behavior**
Unsure what is the correct behavior, expected consistency
