### ISSUE TITLE
Enabling replaceInvalidRoutes generates warning messages

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3867]
**Describe the bug**
When replaceInvalidRoutes is enabled and there's an invalid route (a missing upstream, for example), the log starts to be filled with the following warning:

```
[2020-11-13 09:48:58.414][8][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:107] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) fallback_listener_for_invalid_routes: Proto constraint validation failed (HttpConnectionManagerValidationError.RouteConfig: ["embedded message failed validation"] | caused by RouteConfigurationValidationError.VirtualHosts[i]: ["embedded message failed validation"] | caused by VirtualHostValidationError.Routes[i]: ["embedded message failed validation"] | caused by RouteValidationError.DirectResponse: ["embedded message failed validation"] | caused by DirectResponseActionValidationError.Status: ["value must be inside range [" 'd' ", " 'ɘ' ")"]): stat_prefix: "fallback_listener_for_invalid_routes"
route_config {
  name: "fallback_routes"
  virtual_hosts {
    name: "fallback_virtualhost"
    domains: "*"
    routes {
      match {
        prefix: "/"
      }
      direct_response {
        body {
          inline_string: ""
        }
      }
    }
  }
}
http_filters {
  name: "envoy.router"
}
```

**To Reproduce**
Enable replaceInvalidRoutes and create a VirtualService with an Upstream that doesn't exist.
Then, take a look at the `gateway-proxy` logs.

**Additional context**
- Gloo Edge version: 1.5.0

**Comment by lgadban** [comment]
This happens if the invalid config policy does not contain at least a response code e.g. :
```
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404
      replaceInvalidRoutes: true
```

The [docs should probably be updated](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/invalid_route_replacement/) since the `patch` command provided leaves the other fields empty. Runtime checks should probably be added to provide defaults. Not sure off the top of my head how the helm values work for this field but should be validated.

**Comment by lgadban** [comment]
Confirmed that this is possible to be set correctly via helm, although the values are a bit clumsy.

```
settings:
  replaceInvalidRoutes: true
  invalidConfigPolicy:
    invalidRouteResponseBody: Gloo Gateway has invalid configuration
    invalidRouteResponseCode: 404
    replaceInvalidRoutes: true
```

Or set as inline values:
```
helm install glooe glooe/gloo-ee -n gloo-system \
  --set-string license_key=$GLOO_LICENSE_KEY \
  --version 1.5.8 \
  --set settings.replaceInvalidRoutes=true \
  --set settings.invalidConfigPolicy.replaceInvalidRoutes=true \
  --set "settings.invalidConfigPolicy.invalidRouteResponseBody=Invalid config" \
  --set "settings.invalidConfigPolicy.invalidRouteResponseCode=404" \
  --create-namespace
```
