### ISSUE TITLE
Simultaneous use of global rate limiting and RateLimitConfig crds silently fails

### ISSUE THREAD

**Issue by arianaw66** [solo-io/gloo#3914]
**Describe the bug**
VirtualHost/Route options can only use either global rate limiting or RateLimitConfig crds, but global rate limiting is silently ignored when the user specifies both.

**To Reproduce**
1. Deploy pet store sample application: `kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml`
2. Install Gloo Edge Enterprise: `glooctl install gateway enterprise --license-key {licenseKey} --version 1.6.0-beta8`
3. Add RateLimitConfig crd: `k apply -f rateLimitConfig.yaml` where rateLimitConfig.yaml contains:
```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: my-rate-limit-policy
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: number
      value: example
      rateLimit:
        requestsPerUnit: 1
        unit: MINUTE
    rateLimits:
    - actions:
      - requestHeaders:
          descriptorKey: number
          headerName: x-number
```
4. Add vs routing to petstore application: `glooctl add route --name petstore --path-prefix / --dest-name default-petstore-8080`
5. Edit the settings: `k edit settings -n gloo-system` to include this rate limit configuration under `spec:`:
```
  ratelimit:
    descriptors:
    - key: type
      value: example
      rateLimit:
        requestsPerUnit: 1
        unit: DAY
```
6. Edit the vs: `k edit vs petstore -n gloo-system` to include this rate limit configuration under `routes:` (or start by omitting one of the setups and follow steps 6 and 7 to see both configs work without the other):
```
      options:
        rateLimitConfigs:
          refs:
          - name: my-rate-limit-policy
            namespace: gloo-system
        ratelimit:
          rateLimits:
          - actions:
            - requestHeaders:
                descriptorKey: type
                headerName: x-type
```
6. Send a request that uses the RateLimitConfig crds setup: `curl $(glooctl proxy url)/api/pets -v -H "x-number: example"`. Should give back a successful 200 response. Send the same request again. Should give back a 429 response indicating that the request was rate limited.
7. Send a request that uses the global rate limiting setup: `curl $(glooctl proxy url)/api/pets -v -H "x-type: example"`. Should give back a successful 200 response. Send the same request again. User would expect a 429 response indicating that the request was rate limited but you'll see a 200 response instead since the global rate limiting setup is ignored.
8. Note that the configuration was accepted without any indication of the ignored setup: `glooctl check` and `glooctl get vs petstore` 

**Expected behavior**
A virtual service with this config should be rejected with a useful error message.

**Additional context**
The proto `oneof` and comments clearly indicate that we do not expect to support both configurations at once: https://github.com/solo-io/gloo/blob/ca2437d26a1c5f2d539748ef88c8169273546c22/projects/gloo/api/v1/options.proto#L168
It's really just a matter of making sure this is clear to the user if they do it anyway.
