### ISSUE TITLE
Variable expansion in Destination references

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#3985]
**Context & problem**
Some companies, acting as SaaS/PaaS operators, do delegate part of routing to their tenants. In such a multi-tenant environment, one would like to dome some dynamic routing, based on variables and, more generally, upon the current context. Like using variable expansion in Destinations attributes, especially on the [ResourceRef](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/solo-kit/api/v1/ref.proto.sk/#resourceref) object, ie. the `name:` and `namespaces:` fields.

Also, it would be great if one could reuse context parameters in these values. Like the labels applied to the RouteTable or even some other metadata information from the parent VirtualService.

**Minimalist scenario with dynamic namespace selection**
![image](https://user-images.githubusercontent.com/9626829/102070372-52cc2f00-3dff-11eb-940f-80cfd1f5895f.png)

This simple use-case if only for demo purpose. In the real world, these companies would like to do some more extensive use of variables based "pointers" to Destinations, as described above and below.

**Describe the solution you'd like**
Here is an example, with fictional fields, making use of _regex_ and _inja templates_ in order to dynamically build values in the [ResourceRef](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/solo-kit/api/v1/ref.proto.sk/#resourceref) fields (`name:` + `namespace:`).
https://gist.github.com/bcollard/93830f775be2a9fe5c5bc2385c79a475#file-multi-tenant-sh

As you can see, there are 3 different suggestions here:
1. use of _inja template_ in the [ResourceRef](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/solo-kit/api/v1/ref.proto.sk/#resourceref) + custom function
2. use of _regex groups_ references in the [ResourceRef](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/solo-kit/api/v1/ref.proto.sk/#resourceref)
3. use in _inja template_, with a reference to  _metadata labels_ in the [ResourceRef](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/solo-kit/api/v1/ref.proto.sk/#resourceref)

You may find a more appropriate syntax...

**Describe alternatives you've considered**
GitOps + applying some kustomize patches per tenant --> would bring lot of duplicate route definitions for shared definitions. The company we talked to would like to avoid this.

Perhaps this will help for references to regex groups: https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#route-routeaction -> see the `regex_rewrite` paragraph (as already requested by https://github.com/solo-io/gloo/issues/2562).

**Comment by OcamsRazor** [comment]
I'm also very interested in this. 

I have a use case with a lot of tenants which are identified by header over the same domain after authentication. By default they share all routing paths but we have upstreams per tenant. Using the captured value of the Inja templates in the destinations would be very useful. 

This would mean a lot less config but also the advantage that we don't need a huge amount of matchers for the header value. Variable expansion would be a lot more efficient.

**Comment by galgro** [comment]
I'm also very interested in this.

**Comment by kdorosh** [comment]
Another option here is to leverage [cluster header routing](https://github.com/solo-io/gloo/blob/01d04751f72c168e304977c4f67fdbcbf30232a9/projects/gloo/api/v1/proxy.proto#L248) and [transformations](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/transformations/) to achieve what you want. For example:

```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: tenants-superpaas-com
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: wildcarddotsuperpaasdotcom-tls
      namespace: gloo-system  
    sniDomains:
      - "*.superpaas.com"
  virtualHost:
    domains:
      - '*.superpaas.com'
    routes:
      - matchers:
          - prefix: /api
        delegateAction:
          ref:
            name: 'tenant-hub'
            namespace: 'gloo-system'
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: 'tenant-hub'
  namespace: 'gloo-system'
spec:
  routes:
    - matchers:
       prefix: "/api"
      delegateAction:
        selector:
          namespaces: "*" # delegate to all route tables in all namespaces, consider using labels here to only match ones that begin with `/api`
    # OTHER optional shared routes across tenants                           # :authority header because https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/core/matchers/matchers.proto.sk/#headermatcher
    # ...
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: 'main-rt'
  namespace: 'tenanta'
spec:
  routes:
    - matchers:
       - regex: '/api/cars/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)' # where the 1st regex group is - say - the car model and the 2nd regex group is the API we actually target
    options:
      stagedTransformations:
        early:
          requestTransforms:
          - clearRouteCache: true
            requestTransformation:
              transformationTemplate:
                extractors:
                  second-regex-group: # create an extractor to get the second regex group from :authority header
                    header: :authority
                    regex: /api/cars/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)
                    subgroup: 2
                headers:
                  cluster-header-name:
                    text: '{{ second-regex-group }}' # use extractor to set cluster header for routing. might need to tweak slightly to match cluster name, which has expected format see https://github.com/solo-io/gloo/blob/01d04751f72c168e304977c4f67fdbcbf30232a9/projects/gloo/pkg/translator/utils.go#L16
      routeAction:
        cluster_header: "cluster-header" # route to clusters named by the value of the "cluster-header" header, which was set by the transformation above
    # Others routes belonging to tenanta
    # ...

```

The trick here is to use dynamic routing via envoy cluster header routing, and set the header using transformations to grab the metadata you cared about. Then the tenant hub selects all / the appropriate route tables using our flexible route table selector. I tested that transformations and cluster header routing work together, did not test the entire yaml provided above -- hopefully it provides a starting place. Do you think this will work for your use case?

(more for my future self): I tested and confirmed that you can use transformations to set the header used in cluster header routing by running [this test](https://github.com/solo-io/gloo/blob/ddcfb31c08fc07f97bf31dda21322e6f9317a3f5/test/e2e/gateway_test.go#L470) with the following virtual service:

```golang
vs.GetVirtualHost().Routes = []*gatewayv1.Route{{
Options: &gloov1.RouteOptions{
	StagedTransformations: &transformation.TransformationStages{
		Early:&transformation.RequestResponseTransformations{
			RequestTransforms:[]*transformation.RequestMatch{
				{
					Matcher:                nil,
					ClearRouteCache:        true,
					RequestTransformation:  &transformation2.Transformation{
						TransformationType: &transformation2.Transformation_TransformationTemplate{
							TransformationTemplate: &transformation2.TransformationTemplate{
								Headers: map[string]*transformation2.InjaTemplate{
									"cluster-header-name": &transformation2.InjaTemplate{Text:upstreamName},
									//"cluster-header-name": &transformation2.InjaTemplate{Text:"{{ second-regex-group }}"},
								},
								//Extractors: map[string]*transformation2.Extraction{
								//	"second-regex-group": &transformation2.Extraction{
								//		Source:   &transformation2.Extraction_Header{Header:":authority"},
								//		Regex:    "/api/cars/([a-zA-Z0-9]+)/([a-zA-Z0-9]+)",
								//		Subgroup: 2,
								//	},
								//},
							},
						},
					},
					ResponseTransformation: nil,
				},
			},
		},
	},
},
Action: &gatewayv1.Route_RouteAction{
	RouteAction: &gloov1.RouteAction{
		Destination: &gloov1.RouteAction_ClusterHeader{
			ClusterHeader: "cluster-header-name",
		},
	},
}}}
```
