### ISSUE TITLE
Consul Upstreams not working when discovery is disabled

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#3988]
**Describe the bug**
When discovery is disabled in the Settings (by omitting the `serviceDiscovery` entry) and an Upstream is created, its status shows an error:
```
status:
  reason: "1 error occurred:\n\t* cluster was configured improperly by one or more
    plugins: name:\"petstore_gloo-system\" connect_timeout:<seconds:5 > lb_subset_config:<fallback_policy:ANY_ENDPOINT
    subset_selectors:<> > metadata:<> : cluster type STATIC specified but LoadAssignment
    was empty\n\n"
```

**To Reproduce**
Disable discovery in the Settings and create a simple Upstream like below:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: petstore
  namespace: gloo-system
spec:
  consul:
    serviceName: petstore
    dataCenters:
    - dc
```

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.5.12
