### ISSUE TITLE
How does it match with multiple jwt providers and routes

### ISSUE THREAD

**Issue by mjaow** [solo-io/gloo#4062]
**Describe the requested changes**

I have a question that how it matches if I have multiple jwt providers and routes. If I have 2 routes (/petstore1 and /petstore2), and 3 providers, it's a little confused that how does it match with these providers and routes

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /petstore1
      routeAction:
        single:
          kube:
            ref:
              name: petstore1
              namespace: default
            port: 8080
    - matchers:
      - prefix: /petstore2
      routeAction:
        single:
          kube:
            ref:
              name: petstore2
              namespace: default
            port: 8080
    options:
      jwt:
        providers:
          kube1:
            issuer: kubernetes/serviceaccount
            jwks:
              local:
                key: xxx
          kube2:
            issuer: kubernetes/serviceaccount
            jwks:
              local:
                key: xxx
          kube3:
            issuer: kubernetes/serviceaccount
            jwks:
              local:
                key: xxx
```

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/guides/security/auth/jwt/access_control/

**Browser Information**
If the change isn't related to content, please include your browser version and any other relevant information 
(e.g., browser zoom) to help us reproduce docs-related bugs.

**Additional context**
