### ISSUE TITLE
Inconsistent error behavior with invalid resources

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4072]
**Describe the bug**
We have inconsistent error handling when invalid resources are written to storage and then read into Gloo components.

On startup, we fail and exit the process. If the pod has already started, then we just log errors.

**To Reproduce**
Write an invalid resource to storage, e.g.:

```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: json-upstream
  namespace: gloo-system
spec:
  static:
    hostss: # typo here
      - addr: jsonplaceholder.typicode.com
        port: 80
```
Gloo will just log an error. But if you bounce the pod, Gloo will go into a crash loop (not ideal, e.g. pod gets rescheduled)

**Expected behavior**
Gloo components don't enter crash loop, just log errors
