### ISSUE TITLE
Specifying "name" in Auth Config triggers binary validation

### ISSUE THREAD

**Issue by RichiCoder1** [solo-io/gloo#4082]
**Describe the bug**
Specifying a `name` field for a config in `AuthConfig` results in the ext-auth service validating the binary expr, even if only one config is specified.

**To Reproduce**

```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: default-auth
  namespace: gloo-system
spec:
  configs:
  - name: opa
    passThroughAuth:
      grpc:
        address: authz.gloo-system.svc.cluster.local:9191
```

**Expected behavior**
I would have expected for the name to work. Added it just in case I wanted to add others later and to be more explicit.

**Additional context**
- Gloo Edge version: 1.6.1
- Kubernetes version: 1.16 (EKS-1)
