### ISSUE TITLE
Ratelimit config dump endpoint can be misformatted

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#4098]
**Describe the bug**
If you're debugging the rate limit server, we recommend looking at the configuration the rate limit server has received (e.g., we recommend so here https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/crds/)

In simple cases, the formatting is clean (e.g., as documented above). In more complex ones, we can get a mess such as:
```
treeDescriptors:
setDescriptors: treeDescriptors: crd.generic_key_gloo-system.global-limit.generic_key_count: unit=MINUTE requests_per_unit=4 weight=0 always_apply=false
crd.generic_key_gloo-system.per-upstream-counter.destination_cluster: unit=MINUTE requests_per_unit=3 weight=0 always_apply=false

setDescriptors: treeDescriptors:
setDescriptors: custom.accountid_test_account.api_voice.generic_key_solo.setDescriptor.uniqueValue: unit=MINUTE requests_per_unit=5 always_apply=true
```

**Expected behavior**
Render in useful manner, e.g.
```
domain: custom
  treeDescriptors:
  setDescriptors:
    - custom.accountid_test_account.api_voice.generic_key_solo.setDescriptor.uniqueValue: unit=MINUTE requests_per_unit=5 always_apply=true
domain: ingress
  treeDescriptors:
  setDescriptors:
domain: crd
  treeDescriptors:
    - crd.generic_key_gloo-system.global-limit.generic_key_count: unit=MINUTE requests_per_unit=4 weight=0 always_apply=false
    - crd.generic_key_gloo-system.per-upstream-counter.destination_cluster: unit=MINUTE requests_per_unit=3 weight=0 always_apply=false
  setDescriptors:
```

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.6.1
- Kubernetes version: not relevant
