### ISSUE TITLE
Some helm defaults aren't carried over from gloo into solo-projects

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/gloo#4130]
When Gloo EE is deployed with:
```
gloo:
  gatewayProxies:
    gatewayProxy:
      failover:
        enabled: true
      service:
        type: LoadBalancer
```

The default failoverSecret name from Gloo isn't read in, resulting in a wrong Gateway object:
```
      sslConfig:
        secretRef:
          namespace: gloo-system
```
with no name.

The reason for this is because the gloo helm chart default values look like:
```
gatewayProxies:
  gatewayProxy:
    envoyApiVersion: V3
    gatewaySettings: {}
    failover:
      enabled: false
      port: 15443
      secretName: failover-downstream
```

while the gloo-ee helm chart default values look like:
```
gloo:
  gatewayProxies:
    gatewayProxy:
      failover:
        enabled: false
```
