### ISSUE TITLE
Allow setting istio-proxy image for istio sds during a helm installation of gloo

### ISSUE THREAD

**Issue by malmanzor** [solo-io/gloo#4152]
**Is your feature request related to a problem? Please describe.**

When deploying gloo via helm I can set `global.istioSDS.enabled: true` to add istio/sds sidecars to the gateway-proxy. We would like to customize the image used for the `istio-proxy container` so that it matches the version of istio that we are using rather than the default version that is set in the gloo chart https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L301. Currently, this is only possible by providing a `customSidecar` definition which would be overkill for just setting the `istio-proxy` image name.

**Describe the solution you'd like**

I would like to be able to set the istio-proxy container name via a helm value:

~~~
global:
  istioSDS:
    enabled: true
    proxyImage: docker.io/istio/proxyv2:<myversion>
~~~

**Describe alternatives you've considered**

Currently, we update the gloo helm chart as part of our build process to change the image version.

**Comment by rinormaloku** [comment]
> global:
>   istioSDS:
>     enabled: true
>     proxyImage: docker.io/istio/proxyv2:<myversion>

The following PR adds this feature: https://github.com/solo-io/gloo/pull/6651. I put it under glooMtls and named it `envoySidecarImage` so that it is similar to the other options.

```
global:
  istioSDS:
    enabled: true
    customSidecars:
  glooMtls:
    sds:
      image:
        tag: 1.11.16
    envoySidecarImage: docker.io/istio/proxyv2:1.12.6
```

**Comment by jenshu** [comment]
this will be available in gloo OSS v1.12.0-beta27 and v1.11.20

the new helm value is `global.glooMtls.istioProxy.image` e.g.
```
global:
  glooMtls:
    istioProxy:
      image:
        repository: proxyv2
        registry: docker.io/istio
        tag: 1.9.5
```
