### ISSUE TITLE
Regression in 1.6.x, metadata is now required in the spec

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#4171]
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: customfrontendservice-host-us
  namespace: gl-svc-almam-gls-140-snapshot
spec:
  kube:
    selector:
      app.kubernetes.io/instance: myservice
      app.kubernetes.io/name: opsservice
    serviceName: opsservice
    serviceNamespace: gl-svc-almam-gls-140-snapshot
    servicePort: 443
  loadBalancerConfig:
    ringHash:
      ringHashConfig:
        maximumRingSize: "1000"
        minimumRingSize: "100"
  metadata: {}
  sslConfig:
    alpnProtocols:
    - istio
    sds:
      certificatesSecretName: istio_server_cert
      clusterName: gateway_proxy_sds
      targetUri: 127.0.0.1:8234
      validationContextName: istio_validation_context
  useHttp2: true

```  
  no metadata in the spec result in a warning 
  
 this impacts upstream, rt. afaik
