### ISSUE TITLE
GRPC access logging with nonexistent cluster causes envoy segfault

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4203]
**Describe the bug**
Configuring a `Gateway` with a nonexistent static cluster causes envoy to segfault

**To Reproduce**
Create/modify a `Gateway` resource that points to a nonexistent static cluster, e.g.
```
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  options:
    accessLoggingService:
      accessLog:
      - grpcService:
          logName: prom-access-log
          staticClusterName: prom-access-log
  proxyNames:
  - gateway-proxy
  useProxyProto: false
```

**Expected behavior**
Some user safe guard to prevent segfault and proxy outage

**Additional context**
```
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.5.14","Name":"grpcserver-ui","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"grpcserver-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"grpcserver-envoy","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.5.14","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```
