### ISSUE TITLE
Bug around claims based routing

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4216]
**Describe the requested changes**
 The claims based routing works _IF_ you have a matcher **without** a header value. When you have 2 matchers, both containing header values it does not work.

E.g. from the guide on claim based routing: if you omit the second matcher without the header matcher for primary, the example won't work anymore.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/guides/security/auth/jwt/claim_routing/

**Browser Information**
n/a

**Additional context**

**Comment by cmwylie19** [comment]
Upon confirming with Gloo Edge product engineering this appears to be a bug. You should in fact be able to do Claims Based Routing with Headers at the route level.

**Comment by sam-heilbron** [comment]
I noticed that this bug appeared when you use claim based routing (like in the demo), without a default (wildcard) route. The demo config:

```
    - matchers:
      - prefix: /
        headers:
        - name: x-company
          value: solo.io
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: canary
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: primary
```

allows you to route requests with a jwt claim of x-company=solo.io to the canary pod, and all others to the primary.

If you were to adjust the route matching rules to include the jwt claim of x-company=othercompany.com, you could get routes to the canary pod and all others to the primary:

```
    - matchers:
      - prefix: /
        headers:
        - name: x-company
          value: solo.io
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: canary
    - matchers:
      - prefix: /
        headers:
        - name: x-company
          value: othercompany.com
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: canary
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: primary
```

However, if you remove the final default matcher, and leave the 2 header matchers the same, none of the requests work:

```
    - matchers:
      - prefix: /
        headers:
        - name: x-company
          value: solo.io
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: canary
    - matchers:
      - prefix: /
        headers:
        - name: x-company
          value: othercompany.com
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: canary
```

Interestingly, this same behavior exists if you have a non-header matcher with a non-default route. For example, configuring a prefix route matcher for `/primary`, will still not route requests properly:

```
    - matchers:
      - prefix: /
        headers:
        - name: x-company
          value: solo.io
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: canary
    - matchers:
      - prefix: /
        headers:
        - name: x-company
          value: othercompany.com
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: canary
    - matchers:
      - prefix: /primary
      routeAction:
        single:
          upstream:
            name: echoapp
            namespace: gloo-system
          subset:
            values:
              stage: primary
```

When using claims based routing, if a default route is not included, none of the route matching works.
