### ISSUE TITLE
Unable to use both outlierDetection and healthCheck

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4217]
**Describe the bug**
Gloo fails to update Upstream if it contains both a `outlierDetection` and a `healthCheck`.

Logs:
```json
{
    "level": "warn",
    "ts": 1611847321.0355997,
    "logger": "gloo.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer",
    "caller": "syncer/envoy_translator_syncer.go:142",
    "msg": "proxy gloo-system.gateway-proxy was rejected due to invalid config: 2 errors occurred:
  * invalid resource default.logger1
  * WARN: 
  [1 error occurred:
  * The field OutlierDetection.HealthChecker cannot be nil

]
Attempting to update only EDS information",
    "version": "1.6.5"
}
```

Config:
```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  labels:
    discovered_by: kubernetesplugin
  name: default-httpbin-8000
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      app: httpbin
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    serviceNamespace: default
    servicePort: 8000

  healthChecks:
    - healthyThreshold: 1
      httpHealthCheck:
        path: /health
      interval: 1s
      noTrafficInterval: 1s
      timeout: 1s
      unhealthyThreshold: 1

  outlierDetection:
    consecutive5xx: 3
```

If I pick only one of those two filters, that works.

**Expected behavior**
Be able to use both filters.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: could reproduce with v1.5.16 and v1.6.5
- Kubernetes version: kind 1.19
