### ISSUE TITLE
Expose Access Log Filters

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4218]
Similarly to Envoy, make possible the use of access log filters.

Ex.
```yaml
    access_log:
    - name: envoy.access_loggers.file
      filter:
        status_code_filter:
          comparison:
            op: GE
            value:
              default_value: 400
              runtime_key: key_b
```
