### ISSUE TITLE
Upstream failover hosts do not respect hostname

### ISSUE THREAD

**Issue by EItanya** [solo-io/gloo#4227]
**Describe the bug**
Currently when specifying an upstream failover config, the failover endpoints do not respect the hostname of the supplied config. This can lead to difficulties when relying on the authority/host header to make upstream routing decisions.

**To Reproduce**

Create the following Upstream:
```
spec:
  failover:
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: httpbin.org
          port: 443
          upstreamSslConfig: {}
        locality:
          region: px
          zone: alpha
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /status/200
    interval: 10s
    timeout: 5s
    unhealthyThreshold: 1
  loadBalancerConfig:
    healthyPanicThreshold: 0
  static:
    hosts:
    - addr: httpbin.org
      healthCheckConfig:
        path: /status/400
      port: 443
    useTls: true
 ```

Add a route to this upstream. When curling the route at `/headers`, the authority will not equal `httpbin.org`

**Expected behavior**
 The authority will equal `httpbin.org`
