### ISSUE TITLE
Install gloo by docker-compose-consul way problem

### ISSUE THREAD

**Issue by JING21** [solo-io/gloo#4248]
I meet a problem that I follow the official guide https://docs.solo.io/gloo-edge/1.5.15/installation/gateway/development/docker-compose-consul/ to install gloo. When I followed the guidance to install the gloo and envoy. I use 'curl http://localhost:8080/all-pets' but it reported 
curl: (56) Recv failure: Connection reset by peer. 
Then I use command 'docker exec -ti docker-compose-consul_gateway-proxy_1 sh',it turned out there are not existing 8080 8443 80 443 port .It only set up 19000 port.
![image](https://user-images.githubusercontent.com/31011622/106867198-46ca6280-6708-11eb-9639-f284d5513521.png)

The gloo version is 1.5.12, consul is 1.9.0 and vault is 1.6.0. Any one get any suggestion? thank u.

The envoy config is shown as following
```
node:
  cluster: gateway
  id: docker-compose-node
  metadata:
    # this line must match !
    role: "gloo-system~gateway-proxy"
static_resources:
  clusters:
  - name: xds_cluster
    connect_timeout: 5.000s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: gloo
                port_value: 9977
    http2_protocol_options: {}
    type: STRICT_DNS
dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services:
    - envoy_grpc: {cluster_name: xds_cluster}
  cds_config:
    ads: {}
  lds_config:
    ads: {}
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 19000
```

The gw file is shown below
```
metadata:
  name: gateway-proxy
  namespace: gloo-system
bindAddress: '::'
bindPort: 8080
httpGateway: {}
proxyNames:
  - gateway-proxy
ssl: false
useProxyProto: false
```

![image](https://user-images.githubusercontent.com/31011622/106872586-6cf30100-670e-11eb-89ad-094e95ad8057.png)
