### ISSUE TITLE
redirection after oidc logout does not work

### ISSUE THREAD

**Issue by zamrokk** [solo-io/gloo#4271]
I have this configuration for my virtual service under oidc protection :

```
...
- matchers:
      - exact: /auth/callback
      routeAction:
        single:
          upstream:
            name: <redirection to / here>
    - matchers:
      - exact: /auth/logout
      routeAction:
        single:
          upstream:
            name: <redirection to / here>
```
When I login, I have correct redirection to /
When I logout, the session is correctly invalidated but I don't have a redirection to /   . The browser stays on <HOST>/auth/logout

**Expected behavior**
When I logout, the session is correctly invalidated but I should have a redirection to /   ... then redirection to the oidc provider login page as there is no active session under /

**Additional context**
- Gloo Edge version : 1.6.4
