### ISSUE TITLE
glooe/gloo-ee helm chart doesn't respect `gatewayProxies.kind.deployment.replicas`  value

### ISSUE THREAD

**Issue by dongsu** [solo-io/gloo#4296]
**Describe the bug**
I am installing Gloo edge enterprise version using the helm chart with the following `values.yaml`:
```yaml
global:
  glooRbac:
    create: true
  extensions:
    extAuth:
      envoySidecar: true
      standaloneDeployment: true
gatewayProxies:
  gatewayProxy:
    kind:
      deployment:
        replicas: 2
```
When I run `helm template` it doesn't generate `replicas: 2`. Instead, it always generates `replicas: 1`. 
This works as expected in open source version.

**Expected**:
```yaml
# Source: gloo-ee/charts/gloo/templates/7-gateway-proxy-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: gateway-proxy
  name: gateway-proxy
  namespace: gloo-system
spec:
  replicas: 2
  selector:
    matchLabels:
      gloo: gateway-proxy
      gateway-proxy-id: gateway-proxy
...
```

**Actual**:
```yaml
# Source: gloo-ee/charts/gloo/templates/7-gateway-proxy-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: gateway-proxy
  name: gateway-proxy
  namespace: gloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: gateway-proxy
      gateway-proxy-id: gateway-proxy
...
```

**To Reproduce**
1. create `values.yaml`

    ```bash
    cat <<-EOF > values.yaml
    global:
      extensions:
        extAuth:
          envoySidecar: true
          standaloneDeployment: true
    gatewayProxies:
      gatewayProxy:
        kind:
          deployment:
            replicas: 2
    EOF
    cat <<-EOF > secrets.yaml
    license_key: {your_license_key_here}
    EOF
    ```

2. generate a template 

    ```
    helm template gloo glooe/gloo-ee --namespace gloo-system -f values.yaml -f secrets.yaml --version 1.6.12 > all-1.6.12.yam
    ```

3. you can see the generated output got `replicas: 1`, not `replicas: 2`

**Comment by dongsu** [comment]
It was user error.  The values need `gloo` prefix when using enterprise chart.

the correct values.yaml:
```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          replicas: 2
```
