### ISSUE TITLE
Add support for multiple shadowing destinations

### ISSUE THREAD

**Issue by supasteev0** [solo-io/gloo#4298]
**Is your feature request related to a problem? Please describe.**

In Envoy, it is possible to mirror traffic to multiple destinations in the same route, by adding multiple request_mirror_policies.
For example:
```
  request_mirror_policies:
  - cluster: cluster1
    runtime_fraction:
      default_value:
        numerator: 100
  - cluster: cluster2
    runtime_fraction:
      default_value:
        numerator: 100
```

**Describe the solution you'd like**
It would be very helpful to be able to configure multiple shadowing upstreams in a virtualservice.
For example:
```
        options:
          timeout: 0s
          shadowing:
            - upstream:
                name: cluster1
                namespace: default
              percentage: 100
            - upstream:
                name: cluster2
                namespace: default
              percentage: 100
```
The shadowing would of course be available to any kind of upstream (kube, static, etc ...)
