### ISSUE TITLE
Helm chart issue for gloo-ee 1.6.10 for invalidConfigPolicy.  Setting does not work as documented

### ISSUE THREAD

**Issue by tmojlupo** [solo-io/gloo#4321]
**Describe the bug**
According to Gloo documentation [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/#invalidconfigpolicy) and [here](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/invalid_route_replacement/), the "replaceInvalidRoutes" needs to be part of the invalidConfigPolicy.  The second link says you should be able to enable it in helm with the setting `--set settings.invalidConfigPolicy.replaceInvalidRoutes=true`, but this doesn't work.

**To Reproduce**
1. helm template gloo-ee glooe/gloo-ee --set settings.invalidConfigPolicy.replaceInvalidRoutes=true --version 1.6.10
2. Look through the output for the section that contains "kind: Settings" for the default settings resource and it will not have a section for invalidConfigPolicy
```
    apiVersion: [gloo.solo.io/v1](http://gloo.solo.io/v1)
    kind: Settings
    metadata:
      labels:
        app: gloo
        gloo: settings
      name: default
      namespace: kube-system
    spec:
      gloo:
        xdsBindAddr: "0.0.0.0:9977"
        restXdsBindAddr: "0.0.0.0:9976"
        enableRestEds: false
        invalidConfigPolicy:
          null
        disableKubernetesDestinations: false
        disableProxyGarbageCollection: false
      discoveryNamespace: kube-system
      kubernetesArtifactSource: {}
      kubernetesConfigSource: {}
      kubernetesSecretSource: {}
      refreshRate: 60s
      gateway:
        validation:
          proxyValidationServerAddr: "gloo:9988"
          alwaysAccept: true
      discovery:
        fdsMode: WHITELIST
      extauth:
        extauthzServerRef:
          # arbitrarily default to the standalone deployment name even if we're using both
          name: extauth
          namespace: kube-system
        userIdHeader: "x-user-id"
      ratelimitServer:
        ratelimit_server_ref:
          name: rate-limit
          namespace: kube-system
```
3. If you use `settings.replaceInvalidRoutes=true` instead, it does enable the invalidConfigPolicy.
`helm template gloo-ee glooe/gloo-ee --set settings.replaceInvalidRoutes=true --version 1.6.10`
```
    # Source: gloo-ee/templates/40-settings.yaml
    apiVersion: gloo.solo.io/v1
    kind: Settings
    metadata:
      labels:
        app: gloo
        gloo: settings
      name: default
      namespace: kube-system
    spec:
      gloo:
        xdsBindAddr: "0.0.0.0:9977"
        restXdsBindAddr: "0.0.0.0:9976"
        enableRestEds: false
        invalidConfigPolicy:
          null
        disableKubernetesDestinations: false
        disableProxyGarbageCollection: false
      discoveryNamespace: kube-system
      kubernetesArtifactSource: {}
      kubernetesConfigSource: {}
      kubernetesSecretSource: {}
      refreshRate: 60s
      gateway:
        validation:
          proxyValidationServerAddr: "gloo:9988"
          alwaysAccept: true
      discovery:
        fdsMode: WHITELIST
      extauth:
        extauthzServerRef:
          # arbitrarily default to the standalone deployment name even if we're using both
          name: extauth
          namespace: kube-system
        userIdHeader: "x-user-id"
      ratelimitServer:
        ratelimit_server_ref:
          name: rate-limit
          namespace: kube-system
```
**Expected behavior**
I would expect that adding that parameter would enable the invalidConfigPolicy.

**Additional context**

The problem is in the helm template files for both gloo-ee 1.6.10 (40-settings.yaml) and its subchart gloo 1.6.7 (18-settings.yaml). 
```
    {{- if .Values.settings.replaceInvalidRoutes }}
        invalidConfigPolicy:
    {{ toYaml .Values.settings.invalidConfigPolicy | indent 6}}
```
This should be changed to:
```
    {{- if .Values.settings.invalidConfigPolicy.replaceInvalidRoutes }}
        invalidConfigPolicy:
    {{ toYaml .Values.settings.invalidConfigPolicy | indent 6}}
```
Applies to gloo-ee 1.6.10 and also gloo 1.6.7
