### ISSUE TITLE
static upstream cause "﻿no healthy upstream" error in Kubernetes cluster with IPv6 only networking

### ISSUE THREAD

**Issue by fubinl** [solo-io/gloo#4383]
**Describe the bug**
Deploy the Gloo Edge (1.5.0) into a Kubernetes cluster that only configured with IPv6 networking and then define a "VirtualService" and an "Upstream" with a "static" type configuration.

When sending request to the gateway-proxy NodePort endpoint, the response always "http 503" response code and "﻿no healthy upstream" body.

**To Reproduce**
upstream definition:
```
apiVersion: gloo.solo.io/v1
kind: Upstreamspec:
﻿metadata:
  ﻿name: test-service-us
  namespace: test
﻿spec:
  static:
    hosts:
    - addr: my-test-service
      port: 8080
```
VirtualService definition: 
```
﻿apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  ﻿name: test-service-vs
  namespace: test
﻿spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /abc
      routeAction:
        single:
          upstream:
            name: test-service-us
            namespace: test
```
CURL command and response
```
﻿curl -v http://[fc00:f853::6]:31938/abc/id

﻿< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Thu, 04 Mar 2021 14:56:57 GMT
< server: envoy
< 
* Connection #0 to host fc00:f853::6 left intact
no healthy upstream
```
The generated cluster definition and it has default to **"dns_lookup_family": "V4_ONLY"**,
```
﻿{
 "version_info": "9509590394170194452",
 "cluster": {
  "@type": "type.googleapis.com/envoy.api.v2.Cluster",
  "name": "test-service-us_test",
  "type": "STRICT_DNS",
  "connect_timeout": "5s",
  "dns_lookup_family": "V4_ONLY",
  "metadata": {},
  "load_assignment": {
   "cluster_name": "test-service-us_test",
   "endpoints": [
    {
     "lb_endpoints": [
      {
       "endpoint": {
        "address": {
         "socket_address": {
          "address": "my-test-service.test",
          "port_value": 8080
         }
        },
        "health_check_config": {
         "hostname": "my-test-service.test"
        },
        "hostname": "my-test-service.test"
       }
      }
     ]
    }
   ]
  }
 },
 "last_updated": "2021-03-04T14:24:52.327Z"
}
```
This line may be the cause of the issue:
https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/static/plugin.go#L169

**Expected behavior**
the curl command return successful with http 200 return code and expected payload

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.5.0
- Kubernetes version: ﻿v1.18.x
