### ISSUE TITLE
Redirect traffic to additional endpoint after logout

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4391]
**Is your feature request related to a problem? Please describe.**
Not related to a problem but a question for additional functionality from a customer.

**Describe the solution you'd like**
In the `AuthConfig` you have a `logoutPath`. A customer would like to be able to add an additional parameter to redirect the client after hitting the `callback_path` or `logoutPath`.  The request would be directed to this new path after logging out.
```
afterLogout:
  path: /
  
afterLogin:
  path: /home
```

The functionality would be:
- You hit the logoutPath endpoint, your requestion is invalidated, and removed from the cache, then you are redirected to the final destination

```
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        app_url: http://localhost:8080/
        callback_path: /callback
        client_id: gloo
        client_secret_ref:
          name: oauth
          namespace: gloo-system
        issuer_url: http://dex.gloo-system.svc.cluster.local:32000/
        scopes:
        - email
        session:
          cookieOptions:
            notSecure: true
            maxAge: 360
          failOnFetchFailure: true
          redis:
            cookieName: cookie
            options:
              host: redis.gloo-system.svc.cluster.local:6379
        logoutPath: /auth/logout
```

**Describe alternatives you've considered**
Using a custom micro service to redirect the user

**Additional context**
