### ISSUE TITLE
Audit log display incorrect results for `http_code`

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4422]
**Describe the bug**
Audit log displays incorrect results for `http_code`.

**To Reproduce**
1. Create a WAF
2. Create a WAF rule 
3. Send a request that will be rejected: (ex: `curl -H "User-Agent: scammer" $(gc proxy url)/get`)
4. Watch the access log
![image](https://user-images.githubusercontent.com/1096507/110980119-8140a400-8333-11eb-94ad-7156aa59f325.png)

**Expected behavior**
There should be consistency between the responseCode in the access log and the http_code in the audit log.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version `1.6.17` && `1.6.19`
- Gateway Proxy Manifest snippet
```
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      healthCheck:
        path: /check/healthz
      httpConnectionManagerSettings:
        useRemoteAddress: true
      waf:
        auditLogging:
          action: ALWAYS
          location: FILTER_STATE
        customInterventionMessage: ModSecurity intervention! Custom message details
          here..
        ruleSets:
        - ruleStr: |
            # Turn rule engine on
            SecRuleEngine On
            SecAuditLogFormat JSON
            SecRule REQUEST_HEADERS:User-Agent "scammer" "deny,status:403,id:107,phase:1,msg:'blocked scammer'"
```
