### ISSUE TITLE
[validation] param allowWarnings is not rendered in the EE version of the Helm chart

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4465]
```shell
cat << EOF > values.yaml
gloo:
  gateway:
    validation:
      allowWarnings: false
EOF
```

helm install -f values.yaml ...

This value was not rendered in the final settings object:
```yaml
...
spec:
  discovery:
    fdsMode: WHITELIST
  discoveryNamespace: gloo-system
  extauth:
    extauthzServerRef:
      name: extauth
      namespace: gloo-system
    userIdHeader: x-user-id
  gateway:
    validation:
      alwaysAccept: true
      proxyValidationServerAddr: gloo:9988
```

This parameter is read in the OS version of the Helm chart, but not in the EE version; see 40-settings.yaml
