### ISSUE TITLE
Missing yaml separator in the chart when deploying a failover Gateway

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4485]
**Describe the bug**
The `charts/gloo/templates/8-default-gateways.yaml` file is used to generate the gateway objects, but as you can see below, there's no separator between the ssl and the failover gateways in the yaml generated:

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy-ssl
  namespace: gloo-system
  labels:
    app: gloo
spec:
  bindAddress: "0.0.0.0"
  bindPort: 8443
  httpGateway: {}
  useProxyProto: false
  ssl: true
  proxyNames:
  - gateway-proxy
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy-failover
  namespace: gloo-system
  labels:
    app: gloo
spec:
  bindAddress: "0.0.0.0"
  bindPort: 15443
  tcpGateway:
    tcpHosts:
    - name: failover
      sslConfig:
        secretRef:
          name: failover-downstream
          namespace: gloo-system
      destination:
        forwardSniClusterName: {}
  proxyNames:
  - gateway-proxy
```

The `charts/gloo/templates/8-default-gateways.yaml` file should be modified as follow:

```
...
  proxyNames:
  - {{ $name | kebabcase }}
{{- end }}
---
{{- if $spec.failover }}
{{- if $spec.failover.enabled }}
apiVersion: gateway.solo.io/v1
kind: Gateway
...
```
