### ISSUE TITLE
Potential bug when using SNI 

### ISSUE THREAD

**Issue by marcogschmidt** [solo-io/gloo#4488]
**Describe the bug**
During a recent call with a customer we were not able to get a simple HTTPS `VirtualService` with SNI working. As soon as the `sniDomains` config was removed from the `Virtual Service`, we were able to reach the upstream.

We should try to reproduce the issue to verify whether it is a bug in Gloo Edge and add an e2e tests for HTTPS+SNI if we don't have one already.

**To Reproduce**
I have not tried to reproduce the issue, so I am going to share my notes on the customer environment. @jameshbarton and @yuval-k please feel free to correct/add context as needed (since you were on the call as well).

- default `gateway-proxy` exposed as a `LoadBalancer` service in AWS using an NLB
- the service defines a `nodePort` for the HTTPS listener which is used for health checks; health checks were passing.
- proxy protocol enabled
- cluster contains a wildcard TLS secret that is referenced by the VS
- VS defines a single `sniDomains` entry; no other TLS virtual services exist
- `glooctl check` returns no relevant errors/warnings

When `curl`ing the proxy while following the proxy logs at the debug level, we could determine that a connection can be established, but the Envoy logs indicate that no filter chain match could be found.

After removing the `sniDomains` curl would return the expected response from the upstream.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: Enterprise `1.7.0-beta13`
- Kubernetes version: N/A

**Comment by rustrial** [comment]
Same here with 1.7.1

**Comment by alex-berger** [comment]
Maybe this is related to https://github.com/solo-io/gloo/pull/4478 and maybe setting `oneWayTls` to `true` might solve this issue. (Just thinking loud, had not yet any chance to test this).

**Comment by kdorosh** [comment]
Was unable to reproduce locally in kind following the steps documented [here](https://docs.solo.io/gloo-edge/latest/guides/security/tls/server_tls/#serving-certificates-for-multiple-virtual-hosts-with-sni), with the following modifications for kind:
- update the domains for the vs to use '*'
- used the following `curl`: `curl -vk --resolve animalstore.example.com:8443:127.0.0.1 https://animalstore.example.com:8443/animals`

**Comment by kdorosh** [comment]
@rustrial do you have reproduce steps you can share with us? We'd like to look at this and close it out. Please feel free to drop into our public slack and DM me directly as well

**Comment by marcogschmidt** [comment]
@kdorosh I am pretty sure when we ran into this the `VirtualService` did use the same domain used in `sniDomains`, so in this case:
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: animal
  namespace: gloo-system
spec:
  displayName: animal
  sslConfig:
    secretRef:
      name: animal-certs
      namespace: gloo-system
    sniDomains:
    - animalstore.example.com
  virtualHost:
    domains:
    - animalstore.example.com
    # [...]
```

Forgot to add this detail to the initial list of reproduction steps, sorry.

**Comment by kdorosh** [comment]
Specifying the domains explicitly works on both 1.6 and 1.7 versions of Gloo: 
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: animal
  namespace: gloo-system
spec:
  displayName: animal
  sslConfig:
    secretRef:
      name: animal-certs
      namespace: gloo-system
    sniDomains:
    - animalstore.example.com
  virtualHost:
    domains:
    - animalstore.example.com:8443
    routes:
    - matchers:
      - exact: /animals
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```
