### ISSUE TITLE
FDS doesn't work with custom cluster domain

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4490]
**Describe the bug**
Given a kubernetes cluster, set up with a custom cluster domain in coreDNS,
When I want to use FDS,
Then functions are not discovered

**To Reproduce**
Setup kind with a config like this:
```yaml 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
...
networking:
...
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: "10.96.0.1/12"
    podSubnet: "192.168.128.0/17"
    dnsDomain: "cluster.bco"
```

Then, install Gloo Edge v1.6.21 with these Helm values:
```yaml
gloo:
  discovery:
    fdsMode: BLACKLIST
  k8s:
    clusterName: cluster.bco
```

Then, I installed petstore and REST endpoints where no detected.
Same for gRPC endpoints, part of the gloo-system components.

**Expected behavior**
FDS to work

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.6.21
- Kubernetes version 1.20
