### ISSUE TITLE
custom gateway proxies don't override values from the defaul gateway proxy

### ISSUE THREAD

**Issue by jon-walton** [solo-io/gloo#4528]
**Describe the bug**
When defining a custom gatewayProxy, the default values are not correctly overridden.

**To Reproduce**

The following helm values will not render any `Gateway` resource

```yaml
 gatewayProxies:
    gatewayProxy:
      disabled: true

    gatewayProxyPublic:
      disabled: false
```

**Expected behavior**

a `Gateway` resource named `gateway-proxy-public` should be created

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.7.0-rc2
- Kubernetes version
