### ISSUE TITLE
Helm: malformed yaml is rendered when attempting to create multiple gateway proxies

### ISSUE THREAD

**Issue by jon-walton** [solo-io/gloo#4529]
**Describe the bug**
When defining multiple `gatewayProxy` in a helm values file, malformed yaml is rendered

**To Reproduce**
Define multiple gateway proxies

```yaml
 gatewayProxies:
    gatewayProxy:
      disabled: false

    gatewayProxyPublic:
      disabled: false
```

Helm renders the following yaml

```yaml
---apiVersion: gateway.solo.io/v1
kind: Gateway
```

**Expected behavior**

`apiVersion` should be on a new line

```yaml
---
apiVersion: gateway.solo.io/v1
kind: Gateway
```

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.7.0-rc2
- Kubernetes version
