### ISSUE TITLE
Upstreams fail to reconcile / create

### ISSUE THREAD

**Issue by stephenrob** [solo-io/gloo#4575]
**Describe the bug**
Upstreams are failing to be added to gloo with errors being seen in the discovery logs indicating issues failing to reconcile the upstream which appears in the output of `glooctl get upstreams` for a short time in a pending state and then disappears before it is moved to an accepted state.

**To Reproduce**

Service is created as follows by the elastic operator:

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-04-09T16:32:21Z"
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: observability
  name: observability-es-http
  namespace: observability
  ownerReferences:
  - apiVersion: elasticsearch.k8s.elastic.co/v1
    blockOwnerDeletion: true
    controller: true
    kind: Elasticsearch
    name: observability
    uid: 8a5af7ae-a73d-46e5-b7ae-609d4b915ddc
  resourceVersion: "3439752"
  uid: db5fc60b-9b2d-4707-a880-8b5785dbf526
spec:
  clusterIP: 172.21.47.158
  clusterIPs:
  - 172.21.47.158
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: observability
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Auto discovery of kubernetes services should then resolve the upstream as `observability-observability-es-http-9200` but this doesn't happen.

Discovery Logs

```
{"level":"warn","ts":"2021-04-09T17:19:30.212Z","logger":"uds.v1.event_loop.uds.upstream_reconciler.reconciler","caller":"reconcile/reconciler.go:131","msg":"unable to read updated resource name:\"observability-observability-es-http-9200\"  namespace:\"gloo-system\" to get updated resource version; gloo-system.observability-observability-es-http-9200 does not exist: upstreams.gloo.solo.io \"observability-observability-es-http-9200\" not found","version":"1.7.0"}
{"level":"error","ts":"2021-04-09T17:19:30.212Z","logger":"uds.v1.event_loop.uds","caller":"discovery/discovery.go:145","msg":"failed reconciling upstreams","version":"1.7.0","discovered_by":"kubernetesplugin","upstreams":33,"error":"reconciling resource observability-observability-es-http-9200: gloo-system.observability-observability-es-http-9200 does not exist: upstreams.gloo.solo.io \"observability-observability-es-http-9200\" not found","errorVerbose":"gloo-system.observability-observability-es-http-9200 does not exist: upstreams.gloo.solo.io \"observability-observability-es-http-9200\" not found\nreconciling resource observability-observability-es-http-9200\ngithub.com/solo-io/solo-kit/pkg/errors.Wrapf\n\t/go/pkg/mod/github.com/solo-io/solo-kit@v0.18.2/pkg/errors/errors.go:15\ngithub.com/solo-io/solo-kit/pkg/api/v1/reconcile.(*reconciler).Reconcile\n\t/go/pkg/mod/github.com/solo-io/solo-kit@v0.18.2/pkg/api/v1/reconcile/reconciler.go:43\ngithub.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*upstreamReconciler).Reconcile\n\t/workspace/gloo/projects/gloo/pkg/api/v1/upstream_reconciler.sk.go:46\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).Resync\n\t/workspace/gloo/projects/gloo/pkg/discovery/discovery.go:141\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).StartUds.func1\n\t/workspace/gloo/projects/gloo/pkg/discovery/discovery.go:112\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).Resync\n\t/workspace/gloo/projects/gloo/pkg/discovery/discovery.go:145\ngithub.com/solo-io/gloo/projects/gloo/pkg/discovery.(*UpstreamDiscovery).StartUds.func1\n\t/workspace/gloo/projects/gloo/pkg/discovery/discovery.go:112"}
{"level":"error","ts":"2021-04-09T17:19:30.213Z","logger":"uds.v1.event_loop.uds","caller":"syncer/setup_syncer.go:99","msg":"error: event_loop.uds: error in uds plugin : reconciling resource observability-observability-es-http-9200: gloo-system.observability-observability-es-http-9200 does not exist: upstreams.gloo.solo.io \"observability-observability-es-http-9200\" not found","version":"1.7.0","stacktrace":"github.com/solo-io/gloo/projects/discovery/pkg/uds/syncer.RunUDS.func2\n\t/workspace/gloo/projects/discovery/pkg/uds/syncer/setup_syncer.go:99"}
```

**Expected behavior**
Upstream should move from processing to accepted state and not keep appearing or disappearing

**Additional context**
- Gloo Edge version: 1.7.0
- Kubernetes version: 1.20.4

Installed from helm chart via argocd with the following chart values. Initially suspected it was because we run 3 replicas of everything but dropping down to 1 did not resolve this.

```yaml
global:
  glooRbac:
    create: true
  glooStats:
    enabled: false
  glooMtls:
    enabled: false
  istioSDS:
    enabled: false
crds:
  create: true
settings:
  integrations:
    knative:
      enabled: false
  create: true
  singleNamespace: false
  linkerd: false
gloo:
  deployment:
    stats:
      enabled: false
    replicas: 1
discovery:
  deployment:
    replicas: 1
  enabled: true
gateway:
  enabled: true
  deployment:
    stats:
      enabled: false
    replicas: 1
gatewayProxies:
  gatewayProxy:
    kind:
      deployment:
        replicas: 1
    service:
      type: NodePort
      httpNodePort: 31380
      httpsNodePort: 31390
    stats:
      enabled: false
ingress:
  enabled: false
accessLogger:
  enabled: true
  stats:
    enabled: false
```
