### ISSUE TITLE
Disabling http/s gateway should disable corresponding port

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4578]
**Describe the bug**
Disabling http/s gateway should disable corresponding port

**To Reproduce**
1. glooctl install with the follow values
```
gloo:
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        disableHttpGateway: true
```
2. Loadbalancer port remains

**Expected behavior**
Disabling http/s gateway should disable corresponding port

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version v1.6/7.X
- Kubernetes version
