### ISSUE TITLE
Gloo Edge doesn't order routes correctly when methods are specified

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4589]
Let's say that I create a VS and 2 RT like that:

```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      delegateAction:
        selector:
          labels:
            businessUnit: nexmo
            serviceType: api-public
          namespaces:
          - '*'
EOF

kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: messaging
  namespace: gloo-system
  labels:
    businessUnit: nexmo
    serviceType: api-public
spec:
  routes:
  - matchers:
    - exact: /v1/applications/ping
      headers:
      - name: :authority
        value: 172.18.1.1
      methods:
      - GET
    routeAction:
      single:
        upstream:
          name: default-echo-service-1-80
          namespace: gloo-system
  - directResponseAction:
      body: <html><head><title>403 Forbidden</title></head><body><centre><h1>403
        Forbidden</h1></centre><hr><centre>envoy</centre></body></html>
      status: 403
    matchers:
    - exact: /v1/applications/ping
      headers:
      - name: :authority
        value: 172.18.1.1
      - invertMatch: true
        name: :method
        regex: false
        value: GET
  - matchers:
    - headers:
      - name: :authority
        value: 172.18.1.1
      methods:
      - GET
      - POST
      - DELETE
      - PUT
      prefix: /v1/applications
    routeAction:
      single:
        upstream:
          name: default-echo-service-3-80
          namespace: gloo-system
EOF

kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: messaging2
  namespace: gloo-system
  labels:
    businessUnit: nexmo
    serviceType: api-public
spec:
  routes:
  - matchers:
    - exact: /test
      headers:
      - name: :authority
        value: 172.18.1.1
      methods:
      - GET
    routeAction:
      single:
        upstream:
          name: default-echo-service-1-80
          namespace: gloo-system
EOF
```

Then, a POST request to `/v1/applications/ping` should returns a 403, but is instead by the route with the `prefix: /v1/applications` matcher.
And when I take a look at the Envoy configuration generated by Gloo Edge, I can see that this matcher is coming first (while it shouldn't).

If I replace the first RT by the following it works:

```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: messaging
  namespace: gloo-system
  labels:
    businessUnit: nexmo
    serviceType: api-public
spec:
  routes:
  - matchers:
    - exact: /v1/applications/ping
      headers:
      - name: :authority
        value: 172.18.1.1
      methods:
      - GET
    routeAction:
      single:
        upstream:
          name: default-echo-service-1-80
          namespace: gloo-system
  - directResponseAction:
      body: <html><head><title>403 Forbidden</title></head><body><centre><h1>403
        Forbidden</h1></centre><hr><centre>envoy</centre></body></html>
      status: 403
    matchers:
    - exact: /v1/applications/ping
      headers:
      - name: :authority
        value: 172.18.1.1
      - invertMatch: true
        name: :method
        regex: false
        value: GET
  - matchers:
    - headers:
      - name: :authority
        value: 172.18.1.1
      - name: :method
        regex: true
        value: GET|POST|DELETE|PUT
      prefix: /v1/applications
    routeAction:
      single:
        upstream:
          name: default-echo-service-3-80
          namespace: gloo-system
EOF
```

So, it looks like the order isn't right when methods are indicated in a matcher.
