### ISSUE TITLE
updating the TLS secret caused a "Pending state"

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4609]
**Describe the bug**
A client wanted to update the TLS server certificate for a set of subdomains, part of a single VS. 
The VS is properly configured with SNI, and a wildcard cert (with the pattern `*.mydomain.com`)
When the secret was updated, an error was reported by `glooctl get vs`
```
Accepted
*v1.Proxy.gloo-system.gateway-proxy
is in a Pending state. Updates to
this resource may be blocked by
problems with another resource
```

The workaround was to modify the order of the domains listed under `sniDomains` and `domains`. This way, the control plane was unblocked.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: Gloo EE 1.3.32
- Kubernetes version?

**Comment by djannot** [comment]
Here is the yaml they were using:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  displayName: default (https)
  sslConfig:
    secretRef:
      name: ssl
      namespace: gloo-system
    sniDomains:
    - virta-gke.test.com
    - ti-virta-gke.test.com
    - virta.test.com
    - ti-virta.test.com
  virtualHost:
    domains:
    - virta-gke.test.com
    - ti-virta-gke.test.com
    - virta.test.com
    - ti-virta.test.com
    routes:
    - matchers:
      - prefix: /
      options:
        timeout: 600s
      routeAction:
        single:
          upstream:
            name: test
            namespace: gloo-system
```

**Comment by cmwylie19** [comment]
I am seeing this on a customer as well where `glooctl check` is returning no errors, also the prometheus metric is indicating that everything is working normally (`envoy_control_plane_connected_state`) but are still seeing this output when issuing `glooctl get vs` :

```
Accepted
*v1.Proxy.gloo-system.gateway-proxy
is in a Pending state. Updates to
this resource may be blocked by
problems with another resource
```

VirtualService:
```
displayName: customer-vs
metadata:
  name: customer-vs
  namespace: gloo-ee
sslConfig:
  parameters:
    minimumProtocolVersion: TLSv1_2
  secretRef:
    name: some-internal-certificate
    namespace: gloo-ee
  sniDomains:
  - sub.internal.domain.com
status:
  reportedBy: gateway
  state: Accepted
  subresourceStatuses:
    '*v1.Proxy.gloo-ee.gateway-proxy': {}
virtualHost:
  domains:
  - sub.internal.domain.com
  options:
    headerManipulation:
      responseHeadersToAdd:
      - header:
          key: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains
    retries:
      numRetries: 3
      retryOn: gateway-error
  routes:
  - matchers:
    - prefix: /
    routeAction:
      single:
        upstream:
          name: k8s-ec2-upstream
          namespace: gloo-ee
 ```
