### ISSUE TITLE
Knative TLS annotations not working

### ISSUE THREAD

**Issue by techBeck03** [solo-io/gloo#4614]
**Describe the bug**
Similar to [#3167](https://github.com/solo-io/gloo/issues/3167) I'm struggling to get TLS annotations to work with my Knative services.  This syntax has worked for me in the past for earlier versions of Knative/Gloo.  My services work without the TLS annotations but become inaccessible once added.

**To Reproduce**
Apply tls annotations to knative service

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auslab-api
  namespace: faas
  annotations:
    gloo.networking.knative.dev/ssl.sni_domains: auslab-api.faas.infkn.auslab.example.com
    gloo.networking.knative.dev/ssl.secret_name: auslab-api-tls
```

```bash
❯ curl -v -k \
   --resolve "auslab-api.faas.infkn.auslab.example.com:443:172.16.91.104" \
   https://auslab-api.faas.infkn.auslab.example.com:443
* Added auslab-api.faas.infkn.auslab.example.com:443:172.16.91.104 to DNS cache
* Hostname auslab-api.faas.infkn.auslab.example.com was found in DNS cache
*   Trying 172.16.91.104...
* TCP_NODELAY set
* Connected to auslab-api.faas.infkn.auslab.example.com (172.16.91.104) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS alert, handshake failure (552):
* error:1401E410:SSL routines:CONNECT_CR_FINISHED:sslv3 alert handshake failure
* Closing connection 0
curl: (35) error:1401E410:SSL routines:CONNECT_CR_FINISHED:sslv3 alert handshake failure
```

I verified the certificate is valid and stored under the proper name.

```bash
❯ k get certificate       
NAME         READY   SECRET           AGE
auslab-api   True    auslab-api-tls   31m
```

**Expected behavior**
The https endpoint should be reachable and passed to the corresponding knative service

**Additional context**
Add any other context about the problem here, e.g.
- Glooctl version: `1.7.2`
- Kubernetes version: `1.19`
- Knative version: `0.22`
- Install method followed: [Knative Operator Install](https://knative.dev/docs/install/knative-with-operators/)
