### ISSUE TITLE
FDS does not fully populate swagger/openapi 3.0 and 3.1 spec functions

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4622]
**Describe the bug**
Parts of a discovered function are not written to the upstream when the swagger/openapi spec is 3.0 or 3.1

Sample spec:
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "My.Api",
    "description": "ASP.NET Core Web API for working with stuff",
    "contact": {
      "name": "foo",
    },
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://my-api-service:5000"
    }
  ],
  "paths": {
 "/api/v1/my-api/media-types": {
      "get": {
        "tags": [
          "MediaTypes"
        ],
        "summary": "Gets List of Media Types",
        "description": "This route requires ApiKey and Bearer authorization",
        "operationId": "GetMediaTypesAsync",
        "responses": {
          "200": {
            "description": "List of Media Types",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MediaTypeDto"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
"components": {
    "schemas": {
      "MediaTypeDto": {
        "type": "object",
        "properties": {
          "mediaTypeId": {
            "type": "integer",
            "format": "int32"
          },
          "nameEng": {
            "type": "string",
            "nullable": true
          },
          "nameFra": {
            "type": "string",
            "nullable": true
          },
          "active": {
            "type": "boolean"
          }
        },
        "additionalProperties": false
      },
  },
},
}
```

Generated function:
```yml
          GetMediaTypesAsync:
            body: {}
            headers:
              :method:
                text: GET
              :path:
                text: /api/v1/infomedia/media-types
              content-length:
                text: "0"
              content-type: {}
              transfer-encoding: {}
```

**To Reproduce**
1. create a sample app that has a swagger/openapi spec >= 3.0.0
2. enable FDS
3. See discovered functions

**Expected behavior**
More details about the function should be copied over for swagger/openapi spec>= 3.0.0

**Additional context**

Docs produce complete function in swagger 2.0: https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/discovered_upstream/

```yml
          addPet:
            body:
              text: '{"id": {{ default(id, "") }},"name": "{{ default(name, "")}}","tag":
                "{{ default(tag, "")}}"}'
            headers:
              :method:
                text: POST
              :path:
                text: /api/pets
              content-type:
                text: application/json
```

- Gloo Edge version v1.7.2
- Kubernetes version
