### ISSUE TITLE
Fix Tracing Doc

### ISSUE THREAD

**Issue by murphye** [solo-io/gloo#4656]
Per https://github.com/solo-io/gloo/blob/9b065bb1582238a8786c0d7e2c68eab25d0df507/docs/content/guides/observability/tracing.md

## Problem 1

```
      tracing:
        provider:
          zipkinConfig:
            collector_cluster: zipkin
            collector_endpoint: /api/v2/spans
```
should be
```
      tracing:
        provider:
          zipkinConfig:
            cluster_name: zipkin
            collector_endpoint: /api/v2/spans
```

## Problem 2

```
 lb_policy: round_robin
```
should be
```
 lb_policy: ROUND_ROBIN
```

## Problem 3

Also need to document for Gloo EE, as `gatewayProxies` will be under `gloo` such as:

```
gloo:
  gatewayProxies:
    gatewayProxy:
      tracing:
        provider:
          zipkinConfig:
            cluster_name: zipkin
            collector_endpoint: /api/v2/spans
        cluster:
          - name: zipkin
            connect_timeout: 1s
            type: STRICT_DNS
            respect_dns_ttl: true
            lb_policy: ROUND_ROBIN
            load_assignment:
              cluster_name: zipkin
              endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: zipkin.istio-system
                          port_value: 9411
```
