### ISSUE TITLE
Improved Tracing between Gloo Edge and Istio

### ISSUE THREAD

**Issue by murphye** [solo-io/gloo#4666]
Long story short, there is an issue with spans between the Gateway Proxy and the first Istio sidecar when it comes to tracing. In this situation, Gloo Edge and Istio are using the same Zipkin service.

The main problem is that the root span and the 1st span get merged together, as they have the same traceId and parentId. So, from a Zipkin dashboard view, it's very confusing what you're seeing. Ideally there would be a parent span that only represents tags from Gloo Proxy.

View of merged span on Zipkin:
<img width="1615" alt="Screen Shot 2021-04-26 at 11 58 06 AM" src="https://user-images.githubusercontent.com/643097/116146775-b9a60280-a693-11eb-992c-6e3709cc2981.png">

View of span with same parentId and traceId
![Screen Shot 2021-04-26 at 1 06 25 PM](https://user-images.githubusercontent.com/643097/116146675-9b400700-a693-11eb-88b8-a405defa63cf.png)

**Comment by murphye** [comment]
I am not exactly sure what the fix is for this. It may be worth looking at how tracing is handled with Istio Ingress.

**Comment by snuggie12** [comment]
Came across this while looking for a different tracing request. I think mine are separate and I added two options that weren't in the tutorial (after looking at istio's envoy config):

```
spec:  
  httpGateway:
    options:
      httpConnectionManagerSettings:
        tracing:
          requestHeadersForTags:
          - path
          - origin
          verbose: true
          zipkinConfig:
            collectorEndpoint: /api/v2/spans
            collectorEndpointVersion: HTTP_JSON
            collectorUpstreamRef:
              name: REDACTED
              namespace: REDACTED
            # this is the one I think solves your problem possibly?
            sharedSpanContext: false
            # In gloo 1.8 this is a lowercase "b" for "bit". In 1.10 it appears to be "Bit" in the docs
            # check your version's API reference for whenever this got switched over.
            traceId128bit: true
```
