### ISSUE TITLE
gRPC service behind Virtual Service fails when you have WAF logic in Gateway Proxy 

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4671]
**Describe the bug**
When you have WAF logic in the Gateway Proxy, gRPC calls to a VirtualService fronting a gRPC services fail.

**This should fail**
`gateway-proxy-waf.yaml`
```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      healthCheck:
        path: /check/healthz
      httpConnectionManagerSettings:
        useRemoteAddress: true
      waf:
        auditLogging:
          action: ALWAYS
          location: FILTER_STATE
        customInterventionMessage: ModSecurity intervention! Custom message details
          here..
        ruleSets:
        - ruleStr: |
            # Turn rule engine on
            SecRuleEngine On
            SecAuditLogFormat JSON
            SecRule REQUEST_HEADERS:User-Agent "scammer" "deny,status:403,id:107,phase:1,msg:'blocked scammer'"
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            duration: '%DURATION%'
            dynamicMetadata: '%DYNAMIC_METADATA("io.solo.filters.http.modsecurity:audit_log")%'
            endpoint_url: '%DYNAMIC_METADATA(io.solo.transformation:endpoint_url)%'
            filterState: '%FILTER_STATE(io.solo.modsecurity.audit_log)%'
            method: '%REQ(:METHOD)%'
            path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            pod_name: '%DYNAMIC_METADATA(io.solo.transformation:pod_name)%'
            protocol: '%PROTOCOL%'
            clientDuration: '%DURATION%'
            targetDuration: '%RESPONSE_DURATION%'
            remoteAddress: '%DOWNSTREAM_REMOTE_ADDRESS%'
            responseCode: '%RESPONSE_CODE%'
            stringFormat: "%FILTER_STATE(io.solo.modsecurity.audit_log)%\n"
            systemTime: '%START_TIME%'
            upstreamCluster: '%UPSTREAM_CLUSTER%'
            upstreamHost: '%UPSTREAM_HOST%'
            xForwardFor: '%REQ(X-FORWARDED-FOR)%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  ssl: false
  useProxyProto: false
```

**This should  pass**
`gateway-proxy-no-waf.yaml`
```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      healthCheck:
        path: /check/healthz
      httpConnectionManagerSettings:
        useRemoteAddress: true
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            duration: '%DURATION%'
            dynamicMetadata: '%DYNAMIC_METADATA("io.solo.filters.http.modsecurity:audit_log")%'
            endpoint_url: '%DYNAMIC_METADATA(io.solo.transformation:endpoint_url)%'
            filterState: '%FILTER_STATE(io.solo.modsecurity.audit_log)%'
            method: '%REQ(:METHOD)%'
            path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
            pod_name: '%DYNAMIC_METADATA(io.solo.transformation:pod_name)%'
            protocol: '%PROTOCOL%'
            clientDuration: '%DURATION%'
            targetDuration: '%RESPONSE_DURATION%'
            remoteAddress: '%DOWNSTREAM_REMOTE_ADDRESS%'
            responseCode: '%RESPONSE_CODE%'
            stringFormat: "%FILTER_STATE(io.solo.modsecurity.audit_log)%\n"
            systemTime: '%START_TIME%'
            upstreamCluster: '%UPSTREAM_CLUSTER%'
            upstreamHost: '%UPSTREAM_HOST%'
            xForwardFor: '%REQ(X-FORWARDED-FOR)%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  ssl: false
  useProxyProto: false
```

**To Reproduce**
1. Go through the steps to deploy a gRPC service in the [docs](https://docs.solo.io/gloo-edge/master/guides/traffic_management/destination_types/grpc/#validate-with-grpc-client) 
2. `kubectl apply -f gateway-proxy-waf.yaml`
3. `grpcurl -plaintext $(glooctl proxy address --port http) list`
4. On `1.7.2` see error, or if you are on `1.6.22` or `1.7.1` no error, just no response
5. `kubectl apply -f gateway-proxy-no-waf.yaml`
6. see response resolve successfully 

Looking at logs from the gateway-proxy these calls succeed with a 200 response, in `1.7.2` you get a message:
```
{
  "grpc-message": "downstream duration timeout", 
  "grpc-status": "4",
  "status": "200", 
  "content-type": "application/grpc"
}
```

**Expected behavior**
The WAF not to interfere with the VirtualService

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version `1.7.2` `1.6.22` `1.7.1`
- Kubernetes version
