### ISSUE TITLE
Transformation of the status header without a else statement is causing Envoy to crash

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4675]
**Describe the bug**
A transformation of the status header causes Envoy to crash when the transformation doesn't have a `else` statement.

**To Reproduce**
```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    options:
      stagedTransformations:
        regular:
          responseTransforms:
          - responseTransformation:
              transformationTemplate:
                parseBodyBehavior: DontParse
                headers:
                    ":status":
                        text: '{% if header(":status") == "404" %}302{% endif %}'
    domains:
    - '*'
    routes:
    - matchers:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
EOF
```

Then run a `curl` on `/get`.
It crashes as soon as the value of the status header isn't `404`

I think that when there's no `else` statement and the current status doesn't match the `if` condition , the value of the `status` header is probably set to an empty string and it's causing Envoy to crash.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version: 1.7.2
