### ISSUE TITLE
Documentation for additional data planes via Helm

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#4677]
**Describe the requested changes**
There is functionality built into the helm chart to deploy more than one gatewayProxy as well supplemental data-plane components when using glooE, but there are no examples for how to utilize these features.

We should have a guide or example that shows how to correctly configure a multi-data-plane deployment.

**Link to any relevant existing docs**
N/A

**Additional context**
No existing docs for `global.extensions.dataplanePerProxy`
No explanation of how to use `gatewayProxies.$NAME`

**Comment by lgadban** [comment]
with 1.8.0-beta3, the following works:

```
global:
  extensions:
    dataplanePerProxy: true
gloo:
  gatewayProxies:
    gatewayProxy:
      #disabled: true
      gatewaySettings:
        customHttpGateway:
           options:
             extauth:
               extauthzServerRef:
                 name: extauth-gateway-proxy
                 namespace: gloo-system
    internalProxy:
      gatewaySettings:
        customHttpGateway:
          options:
            extauth:
              extauthzServerRef:
                name: extauth-internal-proxy
                namespace: gloo-system
          virtualServiceSelector:
            gateway-type: internal
```
