### ISSUE TITLE
Add an option to enable mTLS on all the discovered Upstreams by default

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4691]
**Is your feature request related to a problem? Please describe.**
When a user wants to enable mTLS for all the workloads, he needs to update all the Upstreams manually to add the following:

```
  sslConfig:
    alpnProtocols:
    - istio
    sds:
      certificatesSecretName: istio_server_cert
      clusterName: gateway_proxy_sds
      targetUri: 127.0.0.1:8234
      validationContextName: istio_validation_context
```

**Describe the solution you'd like**
A new option (driven by Helm) to have it enabled by default on all the discovered Upstreams.
