### ISSUE TITLE
Update docker-compose documentation and scripts

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#4692]
**Describe the requested changes**
It's currently based on Gloo Edge 1.5 and it's not working with 1.7.

It should be updated with each new Gloo Edge version.

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/installation/gateway/development/docker-compose-file/
2. https://github.com/solo-io/gloo/tree/master/install/docker-compose-file

**Comment by djannot** [comment]
For reference, here is a working Envoy config:

```
node:
  cluster: gateway
  id: docker-compose-node
  metadata:
    # this line must match !
    role: "gloo-system~gateway-proxy"
static_resources:
  clusters:
  - name: xds_cluster
    http2_protocol_options: {}
    connect_timeout: 5.000s
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: gloo
                port_value: 9977
    http2_protocol_options: {}
    type: STRICT_DNS
dynamic_resources:
  ads_config:
    transport_api_version: V3
    api_type: GRPC
    grpc_services:
    - envoy_grpc: {cluster_name: xds_cluster}
  cds_config:
    ads: {}
    resource_api_version: V3
  lds_config:
    ads: {}
    resource_api_version: V3
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 19000
```
