### ISSUE TITLE
UX problem when using interactive mode on glooctl add route

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#470]
When we want to add a route, as part of interactive mode, it will ask us to select a function to which we should route -- it doesn't give us an option to skip this. Which means when we get to the question about prefix rewrite, it will always be overridden by the function routing. ie, we end up with this:

```
  routes:
  - matcher:
      prefix: /foo
    routeAction:
      single:
        destinationSpec:
          rest:
            functionName: findPets
            parameters: {}
        upstream:
          name: default-petstore-8080
          namespace: gloo-system
    routePlugins:
      prefixRewrite:
        prefixRewrite: /api/pets
```

Where we have both function routing and prefix rewrite. We need a way to pick one or the other.
