### ISSUE TITLE
Enterprise dashboard not showing upstreams or virtual services

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#4703]
**Describe the bug**
The enterprise dashboard in 1.7.3 is not showing upstreams or virtual services.

**To Reproduce**
1. `kubectl apply -f https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml`
2. Apply this virtual service:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: gloo-system
spec:
  displayName: httpbin
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
        - prefix: /
        routeAction:
          single:
            upstream:
              name: default-httpbin-8000
              namespace: gloo-system
```
3. Confirm that it works:
```
% curl $(glooctl proxy url)/get -i
HTTP/1.1 200 OK
server: envoy
date: Wed, 05 May 2021 18:29:17 GMT
content-type: application/json
content-length: 230
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 3

{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "35.231.87.2",
    "User-Agent": "curl/7.64.1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  },
  "origin": "10.92.1.8",
  "url": "http://35.231.87.2/get"
}
```
4. Activate `glooctl dashboard`
5. See that both virtual services and upstreams are missing from dashboard, although they are all clearly active in the cluster.

<img width="1092" alt="Screen Shot 2021-05-05 at 2 30 31 PM" src="https://user-images.githubusercontent.com/52334260/117191453-945d7680-adae-11eb-945e-e037152bd633.png">

**Expected behavior**
Virtual services and upstreams are visible in dashboard.

**Additional context**
```
% glooctl version
Client: {"version":"1.7.3"}
Server: {"type":"Gateway","enterprise":true,"kubernetes":{"containers":[{"Tag":"1.7.3","Name":"discovery","Registry":"quay.io/solo-io"},{"Tag":"1.7.3","Name":"extauth-ee","Registry":"quay.io/solo-io"},{"Tag":"1.7.3","Name":"gateway","Registry":"quay.io/solo-io"},{"Tag":"1.7.3","Name":"gloo-ee-envoy-wrapper","Registry":"quay.io/solo-io"},{"Tag":"1.7.3","Name":"gloo-ee","Registry":"quay.io/solo-io"},{"Tag":"1.7.3","Name":"observability-ee","Registry":"quay.io/solo-io"},{"Tag":"1.7.3","Name":"rate-limit-ee","Registry":"quay.io/solo-io"},{"Tag":"5","Name":"redis","Registry":"docker.io"}],"namespace":"gloo-system"}}
```
- Kubernetes version v1.18.16-gke.2100
