### ISSUE TITLE
RateLimitConfig causes error when descriptors are nested 2+ times

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4741]
**Describe the bug**
RateLimitConfig causes error when descriptors are nested 2+ times, even though it is accepted by gloo

```yaml
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: my-rate-limit-policy
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - descriptors:
      - descriptors:
        - key: path
          rateLimit:
            requestsPerUnit: 4
            unit: MINUTE
      - key: user-agent
        rateLimit:
          requestsPerUnit: 10
          unit: MINUTE
      key: uid
      rateLimit:
        requestsPerUnit: 20
        unit: MINUTE
    - descriptors:
      - descriptors:
        - key: path
          rateLimit:
            requestsPerUnit: 25
            unit: MINUTE
      - key: user-agent
        rateLimit:
          requestsPerUnit: 30
          unit: MINUTE
      key: remote_address
      rateLimit:
        requestsPerUnit: 40
        unit: MINUTE
    rateLimits:
    - actions:
      - requestHeaders:
          descriptorKey: uid
          headerName: uid
    - actions:
      - requestHeaders:
          descriptorKey: uid
          headerName: uid
      - requestHeaders:
          descriptorKey: user-agent
          headerName: user-agent
    - actions:
      - requestHeaders:
          descriptorKey: uid
          headerName: uid
      - requestHeaders:
          descriptorKey: user-agent
          headerName: user-agent
      - requestHeaders:
          descriptorKey: path
          headerName: :path
    - actions:
      - remoteAddress: {}
    - actions:
      - remoteAddress: {}
      - requestHeaders:
          descriptorKey: user-agent
          headerName: user-agent
    - actions:
      - remoteAddress: {}
      - requestHeaders:
          descriptorKey: user-agent
          headerName: user-agent
      - requestHeaders:
          descriptorKey: path
          headerName: :path
```

```sh
{"level":"error","ts":1620921585.4205527,"logger":"gloo-ee.v1.event_loop.setup","caller":"syncer/setup_syncer.go:613","msg":"gloo main event loop","version":"1.6.23","error":"event_loop.gloo: 1 error occurred:\n\t* Error loading new tree descriptors: descriptor has empty key\n\n","errorVerbose":"1 error occurred:\n\t* Error loading new tree descriptors: descriptor has empty key\n\n\nevent_loop.gloo\ngithub.com/solo-io/go-utils/errutils.AggregateErrs\n\t/go/pkg/mod/github.com/solo-io/go-utils@v0.20.3/errutils/aggregate_errs.go:19\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/solo-io/gloo/projects/gloo/pkg/syncer.RunGlooWithExtensions.func6\n\t/go/pkg/mod/github.com/solo-io/gloo@v1.6.19/projects/gloo/pkg/syncer/setup_syncer.go:613"}
```

**To Reproduce**
1. Create ratelimticonfig with the above yaml
2. make calls
3. See error

**Expected behavior**
Nesting descriptors 2+ times should work

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version - glooe v1.6.23
- Kubernetes version
