### ISSUE TITLE
allow for child routes with regex to extend parent routes with prefix

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4747]
**Describe the bug**
Given a VS having a route with matcher `prefix: /`
And its RouteTable having a route with matcher `regex: '^\/get$'`
Then, the config should be accepted

Currently, the config is rejected:
```
* Found rejected virtual service: gloo-system httpbin (Reason: 1 error occurred:
	* on sub route table gloo-system.regex: required prefix: /, prefix: ^\/get$: invalid route: route table matchers must begin with the prefix of their parent route's matcher
```

**To Reproduce**
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        delegateAction:
          ref:
            name: regex
            namespace: 'gloo-system'
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: regex
  namespace: gloo-system
spec:
  routes:
    - matchers:
       - regex: '^\/get$'
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
```

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.7.6
- Kubernetes version KinD 1.20
