### ISSUE TITLE
Redact headers/info from proxy dump

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#4755]
**Is your feature request related to a problem? Please describe.**

Customer is appending a header from a secret ref, and would like this information redacted from proxy dumps.
Right now the value is in the dump.

```
glooctl create secret header secret-header --headers x-header-1=DoNotShowThis
```

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: json-upstream
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80

```

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: my-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "*"
    routes:
      - matchers:
          - prefix: /test
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
        options:
          autoHostRewrite: true
          headerManipulation:
              - headerSecretRef:
                  name: secret-header
                  namespace: gloo-system
                append: false
```

```
glooctl proxy dump
...

           {
            "header": {
             "key": "x-header-1",
             "value": "DoNotShowThis"
            },
```

**Describe the solution you'd like**
Option to redact proxy dump info

similar to how cert info is redacted

``` 
            "tls_certificates": [
             {
              "certificate_chain": {
               "filename": "/certs/crt/tls.crt"
              },
              "private_key": {
               "filename": "[redacted]"
              }

```

**Describe alternatives you've considered**

**Additional context**
