### ISSUE TITLE
Cannot get remote-address of client in AWS

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4761]
**Describe the bug**
Unable to get the remote-address of the client when the cluster is in AWS despite having the prescribed configuration.

1. Configure the gateway-proxy service: 
```
k patch svc gateway-proxy -n gloo-system -p '{"spec":{"externalTrafficPolicy":"Local"}}'
```
2. Configure Gateway gateway-proxy:
```
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      httpConnectionManagerSettings:
        useRemoteAddress: true
        xffNumTrustedHops: 2 #Account for load balancer, I have also tried with 1 hop
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            downstreamRemoteAddress: '%DOWNSTREAM_REMOTE_ADDRESS%'
            duration: '%DURATION%'
            protocol: '%PROTOCOL%'
            upstreamCluster: '%UPSTREAM_CLUSTER%'
            upstreamHost: '%UPSTREAM_HOST%'
            xForwardedFor: '%REQ(X-FORWARDED-FOR)%'
          path: /dev/stdout
```

**To Reproduce**
1. deploy httpbin app
2. Configure access logs
3. configure gateway-proxy svc to have externalTrafficPolicy of Local
4. Configure gateway gateway-proxy to useRemoteAddress
5. Create vs for httpbin
6. Send requests and check the access logs to see only the remote-address of the load balancer 

**Expected behavior**
Expecting to get the remote address of the client sending the request

**Additional context**
I have seen this occur in the environments of 2 clients this week and several more over the last few months.
- Gloo Edge version [`v1.6.29`, `v1.7.6`]
- Kubernetes version

**Comment by cmwylie19** [comment]
Solved, thanks to @jmunozro 

```aws elb create-load-balancer-policy --load-balancer-name a405c07f9447e4ebab7ce2c9ea5399b8 --policy-name case-xff-policy --policy-type-name ProxyProtocolPolicyType --policy-attributes AttributeName=ProxyProtocol,AttributeValue=true```

```aws elb set-load-balancer-policies-for-backend-server --load-balancer-name a405c07f9447e4ebab7ce2c9ea5399b8 --instance-port 32455 --policy-names case-xff-policy```

```kubectl annotate svc/gateway-proxy -n gloo-system 'service.beta.kubernetes.io/aws-load-balancer-backend-protocol'=tcp 'service.beta.kubernetes.io/aws-load-balancer-proxy-protocol'='*'```

Update Gateway Proxy:
```
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      httpConnectionManagerSettings:
        useRemoteAddress: true
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            downstreamRemoteAddress: '%DOWNSTREAM_REMOTE_ADDRESS%'
            duration: '%DURATION%'
            protocol: '%PROTOCOL%'
            upstreamCluster: '%UPSTREAM_CLUSTER%'
            upstreamHost: '%UPSTREAM_HOST%'
            xForwardedFor: '%REQ(X-FORWARDED-FOR)%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  useProxyProto: true
 ```
