### ISSUE TITLE
Gloo discovery creates invalid ownerReferences in upstream

### ISSUE THREAD

**Issue by andylibrian** [solo-io/gloo#4790]
**Describe the bug**
When Gloo discovery creates upstreams from services, it also copies the `metadata.ownerReferences` of the service to the upstream. This becomes a problem when it discovers services from different namespaces, resulting in the upstream having ownerReference from different namespace.

Kubernetes Garbage Collector would delete the upstreams due to having ownerReferences in different namespace.

ref:
- https://github.com/kubernetes/kubernetes/issues/65200
- https://github.com/kubernetes/kubernetes/pull/92743

**To Reproduce**
Steps to reproduce the behavior (tested on k8s 1.19):

1. Create a service with ownerReferences

   ```
   kubectl create deployment nginx --image=nginx --port=80 -n default
   kubectl expose deployment/nginx --port=80
   
   kubectl edit svc nginx ; add ownerReferences
   metadata:
     ownerReferences:
     - apiVersion: apps/v1
       blockOwnerDeletion: true
       controller: true
       kind: Deployment
       name: nginx
       uid: uid_of_deployment/nginx
   ```

2. Install gloo through helm chart with additional watch namespaces:

   ```
   kubectl create ns gloo-system
   helm upgrade -i gloo gloo/gloo --timeout 15m --set "settings.watchNamespaces={gloo-system,default}" -n gloo-system
   ```

2. See the upstream created with ownerReferences copied from the service, which is invalid / cross-namespace

**Expected behavior**
ownerReferences shouldn't be copied to different namespaces.

**Additional context**
- This tool https://github.com/kubernetes-sigs/kubectl-check-ownerreferences also reports this as an error (child namespace does not match owner namespace)
   ```
   GROUP          RESOURCE    NAMESPACE     NAME               OWNER_UID                              LEVEL   MESSAGE
   gloo.solo.io   upstreams   gloo-system   default-nginx-80   df502980-70a1-47a8-946e-b6fabe6580e5   Error   child namespace does not match owner namespace (default)

   1 error, 0 warnings
   ```

- "Cross-namespace owner references are disallowed by design." source: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

- In my real world use-case, I use flagger with gloo for canary / progressive deployment. Flagger creates 2 services: canary and primary, with ownerReferences to the canary object (CRD). Gloo discovers these services and creates upstreams with cross-namespace ownerReferences.
