### ISSUE TITLE
Pass custom headers in healthcheck 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#4797]
Provide a way to pass custom headers when calling the healthcheck endpoint 
example: 
```
  failover:
    prioritizedLocalities:
      - localityEndpoints:
          - lbEndpoints:
              - address: edge-usw2.internal.dev.customer.net
                port: 443
                healthCheckConfig:
                  hostname: echo-extauth.internal.dev.customer.net
                  path: /healthz
                  headers:
                    - name: custom-auth-header
                      value: foo
                upstreamSslConfig:
                  sni: echo-extauth.internal.dev.customer.net
                  secretRef:
                    name: star-internal-customer-net-certificate
                    namespace: gloo-ee
```
