### ISSUE TITLE
Enable Route Replacement docs are incorrect

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4841]
**Describe the requested changes**
The values for Enabling Route replacement for helm are incorrect in our docs.

Docs incorrectly show:
```
# set the following value when running `helm install` or `helm template`
--set settings.invalidConfigPolicy.replaceInvalidRoutes=true
```

The correct settings are:
```
settings:
  replaceInvalidRoutes: true
  invalidConfigPolicy:
    invalidRouteResponseBody: Gloo Edge has invalid configuration. Administrators
      should run `glooctl check` to find and fix config errors.
    invalidRouteResponseCode: 404
    replaceInvalidRoutes: true
```

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/invalid_route_replacement/
2. ...

**Browser Information**
If the change isn't related to content, please include your browser version and any other relevant information 
(e.g., browser zoom) to help us reproduce docs-related bugs.

**Additional context**
Link to correct helm overrides - https://github.com/solo-io/gloo/issues/3619#issuecomment-756121223
