### ISSUE TITLE
Customize error response when JWT expired

### ISSUE THREAD

**Issue by YaoweiDu** [solo-io/gloo#4871]
Hi Gloo team,

I'm using the `jwt` authentication and it works for the happy path. However, for the `401 unauthorized` case, it returns a plant text response like `JWT is missing` or. `JWT is expired`. What I want is to return a customized JSON response like this: 

```
{ 
    "errorMessage": "Jwt is expired", 
    "errorType": "UNAUTHORIZED" 
}
```

I follow the [transformation document here](https://docs.solo.io/gloo-edge/master/guides/traffic_management/request_processing/transformations/) and use the regular transformations. My understanding is the regular transformation would run after the JWT. My setting is like below, however, it doesn't work.

```
            options:
              stagedTransformations:
                regular:
                  requestTransforms:
                    - matcher:
                        prefix: /
                      responseTransformation:
                        transformationTemplate:
                          body:
                            text: '{% if body() == "Jwt is expired" %}{ "errorMessage": "Jwt is expired", "errorType": "UNAUTHORIZED" }{% else if header(":status") == "401" %}{ "errorMessage": "Unauthorized", "errorType": "UNAUTHORIZED" }{% else %}{{ body() }}{% endif %}'
```

Also I'm using the Gloo server `v1.6.28`.
Could you please help me to clarify if I'm using it the right way, or is there any other way to customize the JWT error response? 

Thank you very much!
