### ISSUE TITLE
Envoy not respecting timeout set on Virtual Service

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#4878]
**Describe the bug**
A client has an endpoint that takes around ~40s to resolve as it goes and fetches data from a data lake. In Gloo, the request comes back in with an `upstream request timeout` after 15s. 

We have set the timeout and retries on the virtual service, and verified that they were accepted by Gloo. 
```
matchers:
  - prefix: /api
options:
  retries:
    numRetries: 3
    perTryTimeout: 60s
    retryOn: connect-failure
  timeout: 180s
```

We see in the envoy debug logs that these settings were propagated to the dataplane. 

We also verified in the proxy dump.

We have also tried setting `connectTimeout` `tcpKeepalive` on the connectionConfig in the Upstream without success. 

We have also tried with the timeout set to 0s.

For some reason the duration still only lasts around 15 seconds which makes it seem like there is still some timeout that is overriding our configs.

The client tried without Gloo in Postman and the request resolved with a 200 response after 40 seconds

**To Reproduce**
1. Unable to reproduce so far locally

**Expected behavior**

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version (Waiting for confirmation)
- Kubernetes version
