### ISSUE TITLE
add healthCheckConfig to all destinations types

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#4942]
**Is your feature request related to a problem? Please describe.**
Given an Upstream, be it using a `kube` or `static` destination type,
I want to define an alternative health check port

Envoy now has this [healthCheckConfig](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/health_checking#per-cluster-member-health-check-config), for the upstream cluster members.
The Envoy doc states:

> If active health checking is configured for an upstream cluster, a specific additional configuration for each registered member can be specified by setting the HealthCheckConfig in the Endpoint of an LbEndpoint of each defined LocalityLbEndpoints in a ClusterLoadAssignment.

This is currently possible for endpoints defined in a `failover`.

**Alternatives I've tried**
I tried to define a `kube` service with a dummy health check, in combination with `failover`, like this:
```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-actuator-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      app.kubernetes.io/instance: actuator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: actuator
      app.kubernetes.io/version: 1.16.0
      helm.sh/chart: actuator-0.1.0
  kube:
    selector:
      app.kubernetes.io/instance: actuator
      app.kubernetes.io/name: actuator
    serviceName: actuator
    serviceNamespace: default
    servicePort: 8080
  healthChecks:
    - timeout: 1s
      interval: 2s
      unhealthyThreshold: 2
      healthyThreshold: 1
      httpHealthCheck:
        host: actuator.default
        path: /does/not/exist
  failover:
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: actuator.default
          port: 8080
          healthCheckConfig:
            portValue: 8081
            hostname: actuator.default
            path: /actuator/health
        locality:
          region: px
          zone: alpha
```
But it doesn't work.

Not sure if this is a duplicate of https://github.com/solo-io/gloo/issues/1821

**Additional context**
Gloo Edge 1.8-beta10
