### ISSUE TITLE
Regex do not behave as expected

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5000]
**Describe the bug**
Regex do not behave as expected. There must be a parsing which is not transparent for the user.
We are trying to obtain a value from a json-like body but received with content-type: 

**To Reproduce**
1. Install httpbin application (https://raw.githubusercontent.com/istio/istio/master/samples/httpbin/httpbin.yaml)
2. Create followign Virtual Service:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: demo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    options:
      stagedTransformations:
        early:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                parseBodyBehavior: DontParse
                extractors:
                  all:
                    body: {}
                    regex: '(\{([^}]+)\})'
                    subgroup: 1
                  myToken:
                    body: {}
                    regex: '.*"key_x\\*":[^"]*"([^"\/\\]*).*".*'
                    subgroup: 1
                headers:
                  x-all:
                    text: '_{{ all }}_'
                  x-token:
                    text: '__{{ myToken }}__'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: default-httpbin-80
              namespace: gloo-system
```

3. Create the payload file with name `payload.json` and content:
```
{
  "any_number_of_keys": "any_value",
  "key_x": "value", 
  "key_1": "value2"
  }
```

4. Run the curl command to the `httpbin` application deployed in the cluster with:
```bash
curl -vvv --location --request POST 'http://127.0.0.1:8080/post' \
--header 'x-original-client-ip-address: 0.0.0.0' \
--header 'Host: rest-eu.dev.nexmo.com' \
--header 'Content-Type: application/json' \
--data-binary @payload.json
```

5. The output is:
```
{
  "args": {}, 
  "data": "{\n  \"any_number_of_keys\": \"any_value\",\n  \"key_x\": \"value\", \n  \"key_1\": \"value2\"\n  }", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "83", 
    "Content-Type": "application/json", 
    "Host": "rest-eu.dev.nexmo.com", 
    "User-Agent": "curl/7.64.1", 
    "X-All": "_{\n  \"any_number_of_keys\": \"any_value\",\n  \"key_x\": \"value\", \n  \"key_1\": \"value2\"\n  }_", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000", 
    "X-Original-Client-Ip-Address": "0.0.0.0", 
    "X-Token": "____"
  }, 
  "json": {
    "any_number_of_keys": "any_value", 
    "key_1": "value2", 
    "key_x": "value"
  }, 
  "origin": "xxxxx", 
  "url": "http://rest-eu.dev.nexmo.com/post"
}
```

Explanation of the regex:
It tries to find the string `key_x` and match what it comes after in between quotes `"`. Like trying to access the value of a json attribute, but with regex.

**Expected behavior**

The regex should find the value and add it to the header `X-Token`follows:
```
"X-Token": "__<HERE THE MATCHING VALUE>__"
```

**Additional context**
Add any other context about the problem here, e.g.

- Gloo Edge version: 1.7.5
- To test the regex it has been used following online regex testers:
https://regoio.herokuapp.com/
https://regex101.com/
- To test through the online tester:

regexp:
```
.*"key_x\\*":[^"]*"([^"\/\\]*).*".*
```
Text to test:
```
{
  "any_number_of_keys": "any_value",
  "key_x": "value", 
  "key_1": "value2"
  }
```
Text taken from the output header which I could work since it is escaping the content:
```
{\n  \"any_number_of_keys\": \"any_value\",\n  \"key_x\": \"value\", \n  \"key_1\": \"value2\"\n  }
```
In the online tester, it works perfectly:

![image](https://user-images.githubusercontent.com/5262332/125060816-069f4f80-e0ad-11eb-920a-4b4de057e6de.png)
