### ISSUE TITLE
Enterprise helm chart fails to produce extAuth requestBody attributes in Settings

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#5016]
**Describe the bug**
The Enterprise helm chart fails to produce extAuth requestBody attributes in Settings.

**To Reproduce**
1. Generate helm template with these `extAuth.requestBody` values.
```
helm template gloo-ee --version v1.8.0  glooe/gloo-ee --namespace gloo-system --set-string license_key=$GLOO_KEY --set global.extensions.extAuth.requestTimeout=2s --set global.extensions.extAuth.requestBody.maxRequestBytes=64000 --set global.extensions.extAuth.requestBody.packAsBytes=true
```
2. Observe that the `requestTimeout` is produced as expected in the generated `Settings` object, but the `requestBody` attributes, `maxRequestBytes` and `packAsBytes`, are not produced.
```
  extauth:
    transportApiVersion: V3
    extauthzServerRef:
      # arbitrarily default to the standalone deployment name even if we're using both
      name: extauth
      namespace: gloo-system
    requestTimeout: "2s"
    userIdHeader: "x-user-id"
  ratelimitServer:
    ratelimitServerRef:
      name: rate-limit
      namespace: gloo-system
```

**Expected behavior**
All `extAuth.requestBody` attributes are rendered to the `Settings` config as expected.

**Additional context**
- Gloo Edge Enterprise version 1.7.11, 1.8.0
- Internal reference: https://solo-io.slack.com/archives/G01MKQQ0Q3W/p1626176796150400
