### ISSUE TITLE
Unable to disable monitoring stack via parent chart for gloo-ee

### ISSUE THREAD

**Issue by asafdl** [solo-io/gloo#5026]
**Describe the bug**
When wrapping the gloo-ee chart you are unable to change the values that the chart's requirement.yaml reads under the condition, this helm issue can be seen here https://github.com/splisson/helm/blob/master/docs/charts.md#tags-and-condition-fields-in-requirementsyaml

**To Reproduce**
1. create a simple wrapper chart with nothing other than Chart.yaml, empty values.yaml, and under charts/(place gloo-ee here)
2. add the correct values to disable monitoring in parent chart:
```yaml
gloo-ee:
  prometheus:
    enabled: false
  grafana:
    defaultInstallationEnabled: false
```
3. run `helm template .` see that prometheus and grafana are deployed

**Expected behavior**
be able to not deploy monitoring stack from parent chart
this can be achieved like this:
requirement.yaml
```yaml
dependencies:
- name: gloo
  repository: https://storage.googleapis.com/solo-public-helm
  version: 1.6.7
- condition: prometheus.enabled,global.prometheus.enabled
  name: prometheus
  repository: https://charts.helm.sh/stable
  tags:
  - monitoring
  version: 9.5.1
- condition: grafana.defaultInstallationEnabled,global.grafana.defaultInstallationEnabled
  name: grafana
  repository: https://charts.helm.sh/stable
  tags:
  - monitoring
  version: 5.0.8
```
then can configure in parent values.yaml:
```yaml
global:
  prometheus:
    enabled: false
  grafana:
    defaultInstallationEnabled: false
```
**Additional context**
Add any other context about the problem here, e.g.
- in 1.6.8 > as far as i can see
