### ISSUE TITLE
[helm] Provide a global and consistent floatingUserId

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#5034]
**Is your feature request related to a problem? Please describe.**
to install on OCP, you have to enable floatingUserId on tons of components. it is very error-prone and provides a poor UX

**Describe the solution you'd like**
A global way to turn on floatingUserId (and also have it include things like fsGroup)

This relates to part 2A of https://github.com/solo-io/solo-projects/issues/6323

Part of the scope of this ticket includes considering how this applies to the Kubes GW helm charts, which currently do not support `floatingUserId`, getting consensus on an approach, and implementing the decided-upon approach, if any.

**Additional context**
This is what a values file looks like to install on OCP:
```
global:
  extensions:
    extAuth:
      deployment:
        floatingUserId: true
        fsGroup: 1001850000
    rateLimit:
      deployment:
        floatingUserId: true
gloo:
  gloo:
    deployment:
      floatingUserId: true
  discovery:
    deployment:
      floatingUserId: true
      fsGroup: 1001850000
  gateway:
    deployment:
      floatingUserId: true
    certGenJob:
      floatingUserId: true  
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        floatingUserId: true
        fsGroup: 1001850000
redis:
  deployment:
    floatingUserId: true
    fsGroup: 1001850000
observability:
  deployment:
    floatingUserId: true
    fsGroup: 1001850000
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207720937031997) by [Unito](https://www.unito.io)
