### ISSUE TITLE
cannot use Gateway's socketOptions in v1.8.0

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5043]
**Describe the bug**
When using `socketOptions` on a Gateway CR, the Gateway controller reports error like this:
```json
{"level":"error","ts":1626686105.8066683,"logger":"gateway.v1.event_loop.gateway","caller":"syncer/setup_syncer.go:296","msg":"error: event_loop: 1 error occurred:\n\t* reconciling resource gateway-proxy: creating kube resource gateway-proxy: Proxy.gloo.solo.io \"gateway-proxy\" is invalid: [spec.listeners.options.socketOptions.level: Invalid value: \"string\": spec.listeners.options.socketOptions.level in body must be of type integer: \"string\", spec.listeners.options.socketOptions.name: Invalid value: \"string\": spec.listeners.options.socketOptions.name in body must be of type integer: \"string\", spec.listeners.options.socketOptions.intValue: Invalid value: \"string\": spec.listeners.options.socketOptions.intValue in body must be of type integer: \"string\"]\n\n","version":"1.8.0","stacktrace":"github.com/solo-io/gloo/projects/gateway/pkg/syncer.RunGateway.func1\n\t/workspace/gloo/projects/gateway/pkg/syncer/setup_syncer.go:296"}
```

Helm values example:
```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        options:
          socketOptions:
            - description: "enable keep-alive"
              level: 1
              name: 9
              intValue: 1
              state: STATE_LISTENING
            - description: "idle time before first keep-alive probe is sent"
              level: 6
              name: 4
              intValue: 60
              state: STATE_LISTENING
            - description: "keep-alive interval"
              level: 6
              name: 5
              intValue: 20
              state: STATE_LISTENING
            - description: "keep-alive probes count"
              level: 6
              name: 6
              intValue: 2
              state: STATE_LISTENING
```

The helm-generated `gateway-proxy` CR:
```yaml
...
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  options:
    socketOptions:
    - description: enable keep-alive
      intValue: 1
      level: 1
      name: 9
      state: STATE_LISTENING
    - description: idle time before first keep-alive probe is sent
      intValue: 60
      level: 6
      name: 4
      state: STATE_LISTENING
    - description: keep-alive interval
      intValue: 20
      level: 6
      name: 5
      state: STATE_LISTENING
    - description: keep-alive probes count
      intValue: 2
      level: 6
      name: 6
      state: STATE_LISTENING
...
```

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.8.0
- Kubernetes version 1.19 GKE
