### ISSUE TITLE
Production Deployment Doc shows incorrect helm values for disableKubernetesDestination

### ISSUE THREAD

**Issue by cmwylie19** [solo-io/gloo#5080]
**Describe the requested changes**
while the docs read `settings.gloo.disableKubernetesDestinations`, the `gloo/install/helm/gloo/templates/18-settings.yaml` file is reading from the variable `.Values.settings.disableKubernetesDestinations`.

Are the Production Deployment docs actually referring to the default settings object and not the helm overrides value?  

```
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  name: default
  namespace: gloo-system
spec:
  gloo:
    disableKubernetesDestinations: false # .spec.gloo.disableKubernetesDestinations
```

**Link to any relevant existing docs**
1. Docs - https://docs.solo.io/gloo-edge/latest/operations/production_deployment/ 
2. File - https://github.com/solo-io/gloo/blob/8697bee5f9bf4247acfb63a4a52803da391fc7fc/install/helm/gloo/templates/18-settings.yaml

**Browser Information**
If the change isn't related to content, please include your browser version and any other relevant information 
(e.g., browser zoom) to help us reproduce docs-related bugs.

**Additional context**
