### ISSUE TITLE
helm - options under gatewaySettings.options, other than ALS, are not rendered correctly

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5089]
**Describe the bug**
Gateway options like `socketOptions` or `perConnectionBufferLimitBytes` are not well formatted: indentation is set to 6 instead of  4. This leads to helm template rendering errors like `Error: YAML parse error on gloo-ee/charts/gloo/templates/8-default-gateways.yaml: error converting YAML to JSON: yaml: line 35: did not find expected key`

**To Reproduce**
values.yaml
```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        options:
          socketOptions:
            - description: "enable keep-alive" # socket level options
              level: 1 # means socket level options
              name: 9 # means the keep-alive parameter
              intValue: 1 # a nonzero value means “yes” - 
              state: STATE_LISTENING
            - description: "idle time before first keep-alive probe is sent" # TCP protocol
              level: 6 # IPPROTO_TCP
              name: 4 # TCP_KEEPIDLE parameter - The time (in seconds) the connection needs to remain idle before TCP starts sending keepalive probes
              intValue: 60 # seconds
              state: STATE_LISTENING
            - description: "keep-alive interval" # TCP protocol
              level: 6 # IPPROTO_TCP
              name: 5 # the TCP_KEEPINTVL parameter - The time (in seconds) between individual keepalive probes.
              intValue: 20 # seconds
              state: STATE_LISTENING
            - description: "keep-alive probes count" # TCP protocol
              level: 6 # IPPROTO_TCP
              name: 6 # the TCP_KEEPCNT parameter - The maximum number of keepalive probes TCP should send before dropping the connection
              intValue: 2 # number of failed probes
              state: STATE_LISTENING
```

```bash
helm upgrade -i gloo glooe/gloo-ee --namespace ${NS} --version ${GLOO_VERSION} --create-namespace --set-string license_key="$LICENSE_KEY" -f values.yaml
```

**Expected behavior**
correct YAML formatting 

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version EE 1.8.1
- Kubernetes version 1.19
