### ISSUE TITLE
Document the data transformation used to add a request header in the response

### ISSUE THREAD

**Issue by djannot** [solo-io/gloo#5103]
**Describe the requested changes**
Here is an example:

```
    options:
      transformations:
        responseTransformation:
          transformationTemplate:
            headers:
              bar:
                text: '{{ request_header("foo") }}'
```
