### ISSUE TITLE
adding the validationServerGrpcMaxSize  crashes the gloo and the gateway pods 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5160]
adding the validationServerGrpcMaxSize to  gloo edge enterprise 1.8.4 (based on 1.8.6 OSS) crash all the pods using the settings crd:
```
spec:
  gateway:
    validation:
      validationServerGrpcMaxSize: 
        value: 104857600
```

result: 
```
"Thu, 12 Aug 2021 23:07:03 UTC: /workspace/solo-projects/projects/gloo/cmd/main.go:12"	err in main: "starting snapshot watch: initial Settings list: converting output crd: reading crd spec on resource default in namespace gloo-system into v1Settings: json: cannot unmarshal object into Go value of type int64"
```
