### ISSUE TITLE
Envoy wrapper hostIP interpolation for tracing with Datadog

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5186]
**Is your feature request related to a problem? Please describe.**
The Datadog agent is deployed as a Daemonset. It expects the app/Envoy to push traces to the k8s node where the app runs.
Today, we cannot dynamically configure the Envoy configmap to target the host IP. 

**Describe the solution you'd like**
In our Envoy wrapper dockerfile: https://github.com/solo-io/solo-projects/blob/18a7aa74450ea09d38f0c1bb0ef077e18093176c/cmd/envoyinit/docker-entrypoint.sh
It calls the `envoyinit` app, which performs some variable interpolation with the homemade downward API.
Although the `{{.NodeIp}}` variable looks like ready-to-use, itself consuming the `NODE_IP` env var, the [transformer](https://github.com/solo-io/envoy-operator/blob/master/pkg/downward/transform.go#L79) will not replace variables under the `static_resources.clusters`. It will only replace vars under `Node.Id`, `Node.Cluster`and `Node.Metadata` 

The goal is to have a deployment config as shown below:
```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          customEnv:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      tracing:
        cluster:
          - name: datadog_agent
            connect_timeout: 1s
            type: STRICT_DNS
            load_assignment:
              cluster_name: datadog_agent
              endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "{{.NodeIp}}"
                          port_value: 8126
```
.. that will be transformed by the wrapper with the correct IP address of the current k8s node.

**Additional info**
Gloo v1.8.5

**Comment by chrisgaun** [comment]
@bcollard can you add workaround information

**Comment by bcollard** [comment]
the workaround is an extra init container in the gateway-proxy pod, that create a routing rule with iptables, so that Envoy sends traces to 127.0.0.1:8126 but this is forwarded to the datadog agent running on the same node. Not ideal.

```yaml
gatewayProxies:
    gatewayProxy:
      antiAffinity: true
      kubeResourceOverride:
        spec:
          template:
            spec:
              initContainers:
                - command:
                  - sh
                  - -c
                  - iptables -t nat -A OUTPUT -m addrtype --src-type LOCAL --dst-type LOCAL -p tcp --dport 8126 -j DNAT
                    --to-destination $DD_AGENT_HOST && iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
                  env:
                  - name: DD_AGENT_HOST
                    valueFrom:
                      fieldRef:
                        apiVersion: v1
                        fieldPath: status.hostIP
                  image: xxxxx/iptables:1.0.0
                  imagePullPolicy: IfNotPresent
                  name: gloo-proxy-iptables
                  resources: {}
                  securityContext:
                    allowPrivilegeEscalation: false
                    capabilities:
                      add:
                      - NET_ADMIN
                    runAsUser: 0

      tracing:
        cluster:
          - name: datadog_agent
            connect_timeout: 1s
            type: STRICT_DNS
            load_assignment:
              cluster_name: datadog_agent
              endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: 127.0.0.1
                          port_value: 8126
```

see also https://github.com/solo-io/gloo/issues/5187

**Comment by sam-heilbron** [comment]
@bewebi and @MitchAman have done some work on tracing recently, and would be good points of contact

**Comment by bcollard** [comment]
Thanks to the fix, the following config now works perfectly 👍 

```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          customEnv:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      tracing:
        cluster:
          - name: datadog_agent
            connect_timeout: 1s
            type: STRICT_DNS
            load_assignment:
              cluster_name: datadog_agent
              endpoints:
                - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: "{{.NodeIp}}"
                          port_value: 8126
        provider:
          datadogConfig:
            clusterName: datadog_agent
            serviceName: gloo
```
