### ISSUE TITLE
cannot use extraInitContainersHelper in Helm

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5187]
**Describe the bug**
Cannot render the gateway-proxy deployment with 

```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      extraInitContainersHelper:
        - command:
          - sh
          - -c
          - iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 8126 -j DNAT --to $DD_AGENT_HOST:8126
          env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.hostIP
          image: registry/iptables:1.0.0
          imagePullPolicy: IfNotPresent
          name: gloo-proxy-iptables
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
              - NET_ADMIN
            runAsUser: 0
```

Command:
```
helm template -f values.yaml gloo -n gloo-system glooe/gloo-ee  -s charts/gloo/templates/7-gateway-proxy-deployment.yaml
```

Result:
```
Error: template: gloo-ee/charts/gloo/templates/7-gateway-proxy-deployment.yaml:473:4: executing "gloo-ee/charts/gloo/templates/7-gateway-proxy-deployment.yaml" at <include "gloo.util.merge" (list $ctx $kubeResourceOverride "gatewayProxy.deploymentSpec")>: error calling include: template: gloo-ee/charts/gloo/templates/_helpers.tpl:93:22: executing "gloo.util.merge" at <include (index . 2) $top>: error calling include: template: gloo-ee/charts/gloo/templates/7-gateway-proxy-deployment.yaml:118:23: executing "gatewayProxy.deploymentSpec" at <$spec.extraInitContainersHelper>: wrong type for value; expected string; got []interface {}
```

**Additional context**
- Gloo Edge version 1.8.5
