### ISSUE TITLE
aws lambda: golang contains no event payload

### ISSUE THREAD

**Issue by lilley2412** [solo-io/gloo#5206]
**Describe the bug**

Golang lambdas are invoked with no event payload, I cannot find a way to access headers, querystring, or request body.

**To Reproduce**

* Create a basic lambda:
```go
package main

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/aws/aws-lambda-go/lambda"
	"github.com/aws/aws-lambda-go/lambdacontext"
	"github.com/davecgh/go-spew/spew"
)

func main() {
	lambda.Start(func(ctx context.Context, event interface{}) (map[string]string, error) {
		spew.Dump(os.Environ())
		lc, _ := lambdacontext.FromContext(ctx)
		ctxDump := strings.ReplaceAll(spew.Sdump(lc), "\n", "\\n")
		eventDump := strings.ReplaceAll(spew.Sdump(event), "\n", "\\n")
		fmt.Println(ctxDump)
		fmt.Println(eventDump)
		return map[string]string{
			"event": eventDump,
			"ctx":   ctxDump,
		}, nil
	})
}
```
* Create a vs / upstream pointing to the lambda
* Invoke the lambda

**Expected behavior**

The api response and cloudwatch logs should show the event type and values from`spew.Sdump(event)`.  The event type is `map[string]interface{}`, which seems correct, but the value is empty.  

I also checked to see if anything is being stuffed into context, but the spew.Dump() of the lambdacontext shows that clientContext.Env and clientConext.Custom are empty map[string]string.  

**Additional context**
- Gloo edge 1.8.1
- Kubernetes 1.21
- I don't think this matters - but I'm using IAM roles for service accounts and not static aws keys for permissions (the lambda does get invoked and the response is written correctly)

**Comment by jameshbarton** [comment]
Internal Reference: 
https://solo-io.slack.com/archives/G0133U4GUP5/p1629470023063200

**Comment by chrisgaun** [comment]
@ben-taussig-solo moving this to close. LMK if that is mistake

**Comment by ben-taussig-solo** [comment]
@chrisgaun sounds good! Detailed update below:

To resolve this issue, we have introduced a new field, `requestTransform` on the AWS destionationSpec, which can be used to configure a default set of request transformations which place all request headers, the request HTTP method, and the path and queryString of the request in the event payload received by the lambda. This field will be available as of Gloo OSS 1.9.0-beta18 and Gloo Enterprise 1.9.0-beta9. The PR introducing this change can be found here: https://github.com/solo-io/gloo/pull/5308

In the meantime, you can configure the following transformations on a route or virtualhost to achieve the same behavior:
```yaml
options:
  stagedTransformations:
    early:
      requestTransforms:
      - requestTransformation:
          headerBodyTransform: {}
    regular:
      requestTransforms:
      - requestTransformation:
          transformationTemplate:
            extractors:
              path:
                header: ':path'
                regex: '([^\?]+)(\?.*)?'
                subgroup: 1
              queryString:
                header: ':path'
                regex: '([^\?]+)(\?(.*))?'
                subgroup: 3
              httpMethod:
                header: ':method'
                regex: '(.*)'
                subgroup: 1
            mergeExtractorsToBody: {}
```

Event payload before transformation:
```json
"This is the request body"
```

Event payload after transformation:
```json
{
  "body": "\"This is the request body\"",
  "headers": {
    ":authority": "localhost:8080",
    ":method": "POST",
    ":path": "/path?parameter_a=value_a&parameter_b=value_b",
    ":scheme": "http",
    "accept": "*/*",
    "accept-encoding": "gzip, deflate, br",
    "content-length": "24",
    "content-type": "text/plain",
    "postman-token": "125afd00-7c8f-4786-b4f8-5dddcf338553",
    "user-agent": "PostmanRuntime/7.28.4",
    "x-forwarded-proto": "http",
    "x-request-id": "07cf3461-38d9-427c-9735-837d031b439d"
  },
  "httpMethod": "POST",
  "path": "/path",
  "queryString": "parameter_a=value_a&parameter_b=value_b"
}
```
