### ISSUE TITLE
prefixRewrite cannot be used with lambda backends

### ISSUE THREAD

**Issue by lilley2412** [solo-io/gloo#5252]
**Describe the bug**

When a lambda upstream is used with options.prefixRewrite, the request results in an auth exception from aws lambda invoke.  When prefixRewrite is removed, the request works regardless of what the route path is.

**To Reproduce**
1. Create a lambda upstream (not sure if it matters but i'm using IAM for service accounts, not static aws credentials)
2. Create a route against the lamba and use prefixRewrite:
```yaml
    routes:
      - matchers:
          - prefix: /my-path
        options:
          prefixRewrite: /
        routeAction:
          single:
            destinationSpec:
              aws:
                logicalName: lambda-function-name
            upstream:
              name: lambda-upstream-name
              namespace: gloo-system
```
3. Make a request to the route
4. Observe the following error:
```
<AccessDeniedException>
  <Message>Unable to determine service/operation name to be authorized</Message>
</AccessDeniedException>
```
If the `prefixRewrite` is removed, the request succeeds.

**Expected behavior**
Prefix rewrite should not cause an authorization failure.  If prefixRewrite is removed, and the route path is changed to `/`, it also works.  Using rewrite should result in the same behavior.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.8.2
- Kubernetes version 1.21
- Using IAM for service accounts, not aws static credentials

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1208332962636068) by [Unito](https://www.unito.io)

**Comment by sam-heilbron** [comment]
Setting this to a Medium. If the work required to resolve this is determined to be larger than a medium, it should not be resolved as part of this work. Instead we'll need to re-scope and prioritize the work.

**Comment by lilley2412** [comment]
We found that regexRewrite does work in place of prefixRewrite:

```yaml
      options:
        regexRewrite: 
          pattern:
            regex: /my-path
          substitution: "/"
```

**Comment by chrisgaun** [comment]
Moving to the backlog

**Comment by Ati59** [comment]
A customer is requesting this. 
I have tested it with 1.14.3 (service account and CLI creds) and the problems remains (following this installation guide : https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/aws_lambda/eks-service-accounts/).
Here is details of my (unsuccessful) local tests : 
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /a/b/lambda
      options:
        prefixRewrite: /lambda
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: ati-lambda-test
              unwrapAsApiGateway: true
              wrapAsApiGateway: true
          upstream:
            name: lambda
            namespace: gloo-system
```
My lambda function just returns the event (discovered by gloo) : 
```python
import json

def lambda_handler(event, context):
    print(type(context))
    return {
        'statusCode': 200,
        "headers": {
            "Content-Type": "application/json"
        },
        'body': json.dumps({
            "event": event
        })
    }
```

With `prefixRewrite` and `wrapAsApiGateway` :
<img width="1721" alt="image" src="https://github.com/solo-io/gloo/assets/35342300/03f105cd-76f4-4c75-bfb0-444514a9ac11">
With `prefixRewrite` but without `wrapAsApiGateway`:
<img width="1726" alt="image" src="https://github.com/solo-io/gloo/assets/35342300/ddbe84a7-daaf-45d2-bb89-7cf521aea9bc">

With `regexRewrite` and `wrapAsApiGateway`:
<img width="1724" alt="image" src="https://github.com/solo-io/gloo/assets/35342300/ad9cefc0-9f9f-43a8-af66-7d6352fce04c">

I try several cases (playing with `wrapAsApiGateway` and try the workaround `regexRewrite`) but could not make it working. Sometimes we get `500` error, sometimes `404` and sometimes get the JSON back without the path change.

**Comment by nfuden** [comment]
Given our current ordering of lambda we will either need to rework our entire setup to use router filter options along with lambda

**Comment by DuncanDoyle** [comment]
Can no longer reproduce the original authentication problem in Gloo Gateway 1.17.0.

Second, `prefixRewrite` and `regexRewrite` run after the Lambda filter and therefore do no have effect. To alter the ":path" that is send in the request to the upstream lambda, you can use a `stagedTransformation` to alter the `:path` pseudo-header. Using some regex in the transformation, you can implement semantics similar to `prefixRewrites`. E.g., the following transformation rewrites the prefix `/test/` to `/`:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: lambda-example-com
  namespace: gloo-system
  labels:
    app: quarkus-lambda-ddoyle
spec:
  virtualHost:
    domains:
    - 'lambda.example.com:81'
    routes:
    - matchers:
      - prefix: /test/
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: QuarkusLambdaDdoyle
              wrapAsApiGateway: true
              unwrapAsApiGateway: false
          upstream:
            name: my-aws-lambda-upstream
            namespace: gloo-system
      options:
        stagedTransformations:
          regular:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    lambdaPathExtractor:
                      header: ':path'
                      regex: '^\/test(.*)'
                      subgroup: 1
                  headers:
                    :path:
                      text: "{{ lambdaPathExtractor }}"
```
