### ISSUE TITLE
Validation error when deploying AuthConfig doc tutorial for Okta integration on 1.8

### ISSUE THREAD

**Issue by ably77** [solo-io/gloo#5272]
**Describe the requested changes**
`okta-oidc` AuthConfig example uses snake_case which results in a validation error in Gloo Edge 1.8
```
error: error validating "wrong.yaml": error validating data: [ValidationError(AuthConfig.spec.configs[0].oauth2.oidcAuthorizationCode): unknown field "app_url" in io.solo.gloo.enterprise.v1.AuthConfig.spec.configs.oauth2.oidcAuthorizationCode, ValidationError(AuthConfig.spec.configs[0].oauth2.oidcAuthorizationCode): unknown field "callback_path" in io.solo.gloo.enterprise.v1.AuthConfig.spec.configs.oauth2.oidcAuthorizationCode, ValidationError(AuthConfig.spec.configs[0].oauth2.oidcAuthorizationCode): unknown field "client_id" in io.solo.gloo.enterprise.v1.AuthConfig.spec.configs.oauth2.oidcAuthorizationCode, ValidationError(AuthConfig.spec.configs[0].oauth2.oidcAuthorizationCode): unknown field "client_secret_ref" in io.solo.gloo.enterprise.v1.AuthConfig.spec.configs.oauth2.oidcAuthorizationCode, ValidationError(AuthConfig.spec.configs[0].oauth2.oidcAuthorizationCode): unknown field "issuer_url" in io.solo.gloo.enterprise.v1.AuthConfig.spec.configs.oauth2.oidcAuthorizationCode]; if you choose to ignore these errors, turn validation off with --validate=false
```

You can fix by using snakeCase instead:
```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: okta-oidc
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: "https://glootest.com"
        callbackPath: /callback
        clientId: ABCDEFG
        clientSecretRef:
          name: okta-client-secret
          namespace: gloo-system
        issuerUrl: https://dev-ABCDEFG.okta.com/oauth2/default
        scopes:
        - email
```

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/okta/
2. https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/auth0/
3. https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/google/
4. https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/dex/

**Browser Information**
If the change isn't related to content, please include your browser version and any other relevant information 
(e.g., browser zoom) to help us reproduce docs-related bugs.

Google Chrome

**Additional context**
