### ISSUE TITLE
helm - can't override nodeSelector on additional gateway proxies

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5286]
**Describe the bug**
Given the following values:
```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        nodeSelector:
          common: 'y'
    publicGw:
      # disabled: false
      # kubeResourceOverride:
      #   spec:
      #     template:
      #       spec:
      #         nodeSelector:
      #           bdp: 'y'
      podTemplate:
        nodeSelector:
          bdp: 'y'
```

Then, the generated deployment for public-gw contains the 2 labels, instead of 1:
```yaml
     nodeSelector:
        bdp: "y"
        common: "y"
```

Also tried with `kubeResourceOverride` but got the same result.

**Additional context**
- Gloo Edge version v1.8.8
