### ISSUE TITLE
additional gateway-proxy not well rendered by Helm - service ports

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5297]
**Describe the bug**

When using additional proxies, the `Service` for the additional Proxy is missing the ports:

```yaml
gloo:
  gatewayProxies:
    gatewayProxy: # HTTP only
      service:
        httpPort: 80
        httpsFirst: false
        httpsPort: 443
        httpNodePort: 32080
        type: NodePort
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: private
        disableHttpsGateway: true
    publicGw: # HTTPS only
      #disabled: false # overwrite the "default" value in the merge step
      kind:
        deployment:
          replicas: 2
      service:
        httpPort: 80
        httpsFirst: true
        httpsPort: 443
        type: LoadBalancer
      gatewaySettings:
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: public
        disableHttpGateway: true
```

Generated Services:

```bash
helm template gloo glooe/gloo-ee --version 1.8.9 --set-string license_key=$LICENSE_KEY -f values-public-private.yaml -s charts/gloo/templates/8-gateway-proxy-service.yaml
```

```yaml
---
# Source: gloo-ee/charts/gloo/templates/8-gateway-proxy-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: gateway-proxy
  name: gateway-proxy
  namespace: default
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
spec:
  # port order matters due to this issue: https://github.com/solo-io/gloo/issues/2571
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 32080
  selector:
    gateway-proxy-id: gateway-proxy
    gateway-proxy: live
  type: NodePort
---
# Source: gloo-ee/charts/gloo/templates/8-gateway-proxy-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gloo
    gloo: gateway-proxy
    gateway-proxy-id: public-gw
  name: public-gw
  namespace: default
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
spec:
  # port order matters due to this issue: https://github.com/solo-io/gloo/issues/2571
  ports: # this is the issue because empty
  selector:
    gateway-proxy-id: public-gw
    gateway-proxy: live
  type: LoadBalancer
```

☝️ see 
```yaml
  ports: # this is the issue because empty
```

Could be related to https://github.com/solo-io/gloo/issues/4956

**Additional context**
- Gloo Edge version 1.8.9
