### ISSUE TITLE
Helm chart with custom Gateway - tricky bug with proxy names

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5298]
**Describe the bug**
Given the following deployment with 2 custom proxies, named `publicGw` and `privateGw` :

```yaml
gloo:
  gatewayProxies:
    publicGw: # HTTPS only
      disabled: false # overwrite the "default" value in the merge step
      kind:
        deployment:
          replicas: 2
      service:
        kubeResourceOverride: # workaround waiting for https://github.com/solo-io/gloo/issues/5297
          spec:
            ports:
              - port: 443
                protocol: TCP
                name: https
                targetPort: 8443
            type: LoadBalancer
      gatewaySettings:
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: public
        disableHttpGateway: true
    privateGw: # HTTP only
      disabled: false # overwrite the "default" value in the merge step
      service:
        httpPort: 80
        httpsFirst: false
        httpsPort: 443
        httpNodePort: 32080
        type: NodePort
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: private
        disableHttpsGateway: true
    gatewayProxy:
      disabled: true # disable the default gateway-proxy deployment and its 2 default GW CRs
    
```

Then the extauth, rate-limit and redis deployments will not be rendered and thus won't exist.

It looks like an issue within `_helpers.tpl`

Here:
`{{- $firstKey := keys .Values.gloo.gatewayProxies | sortAlpha | first }}`

that will sort the gateway-proxies list by name.

So if you disable the default gateway-proxy, you need to have another proxy starting with letter [a-h], ie. before `g` 

Fix is renaming `privateGw` to `corpGw` 

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.8.9
