### ISSUE TITLE
Flexible (anti-)affinity configuration in Helm chart

### ISSUE THREAD

**Issue by pmichna** [solo-io/gloo#5331]
**Is your feature request related to a problem? Please describe.**
I'd like to have more power over how (anti-)affinity is configured for gateway-proxy and extauth. Currently it is hardcoded in the extauth deployment template and gateway-proxy deployment (with a simple switch for `antiAffinity`).

**Describe the solution you'd like**
I'd like to be able to configure gateway-proxy and extauth `podAntiAffinity` and `podAffinity` without using `kubeResourceOverride` value.

**Describe alternatives you've considered**
Currently it is possible with `kubeResourceOverride` but it's not convenient considering we have`gloo.gatewayProxies.gatewayProxy.affinity` as an interface but `gloo.gatewayProxies.gatewayProxy.antiAffinity` as `bool`.

**Additional context**
I wanted to configure the following anti-affinity:
```
podAntiAffinity:
  preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchLabels:
            tags.datadoghq.com/service: *extAuthServiceName
            tags.datadoghq.com/version: *glooVersion
        topologyKey: topology.kubernetes.io/zone
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          tags.datadoghq.com/service: *extAuthServiceName
          tags.datadoghq.com/version: *glooVersion
      topologyKey: kubernetes.io/hostname
```
