### ISSUE TITLE
Gloo-ee Helm chart ratelimit registry not set for gloo-ee helm chart 1.8.13

### ISSUE THREAD

**Issue by genslein** [solo-io/gloo#5388]
To enable the `rate-limit` feature in 1.8.13, the `registry` field for the image of the deployment in the default chart `values.yaml` has to be set

**To Reproduce**
Enable rate-limit deployment in helm.

See `InvalidImage: /rate-limit-ee:1.8.13 not a proper repository`

**Expected behavior**
RateLimit deployment occurs without issue.

**Additional context**
This is solved by adding the following to the chart default `values.yaml` file:

```yaml
global:
  ...
  extensions:
    ...
    rateLimit:
      deployment:
        ...
        image:
          pullPolicy: IfNotPresent
          registry: quay.io/solo-io # This needs to be added to fix
          repository: rate-limit-ee
          tag: 1.8.13
```

- Gloo Edge version 1.8.13
- Kubernetes version v1.21.2
