### ISSUE TITLE
Gloo-ee Helm chart rateLimitBeforeAuth not enabled despite documentation 

### ISSUE THREAD

**Issue by genslein** [solo-io/gloo#5389]
To enable the `rate-limit` feature in 1.8.13, the `registry` field in the yaml has to be set

**To Reproduce**
1. in the overriding `values.yaml `
```yaml
global:
  extensions:
    rateLimit:
      beforeAuth: true
```

**Expected behavior**
`rateLimitBeforeAuth` to be set to `true`
https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/

**Additional context**

We have to re-add to the `charts/gloo-ee/templates/_helpers.tpl` the following check:

```yaml
{{- if $.Values.global.extensions.rateLimit.enabled }}
  ratelimitServer:
    rateLimitBeforeAuth: {{ .Values.global.extensions.rateLimit.beforeAuth | default "false" }} # this line here
    ratelimitServerRef:
      name: rate-limit
      namespace: {{ .Release.Namespace }}
{{- end }}
```
This was previously raised in #5015 and latest docs (v1.8.13 as of writing for gloo-ee) suggests this should be supported by the chart https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/

- Gloo Edge version 1.7.20, 1.8.13
- Kubernetes version v1.21.2

**Comment by artberger** [comment]
@genslein, for this issue, do you mean that the doc needs to be updated with a prereq step to upgrade the Helm installation for Gloo EE `values.yaml` to enable rate limiting before modifying the settings?
```yaml
global:
  extensions:
    rateLimit:
      beforeAuth: true
```
