### ISSUE TITLE
Gloo timeout setting

### ISSUE THREAD

**Issue by AlyssaBetty** [solo-io/gloo#5391]
I hava a problem about gloo's timeout,and I have looked at gloo's official documentation and found that it can set timeout in the VirtualService configuration，but i want to know  Can I set timeout globally somewhere rather than in VirtualService？

Now I set timeout is:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: 'default'
  namespace: 'gloo-system'
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
       - prefix: '/petstore'
      routeAction:
        single:
          upstream:
            name: 'default-petstore-8080'
            namespace: 'gloo-system'
      options:
        timeout: '60s'
        retries:
          retryOn: 'connect-failure'
          numRetries: 3
          perTryTimeout: '30s'
```
