### ISSUE TITLE
ExtAuth - can't use logical OR in booleanExpr with OIDC and OAuth2 config blocks

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5401]
**Describe the bug**
Given an AuthConfig having 2 config blocks.
One is type OIDC, the other one is type OAUTH2 with opaque token introspection

When the client sends a request with the client_credentials grant, triggering the access_token validation, this works 
When the client is an end-user and wants to authenticate over OIDC, then he gets a 403 without any redirection to the /auth endpoint

**To Reproduce**
```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: keycloak-oauth
  namespace: gloo-system
spec:
  booleanExpr: "oauth2 || oidc"
  #booleanExpr: ( oauth2 || oidc ) # no difference with this syntax
  configs:
  - name: oidc
    oauth2:
      oidcAuthorizationCode:
        appUrl: https://mydomain.com
        callbackPath: /callback
        clientId: ${client}
        clientSecretRef:
          name: keycloak-oauth
          namespace: gloo-system
        issuerUrl: "${KEYCLOAK_URL}/realms/master/"
        scopes:
        - email
  - name: oauth2
    oauth2:
      accessTokenValidation:
        introspection:
          clientId: ${client}
          clientSecretRef:
            name: keycloak-oauth
            namespace: gloo-system
          introspectionUrl: "${KEYCLOAK_URL}/realms/master/protocol/openid-connect/token/introspect"
```

Gist with setup and logs: https://gist.github.com/bcollard/d631506ffd9aec7430b23570ff98eae1

**Expected behavior**
Having both authentication methods to work at the same time (one or the other)

**Additional context**
- Gloo Edge version 1.8.13
- Kubernetes version
