### ISSUE TITLE
Data Loss Prevention does not work for Access Logs

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#5464]
**Describe the bug**
It seems that the Data Loss Prevention is not working for the case of access logs anymore. Not when `enabledFor: ALL` nor `enabledFor: ACCESS_LOGS`

However, i works always for `RESPONSE_BODY`.

**To Reproduce**
1. Install gloo Version: 1.8.9 through helm with values:
```
license_key: XXXX
create_license_secret: true 
gloo:
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        accessLoggingService:
          accessLog:
            - fileSink:
                stringFormat: >
                  [ACCESS_LOGS] %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
                path: /dev/stdout
```
2. Install httpbin
3. Apply following CR:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: demo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
            single:
              upstream:
                name: default-httpbin-80
                namespace: gloo-system
        options:
          autoHostRewrite: true
    options:
      transformations:
          requestTransformation:
                transformationTemplate:
                  headers:
                    x-test:
                      text: 'test7'  
      dlp:
        actions:
        - customAction:
            name: test
            regex:
            - 'secret_1'
            #- '(?<=[\&|\?]secret_1=)[^&]+'
            maskChar: "Y"
            percent:
              value: 60
        enabledFor: ALL
```
4. run
```
curl "x.x.x.x/get?x=1&secret_1=val_1&non_secert=val_3"
```
5. The output shows the update in reponse:
```
{
  "args": {
    "non_secert": "val_3",
    "YYYYYt_1": "val_1",
    "x": "1"
  },
  "headers": {
    "Accept": "*/*",
    "Host": "x.x.x.x",
    "User-Agent": "curl/7.71.1",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000",
    "X-Test": "test7"
  },
  "origin": "z.z.z.z",
  "url": "http://x.x.x.x/get?x=1&YYYYYt_1=val_1&non_secert=val_3"
}
```

In the logs you will see:
```
[ACCESS_LOGS] /get?x=1&secret_1=val_1&non_secert=val_3
```

**Expected behavior**
In the logs it should show:
```
[ACCESS_LOGS] /get?x=1&YYYYYt_1=val_1&non_secert=val_3
```

**Additional context**
Version: 1.8.9

**Comment by sam-heilbron** [comment]
@antonioberben can you re-test this with the latest version of 1.8.x (1.8.19)? There has been some recent work done to improve DLP + access logging, and I suspect his has been resolved, but want to confirm that before we close this.

**Comment by antonioberben** [comment]
@sam-heilbron , sorry it is not fixed in that version (1.8.19)

**Comment by jbohanon** [comment]
It appears from the following that this config is trying to mask a pseudo-header: 
``` yaml
                stringFormat: >
                  [ACCESS_LOGS] %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%
```

Because of how Envoy uses pseudo-headers, the plugin will not mask them. A workaround I have tested to ensure the value is masked in the access log is to use a `requestTransformation` to effectively copy the pseudo-header into a header that we can manipulate and use that in the access logs.

I have tested with this `VirtualService`:
``` yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: demo
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
            single:
              upstream:
                name: default-httpbin-80
                namespace: gloo-system
        options:
          autoHostRewrite: true
    options:
      transformations:
          requestTransformation:
                transformationTemplate:
                  headers:
                    x-test:
                      text: 'test7' 
                    x-solo-path: 
                      text: '{{ request_header(":path") }}' 
      dlp:
        actions:
        - customAction:
            name: test
            regex:
            - 'secret_1'
            maskChar: "Y"
            percent:
              value: 60
        enabledFor: ALL
```
and this format string in the gateway:
```
[ACCESS_LOGS] %REQ(X-ENVOY-ORIGINAL-PATH?X-SOLO-PATH)%
```

Note that I am on v1.9.15 because I had trouble getting a v1.8.x cluster up.
