### ISSUE TITLE
⚠️ Envoy crashing because of DLP 

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5491]
**Describe the bug**
Envoy Crashes because of valid configuration, (DLP + Transformation)

**To Reproduce**
apply the config

 
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    options:
      stagedTransformations:
        early:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - key: request_payload
                  value:
                    text: '{{ body }}'    
          responseTransforms:
          - responseTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - key: response_payload
                  value:
                    text: '{{ body }}'    


      dlp:
        actions:
        - customAction:
            maskChar: X
            name: test
            percent:
              value: 20
            regexActions:
            - regex: (.*msisdn.*:)(.*)
              subgroup: 2
            - regex: (.*espn.*:)(.*)"
              subgroup: 2
        enabledFor: ALL 
    domains:
    - '*'
    routes:
    - routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
      options:
        autoHostRewrite: true
```

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: glooe
    meta.helm.sh/release-namespace: gloo-system
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            req_payload: '%DYNAMIC_METADATA(io.solo.transformation:request_payload)%'
            res_payload: '%DYNAMIC_METADATA(io.solo.transformation:response_payload)%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  useProxyProto: false
```

**Expected behavior**
Envoy not to crash because of a valid configuration, (not to crash even if the regex is invalid) 

**Additional context**
Gloo 1.8 and 1.9
