### ISSUE TITLE
DLP not working properly With Access logs

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5492]
**Describe the bug**
when using multiple DLP to mask data in access logs, only the last match is masked

**To Reproduce**
```
      dlp:
        actions:
        - customAction:
            maskChar: X
            name: test
            percent:
              value: 80
            regexActions:
            - regex: (.*msisdn.*:)(.*)
              subgroup: 2
            - regex: (.*espn.*:)(.*)"
              subgroup: 2
        enabledFor: ACCES_LOGS
```

**Expected behavior**
To mask all the fields. 

**Additional context**
1.9
