### ISSUE TITLE
By default, gateway-proxy is causing downtime

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5494]
**Describe the bug**
With a continuous flow of 5 req/s, you are able to see connections dropped when gateway-proxy is restarted. It happens either with 1 or many replicas.

**To Reproduce**
Check video

**Expected behavior**
I expect a clean process not a single request failed, as this is already possible with some helm configuration, please set this as the **default**

**Additional context**
glooedge=1.8.0
https://github.com/solo-io/gloo/pull/3458/
https://github.com/solo-io/gloo/issues/5376

**Workaround**
```
cat <<EOF > gloo-values.yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        probes: true # not needed for shutdown
        gracefulShutdown:
          enabled: true # force the healthcheck/fail, then wait 5s, and then start shutdown
          sleepTimeSeconds: 5 # wait 5s to start shutdown
EOF
helm upgrade gloo glooe/gloo-ee -n gloo-system --values gloo-values.yaml --set="license_key=${LICENSE_KEY}" --version 1.8.0
```

https://user-images.githubusercontent.com/35881711/138437152-6b139db2-e474-4fbc-a326-b955c29f81bc.mov

**Comment by jmunozro** [comment]
These are the settings that makes it work well, without any request failing (taken from [here](https://docs.solo.io/gloo-edge/latest/operations/advanced/zero-downtime-gateway-rollout/#demo)):
```
gloo:
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          replicas: 3
      podTemplate:
        terminationGracePeriodSeconds: 7 # kill the pod after this delay, gives room to the preStop hook
        gracefulShutdown:
          enabled: true
          sleepTimeSeconds: 5 # tells Envoy to fail healthchecks and sleep 5 seconds
        probes: true
        customReadinessProbe:
          httpGet:
            scheme: HTTP
            port: 8080
            path: /envoy-hc
          failureThreshold: 2
          initialDelaySeconds: 5
          periodSeconds: 5
      # define the path for the Envoy health check filter
      gatewaySettings:
        customHttpGateway:
          options:
            healthCheck:
              path: /envoy-hc
            httpConnectionManagerSettings:
              useRemoteAddress: true
```
