### ISSUE TITLE
Rejected RouteTable prevents updates for other RouteTables on same tree

### ISSUE THREAD

**Issue by lgadban** [solo-io/gloo#5502]
**Describe the bug**
When delegating control for a given prefix to route tables via selection, if a selected RT contains a prefix mismatch, any other routes defined in selected RTs will not be processed. In other words, if a single route anywhere in the tree for a given prefix is `Rejected`, users can not update existing routes or add new routes to that node. This may prevent all updates to the VS (?) -- I haven't tested this piece, which could be even more impactful

**To Reproduce**
1. Create VS
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
       - prefix: '/foo'
      delegateAction:
        selector:
          labels:
            routes: petstore
          namespaces:
          - gloo-system
```

2. Create RT for /foo
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes-foo
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /foo
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system
```

3. Create RT with incorrect prefix
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /
    routeAction:
      single:
        upstream:
          name: default-petstore-8080
          namespace: gloo-system
```

4. Modify existing good RT to use a directResponse
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: petstore-routes-foo
  namespace: gloo-system
  labels:
    routes: petstore
spec:
  routes:
  - matchers:
    - prefix: /foo
    directResponseAction:
      status: 200
      body: "Hello, world!"
```

curl against /foo:
```
% curl localhost:8080/foo/
{"code":404,"message":"path /foo/ was not found"}
```

Should be direct response, but get routed to petstore still.

**Expected behavior**
The rejected RT should be sanitized/removed and other updates from other RTs should work fine.

**Additional context**
GlooE 1.8.15
