### ISSUE TITLE
Prohibit delegated resources (e.g. RouteTables) to override WAF rules 

### ISSUE THREAD

**Issue by rinormaloku** [solo-io/gloo#5507]
**The problem**

Add the ability for VirtualServices (and HttpGateway's) to prohibit overriding of WAF rules to delegated resources. 

**Why would you want to do that?**
Adding that capability enables Ops to enforce policies such as an IP allowlist, but as it stands tenants managing the RouteTable can easily override those and in such a way disable the allowlist entirely.

<details><summary>Sample resources:</summary>

```
---
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  proxyNames:
  - gateway-proxy
  httpGateway:
    options:
      waf:
        customInterventionMessage: 'ModSecurity intervention!'
        ruleSets:
        - ruleStr: |
            # Turn rule engine on
            SecRuleEngine On
            SecRule REQUEST_HEADERS:User-Agent "scammer" "deny,status:403,id:107,phase:1,msg:'blocked scammer'"
  useProxyProto: false
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: team1-httpbin-80
            namespace: gloo-system
    options:
      waf:
        customInterventionMessage: 'ModSecurity intervention!'
        ruleSets:
        - ruleStr: |
            # Turn rule engine on
            SecRuleEngine On
            SecRule REQUEST_HEADERS:User-Agent "vsscammer" "deny,status:403,id:107,phase:1,msg:'blocked scammer'"
```

If we make a request with the header **scammer**, it will be allowed, because that is overriden by the VirtualService (despite being forbidden by the HttpGateway)

curl -v -H 'user-agent: vsscammer' $(glooctl proxy url)/
</details>

How we imagine this could work:

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  proxyNames:
  - gateway-proxy
  httpGateway:
    options:
      waf:
        overridable: false                                        (1)
        customInterventionMessage: 'ModSecurity intervention!'
        ruleSets:
        - ruleStr: |
            # Turn rule engine on
            SecRuleEngine On
            SecRule REQUEST_HEADERS:User-Agent "scammer" "deny,status:403,id:107,phase:1,msg:'blocked scammer'"
  useProxyProto: false
```
(1) Setting overridable to false, disables lower level resources from overriding this waf rule
