### ISSUE TITLE
Prometheus port in gloo-fed is wrong (9091 -> 8080)

### ISSUE THREAD

**Issue by jmunozro** [solo-io/gloo#5528]
**Describe the bug**
Error in the chart template `gloo-fed-deployment.yaml`, the annotation `prometheus.io/port` is set on port 9091 but the metrics are available on port 8080 instead

**To Reproduce**
1. kubectl port-forward deployment/gloo-fed 9999:9091 -n gloo-system
2. curl localhost:9999/metrics <---------------fails
3. kubectl port-forward deployment/gloo-fed 9999:8080 -n gloo-system
4. curl localhost:9999/metrics <---------------works

**Expected behavior**
```
spec:
  selector:
    matchLabels:
      app: gloo-fed
  template:
    metadata:
      labels:
        app: gloo-fed
      annotations:
        prometheus.io/path: /metrics
-        prometheus.io/port: "9091"
+        prometheus.io/port: "8080" 
        prometheus.io/scrape: "true"
```

**Additional context**
- Gloo Edge 1.9
