### ISSUE TITLE
http passthrough response not having an header declared in response.allowedUpstreamHeaders

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5542]
**Describe the bug**
Given an HTTP passthrough response not having an expected header as declared in response.allowedUpstreamHeaders
Then an empty string header is added to the request going upstream
`"": ""`

**Workaround**
Delete that non conventional header with a transformation after extauth:
```
options:
  stagedTransformations:
    regular:
      requestTransform:
      - requestTransformation:
          transformationTemplate:
            headers:
              "": ""  
```

**Expected behaviour**
If the header is not present in the extauth response, then don't create an empty string header

**Additional context**
- Gloo Edge version 1.9

**Comment by sam-heilbron** [comment]
@bcollard can you also include relevant config to reproduce this?

**Comment by Ati59** [comment]
Intermax is hitting this too.

To reproduce, you just have to create a passthrough `AuthConfig`, add a `allowedUpstreamHeaders` and you don't returned it as excepted (request or passthrough).

For example, I used this code (`auth-service` is a simple python app I use for passthrough debugging purpose) :
```
kubectl apply -f - <<EOF
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: passthrough-auth
  namespace: gloo-system
spec:
  configs:
  - passThroughAuth:
      http:
        url: http://auth-service.gloo-system.svc.cluster.local:80
        connectionTimeout: 3s
        request:
          passThroughState: true
          allowedHeaders:
            - access_token
            - id_token
        response:
          allowedUpstreamHeaders:
          - "my-dummy-header"
EOF
```

The curl on httpbin get page returned the value `"": ""` (and PHP does not like it in the intermax case) :
<img width="872" alt="image" src="https://user-images.githubusercontent.com/35342300/211535287-51f4f93b-4267-41a0-9165-f2c7bc9a67af.png">
