### ISSUE TITLE
Defined fsGroup is breaking installations of gloo-edge on OpenShift

### ISSUE THREAD

**Issue by nickschuetz** [solo-io/gloo#5596]
When doing an install via `glooctl install gateway --values os-values.yaml -v` where the values are:

```
 gloo:
  deployment:
    floatingUserId: true
discovery:
  deployment:
    floatingUserId: true
    fsGroup: null
gateway:
  certGenJob:
    floatingUserId: true
  deployment:
    floatingUserId: true
    fsGroup: null
gatewayProxies:
  gatewayProxy:
    podTemplate:
      floatingUserId: true
      disableNetBind: true
      runUnprivileged: true
      fsGroup: null
```

(Note that I realize that in `fsGroup: false` boolean is not an appropriate value but it works to remove fsGroup under these objects for some reason. Perhaps a bug in itself. This same behavior does not manifest under gatewayProxies.gatewayProxy.podTemplate)

I get the following error from the gateway-proxy pod when deployed inside of OpenShift:

```
0s          Warning   FailedCreate           replicaset/gateway-proxy-69f96b65cb   Error creating: pods "gateway-proxy-69f96b65cb-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{0}: 0 is not an allowed group, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]

```

**To Reproduce**
1. Install OpenShift Container Platform 4.9.5 cluster on AWS via IPI
2.  `glooctl install gateway --values os-values.yaml -v` where the values are:

```
 gloo:
  deployment:
    floatingUserId: true
discovery:
  deployment:
    floatingUserId: true
    fsGroup: null
gateway:
  certGenJob:
    floatingUserId: true
  deployment:
    floatingUserId: true
    fsGroup: null
gatewayProxies:
  gatewayProxy:
    podTemplate:
      floatingUserId: true
      disableNetBind: true
      runUnprivileged: true
      fsGroup: null
```

**Expected behavior**
A clean install of gloo-edge on OpenShift without scc issues.

**Additional context**
Add any other context about the problem here, e.g.
- Gloo Edge version 1.9.1
# oc version
Client Version: 4.9.5
Server Version: 4.9.5
Kubernetes Version: v1.22.0-rc.0+a44d0f0

If we could get the fsGroup equivalent to `floatingUserId: true` that essentially removes fsGroup from the helm values that would be ideal.
