### ISSUE TITLE
OIDC - improve UX with the UserInfo endpoint

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5600]
**Is your feature request related to a problem? Please describe.**
We have seen a few use cases where the client needs to call the UserInfo endpoint after the OIDC flow. This endpoint usually returns more claims than what is returned during the initial OIDC flow. Today, to do that, you need an additional config step in your AuthConfig CR like the following:

```yaml
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        ...
  - oauth2:
      accessTokenValidation:
        userinfoUrl: ... # note that UserInfo has nothing to do in this place. It is part of the OIDC RFC, so it should be above
```

**Describe the solution you'd like**
- have the `userinfoUrl` as a new option under `oidcAuthorizationCode`, so that this additional callout can be performed by the ExtAuth server after the code exchange, with the `access_token`
- perhaps also keep it where it is today for backward compatibility 

**Additional context**
Gloo Edge 1.9.2
