### ISSUE TITLE
Doc update for OpenShift installation guide

### ISSUE THREAD

**Issue by artberger** [solo-io/gloo#5619]
**Describe the requested changes**
Based on Nick's testing, and following values from Dennis. Update the following:
* `glooctl install` section for OpenShift
* Helm values
* [Blog](https://www.solo.io/blog/from-zero-to-gloo-edge-in-15-minutes-amazon-openshift-edition/), see discussion in Slack: https://solo-io-corp.slack.com/archives/CHJV572TG/p1637768281130000

Potentially wait until after https://github.com/solo-io/gloo/issues/5596 ?

Gloo EE
```yaml
global:
  extensions:
    extAuth:
      deployment:
        floatingUserId: true
        fsGroup: ""
    rateLimit:
      deployment:
        floatingUserId: true
oberservability:
  deployment:
    floatingUserId: true
redis:
  deployment:
    floatingUserId: true
    enablePodSecurityContext: false
gloo:
  gloo:
    deployment:
      floatingUserId: true
  discovery:
    deployment:
      floatingUserId: true
      enablePodSecurityContext: false
  gateway:
    deployment:
      floatingUserId: true
    certGenJob:
      floatingUserId: true
  oberservability:
    deployment:
      floatingUserId: true
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        floatingUserId: true
        enablePodSecurityContext: false
gloo-fed:
  enabled: false
  glooFedApiserver:
    floatingUserId: true
prometheus:
  enabled: false
grafana:
  defaultInstallationEnabled: false
```

Gloo OSS
```yaml
gloo:
  deployment:
    floatingUserId: true
discovery:
  deployment:
    floatingUserId: true
    enablePodSecurityContext: false
gateway:
  deployment:
    floatingUserId: true
  certGenJob:
    floatingUserId: true
oberservability:
  deployment:
    floatingUserId: true
gatewayProxies:
  gatewayProxy:
    podTemplate:
      floatingUserId: true
      enablePodSecurityContext: false
```

**Link to any relevant existing docs**
1. https://docs.solo.io/gloo-edge/latest/installation/platform_configuration/cluster_setup/#openshift
2. Internal Slack thread: https://solo-io-corp.slack.com/archives/CHJV572TG/p1637623375115900
