### ISSUE TITLE
Provide Helm Chart Overrides 

### ISSUE THREAD

**Issue by chrisgaun** [solo-io/gloo#5622]
- Provide helm chart overrides for all images so that they can be redirected to a local registry.  (currently busybox and jimmydyson missing)
  - Global override should work with
  ```
  quay.io/solo-io/gloo-fed-apiserver:1.9.2,
  quay.io/solo-io/gloo-federation-console:1.9.2,
  quay.io/solo-io/gloo-fed-apiserver-envoy:1.9.2
  grafana/grafana:8.2.1
  quay.io/coreos/kube-state-metrics:v1.9.7
  jimmidyson/configmap-reload:v0.5.0,
  quay.io/prometheus/prometheus:v2.24.0
  busybox:1.28
  ```

**Comment by sam-heilbron** [comment]
We support defining a global registry in the helm chart: https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/values-template.yaml#L85

Templates define images using a gloo helper: https://github.com/solo-io/solo-projects/blob/master/install/helm/gloo-ee/templates/2-rate-limit-deployment.yaml#L51

https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/_helpers.tpl#L22

**Comment by jenshu** [comment]
The fix will be available in gloo-ee v1.10.0-beta4

Here is an example of how to override all of the images used in a default gloo-ee install. Note that the prometheus and grafana values expect the registry and repository to be combined in one field `<registry>/<repository>`.

```
helm install -n gloo-system gloo-ee gloo-ee/gloo-ee --set-string license_key=$GLOO_LICENSE_KEY -f - <<EOF
global:
  image:
    registry: MY_REGISTRY
  extensions:
    rateLimit:
      deployment:
        image:
          repository: MY_REPO
          tag: MY_TAG
    extAuth:
      deployment:
        image:
          repository: MY_REPO
          tag: MY_TAG
gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        image:
          repository: MY_REPO
          tag: MY_TAG
  gloo:
    deployment:
      image:
        repository: MY_REPO
        tag: MY_TAG
  discovery:
    deployment:
      image:
        repository: MY_REPO
        tag: MY_TAG
  gateway:
    deployment:
      image:
        repository: MY_REPO
        tag: MY_TAG
    certGenJob:
      image:
        repository: MY_REPO
        tag: MY_TAG
observability:
  deployment:
    image:
      repository: MY_REPO
      tag: MY_TAG
redis:
  deployment:
    image:
      registry: MY_REGISTRY
      repository: MY_REPO
      tag: MY_TAG
    initContainer:
      image:
        registry: MY_REGISTRY
        repository: MY_REPO
        tag: MY_TAG
prometheus:
  configmapReload:
    prometheus:
      image:
        repository: MY_REGISTRY/MY_REPO
        tag: MY_TAG
  kube-state-metrics:
    image:
      repository: MY_REGISTRY/MY_REPO
      tag: MY_TAG
  server:
    image:
      repository: MY_REGISTRY/MY_REPO
      tag: MY_TAG
grafana:
  image:
    repository: MY_REGISTRY/MY_REPO
    tag: MY_TAG
gloo-fed:
  glooFed:
    image:
      repository: MY_REPO
      tag: MY_TAG
  glooFedApiserver:
    image:
      repository: MY_REPO
      tag: MY_TAG
    envoy:
      image:
        repository: MY_REPO
        tag: MY_TAG
    console:
      image:
        repository: MY_REPO
        tag: MY_TAG
EOF
```

To override only the registry and leave the default values for the repository and tag names, use:

```
helm install -n gloo-system gloo-ee gloo-ee/gloo-ee --set-string license_key=$GLOO_LICENSE_KEY -f - <<EOF
global:
  image:
    registry: MY_REGISTRY
redis:
  deployment:
    image:
      registry: MY_REGISTRY
    initContainer:
      image:
        registry: MY_REGISTRY
prometheus:
  configmapReload:
    prometheus:
      image:
        repository: MY_REGISTRY/configmap-reload
  kube-state-metrics:
    image:
      repository: MY_REGISTRY/kube-state-metrics
  server:
    image:
      repository: MY_REGISTRY/prometheus
grafana:
  image:
    repository: MY_REGISTRY/grafana
EOF
```
