### ISSUE TITLE
Enterprise helm chart incorrectly emits istio-proxy image spec under tolerations

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#5665]
**Describe the bug**
The Gloo Edge Enterprise 1.9.4 helm chart incorrectly emits istio-proxy image spec under `tolerations`.

**To Reproduce**
1. Unpack attached [istio-proxy-helm-bug.tar.gz](https://github.com/solo-io/gloo/files/7644652/istio-proxy-helm-bug.tar.gz)
2. `helm template gloo-ee --version v1.9.4  glooe/gloo-ee --namespace gloo-system --set-string license_key=$GLOO_KEY --values ./values1.yaml --values ./values2.yaml`
3. See `istio-proxy` incorrectly generated as part of `tolerations` list. 
```
      nodeSelector:
        node-group: "nyti"
      tolerations:
      - effect: NoSchedule
        key: nodeService
        operator: Equal
        value: nyti
      - name: istio-proxy
        image: docker.io/istio/proxyv2:1.9.5
        args:
```

**Expected behavior**
Valid yaml is generated

**Additional context**
- Gloo Edge Enterprise version 1.9.4
- Internal conversation: https://solo-io.slack.com/archives/C02C7U3K2HF/p1638471862053700
