### ISSUE TITLE
Mixed JSON format

### ISSUE THREAD

**Issue by chrisgaun** [solo-io/gloo#5689]
The WAF space delimited logs are appended to end of JSON which makes it hard to parse in centralize logging tools like Datadog. 

Would like to use JSON logs instead of space delimited.

**Comment by ben-taussig-solo** [comment]
To me it seems likely that this is caused by an improperly specified formatting string. For example, the following format string will format JSON values in the modsecurity audit log properly:

```yaml
...
jsonFormat:
  waf: "%DYNAMIC_METADATA(io.solo.filters.http.modsecurity:audit_log)%"
```

whereas this format string (note the stray `\n`):

```yaml
...
jsonFormat:
  waf: "%DYNAMIC_METADATA(io.solo.filters.http.modsecurity:audit_log)%\n"
```

will mangle JSON formatted audit logs.

Do we have more information about the configuration that was used when this issue came up?
