### ISSUE TITLE
TLS in Kube Ingress not working

### ISSUE THREAD

**Issue by christian-posta** [solo-io/gloo#570]
If you try create a Kube extensions/v1beta1 Ingress resource with TLS defined, it is not picked up correctly and assigned to the TLS/8443 listener in the `ingress-proxy`. To test it out, deploy petstore app with this ingress:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: petstore-ingress
 namespace: default
 annotations:
    kubernetes.io/ingress.class: gloo
spec:
 tls:
  - hosts:
    - foo.bar.com
    secretName: gateway-tls
 rules:
 - http:
     paths:
     - path: /.*
       backend:
         serviceName: petstore
         servicePort: 8080
```

**Comment by christian-posta** [comment]
@rickducott @rettori @ilackarms

**Comment by mitchdraft** [comment]
@christian-posta I checked in with `The Scotts` (@scranton and @ilackarms )
in order for the ssl config to be applied, when you specify a host in the tls `spec`, you need to include it in the `rules`
I updated your config and this worked:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: petstore-ingress
 namespace: default
 annotations:
    kubernetes.io/ingress.class: gloo
spec:
 tls:
  - hosts:
    - foo.bar.com
    secretName: gateway-tls
 rules:
 - host: foo.bar.com
   http:
     paths:
     - path: /.*
       backend:
         serviceName: petstore
         servicePort: 8080
```
