### ISSUE TITLE
Increase use of envoy validate mode in control plane

### ISSUE THREAD

**Issue by kdorosh** [solo-io/gloo#5720]
**Is your feature request related to a problem? Describe the solution you'd like.**
We use envoy's validate mode to validate our inja transformations as part of the translation loop [here](https://github.com/solo-io/gloo/blob/v1.10.0-beta11/projects/gloo/pkg/bootstrap/bootstrap_validation.go#L51). The feature request here is to expand the usage of envoy validation mode to validate all envoy config, rather than just inja transformations. This can provide better safeguards for users from pushing bad config.

The feature request here is to expand the usage of envoy validation mode to validate all envoy config, rather than just inja transformations. This can provide better safeguards for users from pushing bad config.

**Describe alternatives you've considered**

* improve xds-relay functionality to only cache accepted config
  * this would also require an envoy sidecar running in validate mode to confirm config before caching
* in this case, we could also add simple protections from secrets with single `%` in the control plane, which would have prevented the customer issue in config similar to:

```yaml
          headerManipulation: # after api-key auth plugin, we replace the header with an Advisor token
            requestHeadersToAdd:
            - headerSecretRef:
                name: advisor-header
                namespace: gloo-system
              append: false
```

**Additional context**
Initial PR implementation: https://github.com/solo-io/gloo/pull/2827
Feature flag to disable: https://github.com/solo-io/gloo/pull/4520

Calling out to envoy several times out of process is expensive, and we should work to minimize how often we do this. We can leverage two options to improve the performance here:

1. batch more config together at once to validate (can make error messages harder to debug)
1. cache results of previous validations, and don't re-run (taking care to re-run if envoy upgrades/changes)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206681874205238/1208506373798672) by [Unito](https://www.unito.io)
