### ISSUE TITLE
Ensure Gloo Edge is reliable across all pod restarts and invalid configuration

### ISSUE THREAD

**Issue by saiskee** [solo-io/gloo#5721]
**Is your feature request related to a problem? Please describe.**
xDS relay currently only ensures HA for the gloo control plane, but in the case where gloo control plane serves bad config, xDS relay will continue to serve the bad config, even if envoy rejects it. 

**Describe the solution you'd like**
Add a mode to xds-relay where it caches only good config. Not sure about all the implementation details here, but essentially if there is a nack from gateway proxy, xDS relay doesn't cache that config.

We would need to make sure we still keep track of when gloo is trying to serve bad config. Because if we do implement this "serve good config only" mode in xDS relay and gloo serves bad config,  we have to make sure that xDS propogates back the NACKs to the gloo pod from envoy but continues to serve the latest good config only.

**Comment by chrisgaun** [comment]
Related to 1 here https://github.com/solo-io/gloo/issues/5720

**Comment by EItanya** [comment]
> Related to 1 here #5720

Yes and no. The implementation in #5720 is slow because it calls out to an external binary, but we can accomplish this using the NACK capability of `xDS`.

**Comment by kdorosh** [comment]
I believe this logic should live in gloo itself rather than xds relay; xds relay should be as simple as possible since any bugs there affect our HA control plane story

**Comment by kdorosh** [comment]
assumption: most of recent reported user-issues are because of problems that can be resolved by single resource validation or by restoring a missing cluster / route

if so, the fix:
- [`validate_clusters`](https://www.envoyproxy.io/docs/envoy/v1.21.1/api-v3/config/route/v3/route.proto#envoy-v3-api-msg-config-route-v3-routeconfiguration) ensure validate clusters is false  (on for static by default, turn off by default for dynamic clusters)
- validate indiviudal resources in control plane during translation using envoy mode validate
- potentially create `validate_cluster`-esque field for LDS
  - make sure upstream filters and our filters do not NACK if dynamic resource (e.g. cluster) is not present; make sure cluster is nullable. i.e., no NACK from filters if dynamic resource is missing (e.g. router filter [does this](https://github.com/envoyproxy/envoy/blob/0d492f3a80e32f3b3e1a2f0cb3ca98eb24676315/source/common/router/router.cc#L458))

Other versioning proposals rejected:
- on LDS NACK: persist last LDS and revert RDS/CDS deletions to this point. risky if route added back is dangerous
- on RDS NACK: persist last RDS and revert CDS deletions to this point. pretty safe
- overall more involved, may not need to do this
- assumes EDS is pretty safe

We can also explore persisting last known good configuration to a file or database so it outlives a pod restart; although the top solution is preferable because it would prevent (in theory) bad resources from ever being written to etcd and then having envoy NACK the translated configuration

**Comment by kdorosh** [comment]
Example set of steps to reproduce one invalid issue (upstream sanitizer can prevent?):

- `kind create cluster --name kind --image kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6`
- apply petstore `kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml`
- `glooctl install gateway --version 1.10.17`
- `kubectl scale -n gloo-system deploy/discovery --replicas 0` (discovery will update / delete upstreams when we add and remove the backing k8s services later)
- apply initial valid yaml:
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /all-pets
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-petstore-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      service: petstore
  kube:
    selector:
      app: petstore
    serviceName: petstore
    serviceNamespace: default
    servicePort: 8080
```
- confirm we can curl using `kubectl port-forward -n gloo-system deploy/gateway-proxy 8080` and `curl -v localhost:8080/all-pets`
- apply the following valid yaml:
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /all-pets
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
    - matchers:
      - exact: /all-pets2
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore2-8080
            namespace: gloo-system
---
apiVersion: v1
kind: Service
metadata:
  name: petstore2
  namespace: default
  labels:
    service: petstore2
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: petstore
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-petstore2-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      service: petstore2
  kube:
    selector:
      app: petstore2
    serviceName: petstore2
    serviceNamespace: default
    servicePort: 8080
```
- confirm both curls work
- delete the petstore 2 svc (k8s webhook cannot stop us from doing this! --> further, consul or other backend could also disappear) `kubectl delete svc petstore2`
- only the original curl works now, new one returns 503 (expected). Gloo is now in error state (bad upstream, can no longer reconcile and update xds cache)
- apply the following yaml
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /all-pets
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
    - matchers:
      - exact: /all-pets2
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore2-8080
            namespace: gloo-system
    - matchers:
      - exact: /all-pets3
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore3-8080
            namespace: gloo-system
---
apiVersion: v1
kind: Service
metadata:
  name: petstore3
  namespace: default
  labels:
    service: petstore3
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: petstore
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-petstore3-8080
  namespace: gloo-system
spec:
  discoveryMetadata:
    labels:
      service: petstore3
  kube:
    selector:
      app: petstore3
    serviceName: petstore3
    serviceNamespace: default
    servicePort: 8080
```
if kube service 2 hadn't been deleted, this would be valid. This should be accepted and persisted but is not due to translation errors.
