### ISSUE TITLE
DLP not working with Access Logs (Headers Printing)

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#5807]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

When printing a header using AccessLogs, the DLP doesn't mask the sensitive data
Let's say I have a header ssn, I want to mask most of the ssn when printing in the access logs 
```
              ssn: '%REQ(ssn)%'
```              

### Steps to reproduce the bug

```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  proxyNames:
  - gateway-proxy
  useProxyProto: false
  options:
    accessLoggingService:
      accessLog:
        - fileSink:
            path: /dev/stdout
            jsonFormat:
              protocol: "%PROTOCOL%"
              duration: "%DURATION%"
              upstreamCluster: "%UPSTREAM_CLUSTER%"
              upstreamHost: "%UPSTREAM_HOST%"
              authorization: '%REQ(authorization)%'

---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - routeAction:
        single:
          upstream:
            name: json-upstream
            namespace: gloo-system
      options:
        autoHostRewrite: true
    options:
      dlp:
        actions:
            - customAction:
                maskChar: "X"
                name: test   # only used for logging
                percent:
                  value: 80  # % of regex match to mask
                regexActions:
                - regex: '(.*ssn.*:)(.*)'
                  subgroup: 2
            - customAction:
                maskChar: "X"
                name: auth   # only used for logging
                percent:
                  value: 80  # % of regex match to mask
                regexActions:
                - regex: '(.*authorization.*:)(.*)'
                  subgroup: 2                                  
        enabledFor: ALL



```

### Expected Behavior

mask the headers printing

**Comment by chrisgaun** [comment]
Related to this issue https://github.com/solo-io/gloo/issues/5492

**Comment by jameshbarton** [comment]
Related to #5464

**Comment by ben-taussig-solo** [comment]
It appears that this issue may be caused by a misconfiguration

The regexActions specified on the virtual host in this example attempt to match on both the *key and value* of a key/value pair.

E.G., the SSN action looks for the literal `ssn`, followed by a `:`, and will redact anything on the line following that. This works to mask sensitive values in the response body from the JSON upstream configured in the example, because the entire key-value pair is present in the response. I.E., if you do
`curl localhost:8080/ssn/123-45-6789`, the unmasked response body will be `{"ssn": "123-45-6789"}`, which matches the ssn regex.

The issue is that when applied to dynamic metadata/access logs/request headers/response headers, DLP only matches against the *value* of the relevant key/value pair (see relevant snippet for dynamic metadata/access log masking [here](https://github.com/solo-io/envoy-gloo-ee/blob/master/source/extensions/filters/http/transformation_ee/dlp_transformer.cc#L220-L229). The masking for request/response headers is just above.). E.G., in the case where you do `curl localhost:8080 -H "ssn:123-45-6789"`, the DLP filter only matches against `123-45-6789`, which will not match the regex specified in the example. If instead you specify something like:

```yaml
- customAction:
    maskChar: "X"
    name: test   # only used for logging
    percent:
        value: 80  # % of regex match to mask
    regexActions:
    - regex: "(\\D|^)([0-9]{3}\\-[0-9]{2}\\-[0-9]{4})(\\D|$)"
        subgroup: 2
```

which will match just the literal SSN, access logs will redact the SSN header:

```json
{
    "protocol": "HTTP/1.1",
    "authorization": null,
    "duration": 66,
    "upstreamCluster": "json-upstream_gloo-system",
    "ssn": "XXX-XX-XX89",
    "upstreamHost": "142.250.65.243:80"
}
```
