### ISSUE TITLE
Convert all ClusterRoles when setting global.glooRbac.namespaced=true

### ISSUE THREAD

**Issue by havard-fjaer** [solo-io/gloo#5808]
### Version

1.9.x

### Is your feature request related to a problem? Please describe.

I work in an enterprise environment with Kubernetes clusters shared between many teams and applications. These are strictly separated with namespaces, so I have been asked to configure Gloo so it will be installed with namespaced Roles instead of global ClusterRoles.

By setting `global.glooRbac.namespaced=true` I am able to move most ClusterRoles into a namespace as Roles, however I'm still left with two roles that remain as ClusterRoles: `gloo-gateway-secret-create-vwc-update` and `gloo-console`.

### Describe the solution you'd like

If possible, I would like all ClusterRoles to be moved into the namespace as Roles when setting `global.glooRbac.namespaced=true`

### Describe alternatives you've considered

We handle the Helm files manually after they are generated, so we are able to do this change by hand in the .yaml files, but consider this to be to "dirty" and not very manintanable. Also, the consequences of doing a hack like this are unclear.

### Additional Context

These are our Helm values in their entirety:

```
gloo:
  gloo:
    deployment:
      floatingUserId: true
  discovery:
    deployment:
      floatingUserId: true
      enablePodSecurityContext: false
  gateway:
    deployment:
      floatingUserId: true
    certGenJob:
      floatingUserId: true      
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        floatingUserId: true
        enablePodSecurityContext: false
      service:
        type: ClusterIP
  ingress:
    deployment:
      floatingUserId: true
  ingressProxy:
    deployment:
      floatingUserId: true
gloo-fed:
  enabled: false
  glooFedApiserver:
    floatingUserId: true
redis:
  deployment:
    floatingUserId: true
    enablePodSecurityContext: false
grafana:
  defaultInstallationEnabled: false
prometheus:
  enabled: false
rateLimit:
  enabled: true
  deployment:
    floatingUserId: true
observability:
  enabled: true
  deployment:
    floatingUserId: true	    
global:
  glooRbac:
    namespaced: true
  extensions:
      extAuth:
        deployment:
          floatingUserId: true
      rateLimit:
        deployment:
          floatingUserId: true
```
