### ISSUE TITLE
Helm - wrong indentation for custom HTTPS Gateway 

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5874]
### Gloo Edge Version

1.11.x (beta)

### Kubernetes Version

1.23.x

### Describe the bug

Helm - wrong indentation for custom HTTPS Gateway 

### Steps to reproduce the bug

```
gloo:
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        customHttpsGateway:
          options:
            httpConnectionManagerSettings:
              useRemoteAddress: true
```

### Expected Behavior

correct indent
