### ISSUE TITLE
TLS secrets not being created/converted properly

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#5889]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

`glooctl create secret tls` is incorrectly creating k8s secrets with type `Opaque` rather than `kubernetes.io/tls`. 

Additionally, due to recent changes to accept opaque header secrets, opaque k8s TLS secrets are no longer being converted back to Gloo secrets correctly.

This bug affects gloo `v1.10.5`, and `v1.11.0-beta7` and later

### Steps to reproduce the bug

Create a secret:
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
   -keyout tls.key -out tls.crt -subj "/CN=petstore.example.com"

glooctl create secret tls --name test1 --certchain tls.crt --privatekey tls.key
```

The glooctl output is:
```
+--------+---------+
| SECRET |  TYPE   |
+--------+---------+
| test1  | unknown |
+--------+---------+
```

Expected output is:
```
+--------+------+
| SECRET | TYPE |
+--------+------+
| test1  | TLS  |
+--------+------+
```

Apply VS and upstream that uses the secret:
```
k apply -f - << EOF
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: json-upstream
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: test1
      namespace: gloo-system
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-static
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo'
    routes:
      - matchers:
         - prefix: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
EOF
```

Running `glooctl check` shows an error on the upstream:
```
name:"test1"  namespace:"gloo-system" is not a TLS secret`
```

Expected: `glooctl check` should pass

### Expected Behavior

There are two things that should be fixed:
- `glooctl create secret` should create the k8s secret with the correct type (`kubernetes.io/tls`)
- gloo should still be able to process previously-created Opaque TLS secrets
