### ISSUE TITLE
Request transformation matching x-user-id

### ISSUE THREAD

**Issue by jad-solo** [solo-io/gloo#5904]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

We are currently using the AuthConfig (http Auth2, using token introspection) which is working well. We want to implement a transformation that passes a new header field to upstream based on x-user-id value. Gloo edge by default implements an envoy filter that removes x-user-id so the transformation is not working. The transformation is working when matching on a different header field. 

### Describe the solution you'd like

We need the capability to disable removing x-user-id. 

### Describe alternatives you've considered

None

### Additional Context

None

**Comment by jad-solo** [comment]
Adding the vs config for reference.

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs-name
  namespace: gloo-system
spec:
  virtualHost:
    options:
      stagedTransformations:
        inheritTransformation: true
        regular:
          requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  headers:
                    x-user-id2:
                      text: '{% if header("x-user-id2") == "000" %}{{ header("x-tenant-id") }}{% else %}{{ header("x-user-id2") }}{% endif %}'
                      #text: '{% if header("x-user-id") == "sys" %}{{ header("x-tenant-id")} }{% else %}{{ header("x-user-id") }}{% endif %}'
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: test-service-80
            namespace: gloo-system
```

**Comment by sam-heilbron** [comment]
The enterprise ext-auth-service implements certain protocols that gather user information that needs to be sent to upstream processes. Therefore, the server can be configured to set the user identifier as a header (https://github.com/solo-io/ext-auth-service/blob/04e5d38c2e188637234e4d2b1c4e15fff8c3da54/pkg/service/extauth.go#L155) and optionally emit the user metadata as metadata (https://github.com/solo-io/ext-auth-service/blob/04e5d38c2e188637234e4d2b1c4e15fff8c3da54/pkg/service/extauth.go#L172)

For the header support, we need to ensure that the header we use to pass user information to the upstream service is empty. To enable this, we support defining the header you want to use to pass (https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto#L105), this will default to `x-user-id`. Also, we ensure that that header is sanitized before being sent to the extauth service (Pr that introduced this: https://github.com/solo-io/solo-projects/pull/325)

Given that the extauth service sanitizes and sets the `x-user-id` (or some configurable) header, we have a couple of options to propagate the `x-user-id` to an upstream:

1. We could use an early stage transformation, to ensure that we can pull the value of the `x-user-id` and set it to a new header, before the request is processed by the extauth filter. This is available in our product today. https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/transformations/.

@asayah generated the following configuration to demonstrate this:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: bookinfo-vs
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
  virtualHost:
    domains:
    - '*'
    options:
      extauth:
        configRef:
          name: keycloak-oauth
          namespace: gloo-system

      stagedTransformations:
        early:
          requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  headers:
                    x-something-id:
                      text: '{% if header("x-user-id") == "000" %}{{ header("x-tenant-id") }}{% endif %}'
        regular:
          requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  headers:
                    x-something-id:
                      text: '{% if header("x-something-id") %}{{ header("x-something-id") }} {% else %}{{ header("x-user-id")}}{% endif %}'                      
  
    routes:
    - matchers:
      - prefix: /
      routeAction:
        multi:
          destinations:
          - destination:
              upstream:
                name: default-httpbin-8000
                namespace: gloo-system
            weight: 10
```

2. If the above solution is not desirable, we would need to expose some configuration allowing users to opt-out of the header sanitization behavior of the extauth service. There are further considerations when implementing this, so it would be preferable if we could leverage option 1 if possible .
