### ISSUE TITLE
The JWT option on VirtualService cannot anymore be disabled at the route level

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#5917]
### Gloo Edge Version

1.10.x (latest stable)

### Describe the bug

Given a JWT verification configured at the VirtualService level
and a route with JWT option disabled
then the request matching this route is still subject to JWT validation
Also, the JWT option at the VS level is using `claimsToHeader`, so might be related to the filter flow when clear route cache is used.

Works as expected until Gloo EE version `1.10.0-beta8`
It doesn't work anymore since Gloo EE version `1.10.0-rc1`

### Steps to reproduce the bug

see the full test in this gist: https://gist.github.com/bcollard/75be986596bc9c6c9b066e14ae31d5bd

### Expected Behavior

no JWT verification on the route where JWT is disabled

**Comment by ben-taussig-solo** [comment]
Update: 
 - This issue appears to be the result of changes to the behavior of the `extensions.filters.http.jwt_authn.v3.JwtRequirement` filter in Envoy v1.20.0. Unfortunately, these changes are not, as far as we can tell, listed in the v1.20.0 changelog and we have yet to identify them.
   - Essentially, as of envoy v1.20.0/solo-projects v1.10.0-rc1, the envoy [`JwtRequirement`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto.html?highlight=allow_missing#extensions-filters-http-jwt-authn-v3-jwtrequirement) filter's [`allow_missing_or_failed`](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/jwt_authn/v3/config.proto.html?highlight=allow_missing#envoy-v3-api-field-extensions-filters-http-jwt-authn-v3-jwtrequirement-allow-missing-or-failed) setting now must be enabled in order to allow JWT verification to be disabled on a specific route.
 -  For now, you may be able to work around the issue by setting `virtualHost.options.jwtStaged.beforeExtAuth.allowMissingOrFailedJwt` to true.

**Comment by kevin-shelaga** [comment]
The proposed workaround would open all routes to allow a missing or failed jwt, which is not ideal for my use case.

**Comment by ben-taussig-solo** [comment]
Some clarification -- the JWT filter can be disabled at route level when the route specifies a `routeAction`. Take, for example, the following virtual service configured with the other resources present in the gist linked in the original issue:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers: # the end-user didn't sent a JWT in the Authorization header, so we disable JWT validation (which is set at the VS level), and we redirect the user to some other page (here /status/401)
      - prefix: /
        headers:
        - name: authorization
          invertMatch: true
      options:
        jwtStaged:
          beforeExtAuth:
            disable: true
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
    - matchers: # the default route, picked at first when the user comes with the Authorization header (containing a JWT)
      - prefix: /
      options:
        prefixRewrite: /ip # dummy route, not used because of the dynamic route selection after a claim is extracted from the JWT
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
    options:
      jwtStaged:
        beforeExtAuth:
          providers:
            inline:
              jwks:
                local:
                  key: |
                    -----BEGIN PUBLIC KEY-----
                    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6u+z4YAGfkMKX5EJJIk+
                    jcX91JBfl2iUVcrC1NOYza8K5rQbOb0eg8fy3GiITZ/e8V5wmWf90Fr8z+3rhy1x
                    ehcH+S3usNFfDE01rhGmofGOvUXAvzBvDgM+9s8zW1hi7HZnNi4eXagIYxirTD4Y
                    ANQq02IhUr9/IQbsNpwshPmDsav59ApDn69jw9WcWW6kiJerA+mvlw+xOzGfl2RA
                    OB8f7zO11yuSYrXgy7ap4jvrkV6FMkqf6fLpd1mOiNGEENixSMUjoXRPsZ3CpqZ8
                    WZgZGTPKnz2FwLY6wO7BJhJ30hGzzk6T8hhJMQN/AB342ZKnOgpRg/1glLg5A6HN
                    gwIDAQAB
                    -----END PUBLIC KEY-----
              issuer: "solo.io"
              tokenSource:
                headers:
                - header: authorization
                  prefix: "Bearer "
              claimsToHeaders:
              - claim: name
                header: x-solo-end-user
              audiences:
              - frontend
```

Requests to `$(glooctl proxy url)/l` which do not provide an authorization header are forwarded to the upstream without being authenticated. 

Current working theory is that changes to the way that envoy handles redirects are responsible for the bug
