### ISSUE TITLE
FederatedRateLimitConfig reconcilliation fail on gloo-fed pod

### ISSUE THREAD

**Issue by amiramw** [solo-io/gloo#5928]
I'm trying to deploy the following FederatedRateLimitConfig resource:
```yaml
apiVersion: fed.ratelimit.solo.io/v1alpha1
kind: FederatedRateLimitConfig
metadata:
  name: my-rate-limit-policy
  namespace: tbdddb-e2e-consumer
spec:
  template:
    metadata:
      name: my-rate-limit-policy
    spec:
      raw:
        descriptors:
        - key: generic_key
          value: counter
          rateLimit:
            requestsPerUnit: 10
            unit: MINUTE
        rateLimits:
        - actions:
          - genericKey:
              descriptorValue: counter
```

Gloo fed pod seems to fail with the message: `Operation cannot be fulfilled on federatedratelimitconfigs.fed.ratelimit.solo.io \"my-rate-limit-policy\": the object has been modified; please apply your changes to the latest version and try again`

The Ratelimitconfigs is not created on edge.
