### ISSUE TITLE
Regex route short-circuiting false positives

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#5958]
### Gloo Edge Version

1.11.x (beta)

### Describe the bug

When `warnRouteShortCircuiting` is set to true, gloo sometimes mistakenly warns about unordered regex routes, when the routes are actually valid. This seems to happen specifically when a route with a regex matcher is followed by a route with a prefix or exact matcher AND the earlier matcher does not have more specific headers/methods/query params than the later matcher.

### Steps to reproduce the bug

Make sure `gateway.validation.warnRouteShortCircuiting` is set to `true` in Gloo settings.

Apply the following VS:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs1
  namespace: default
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - regex: /foo
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```
Check the VS status or do a `glooctl check`. There will be a warning on the VS:
```
virtual host [default.vs1] has unordered regex routes, earlier regex [/foo] short-circuited later route [prefix:"/"])
```
however the route configuration is valid.

### Expected Behavior

The above config should not produce a warning.

### Additional Context

This bug affects all supported gloo edge versions
