### ISSUE TITLE
Remove the `x-envoy-upstream-service-time` header from the request but still contain it in the envoy access logs

### ISSUE THREAD

**Issue by rinormaloku** [solo-io/gloo#5970]
### Is your feature request related to a problem? Please describe.

The ability to remove headers (specifically the `x-envoy-upstream-service-time` header) from Responses but still show it in access logs. Currently, the access logs show null.

**How to reproduce:**
1. **Prerequisite:** A cluster with Gloo Edge installed.
2. Update the HTTP Gateway to show envoy access logs and to contain this header:
```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            duration: '%DURATION%'
            envoyUpstreamTime: '%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%'
            protocol: '%PROTOCOL%'
            upstreamCluster: '%UPSTREAM_CLUSTER%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  useProxyProto: false
EOF
```

3. Create an upstream and a virtual service
```
kubectl apply -f - <<EOF
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: json-upstream
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80
EOF

## GLOO EDGE VS
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
        options:
          headerManipulation:
            responseHeadersToRemove:
            - x-envoy-upstream-service-time
EOF
```

4. Generate traffic:
```
curl -H "Host: jsonplaceholder.typicode.com" -v http://$GATEWAY_IP/users
```

5. Get the logs:
```
kubectl -n gloo-system logs deploy/gateway-proxy | grep envoyUpstream
```
You will find the following output:
```
{"envoyUpstreamTime":null,"protocol":"HTTP/1.1","upstreamCluster":"json-upstream_gloo-system","duration":97} 
```
Actual result: **envoyUpstreamTime=null**
Desired result: envoyUpstreamTime still shows the real value in access logs.

### Describe the solution you'd like

Move the filter that removes the response header after the access log filter (if possible)

### Describe alternatives you've considered

Customizing metrics, to show this information instead of using access logs.

**Comment by rinormaloku** [comment]
@asayah You can get this _SORT-OF_ to work by adding the header into Filter Metadata (and overwriting it with e.g. - )

```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
    options:
      stagedTransformations:
        early:
          responseTransforms:     
          - responseTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - metadataNamespace: body-logging
                  key: upstream-service-time
                  value:
                    text: '{{ header("x-envoy-upstream-service-time") }}'
                headers:
                  x-envoy-upstream-service-time:
                    text: ''
EOF
```

Then add this dynamic metadata value to the access logs:
```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway: {}
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            duration: '%DURATION%'
            envoyUpstreamTime: '%DYNAMIC_METADATA(body-logging:upstream-service-time)%'
            protocol: '%PROTOCOL%'
            upstreamCluster: '%UPSTREAM_CLUSTER%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  useProxyProto: false
EOF
```


What is this solution missing? We still have the header `x-envoy-upstream-service-time: -` in the response (although it is not revealing some information.)

Desired solution is to use the following property:

```
      headerManipulation:
        responseHeadersToRemove:
        - x-envoy-upstream-service-time
```

However, this is executed before the extraction to the dynamic filter metadata, thus the access log would be empty as well.

**Comment by rinormaloku** [comment]
Oh actually just setting the header to empty '' removes it from the response, this fixes it:

```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
    options:
      stagedTransformations:
        early:
          responseTransforms:     
          - responseTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - metadataNamespace: body-logging
                  key: upstream-service-time
                  value:
                    text: '{{ header("x-envoy-upstream-service-time") }}'
                headers:
                  x-envoy-upstream-service-time:
                    text: ''
EOF
```
