### ISSUE TITLE
Gloo edge does not work with istio 1.13.x

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#5989]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

`glooctl istio inject` and istioSDS helm values wont work with istio 1.13.x

```yml
 global:
   istioSDS:
     enabled: true
     customSidecars:
         - name: istio-proxy
           image: docker.io/istio/proxyv2:1.13.1
```

### Steps to reproduce the bug

1. install istio
2. glooctl install gateway
3. glooctl istio inject
or
install gloo with the provided yaml 

### Expected Behavior

istio mtls should work with gloo
