### ISSUE TITLE
Helm chart extAuth label name is different between deployment and pdb templates

### ISSUE THREAD

**Issue by pippitt** [solo-io/gloo#5994]
### Gloo Edge Version

1.9.x

### Describe the bug

While updating to gloo enterprise edge helm chart version 1.9.11 (also appears to be in 1.10.8). 
Setting the pdb value `global.extensions.extAuth.deployment.podDisruptionBudget.minAvailable` (also setting enabled: true)
It was observed the pdb uses a hardcoded `matchLabels` of `gloo: ext-auth` but the deployment has a configurable label that defaults to `extauth`.
Template files: `21-extauth-pod-disruption-budget.yaml` and  `21-extauth-deployment.yaml`
The name is also hard coded in the rate-limit-pdb (but matches the default).

Nice to have, would be configurable names of the PDBs.
Also ext-auth is more generally referenced as extauth or extAuth throughout the rest of the helm chart (but if configurable shouldn't matter).

### Steps to reproduce the bug

1. Using gloo edge enterprise helm chart 1.9.11 (or 1.10.8).  Enable extauth and set a pdb value
2. matchLabels in pdb should align with label in extauth deployment

### Expected Behavior

Labels between deployment and pdb should match (and be configurable).

**Comment by pippitt** [comment]
Related to https://github.com/solo-io/gloo/issues/5648

**Comment by Azahorscak** [comment]
Still an issue in 1.17.19

I worked around with an override. 
```
extAuth:
   deployment:
      kubeResourceOverride:
          spec:
             selector:
                 matchLabels:
                    gloo: ext-auth
```
