### ISSUE TITLE
Route replacement does not work when upstream points to missing service

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6008]
### Gloo Edge Version

1.10.x (latest stable)

### Describe the bug

[Invalid route replacement](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/configuration_validation/invalid_route_replacement/) works fine when a route points to a nonexistent upstream, but does not work when a route points to an upstream that exists but is referencing a nonexistent service.

### Steps to reproduce the bug

Install gloo with replaceInvalidRoutes=true:
```
helm install -n gloo-system gloo gloo/gloo --create-namespace -f - <<EOF
settings:
  invalidConfigPolicy:
    invalidRouteResponseBody: Invalid config!
    invalidRouteResponseCode: 404
    replaceInvalidRoutes: true
EOF
```
Apply petstore demo service
```
k apply -f https://raw.githubusercontent.com/solo-io/gloo/v1.2.9/example/petstore/petstore.yaml
```
Apply the following VS:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: partially-valid
  namespace: default
spec:
  virtualHost:
    routes:
    - matchers:
      - prefix: /good-route
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
    - matchers:
      - prefix: /bad-route
      options:
        prefixRewrite: /api/pets
      routeAction:
        single:
          upstream:
            name: test-upstream
            namespace: gloo-system
```
and upstream:
```
# upstream points to nonexistent service
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: test-upstream
  namespace: gloo-system
spec:
  kube:
    selector:
      app: petstore
    serviceName: petstore123
    serviceNamespace: default
    servicePort: 8080
```
Try to reach the bad route:
`curl http://localhost:<port>/bad-route` returns a 503

### Expected Behavior

The curl should return a 404 with the message "Invalid config!", as specified by the invalidConfigPolicy above
