### ISSUE TITLE
Graphql Rest resolver not work properly

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#6027]
### Gloo Edge Version

1.11.x (beta)

### Kubernetes Version

1.23.x

### Describe the bug

REST resolver not working properly (because of the transformation), define the following resolver
```
          ratings:
            restResolver:
              request:
                headers:
                  :method: GET
                  :path: /ratings/{$parent.id}
              response:
                resultRoot: "ratings[*]"
                setters:
                  reviewer: "{$body[*][0]}"
                  numStars: "{$body[*][1]}"
              upstreamRef:
                name: default-ratings-9080
                namespace: gloo-system
```

result into: 

```
                      "provider_template": "/ratings/{parentid}"
                     }
                    }
                   },
                   "pre_execution_transform": {
                    "result_root": [
                     {
                      "key": "ratings"
                     },
                     {
                      "all": true
                     }
                    ],
                    "setters": {
                     "numStars": {
                      "path_template": "{body[*][1]}",
                      "named_paths": {
                       "body[*][1]": {
                        "segments": [
                         {
                          "all": true
                         },
                         {
                          "index": 1
                         }
                        ]
                       }
                      }
                     },
                     "reviewer": {
                      "path_template": "{body[*][0]}",
                      "named_paths": {
                       "body[*][0]": {
                        "segments": [
                         {
                          "all": true
                         },
                         {
                          "index": 0
                         }
                        ]
                       }
                      }
                     }
                    }
                   }
                  }
                 },
                 "stat_prefix": "ratings."
```

Here is the result from the upstream: 
```
[2022-03-04 20:23:12.820][25][debug][router] [external/envoy/source/common/router/router.cc:457] [C0][S4839155658878990068] cluster 'default-ratings-9080_gloo-system' match for URL '/ratings/0'
':path', '/ratings/0'
[2022-03-04 20:23:12.827][25][debug][filter] [source/extensions/graphql/resolvers/rest/rest_resolver_resolution_handle.cc:77] [C98][S5775337620796506041] rest resolver: onSuccess body: '{"id":0,"ratings":{"Reviewer1":5,"Reviewer2":4}}'
```

### Steps to reproduce the bug

see above

### Expected Behavior

When executing the GQL query return a non-empty array
