### ISSUE TITLE
wrong indentation in discovery-service 

### ISSUE THREAD

**Issue by yanivNaor92** [solo-io/gloo#6041]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

When installing gloo with the following values:
```yaml
  global:
    glooStats:
      enabled: true
      serviceMonitorEnabled: true
```
The installation fails with the following error: error validating data: ValidationError(Service): unknown field "selector" in io.k8s.api.core.v1.Service
The error occurs due to a wrong indentation in the [3-discovery-service.yaml](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/3-discovery-service.yaml#L16) file.
The `selector` property should be under `spec` instead of the root.

### Steps to reproduce the bug

Install gloo v1.10.x with the following Helm values:
```yaml
  global:
    glooStats:
      enabled: true
      serviceMonitorEnabled: true
```

### Expected Behavior

The installation should be completed without any errors and all the relevant resources should be created successfully.
