### ISSUE TITLE
aws.responseTransformation not honored when routes.options.tranformations is defined

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#6062]
### Gloo Edge Version

1.10.x (latest stable)

### Describe the bug

aws.responseTransformation not honored when routes.options.tranformations is defined

### Steps to reproduce the bug

Apply the following VirtualService

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /transform-response-code
      options:
        transformations:
          responseTransformation:
            transformationTemplate:
              headers:
                # We set the response status via the :status pseudo-header based on the response code
                ":status":
                  text: '{% if (header(":status") == "200") %}202{% else %}{{ header(":status") }}{% endif %}' 
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: go-example
              requestTransformation: true
              responseTransformation: true
          upstream:
            name: my-aws-upstream
            namespace: gloo-system
    - matchers:
      - prefix: /no-transform
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: go-example
              requestTransformation: true
              responseTransformation: true
          upstream:
            name: my-aws-upstream
            namespace: gloo-system
    - matchers:
      - prefix: /no-aws-transform
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName:  go-example
          upstream:
            name: my-aws-upstream
            namespace: gloo-system   
```

There is transformation on the /transform-response-code route that changes the status header and have aws.responseTransformation=true

When curled, the transformation in the routes.option happens but the aws.responseTransformation doesn't occur.

```
curl -s http://34.148.12.32/transform-response-code -i
HTTP/1.1 202 Accepted
date: Wed, 09 Mar 2022 18:23:42 GMT
content-type: application/json
content-length: 83
x-amzn-requestid: dba39110-7d31-4a48-ab2e-7d332effd80d
x-amzn-remapped-content-length: 0
x-amz-executed-version: $LATEST
x-amzn-trace-id: root=1-6228f0ae-0ac495465ed5942a468cd29b;sampled=0
x-envoy-upstream-service-time: 38
server: envoy

{"body":"{\"hello\": \"world\"}","headers":{"header1":["value1"]},"statusCode":404} 
```

### Expected Behavior

When curling the no-transform (which has the lambda transformation but no route level ones). The lambda transformation happens:
```
curl -s http://34.148.12.32/no-transform -i
HTTP/1.1 200 OK
date: Wed, 09 Mar 2022 18:23:26 GMT
x-amzn-requestid: 4f3f99a5-dc01-4677-9a96-c887f1fa2005
x-amzn-remapped-content-length: 0
x-amz-executed-version: $LATEST
x-amzn-trace-id: root=1-6228f09e-48e1644c5f05bcdc2dcfd575;sampled=0
x-envoy-upstream-service-time: 46
content-type: text/html
content-length: 18
server: envoy

{"hello": "world"}
```

When both `routes.options.tranformations` and `aws.responseTransformation` is defined, both transformation should occur.
