### ISSUE TITLE
Indentation of "Outputting structured json" example in Access Logging invalid

### ISSUE THREAD

**Issue by havard-fjaer** [solo-io/gloo#6092]
### Version

master

### Describe the requested changes

Parts of the indentation of "Outputting structured json" example in Access Logging is invalid.

```
apiVersion: gateway.solo.io/v1
   kind: Gateway
   metadata:
     name: gateway-proxy
     namespace: gloo-system
   spec:
...
```

`kind`, `metadata` and `spec` should be on the same level as `apiVersion`.

_I'll use this issue to get my toes wet, and will provide my own PR._

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/1.7.23/guides/security/access_logging/
