### ISSUE TITLE
Gloo ingress does not seem to support default backend spec

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#617]
Ingress' support a default backend spec where all traffic is to be routed to a service without needing to specify the path in the Ingress object

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: petstore-ingress
 annotations:
    kubernetes.io/ingress.class: gloo
spec:
  backend:
    serviceName: petstore
    servicePort: 8080
```

https://kubernetes.io/docs/concepts/services-networking/ingress/#single-service-ingress

It looks like Gloo is NOT configuring an Envoy listener as I'm assuming no route rules are created for this Ingress spec. This Ingress spec should create a wildcard route in Gloo for all traffic.
