### ISSUE TITLE
Istio Compat: Route Kubernetes Upstreams based on the Kube Service rather than the Pod VIP

### ISSUE THREAD

**Issue by murphye** [solo-io/gloo#6195]
### Version

1.10.x (latest stable)

### Is your feature request related to a problem? Please describe.

Right now, there is only basic mTLS integration with Gloo Edge and Istio. SDS is hijacked from an Istio sidecar, but otherwise Gloo Edge Envoy proxy remains outside the service mesh.

To fully engage Gloo Edge into the Istio service mesh, an Istio sidecar is needed for all traffic routing, therefore requiring double proxying of requests inside of the `gateway-proxy` pod. This is a reasonable trade-off at the moment to perform this extra proxying in order to leverage the benefits of routing requests from Gloo Edge into the Istio service mesh and have the ability to perform failover routing to an east-west gateway, as an example.

There is a problem in having Gloo Edge be compatible with Istio in that Kubernetes destinations (Upstreams) route to the Pod rather than the Service VIP. Without routing through the Service, Strict mTLS in Istio will fail to work.

### Describe the solution you'd like

Here is an example to show how this can work with a Static Upstream (which is not a good solution for this problem, only to show it can work):

Here is an existing Upstream that doesn't work correctly with Istio (i.e. fails with Strict mTLS):

**Example 1**:
```
          single:
            upstream:
              name: petstore-petstore-8080
              namespace: gloo-system
---
kind: Upstream
metadata:
  name: petstore-petstore-8080
  namespace: gloo-system
spec:
  kube:
    selector:
      app: petstore
    serviceName: petstore
    serviceNamespace: petstore
    servicePort: 8080
```

However, when this Upstream is defined as static and referencing the `petstore.petstore`, it WILL work in Istio even with Strict mTLS. This is because traffic is routed via the Service rather than directly to the Pod.

**Example 2**:
```
          single:
            upstream:
              name: petstore-static-upstream
              namespace: gloo-system
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: petstore-static-upstream
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: petstore.petstore
        port: 8080
````

**Desired Solution**

Offer a new Helm chart configuration that will change how Gloo Edge routes to Upstream Kubernetes destinations based on Service rather than Pod VIP. It might be something like:

```
gloo.settings.kubernetesDestinationsAsServices
```

This would have a default value of `false` to retain the current behavior. When this is set to `true` any Kubernetes upstream will route via the Service and not directly to the Pod.

--> In other words, an Upstream represented as **Example 1** would behave as **Example 2**.

### Describe alternatives you've considered

I have tried the existing Gloo Edge Istio mTLS integration, and it doesn't provide the needed functionality to leverage Istio at the gateway.
https://docs.solo.io/gloo-edge/latest/guides/integrations/service_mesh/gloo_istio_mtls/

### Additional Context

1. This would also enable Gloo Portal, via Gloo Edge, to integrate with Istio and Gloo Mesh.
2. This provides a better avenue for existing Gloo Edge users to integrate with Istio
3. Here is a demo project to show how to integrate Gloo Edge gateway proxy into the Istio service mesh:
https://github.com/murphye/demo-gloo-edge-istio
