### ISSUE TITLE
Gloo sends access-control-allow-origin in response when CORS origin is invalid

### ISSUE THREAD

**Issue by willowmck** [solo-io/gloo#6221]
### Gloo Edge Version

1.7.x

### Kubernetes Version

1.20.x

### Describe the bug

I was able to replicate this in 1.10.1, but the customer is using 1.7.20.  

I deployed httpbin and have the following VirtualService pointing to it.

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      cors:
        allowCredentials: true
        allowHeaders:
        - origin
        - content-type
        - request-id
        - x-requested-with
        - authorization
        allowMethods:
        - GET
        - POST
        - UPDATE
        - OPTIONS
        allowOrigin:
        - http://steve
        exposeHeaders:
        - origin
        maxAge: 1d
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
```

When I initiate a curl with the incorrect origin, I see the `access-control-allow-origin` returned even though prometheus stats indicate an invalid origin.

```
curl -I $(glooctl proxy url)/get -X OPTIONS -H "accept: application/json"  -H "origin: http://martha" -H "Access-Control-Request-Method: GET" -H "Access-Control-Request-Headers: Content-Type"
HTTP/1.1 200 OK
server: envoy
date: Fri, 01 Apr 2022 17:41:57 GMT
content-type: text/html; charset=utf-8
allow: HEAD, OPTIONS, GET
access-control-allow-origin: http://martha
access-control-allow-credentials: true
access-control-allow-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
access-control-max-age: 3600
access-control-allow-headers: Content-Type
content-length: 0
x-envoy-upstream-service-time: 0
```

```
curl -s http://localhost:19000/stats/prometheus | grep cors
Handling connection for 19000
# TYPE envoy_http_cors_origin_invalid counter
envoy_http_cors_origin_invalid{envoy_http_conn_manager_prefix="http"} 1
# TYPE envoy_http_cors_origin_valid counter
envoy_http_cors_origin_valid{envoy_http_conn_manager_prefix="http"} 0
# TYPE envoy_http_jwt_authn_cors_preflight_bypassed counter
envoy_http_jwt_authn_cors_preflight_bypassed{envoy_http_conn_manager_prefix="http"} 0
```

### Steps to reproduce the bug

1. Deploy httpbin or some other simple service.
2.  Deploy the above VirtualService to access it.
3.  Use curl with the Origin header set.
4.  Check prometheus stats.

### Expected Behavior

The response should not contain the `access-control-allow-origin` header.
