### ISSUE TITLE
Nested descriptors results in first key not being written to redis

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#6225]
### Gloo Edge Version

1.10.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Nested descriptors do not appear to work properly and are not using the descriptor key in the redis key. This causes multiple hits against the same key for multiple users. Right now the only workaround I have is removing rate limiting

Keys in redis (notice uid value is not written to key)
```
curl -v -H "uid:12345678901" $(glooctl proxy url)/a
```
```
1) "tree|crd|generic_key^gloo-system.rlc|uid|user-agent^`curl/7.82.0|1649011620"
```

In 1.6.23 notice that the uid value is used in the redis key (same provided configs, same curl command)
```
1) "crd_generic_key_gloo-system.rlc_uid_12345678901_user-agent_curl/7.82.0_1649012400"
```

### Steps to reproduce the bug

(values can contain just the license key)

```   helm upgrade gloo glooe/gloo-ee \
    --namespace gloo-system \
    --version v1.11.0-rc3 \
    --values ./values.yaml \
    --create-namespace \
    --install
```

```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: rlc
  namespace: gloo-system
spec:
  raw:
    descriptors:
      - key: uid
        descriptors:
          - key: user-agent
            rateLimit:
              requestsPerUnit: 5
              unit: MINUTE
    rateLimits:
      - actions:
          - requestHeaders:
              descriptorKey: uid
              headerName: uid
          - requestHeaders:
              descriptorKey: user-agent
              headerName: user-agent
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: httpbin-upstream
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: httpbin.org
        port: 443
---
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: "a-routes"
  namespace: "gloo-system"
spec:
  routes:
    - matchers:
        - prefix: "/a"
      routeAction:
        single:
          upstream:
            name: "httpbin-upstream"
      options:
        prefixRewrite: "/anything"
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default-http
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "*"
    routes:
      - matchers:
          - prefix: /a
        delegateAction:
          ref:
            name: a-routes
            namespace: gloo-system
    options:
      rateLimitConfigs:
        refs:
          - name: rlc
            namespace: gloo-system

```

### Expected Behavior

Given the above scenario, I would expect each call to be rate limited by uid AND user agent combination. But right now its only rate limited by user agent.
