### ISSUE TITLE
ExtAuth should return a 401 for expired access_token

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6318]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

In the ExtAuth service, our JWT validation logic will return a 403 for any error instead of a 401. 

[Validator.go](https://github.com/solo-io/ext-auth-service/blob/26052235c2f91e9d0a0f77a340c636cd3aa2b324/pkg/config/oauth/token_validation/jwt/validator.go#L108)
[Auth_service.go](https://github.com/solo-io/ext-auth-service/blob/26052235c2f91e9d0a0f77a340c636cd3aa2b324/pkg/config/oauth/token_validation/auth_service.go#L60)

[RFC 6750](https://www.rfc-editor.org/rfc/rfc6750) states that the HTTP code should be 401 when the access token expires.

### Steps to reproduce the bug

```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: hello-world
  namespace: apps
spec:
  configs:
  - oauth2:
      accessTokenValidation:
        jwt:
          remoteJwks:
            url: <URL_HERE>
```

### Expected Behavior

HTTP 401
