### ISSUE TITLE
GraphQL with grpc datasource errors when listing elements  

### ISSUE THREAD

**Issue by asayah** [solo-io/gloo#6329]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

using the following backend: https://github.com/solo-io/grpc-example-app

When creating a grpc resolover: 
```
          Query|StoreService.ListItems:
            grpcResolver:
              requestTransform:
                methodName: ListItems
                outgoingMessageJson: {}
                serviceName: solo.examples.v1.StoreService
              upstreamRef:
                name: default-grpcstore-demo-80
                namespace: gloo-system
```

and using it in a Query

```
      type Query {
        ListItems: ListItemsResponse @resolve(name: "Query|StoreService.ListItems")
```

when executing the following gql query: 
```

type ListItemsResponse {
  items: [Item]
}

query Items {
  ListItems {
    items {
      name
    }
  }
}
```
we receive this error: 
```
{
  "data": {
    "ListItems": null
  },
  "errors": [
    {
      "message": "grpc resolver json to binary string status is INVALID_ARGUMENT:: Root element must be a message.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

### Steps to reproduce the bug

see above 

### Expected Behavior

Returning a list of items
