### ISSUE TITLE
request still returns 200 to static upstream when dns record is deleted.

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#6331]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.21.x

### Describe the bug

Requests through the gateway-proxy returns `200` successful after the dns record is deleted.

### Steps to reproduce the bug

1.  Create a dns record `gloo-test.duckdns.org` and point to `34.231.5.222` which is httpbin.org
2. Create a static upstream to with host address: `gloo-test.duckdns.org`
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: static-upstream
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: gloo-test.duckdns.org
        port: 80
```
3. Create a VirtualService:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: static
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
         - prefix: /
        routeAction:
          single:
            upstream:
              name: static-upstream
              namespace: gloo-system
        options:
          autoHostRewrite: true
          headerManipulation:
            requestHeadersToAdd:
            - header:
                key: went-thru-gloo
                value: "true"
```
4.  Do a nslookup to the `gloo-test.duckdns.org` and verify it's correct:
```
nslookup gloo-test.duckdns.org
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	gloo-test.duckdns.org
Address: 34.231.5.222
```
5.  curl the endpoint through the gateway-proxy: `curl $(glooctl proxy url)/get -v`
```
*   Trying 35.194.94.205:80...
* Connected to 35.194.94.205 (35.194.94.205) port 80 (#0)
> GET /get HTTP/1.1
> Host: 35.194.94.205
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< date: Fri, 15 Apr 2022 18:40:59 GMT
< content-type: application/json
< content-length: 356
< server: envoy
< access-control-allow-origin: *
< access-control-allow-credentials: true
< x-envoy-upstream-service-time: 5
<
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "gloo-test.duckdns.org",
    "User-Agent": "curl/7.77.0",
    "Went-Thru-Gloo": "true",
    "X-Amzn-Trace-Id": "Root=1-6259bc3b-2ea5c8ce3ac145af3828e1e0",
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000"
  },
  "origin": "35.188.239.109",
  "url": "http://gloo-test.duckdns.org/get"
}
* Connection #0 to host 35.194.94.205 left intact
```
6.  Delete the dns record.  Verify the record is gone `** server can't find gloo-test.duckdns.org: NXDOMAIN`
7. Curliing the dns directly should return an error:
```
* Could not resolve host: gloo-test.duckdns.org
* Closing connection 0
curl: (6) Could not resolve host: gloo-test.duckdns.org
```
9.  curl the endpoint through the gateway-proxy: `curl $(glooctl proxy url)/get -v` .  Even after an hour, it still returns a 200 response code.

### Expected Behavior

After deleting the dns record and getting the `** server can't find gloo-test.duckdns.org: NXDOMAIN` from `nslookup gloo-test.duckdns.org`.  I expect the call to the static upstream that is referencing that host to return a `503` - no health host.  Access logs from the proxy shows:

```{"response_code":200,"downstream_remote_address":"10.20.2.1:13674","downstream_local_address":"10.20.2.5:8080","requested_server_name":null,"protocol":"HTTP/1.1","upstream_local_address":"10.20.2.5:58992","authority":"gloo-test.duckdns.org","messageType":null,"response_flags":"-","bytes_received":0,"start_time":"2022-04-15T20:12:18.275Z","targetDuration":4,"user_agent":"curl/7.77.0","path":"/get","response_code_details":"via_upstream","x_forwarded_for":null,"upstream_service_time":"3","bytes_sent":356,"upstream_cluster":"static-upstream_gloo-system","upstream_transport_failure_reason":null,"route_name":"gloo-system_static-route-0-matcher-0","method":"GET","upstream_host":"34.231.5.222:80","request_id":"9e7ee76e-8e0d-4680-afaf-c10f4b259a56","number":null,"duration":4}
```

Once I reboot the gateway proxy,  I get the expect 503

```
===================================================================================
Fri Apr 15 16:13:14 EDT 2022
nslookup gloo-test.duckdns.org
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find gloo-test.duckdns.org: NXDOMAIN

*   Trying 35.194.94.205:80...
* Connected to 35.194.94.205 (35.194.94.205) port 80 (#0)
> GET /get HTTP/1.1
> Host: 35.194.94.205
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< content-length: 19
< content-type: text/plain
< date: Fri, 15 Apr 2022 20:13:13 GMT
< server: envoy
<
* Connection #0 to host 35.194.94.205 left intact
no healthy upstream
```

```{"response_flags":"UH","duration":0,"x_forwarded_for":null,"upstream_local_address":null,"upstream_service_time":null,"authority":"35.194.94.205","upstream_cluster":"static-upstream_gloo-system","request_id":"8262b729-bea6-4158-823f-393cb1f41a3e","protocol":"HTTP/1.1","number":null,"bytes_sent":19,"route_name":"gloo-system_static-route-0-matcher-0","path":"/get","downstream_local_address":"10.20.2.8:8080","downstream_remote_address":"10.138.15.210:18589","messageType":null,"requested_server_name":null,"user_agent":"curl/7.77.0","response_code_details":"no_healthy_upstream","targetDuration":null,"method":"GET","response_code":503,"start_time":"2022-04-15T20:14:04.910Z","upstream_transport_failure_reason":null,"upstream_host":null,"bytes_received":0}
```
