### ISSUE TITLE
Helm override differences between Gloo Edge versions 1.11.0-beta11 and 1.11.2 not reflected in changelog

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#6355]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.20.x

### Describe the bug

Customer noticed: 
The following helm override differences seem to be not documented. I had to figure out myself to resolve helm upgrade error when I did the upgrade from Gloo Edge 1.11.0-beta11 to Gloo Edge 1.11.2 in our Sandbox environment.

The following snippet shows a part of my helm override file that I had prior to upgrading to Gloo Edge 1.11.2. It worked for me with 1.11.0-beta11.

```
global:
  glooStats:
    enabled: true
    serviceMonitor: true
    serviceMonitorReleaseLabel: prometheus-kubeaddons
    podMonitorEnabled: true
```
 

When upgrading to Gloo Edge 1.11.2, helm upgrade failed. I had to update the helm overrides as shown below to resolve the failure.

```
global:
  glooStats:
    enabled: true
    serviceMonitorEnabled: true
    serviceMonitor:
      releaseLabel: prometheus-kubeaddons
    podMonitorEnabled: true
    podMonitor:
      releaseLabel: prometheus-kubeaddons
```

Full values files are attached to [#708](https://solo-io.zendesk.com/agent/tickets/708)

### Steps to reproduce the bug

Previous values file no longer works and customer had to dig through the templates to find the new correct values.  

### Expected Behavior

Better visibility of the change.
