### ISSUE TITLE
gateway.options.socketOptions turns ints into strings which prevents edit/save

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#6490]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

gateway.options.socketOptions turns ints into strings which prevents edit/save

### Steps to reproduce the bug

1. Add gateway.options.socketOptions and save. 
For example: 
```
spec:
  bindAddress: '::'
  bindPort: 8443
  httpGateway: {}
  options:
    socketOptions:
    - description: enable keep-alive
      intValue: 1
      level: 2
      name: 1
```
2. Edit the gateway. The int values are now strings. For example:
  options:
    socketOptions:
    - description: enable keep-alive
      intValue: "1"
      level: "1"
      name: "1"
3. To edit or save the gateway, you need to manually remove all of the quotes to turn the strings back into ints

### Expected Behavior

gateway.options.socketOptions int values preserve type
