### ISSUE TITLE
Ability for the extauth server to connect to tls enabled redis.

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#6496]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

The extauth service can be configured to use Redis to save the OIDC tokens.  
https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/oauth/

The rate limit pod now has the ability to connect to a Redis with TLS enabled.  The extauth service needs to support the same.

### Describe the solution you'd like

When a TLS enabled redis is defined, the extauth service should be able to connect to it.

**Comment by jackstine** [comment]
This will take some time to complete, with my work on my current issue, I will not be able to get to this till later. As there are changes still needed in the PR for ext-auth. I do have code ready for the necessary helm changes in `s-p` as well.

**Comment by sebastian-popa** [comment]
Hi Jacob, Peter, sorry for asking, our security team won't let us go to production with Gloo unless the session data is passed to Redis over TLS (esp. session stuff), would be great if you could give us an ETA in the following days. 

Thanks!

**Comment by chrisgaun** [comment]
@sebastian-popa we will get on it.

**Comment by jackstine** [comment]
This should be in some time early next week @sebastian-popa

**Comment by jackstine** [comment]
helm values that control the use of rate limit
[current helm values](https://docs.solo.io/gloo-edge/master/reference/helm_chart_values/enterprise_helm_chart_values/#:~:text=redis.deployment.image.tag)
[current user session values](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#redisoptions)

Propossed changes
Move [RedisOptions](https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto.sk/#redisoptions) to helm chart values.

helm values
redis:
	- rateLimit
		- enabled (true default)
		- redisOptions
	- userSessions
		- enabled (false default)
		- redisOptions

redisOptions
- redisCert
- service
- aclPrefix

redisCert
- enabled
- crt
- key
- cacrt

service
- port
- name
- db (0 default)
- poolSize (10 default)

get rid of the following
- redis.disabled
	- Not needed anymore, if both `rateLimitEnabled` and `userSessions` are `false` then we do not need it.
		- keep the redis server up and running all the time, because what if user adds to US?  then we need the redis server.

**Comment by jackstine** [comment]
With these added changes it looks like it will take some more time @sebastian-popa

**Comment by jackstine** [comment]
I have to enable the use of the internal `REDIS_PASSWORD` this is the default password given if ACL is defined for the redis deployment. If the value `.Values.global.extensions.glooRedis.enableAcl` in the helm values is set.
This is mentioned in [the issue here](https://github.com/solo-io/gloo/issues/4823)

- Keep the Environment variable as is, and force users to set [username_password_suffix](https://github.com/solo-io/gloo/blob/1077bb6eb5bc2c604d2522b35c3aaed816a3e8ae/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto#L330) to `gloo_internal` so that the redis instance works.
- Or set `REDIS_PASSWORD_GLOO_INTERNAL` as the environment variable for the password and  [username_password_suffix](https://github.com/solo-io/gloo/blob/1077bb6eb5bc2c604d2522b35c3aaed816a3e8ae/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto#L330) = 'gloo_internal'

Either way, it looks like this configuration will be forced on users if they are setting the value `.Values.global.extensions.glooRedis.enableAcl` in the helm chart.

The reason I cannot use `REDIS_PASSWORD` anymore is because there is no way to distinguish from the OAuth Config's host and the name of the gloo internal redis instance.
[From reading this on kubernetes ](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/)it looks like the domain-name and domain can change, causing issues. So there can not be a guaranteed look up on `redis.<namespace>.svc.cluster.local` as the endpoint because `cluster.local` can change.

**Comment by jackstine** [comment]
Looking at this further, I think if the host has `redis.<namespace>.svc` , where namespace is the namespace of the gloo edge cluster, at the start of its name then we could assume that the host is internal.

If this could be true all the time, then we could default to `REDIS_PASSWORD` as the password. Else use the options given in the OAuth configurations.

**Comment by jackstine** [comment]
For Multi-tenant redis hosts for Ext-Auth I have made these changes to the following repos.

[Gloo](https://github.com/solo-io/gloo/tree/ext-auth-multi-tenant-servers)
[Ext-Auth-Service](https://github.com/solo-io/ext-auth-service/tree/ext-auth-multi-tenant-servers)
[Solo-Projects](https://github.com/solo-io/solo-projects/tree/ext-auth-multi-tenant-servers)

**Comment by jackstine** [comment]
Here is an example of a AuthConfig
```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: auth0-ac
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: https://localhost
        callbackPath: /callback
        clientId: <clientID>
        clientSecretRef:
          name: auth0-client-secret
          namespace: gloo-system
        issuerUrl: <issuerUrl>
        scopes:
        - email
        session:
          failOnFetchFailure: true
          redis:
            cookieName: auth0-session
            options:
              host: redis.default.svc.cluster.local:6379
              # setting socketType will enable TLS
              socketType: TLS
               # setting tlsCertMountPath enables CA Root and Certificate to be attached to the TLS Configuration.
              tlsCertMountPath: "/certs"
        headers:
          idTokenHeader: "jwt"
```

**Comment by jackstine** [comment]
Getting some errors when running TLS from a `<server-name>.redis.cache.windows.net` endpoint.
Note this is working on local when running integration tests with the host, REDIS_PASSWORD, and TLS enabled.

Configuration for AuthConfig includes the following
```
        session:
          cookieOptions:
            sameSite: NoneMode
          failOnFetchFailure: true
          redis:
            cookieName: session
            options:
              host: pszeto-test.redis.cache.windows.net:6380
              socketType: TLS
```

Also added `REDIS_PASSWORD` to pod
```
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-azure
```

The output of the logs is as follows
```
"level":"debug","ts":1659973234.1534302,"logger":"ext-auth.ext-auth-service","msg":"callback successfully handled","version":"undefined","x-request-id":"8c20ed39-312b-403d-bb93-6a54d4705641","redirect":"https://website-solo.com/"}
{"level":"debug","ts":1659973234.1536078,"logger":"ext-auth.ext-auth-service","msg":"setting id token cookie","version":"undefined","x-request-id":"8c20ed39-312b-403d-bb93-6a54d4705641","len(idtoken)":1061}
{"level":"debug","ts":1659973234.1538465,"logger":"ext-auth.ext-auth-service","msg":"adding header to the response from the callback","version":"undefined","x-request-id":"8c20ed39-312b-403d-bb93-6a54d4705641","key":"location","len(v)":25}
{"level":"warn","ts":1659973234.289956,"logger":"ext-auth.ext-auth-service","msg":"failed saving session","version":"undefined","x-request-id":"8c20ed39-312b-403d-bb93-6a54d4705641","error":"context canceled"}
{"level":"debug","ts":1659973234.290016,"logger":"ext-auth.ext-auth-service","msg":"Access denied by auth authService","version":"undefined","x-request-id":"8c20ed39-312b-403d-bb93-6a54d4705641","authService":"soloauth"}
```
