### ISSUE TITLE
Using OIDC Auth flow - how can I send the Authorization header with a "Bearer" prefix in the value?

### ISSUE THREAD

**Issue by Sodman** [solo-io/gloo#6501]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

When I configure OIDC as follows, it passes the authorization header to the upstream service in the format "Authorization: <access_token>" but the service needs it to be in the format "Authorization: Bearer <access_token>" (with the "Bearer " prefix in the value).

This is my AuthConfig resource:
```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: keycloak-oidc-auth-config
  namespace: my-app-namespace
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: https://my-oidc.app.url.com
        callbackPath: /callback
        clientId: gloo-ingress
        clientSecretRef:
          name: keycloak-oidc-client-secret
          namespace: my-app-namespace
        issuerUrl: https://my-issuer-url/issuer
        scopes:
        - email
        headers:
          accessTokenHeader: "Authorization"
        logoutPath: /logout
        afterLogoutUrl: /
        sessionIdHeaderName: oidc-session
        session:
          failOnFetchFailure: true
          redis:
            cookieName: oidc-session
            options:
              host: redis.gloo-system.svc.cluster.local:6379
```

How can I have the output "Authorization" header passed to the upstream, have the Bearer prefix in the value?

### Describe the solution you'd like

It would be nice if this was the default format, as that's how most auth bearer tokens work. 

### Describe alternatives you've considered

Using some kind of header manipulation or transformation filter to update the value and prepend the "Bearer " prefix.
