### ISSUE TITLE
Custom searchFilter attribute in LDAP configuration is ignored

### ISSUE THREAD

**Issue by pseudonator** [solo-io/gloo#6513]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

It appears that setting a custom `searchFilter` in 1.11.x is not propagated to the ext-auth service.

For e.g. `searchFilter: "(CN=*)"`.

Hence the `searchFilter` is always set to the default `(uid=*)` causing search issues.

### Steps to reproduce the bug

Injecting the following `AuthConfig`,

```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: ldap-auth-config
  namespace: app-configuration
spec:
  configs:
  - ldap:
      address: ldap://host.docker.internal:389
      allowedGroups:
      - CN=it security,CN=Users,DC=kasunt,DC=local
      userDnTemplate: CN=%s,CN=Users,DC=kasunt,DC=local
      searchFilter: "(CN=*)"
```

### Expected Behavior

It should be possible to customize the search filter in custom LDAP configurations.
