### ISSUE TITLE
Gloo pod crash with NPE

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#6534]
### Gloo Edge Version

1.10.x

### Kubernetes Version
1.20

### Describe the bug

customer reports gloo pod crashes after creating routetable like
```
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: test-dynamic-forward
spec:
  routes:
    - matchers:
        - prefix: "/dynamic-forward/"
      options:
        jwt:
          disable: true
        stagedTransformations:
          early:
            requestTransforms:
              - clearRouteCache: true
                requestTransformation:
                  transformationTemplate:
                    ignoreErrorOnParse: true
                    extractors:
                      json:
                        body: { }
                      x-via-tenant:
                        header: :x-via-tenant
                        regex: '.*'
                      city-id:
                        header: :x-via-city-id
                        regex: '.*'
                    headers:
                      x-via-tenant:
                        text: '{{ x-via-tenant }}'
                      city-id:
                        text: '{% if exists("city_id") %}{{ city_id }}{% endif %}'
                      x-via-city-id:
                        text: '{% if exists("city_id") %}{{ city_id }}{% endif %}'
                      x-mypaas-tenant-backend:
                        text: 'server-sar-sta.ridewithvia.com'
      routeAction:
        dynamicForwardProxy:
          autoHostRewriteHeader: "x-mypaas-tenant-backend"
```
Log from the crash:
```
{"level":"info","ts":"2022-05-30T16:26:53.967Z","logger":"gloo-ee.v1.event_loop","caller":"v1/setup_event_loop.sk.go:57","msg":"event loop started","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:54.721Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop","caller":"v1/eds_event_loop.sk.go:57","msg":"event loop started","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:54.880Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/run.go:35","msg":"begin sync 2148329775083842183 (129 upstreams)","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:54.889Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/discovery.go:193","msg":"Received first EDS update from plugin: *ec2.plugin","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:54.993Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/discovery.go:193","msg":"Received first EDS update from plugin: *kubernetes.plugin","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:54.989Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.syncer","caller":"discovery/run.go:65","msg":"end sync 2148329775083842183","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:55.031Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop","caller":"v1/api_event_loop.sk.go:57","msg":"event loop started","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:55.143Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"syncer/envoy_translator_syncer.go:78","msg":"begin sync 3764030899039016255 (1 proxies, 129 upstreams, 132 endpoints, 30 secrets, 75 artifacts, 4 auth configs, 0 rate limit configs, 0 graphql schemas)","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:55.151Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer.translator","caller":"translator/translator.go:227","msg":"computing envoy resources for listener: listener-::-8080","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:55.154Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer.translator","caller":"translator/translator.go:227","msg":"computing envoy resources for listener: listener-::-8443","version":"1.10.18"}
{"level":"info","ts":"2022-05-30T16:26:56.023Z","logger":"gloo-ee.v1.event_loop.setup.v1.event_loop.envoyTranslatorSyncer","caller":"runtime/panic.go:971","msg":"end sync 3764030899039016255","version":"1.10.18"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2cd5706]

goroutine 508 [running]:
github.com/solo-io/gloo/projects/gloo/pkg/plugins/pluginutils.MarkPerFilterConfig(0x4c612a0, 0xc0021d8a20, 0xc0008c2e00, 0xc0027ad680, 0xc0011a5ea0, 0x480ec15, 0x16, 0xc0016359c8, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/plugins/pluginutils/per_filter_config.go:84 +0x366
github.com/solo-io/gloo/projects/gloo/pkg/plugins/azure.(*plugin).ProcessRoute(0xc0021d86c0, 0x4c612a0, 0xc00277e0c0, 0xc0008c2e00, 0xc001f14de0, 0xc001f434a0, 0xc001f15320, 0xc0027acd00, 0xc0027ad680, 0xc0011a5ea0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/plugins/azure/plugin.go:108 +0xdc
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*httpRouteConfigurationTranslator).runRoutePlugins(0xc00274d540, 0x4c612a0, 0xc00277e0c0, 0xc0008c2e00, 0xc001f14de0, 0xc001f434a0, 0xc001f15320, 0xc0027acd00, 0xc0022bc720, 0xc0027ad680, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/p1rojects/gloo/pkg/translator/route_config.go:326 +0x153
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*httpRouteConfigurationTranslator).setAction(0xc00274d540, 0x4c612a0, 0xc00277e0c0, 0xc0008c2e00, 0xc001f14de0, 0xc001f434a0, 0xc001f15320, 0xc0027acd00, 0xc0022bc720, 0xc0027ad680, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/route_config.go:255 +0xdd5
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*httpRouteConfigurationTranslator).envoyRoutes(0xc00274d540, 0x4c612a0, 0xc00277e0c0, 0xc0008c2e00, 0xc001f14de0, 0xc001f434a0, 0xc001f15320, 0xc0027acd00, 0xc0022bc720, 0xc0027ad680, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/route_config.go:155 +0x1a9
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*httpRouteConfigurationTranslator).computeVirtualHost(0xc00274d540, 0x4c612a0, 0xc00277e0c0, 0xc0008c2e00, 0xc001f14de0, 0xc001f434a0, 0xc001f15320, 0xc0027acd00, 0xc0022bc840, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/route_config.go:112 +0x4c5
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*httpRouteConfigurationTranslator).computeVirtualHosts(0xc00274d540, 0x4c612a0, 0xc00277e0c0, 0xc0008c2e00, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/route_config.go:89 +0x2ae
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*httpRouteConfigurationTranslator).ComputeRouteConfiguration(0xc00274d540, 0x4c612a0, 0xc00277e0c0, 0xc0008c2e00, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/route_config.go:71 +0x12c
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).translateListenerSubsystemComponents(0xc001636d90, 0x4c612a0, 0xc0021d8a20, 0xc0008c2e00, 0xc001f14de0, 0xc0022b01c0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/translator.go:239 +0x404
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).Translate(0xc001636d90, 0x4c612a0, 0xc0021d8a20, 0xc0008c2e00, 0xc001f14de0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/translator.go:120 +0x625
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorFactory).Translate(0xc000920630, 0x4c612a0, 0xc0021d8690, 0xc0008c2e00, 0xc001f14de0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/translator/translator.go:79 +0x27f
github.com/solo-io/gloo/projects/gloo/pkg/syncer.(*translatorSyncer).syncEnvoy(0xc0007e6000, 0x4c612a0, 0xc002088240, 0xc0008c2e00, 0xc002088090, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/syncer/envoy_translator_syncer.go:125 +0xe02
github.com/solo-io/gloo/projects/gloo/pkg/syncer.(*translatorSyncer).Sync(0xc0007e6000, 0x4c611f8, 0xc001f66d40, 0xc0008c2e00, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/syncer/translator_syncer.go:90 +0xbf
github.com/solo-io/gloo/projects/gloo/pkg/api/v1.ApiSyncers.Sync(0xc00247de60, 0x2, 0x2, 0x4c611f8, 0xc001f66d40, 0xc0008c2e00, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/api/v1/api_event_loop.sk.go:28 +0xf9
github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*apiEventLoop).Run.func1(0xc000e79740, 0x4c612a0, 0xc00097c060, 0x0, 0xdf8475800, 0x0, 0x0, 0xc00097c030, 0xc002256180, 0xc0021069c0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/api/v1/api_event_loop.sk.go:84 +0x375
created by github.com/solo-io/gloo/projects/gloo/pkg/api/v1.(*apiEventLoop).Run
	/go/pkg/mod/github.com/solo-io/gloo@v1.10.19/projects/gloo/pkg/api/v1/api_event_loop.sk.go:66 +0x3f2
```
After deleting the routetable and namespace the gloo pod starts running again.

### Steps to reproduce the bug

I haven't managed to reproduce locally. this is most probably a combination of more than just a routetable

### Expected Behavior

routetable is rejected if there is a problem and pod keeps running
