### ISSUE TITLE
Expose option to remove headers in the transformation filter

### ISSUE THREAD

**Issue by ably77** [solo-io/gloo#6539]
### Version

1.11.x (latest stable)

### Is your feature request related to a problem? Please describe.

We are attempting to scrub headers from requests that require extauth.  These particular headers need to be scrubbed before extauth and not after.  We have tried headerManipulation but that seems to scrub headers after extauth.  We have worked around this by using a transformation template to convert the values of these headers as empty strings (see below)

```
stagedTransformations:
  early:
    requestTransforms:
      - requestTransformation:
          transformationTemplate:
            headers:
              x-header1:
                text:
              x-header2:
                text:
              x-header3:
                text:
            passthrough: {}
extauth:
  customAuth: {}
```

Use case for scrubbing these particular headers before customAuth is so that clients cannot pass them in themselves and fake an authenticated request

### Describe the solution you'd like

A more ideal solution would be to expose the option `headersToRemove` in the transformation filter, and set this in the early stage before extauth

### Describe alternatives you've considered

see above example for current workaround to scrub values with transformationTemplate

**Comment by kdorosh** [comment]
@ably77 where do the headers that need to be scrubbed come from in normal flows? I imagine the ideal solution is something that passes this metadata more internal to envoy (rather than request header). for example `metadata_context_namespaces` or `typed_metadata_context_namespaces`, from https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#envoy-v3-api-msg-extensions-filters-http-ext-authz-v3-extauthz

additionally, why are we using an entirely custom extauth server rather than ours with passthrough auth? our server also has similar functionality built into its api we could lean on

**Comment by kdorosh** [comment]
we do this in our extauth server today using https://docs.solo.io/gloo-edge/master/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/extauth/sanitize.proto.sk/

**Comment by kdorosh** [comment]
the above configuration is not available to users, we should either add sanitize header to open source or move header manipulation earlier in the filter chain @ashishb-solo this request makes sense now we can pursue it

**Comment by ashishb-solo** [comment]
A few questions here:

1. @ably77 Based on my testing, client-provided headers are not passed to extauth by default. There are some configuration options that allow this however:

```
spec:         
  extauth:             
    httpService:              
      request:              
        allowedHeaders:        
        - "x-my-custom-header"
        allowedHeadersRegex:           
        - "x-my-customregex-.*"   
```

Could the users' requests here be satisfied by simply updating these rules to be a bit more strict?

2. @kdorosh I'm rather nervous about moving the header manipulation plugin earlier in the filter chain; is there a possibility that this could be an incompatible change to users who already use this plugin?

Based on my trepidations in the previous question, I feel that the best way to go about this is to expose the sanitize extension that envoy provides. @kdorosh, I'd like to know how you feel about this.

Thanks!
