### ISSUE TITLE
helm upgrade fails when trying to apply new Gateway fields via helm values

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#6555]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

When upgrading to a new Gloo Edge version while trying to use newly added Gateway fields, the initial helm upgrade fails because the Gateway goes through the validation service running in the old gloo (pre-1.12: gateway) pod which doesn't know about the new fields.

To fix this we should wait til the new gloo (gateway) pod comes up before applying the Gateway and other custom resources.

### Steps to reproduce the bug

```
# install an older gloo version
helm install -n gloo-system gloo gloo/gloo --create-namespace --version 1.11.0

# (apply CRDs for new version)

# install new version and try to set gateway values that didn't exist in 1.11.0
helm upgrade -n gloo-system gloo gloo/gloo --version 1.11.14 -f - <<EOF
gatewayProxies:
  gatewayProxy:
    gatewaySettings:
      customHttpGateway:
        options:
          dlp:
            dlpRules:
            - actions:
              - actionType: KEYVALUE
                keyValueAction:
                  keyToMask: test
                  name: test
EOF
```

This results in error:
```
Error: UPGRADE FAILED: cannot patch "gateway-proxy" with kind Gateway: admission webhook "gateway.gloo-system.svc" denied the request: resource incompatible with current Gloo snapshot: [could not unmarshal raw object: parsing resource from crd spec gateway-proxy in namespace gloo-system into *v1.Gateway: unknown value "\"KEYVALUE\"" for enum dlp.options.gloo.solo.io.Action.ActionType]
```

### Expected Behavior

upgrade should succeed and be able to set the specified config on the gateway
