### ISSUE TITLE
Elasticache redis in cluster mode Could not execute Redis pipeline: MOVED

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#6577]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

When using elasticache redis  in cluster mode as ratelimit backend, the ratelimiting does not work and errors are logged.

### Steps to reproduce the bug

1. deploy EKS cluster
2. create elasticache redis in cluster mode without encryption and authentication
3. Deploy gloo and point it to the previously created redis 
```
redis:
  disabled: true
  service:
    name: test-cluster-mode.ap9uwo.clustercfg.euc1.cache.amazonaws.com
global:
    glooRedis:
      enableAcl: false
```
4. deploy a service and apply a ratelimit configuration on it
5. query virtualservice more times than ratelimit specified and you still get 200 and error message are logged

### Expected Behavior

I expect to get `429` after reaching the limit and no error message logged.

### Additional Context

This happened after customer's upgrade from 1.10.0 to 1.11.20. In 1.10.0 similar error messages are logged, but the ratelimit is applied properly. Attaching logs from both tested versions for comparison

[1-10-cluster-mode-ratelimit.log](https://github.com/solo-io/gloo/files/8920515/1-10-cluster-mode-ratelimit.log)

[1-11-20-cluster-mode-ratelimit.log](https://github.com/solo-io/gloo/files/8920516/1-11-20-cluster-mode-ratelimit.log)
