### ISSUE TITLE
error in api doc

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#658]
TransformationTemplate doc says headers are of type `map<string, string>`

```yaml
transformationTemplate:
  headers:
    x-foo: bar
```

https://gloo.solo.io/v1/github.com/solo-io/gloo/projects/gloo/api/v1/plugins/transformation/transformation.proto.sk#transformationtemplate

but proto says it's of type map<string, InjaTemplate>

```yaml
transformationTemplate:
  headers:
    x-foo:
      text: bar
```

https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/plugins/transformation/transformation.proto#L45
