### ISSUE TITLE
glooctl check falsely reports missing authconfigs

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#6703]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

glooctl check reports valid and present authconfigs as unknown if 1 of authconfigs is misconfigured.

```
$ glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... 1 Errors!
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... 2 Errors!
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
Error: 3 errors occurred:
	* Found rejected auth config by 'gloo-system': gloo-system opa (Reason: 1 error occurred:
	* failed to translate ext auth config: list did not find artifact test-system.allow-get-users

)
	* Virtual service references unknown auth config:
  Virtual service: gloo-system opa-vs
  Auth Config: gloo-system opa

	* Virtual service references unknown auth config:
  Virtual service: gloo-system vs-1
  Auth Config: gloo-system basic-auth-1

```

### Steps to reproduce the bug

1. Create 2 authconfigs, 1 of them pointing to non-existent opa policies configmap
```
kubectl apply -f- <<EOF
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: basic-auth-1
  namespace: gloo-system
spec:
  configs:
  - basicAuth:
      apr:
        users:
          user:
            hashedPassword: 8BvzLUO9IfGPGGsPnAgSu1
            salt: TYiryv0/
---
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: opa
  namespace: gloo-system
spec:
  configs:
  - opaAuth:
      modules:
      - name: allow-get-users
        namespace: test-system
      query: data.test.allow == true
EOF
```
2. Create 1 vs per authconfig
```
kubectl apply -f -<<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: opa-vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - opa.local
    options:
      extauth:
        configRef:
          name: opa
          namespace: gloo-system
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs-1
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - vs-1.local
    options:
      extauth:
        configRef:
          name: basic-auth-1
          namespace: gloo-system
    routes:
    - routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
EOF
```
3. Run glooctl check and observe it report Error for both virtualservices, even though vs with basic-auth works fine and it's status is accepted.
```
$ glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... 1 Errors!
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... 2 Errors!
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
Error: 3 errors occurred:
	* Found rejected auth config by 'gloo-system': gloo-system opa (Reason: 1 error occurred:
	* failed to translate ext auth config: list did not find artifact test-system.allow-get-users

)
	* Virtual service references unknown auth config:
  Virtual service: gloo-system opa-vs
  Auth Config: gloo-system opa

	* Virtual service references unknown auth config:
  Virtual service: gloo-system vs-1
  Auth Config: gloo-system basic-auth-1

$ kubectl get vs vs-1 -n gloo-system -o jsonpath={.status}|jq -r .
{
  "statuses": {
    "gloo-system": {
      "reportedBy": "gateway",
      "state": 1,
      "subresourceStatuses": {
        "*v1.Proxy.gateway-proxy_gloo-system": {
          "reportedBy": "gloo",
          "state": 1
        }
      }
    }
  }
}
$ kubectl get authconfig basic-auth-1 -n gloo-system -o jsonpath={.status}|jq -r .
{
  "statuses": {
    "gloo-system": {
      "reportedBy": "gloo",
      "state": 1
    }
  }
}
```

### Expected Behavior

To not report the working and accepted authconfig as unknown.
