### ISSUE TITLE
GraphQL Getting Started Guide fails at first service invocation

### ISSUE THREAD

**Issue by jameshbarton** [solo-io/gloo#6721]
### Version

master

### Describe the requested changes

# Describe the bug
In following along with the [GraphQL Getting Started guide](https://docs.solo.io/gloo-edge/master/guides/graphql/getting_started/), the first service call results in a 404 error instead of returning the petstore inventory.

# Steps to reproduce the bug
1. Install Edge Enterprise.
```
glooctl install gateway enterprise \
  --license-key $GLOO_KEY \
  --version v1.12.0-beta12
```

2. Deploy Petstore sample app (copied directly from doc page).
```
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petstore
  name: petstore
  namespace: default
spec:
  selector:
    matchLabels:
      app: petstore
  replicas: 1
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - image: openapitools/openapi-petstore
        name: petstore
        env:
          - name: DISABLE_OAUTH
            value: "1"
          - name: DISABLE_API_KEY
            value: "1"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: default
  labels:
    service: petstore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: petstore
EOF
```

3. Deploy default VS as per docs - jumping to [this link](https://docs.solo.io/gloo-edge/master/guides/security/auth/custom_auth/#setup) as per Step 2.1 in GraphQL doc
```
kubectl apply -f - <<EOF
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
EOF
```

4. Curling endpoint as documented [here](https://docs.solo.io/gloo-edge/master/guides/security/auth/custom_auth/#setup) yields a 404 rather than the inventory of the petstore.
```
% curl $(glooctl proxy url)/api/pets/
{"timestamp":"2022-07-08T19:12:51.793Z","status":404,"error":"Not Found","message":"No message available","path":"/api/pets/"}
```

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/master/guides/graphql/getting_started/
