### ISSUE TITLE
ArgoCD endless sync loop due to one Job

### ISSUE THREAD

**Issue by antonioberben** [solo-io/gloo#6729]
### Gloo Edge Version

1.11.x (latest stable)

### Describe the bug

When running an upgrade from `1.11.26` to `1.11.27` with ArgoCD, there is a job which makes Argo to stay in the sync loop forever, so that it cannot mark the upgrade as successful.

### Steps to reproduce the bug

Having a clean cluster:
1. install argo:
```
kubectl create ns argocd

kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml 
```

2. Wait until pods are running
3. get the password:
```
kubectl get secret argocd-initial-admin-secret -n argocd -ojsonpath={.data.password} | base64 -d
```
4. Access the ui and enter user `admin` password `THE ONE FROM COMMAND BEFORE`
5. Go to applications (it should be empty at first):
![image](https://user-images.githubusercontent.com/5262332/178684630-f6f86048-1adc-43e2-944b-99942b7d0909.png)
6. install GE version `1.11.26` through argo:
```
kubectl apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-oss
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-ee
    helm:
      releaseName: gloo-ee
      values: |
        # no values takes the default values.yaml
    repoURL: http://storage.googleapis.com/gloo-ee-helm
    targetRevision: 1.11.26 # <---------------- HERE THE VERSION!!!!!!!!!!!
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF
```
7. Wait until release is finished and everything is running
8. Check that in argo you see it OK
![image](https://user-images.githubusercontent.com/5262332/178686912-53e88e89-db52-4584-93d5-48e98a5baf97.png)

9. Update the version and apply again the resource:
```
kubectl apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge-oss
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: gloo-ee
    helm:
      releaseName: gloo-ee
      values: |
        # no values takes the default values.yaml
    repoURL: http://storage.googleapis.com/gloo-ee-helm
    targetRevision: 1.11.27  # <---------------- HERE THE VERSION!!!!!!!!!!!
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF
```
10. sync process will start immediately but it will hang forever
![image](https://user-images.githubusercontent.com/5262332/178687568-d7f0fccf-0dec-42cb-be0c-3fe7b7242173.png)

### Expected Behavior

The upgrade process finishes successfully

### Additional Context

Comparing to other Jobs which do not make Argo hang, the only difference is that

From this Job which works `gloo-ee-1.11.27/charts/gloo/templates/6.5-gateway-certgen-job.yaml`, the hooks are:
```
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded
```

But in the failing Job `gloo-ee-1.11.27/charts/gloo/templates/5-resource-migration-job.yaml`, the hooks look like:
```
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "3" # run this job after the role/rolebinding is created, and before the validation webhook is upgraded
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
```
