### ISSUE TITLE
HTTP health check values not honoured in endpoints HC config

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6770]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

Given a static Upstream with HTTP Health Check settings, as follow:

```yaml
kind: Upstream
apiVersion: gloo.solo.io/v1
metadata:
  name: static-us
  namespace: gloo-system
spec:
  static:
    hosts:
    - addr: 10.21.18.118
      port: 80
  healthChecks:
  - healthyThreshold: 3
    httpHealthCheck:
      host: sample.domain.com ## <-- NOT BEING HONOURED
      path: /
    interval: 1s
    timeout: 1s
    unhealthyThreshold: 3
```

In the generated Envoy config, we can see the following endpoint settings:

```json
{
     "version_info": "6599169848059923481",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "static-us_gloo-system",
      "type": "STATIC",
      "connect_timeout": "5s",
      "health_checks": [
       {
        "timeout": "1s",
        "interval": "1s",
        "unhealthy_threshold": 3,
        "healthy_threshold": 3,
        "http_health_check": {
         "host": "sample.domain.com",
         "path": "/"
        }
       }
      ],
      "metadata": {},
      "load_assignment": {
       "cluster_name": "static-us_gloo-system",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "10.21.18.118",
              "port_value": 80
             }
            },
            "health_check_config": {
             "hostname": "10.21.18.118" // <------- HERE
            },
            "hostname": "10.21.18.118"
           },
           "metadata": {
            "filter_metadata": {
             "envoy.transport_socket_match": {
              "10.21.18.118;10.21.18.118:80": true
             }
            }
           }
          }
         ]
        }
       ]
      }
     },
     "last_updated": "2022-07-19T14:22:36.795Z"
    }
```

### Steps to reproduce the bug

see above.

### Expected Behavior

Endpoint's HC config should be inherited from cluster HC config:

Currently:
```json
"health_check_config": {
             "hostname": "10.21.18.118"
            },
````

Expected:
```json
"health_check_config": {
             "hostname": "sample.domain.com"
            },
```

### Additional Context

Current code: https://github.com/solo-io/gloo/blob/a0a2c016cbf9dbe56b910c1f8b0e42eca9de0f21/projects/gloo/pkg/plugins/static/plugin.go#L123
