### ISSUE TITLE
limit function discovery probing with service and namespace annotations

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#678]
currently, function discovery attempts to discover `swagger.json` endpoint on *every service in the cluster*. this leads to undesired behavior and strange logs in some services, e.g. with the knative actuator as referenced in #677 

we should support the use of the annotation:

```yaml
metadata:
  annotations:
    gloo.solo.io/fds: disabled
```

on *upstreams* and *namespaces* which FDS will use to skip probing those services / services in those namespaces.
