### ISSUE TITLE
AutoMapFromMetadata feature in AuthConfig not working

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#6782]
### Gloo Edge Version

1.12.x (beta)

### Describe the bug

When AutoMapFromMetadata is configured, dynamic metadata values in the specified namespace shouldl be mapped to query params on requests made to the OIDC auth endpoint and the OIDC token endpoint. However, I'm not seeing those query params added.

### Steps to reproduce the bug

1.  Create AuthConfig:
```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oauth-httpbin
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: https://httpbin.mysolo.io/
        authEndpointQueryParams:
          authEndPointKey: authEndpointValue
        autoMapFromMetadata:
          namespace: solo_authconfig_oidc
        callbackPath: /callback
        clientId: <redacted>
        clientSecretRef:
          name: oauth
          namespace: gloo-system
        headers:
          idTokenHeader: jwt
        issuerUrl: http://35.243.161.53:8080/auth/realms/master/
        logoutPath: /logout
        scopes:
        - email
        session:
          cookieOptions:
            domain: mysolo.io
          failOnFetchFailure: true
          redis:
            cookieName: session
            options:
              host: redis.gloo-system.svc.cluster.local:6379
        tokenEndpointQueryParams:
          tokenEndpointKey: tokenEndpointValue
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: 1
```
2. Create VS. 
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
  virtualHost:
    domains:
    - httpbin.mysolo.io
    options:
      extauth:
        configRef:
          name: oauth-httpbin
          namespace: gloo-system
      stagedTransformations:
        early:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                dynamicMetadataValues:
                - key: tenantid
                  metadataNamespace: solo_authconfig_oidc
                  value:
                    text: mytenantid
                - key: spaceid
                  metadataNamespace: solo_authconfig_oidc
                  value:
                    text: myspaceid
                extractors:
                  spaceid:
                    header: :path
                    regex: ^\/(.*)\/uat\/(.*)$
                    subgroup: 2
                  tenantid:
                    header: :path
                    regex: ^\/(.*)\/uat\/(.*)$
                    subgroup: 1
                headers:
                  spaceid:
                    text: '{{ spaceid }}'
                  tenantid:
                    text: '{{ tenantid }}'
    routes:
    - matchers:
      - regex: /.*/uat/.*
      options:
        autoHostRewrite: true
        prefixRewrite: /get
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
    - matchers:
      - prefix: /
      options:
        autoHostRewrite: true
        prefixRewrite: /get
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: 1
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reportedBy: gloo
          state: 1
```

hit the endpoint.  When it forwards you the idp, there query params aren't added.

### Expected Behavior

Expected to have the query parameters in the url.

### Additional Context

Logs from the extauth server:
```
{"level":"debug","ts":1658412081.1268353,"logger":"ext-auth.ext-auth-service","msg":"Full Issuer request url is http://35.243.161.53:8080/auth/realms/master/protocol/openid-connect/auth?authEndPointKey=authEndpointValue&client_id=<REDACTED>&redirect_uri=https%3A%2F%2Fhttpbin.mysolo.io%2Fcallback&response_type=code&scope=email+openid&state=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTg0MTM4ODEsImlhdCI6MTY1ODQxMjA4MSwic3RhdGUiOiJodHRwczovL2h0dHBiaW4ubXlzb2xvLmlvLyJ9.gqC8WX5E0443WKoX6vlrXesJ_K00x3uyMb2irhkYY_c","version":"undefined","x-request-id":"34c00a3b-dec7-4051-a7af-159ac93c023a"}
```
