### ISSUE TITLE
WASM FilterStage not being respected for pre Authz and Authn

### ISSUE THREAD

**Issue by genslein** [solo-io/gloo#6784]
### Gloo Edge Version

1.11.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

We use a WASM filter to collect metadata prior to Authz and Authn. However this is not being respected and we lose our metadata if Authz or Authn rejects the request 

https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/wasm/wasm.proto.sk/#filterstage

### Steps to reproduce the bug

Scenarios:

```yaml
      wasm:
        filters:
        - config:
            '@type': type.googleapis.com/google.protobuf.StringValue
            value: |
              {
                "metrics": "true"
              }
          filePath: /wasm-filters/request.metrics.go.wasm
...
          filterStage:
            predicate: Before
            stage: AuthNStage
...
          filterStage:
            predicate: After
            stage: AuthNStage
...
          filterStage:
            predicate: Before
            stage: AuthZStage
...
          filterStage:
            predicate: After
            stage: AuthZStage
```

### Expected Behavior

When we expect the  `filterStage` to be set, we expect to record 401 and 403 responseCode information in the WASM plugin.

This currently does not happen among any of these scenarios.
