### ISSUE TITLE
Provide more flexibility to ExtAuth for OAuth2 use cases not using OIDC

### ISSUE THREAD

**Issue by ky-rafaels** [solo-io/gloo#6925]
### Version

1.12.x (beta)

### Is your feature request related to a problem? Please describe.

Fitch has plans in 2023 to move towards OIDC for their current OAuth provider that was built in-house on Java spring security framework. 

https://soloio.slab.com/posts/fitch-shared-auth-44jvdrdv

### Describe the solution you'd like

I'd like to consider the possibility of providing an override so extauth does not automatically look for /.well-known/openid-configuration endpoint on the OAuth server. I'd like to provide all needed parameters in the authconfig such as:

```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: httpbin-oauth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        appUrl: "https://httpbin.gloo.fitchconnect-dev.com/"
        callbackPath: /callback
        clientId: l9rnegq0bdrr1dhr7omiro4kun 
        clientSecretRef:
          name: httpbin-client-secret
          namespace: gloo-system
        issuerUrl: "https://login.gloo.fitchconnect-dev.com/"
        discoveryOverride:
          jwksUri: https://login.gloo.fitchconnect-dev.com/jwks.json
          introspectionEndpoint: https://login.gloo.fitchconnect-dev.com/oauth/check_token
.....
```

Currently evaluating the possibility of creating a dummy /.well-known/openid-configuration endpoint on OAuth server and then overriding the parameters in the discoveryOverride. Customer however would like to see the possibility of not having to make any current code changes to their OAuth implementation

### Describe alternatives you've considered

https://soloio.slab.com/posts/fitch-shared-auth-44jvdrdv#hhyyz-possible-workarounds

The slab doc lists the possible workarounds that have been attempted. 

### Additional Context

See slab document for workarounds tried and considered

https://soloio.slab.com/posts/fitch-shared-auth-44jvdrdv
