### ISSUE TITLE
Helm - expose Gloo's option removeUnusedFilters

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#6940]
### Is your feature request related to a problem? Please describe.

expose in Helm the Gloo setting named `removeUnusedFilters`

**Comment by sam-heilbron** [comment]
@bcollard Since the Settings support [KubeResourceOverrides](https://github.com/solo-io/gloo/blob/26e84f03aad4f41da5e008a1dc661df8daba9586/install/helm/gloo/generate/values.go#L196), is it possible to set this value using that field?

**Comment by bcollard** [comment]
yes, it works with overrides:
```yaml 
gloo:
  settings:
    kubeResourceOverride:
      spec:
        gloo:
          removeUnusedFilters: true
```
Thanks for the reminder!
