### ISSUE TITLE
Helm template generator not pulling all values from input templates

### ISSUE THREAD

**Issue by scranton** [solo-io/gloo#696]
Related to #694

The Helm Template generator is not intuitively processing source templates, ie., it's dropping some fields with no clear pattern. Need to clean up generator such that it intuitively translates fields such that there are no future surprises.

Ideally, the generator should also translate over comments as well.

For example, in source `values-gateway-template.yaml`

```
settings:
  # if this is set to false, default settings will be created by pods upon boot
  create: false
  integrations:
    knative:
      enabled: false
  # namespaces that Gloo should watch. this includes watches set for pods, services, as well as CRD configuration objects
  watchNamespaces: []
  # the namespace that Gloo should write discovery data (Upstreams)
  writeNamespace: "gloo-system"
```

gets translated to

```
settings:
  integrations:
    knative:
      enabled: false
  writeNamespace: gloo-system
```

dropping the `create: false` and empty `watchNamespaces` list.
