### ISSUE TITLE
Upstream validation error with useHttp2 and maxStreamDuration

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#6983]
### Gloo Edge Version

1.11.x

### Describe the bug

Combining `useHttp2` and `maxStreamDuration` results in 

```
status:
  statuses:
    gloo-system:
      reason: "warning: \n  1 error occurred:\n\t* Both HTTP1 and HTTP2 options may
        only be configured with non-default 'Upstream_USE_DOWNSTREAM_PROTOCOL' specified
        for Protocol Selection\n\n"
      reportedBy: gloo
      state: 3
```

### Steps to reproduce the bug

Create this upstream:

```
spec:
  connectionConfig:
    commonHttpProtocolOptions:
      maxStreamDuration: 600s
  discoveryMetadata:
    labels:
      app: grpc-helloworld
      service: grpc-helloworld
  kube:
    selector:
      app: grpc-helloworld
    serviceName: grpc-helloworld
    serviceNamespace: default
    servicePort: 50051
  useHttp2: true
```

### Expected Behavior

These 2 settings should be compatible
