### ISSUE TITLE
gloo-envoy crash

### ISSUE THREAD

**Issue by ashishb-solo** [solo-io/gloo#7023]
### Gloo Edge Version

1.12.x (latest stable)

### Describe the bug

gloo-ee version 1.12.9

Envoy crashes in gloo-ee when applying the following yaml:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-httpbin-8000
            namespace: gloo-system
```

```yaml
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: default-httpbin-8000
  namespace: gloo-system
spec:
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      path: /status/200
      responseAssertions:
        noMatchHealth: degraded
        responseMatchers:
        - matchHealth: unhealthy
          responseMatch:
            body: {}
            jsonKey:
              path:
              - key: origin
            regex: ^10\.8\.0\.20$
            # regex: ^"10.8.0.20"$
    interval: 9s
    noTrafficInterval: 2s
    timeout: 1s
    unhealthyThreshold: 2
    reuseConnection: false
  discoveryMetadata:
    labels:
      app: httpbin
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    serviceNamespace: default
    servicePort: 8000
```

Possibly related to https://github.com/solo-io/gloo/issues/6138

### Steps to reproduce the bug

1. Instantiate cluster as above and apply yaml
2. Change the regex to the commented version and reapply the yaml file
3. Envoy should report a crash

### Expected Behavior

expect envoy to not crash
