### ISSUE TITLE
Gloo-Fed federation errors - "Failed to list resource"

### ISSUE THREAD

**Issue by Ido-Itz** [solo-io/gloo#7024]
### Gloo Edge Version

1.11.x

### Kubernetes Version

1.23.x

### Describe the bug

Since upgrading to gloo-fed v1.11.33 when the gloo-fed controller attempts to reconcile the `FederatedUpstream` and `FederatedVirtualService` resources in the cluster, it will sporadically fail to federate and evaluate the status of resources with the following error:

```yaml
status:
  placementStatus:
    clusters:
      bnre-ba-gateway:
        namespaces:
          disaster:
            message: Failed to list upstream on cluster bnre-ba-gateway.
            state: FAILED
    message: Resource is not federated to all destinations
    observedGeneration: 1
    state: FAILED
    writtenBy: gloo-fed-5cfb8db986-4lmlr
```

And the same for `FederatedVirtualServices` with "Failed to list virtual service ..."

After these errors, it looks like gloo-fed won't try to reconcile these resources again, and they remain stuck in this broken state.

This also happens to resources that were already `PLACED` before a gloo-fed restart, but the reconcile will invalidate their status and move them to a `FAILED` state, despite the actual status being positive.

This essentially creates a situation where if all upstreams but upstream A were `PLACED`, a gloo-fed restart could then make A `PLACED` but move B into a `FAILED` state. In a situation like this, and with enough upstreams/virtualServices, it's almost impossible to move the system to a healthy state.

### Steps to reproduce the bug

1. Create multiple federated upstreams and virtual services with placements on multiple remote clusters
2. Upgrade gloo-fed to v1.11.33

### Expected Behavior

1. Gloo-Fed should successfully reconcile all of the federated resources to the remote clusters.
2. Gloo-Fed should (probably) not remove a positive status from a resource that was already `PLACED` in the past, in case it was unable to verify the placement after the controller was restarted.
