### ISSUE TITLE
`failureModeAllow` is ignored

### ISSUE THREAD

**Issue by omerlh** [solo-io/gloo#7089]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

I'm installing Gloo with the helm chart. I tried setting `failureModeAllow` like this:
```
global:
  extensions:
    extAuth:
      failureModeAllow: false
```

But I can see the changes are not reflected in the actual envoy config generated (dumped using `glooctl proxy served-config`):
```
- name: envoy.filters.http.ext_authz
        typedConfig:
          '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
          httpService:
            pathPrefix: <>
            serverUri:
              cluster: <>
              timeout: 0.500s
              uri: http://not-used.example.com/
          metadataContextNamespaces:
          - envoy.filters.http.jwt_authn
          transportApiVersion: V3
```

### Steps to reproduce the bug

Deploy gloo like mentioned above and check the config

### Expected Behavior

Envoy config should honor the `failureModeAllow` config value
