### ISSUE TITLE
upstream settings USE_DOWNSTREAM_PROTOCOL not working

### ISSUE THREAD

**Issue by DoroNahari** [solo-io/gloo#7096]
### Gloo Edge Version

1.11.x

### Kubernetes Version

1.24.x

### Describe the bug

When configuring an upstream to support http2 with the configuration USE_DOWNSTREAM_PROTOCOL, It seems that it doesn't use the downstream protocol.

### Steps to reproduce the bug

- upstream:
```
spec:
  protocolSelection: USE_DOWNSTREAM_PROTOCOL
  useHttp2: true
 # for example:
  static:
    hosts:
      - addr: httpbin.org
        port: 443
```
- a virtual service refering to this upstream:
```
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /
        options:
          autoHostRewrite: false
        routeAction:
          single:
            upstream:
              name: default-petstore-8080
              namespace: gloo-system
```
- gateway settings:
```
spec:
  bindAddress: '::'
  bindPort: 8443
  httpGateway: {}
  proxyNames:
    - gateway-proxy
  ssl: true
  useProxyProto: false
```

by executing a request to the virtual service with http1.1 we expect that the connection between envoy to the upstream will be with http1.1 (because of the USE_DOWNSTREAM_PROTOCOL) but this is done with http2.
by checking the metric `upstream_cx_http2_total`\`upstream_cx_http1_total` or by checking a custom upstream server logs we can see that this is not the behavior.
