### ISSUE TITLE
metadata_context_namespaces not extract from routes on translation

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#7130]
### Gloo Edge Version

1.11.x

### Describe the bug

When specifying the `dynamicMetadataValues` in a transformation at the route level, the metadata_context_namespaces is not correctly updated.  When the transformation is specified at the VirtualService level it's correctly extracted.

### Steps to reproduce the bug

1.   Apply : 
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
  virtualHost:
    domains:
    - my-solo.io
    options:
      extauth:
        configRef:
          name: oauth
          namespace: gloo-system
    routes:
    - matchers:
      - regex: /.*/uat/.*
      options:
        autoHostRewrite: true
        prefixRewrite: /get
        stagedTransformations:
          early:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  dynamicMetadataValues:
                  - key: tenantid
                    metadataNamespace: solo_authconfig_oidc
                    value:
                      text: '{{ tenantid }}'
                  - key: spaceid
                    metadataNamespace: solo_authconfig_oidc
                    value:
                      text: '{{ spaceid }}'
                  extractors:
                    spaceid:
                      header: :path
                      regex: ^\/(.*)\/uat\/(.*)$
                      subgroup: 2
                    tenantid:
                      header: :path
                      regex: ^\/(.*)\/uat\/(.*)$
                      subgroup: 1
                  headers:
                    spaceid:
                      text: '{{ spaceid }}'
                    tenantid:
                      text: '{{ tenantid }}'        
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
    - matchers:
      - prefix: /
      options:
        autoHostRewrite: true
        prefixRewrite: /get
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
```

```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oauth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        autoMapFromMetadata:
          namespace: solo_authconfig_oidc 
        appUrl: https://my-solo.io
        callbackPath: /callback
        clientId: ${client}
        clientSecretRef:
          name: oauth
          namespace: gloo-system
        issuerUrl: "${KEYCLOAK_URL}/realms/master/"
        scopes:
        - email
        headers:
          idTokenHeader: jwt
        logoutPath: /logout
        session:
          failOnFetchFailure: true
          cookieOptions:
            domain: my-solo.io
          redis:
            cookieName: session
            options:
              host: redis.gloo-system.svc.cluster.local:6379          
```

2.  Gather a config dump and search for `metadata_context_namespaces`

```
{
              "name": "envoy.filters.http.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "extauth_gloo-system"
                },
                "timeout": "0.200s"
               },
               "metadata_context_namespaces": [
                "envoy.filters.http.jwt_authn"
               ],
               "transport_api_version": "V3"
              }
```

However, if the transformation is on the vs level:

```
  spec:
    sslConfig:
      secretRef:
        name: upstream-tls
        namespace: gloo-system
    virtualHost:
      domains:
      - my-solo.io
      options:
        extauth:
          configRef:
            name: oauth
            namespace: gloo-system
        stagedTransformations:
          early:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  dynamicMetadataValues:
                  - key: tenantid
                    metadataNamespace: solo_authconfig_oidc
                    value:
                      text: '{{ tenantid }}'
                  - key: spaceid
                    metadataNamespace: solo_authconfig_oidc
                    value:
                      text: '{{ spaceid }}'
                  extractors:
                    spaceid:
                      header: :path
                      regex: ^\/(.*)\/uat\/(.*)$
                      subgroup: 2
                    tenantid:
                      header: :path
                      regex: ^\/(.*)\/uat\/(.*)$
                      subgroup: 1
                  headers:
                    spaceid:
                      text: '{{ spaceid }}'
                    tenantid:
                      text: '{{ tenantid }}'
      routes:
      - matchers:
        - regex: /.*/uat/.*
        options:
          autoHostRewrite: true
          prefixRewrite: /get
        routeAction:
          single:
            upstream:
              name: httpbin-httpbin-8000
              namespace: gloo-system
      - matchers:
        - prefix: /
        options:
          autoHostRewrite: true
          prefixRewrite: /get
        routeAction:
          single:
            upstream:
              name: httpbin-httpbin-8000
```

The config_dump has the namespace in that field:
```
             {
              "name": "envoy.filters.http.ext_authz",
              "typed_config": {
               "@type": "type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz",
               "grpc_service": {
                "envoy_grpc": {
                 "cluster_name": "extauth_gloo-system"
                },
                "timeout": "0.200s"
               },
               "metadata_context_namespaces": [
                "envoy.filters.http.jwt_authn",
                "solo_authconfig_oidc"
               ],
               "transport_api_version": "V3"
              }
```
                           

### Expected Behavior

Both route and vs transformation should work the same.
