### ISSUE TITLE
ExtAuth failOnRedirect doesn't work

### ISSUE THREAD

**Issue by bcollard** [solo-io/gloo#7167]
### Gloo Edge Version

1.11.x

### Kubernetes Version

1.23.x

### Describe the bug

Given an AuthConfig with two steps, as in:

```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: keycloak-oauth
  namespace: gloo-system
spec:
  booleanExpr: "(oidc || passthrough)"
  configs:
  - name: oidc
    oauth2:
      oidcAuthorizationCode:
        appUrl: https://mydomain.com
        callbackPath: /callback
        clientId: dd99ff5a-5e5f-41ac-b080-7136e43f8e8c
        clientSecretRef:
          name: keycloak-oauth
          namespace: gloo-system
        issuerUrl: http://172.18.1.2:8080/auth/realms/master/
        scopes:
        - email
  - name: passthrough
    passThroughAuth:
      http:
        url: http://http-echo.default.svc:8080
  failOnRedirect: true
```

If the end-user is not logged in, then Keycloack will return a 302 to the login page.
We expect the `failOnRedirect: true` option to prevent this behavior and return a 401 instead.
This is not happening.

### Steps to reproduce the bug

see above

### Expected Behavior

401 HTTP status
