### ISSUE TITLE
Allow custom liveness probe definition

### ISSUE THREAD

**Issue by TheMakboul** [solo-io/gloo#7195]
### Version

1.11.x

### Is your feature request related to a problem? Please describe.

We have a need to define our own livenessProbe on the gateway-proxy pods, but currently the field exposed related to the livenessProbe (`livenessProbeEnabled`) is a binary value and doesn't allow for customization  

### Describe the solution you'd like

Similar to `customReadinessProbe` please expose a `customLivenessProbe` field that can be used to define a custom probe value that will be supported in the helm chart. 

The helm values would be defined as 
```
gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        probes: true
        gracefulShutdown:
          enabled: true
          sleepTimeSeconds: 30
        customLivenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
        customReadinessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
```

The helm chart would be updated to support this value 
```
{{- if $spec.podTemplate.customLivenessProbe }}
{{ toYaml $spec.podTemplate.customLivenessProbe | indent 10}}
{{- else }}
        livenessProbe:
          exec:
            command:
            - wget
            - -O
            - /dev/null
            - {{ $spec.loopBackAddress }}:19000/server_info
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 10
{{- end}}
```

### Describe alternatives you've considered

We've used kustomize as a post-renderer once the helm generates the templates.
