### ISSUE TITLE
Cached responses are not used

### ISSUE THREAD

**Issue by huzlak** [solo-io/gloo#7226]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.24.x

### Describe the bug

While testing caching-service feature, it looks like the cached response is never actually used, no Age header calculated. Always new response is returned and corresponding key body value updated in redis.

### Steps to reproduce the bug

1. Deploy gloo with caching-service enabled.
3. Deploy a single copy of backend used in https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache published via a vs:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: service1
  name: service1
spec:
  containers:
  - image: ghcr.io/huzlak/caching-service:0.2
    name: service1
    ports:
    - name: http
      containerPort: 8000
    readinessProbe:
      httpGet:
        port: 8000
        path: /service/1/no-cache

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
    - port: 8000
      name: http
      targetPort: http
  selector:
    app: service1

---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: "test-cache-us"
  namespace: "gloo-system"
spec:
    kube:
      serviceName: service1
      serviceNamespace: default
      servicePort: 8000

---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: cache-test-vs
  namespace: gloo-system
spec:
  virtualHost:
    routes:
      - matchers:
          - prefix: /
        routeAction:
          single:
            upstream:
              name: test-cache-us
              namespace: gloo-system
```
5. call the service several times on `/service/1/valid-for-minute` path
```
$ curl $(glooctl proxy url)/service/1/valid-for-minute -i -H "Cache-Control: max-age=60"
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 99
cache-control: max-age=60
custom-header: any value
etag: "324ce9104e113743300a847331bb942ab7ace81a"
date: Fri, 23 Sep 2022 14:11:39 GMT
server: envoy
x-envoy-upstream-service-time: 1

This response will stay fresh for one minute

Response generated at: Fri, 23 Sep 2022 14:11:39 GMT
$ curl $(glooctl proxy url)/service/1/valid-for-minute -i -H "Cache-Control: max-age=60"
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 99
cache-control: max-age=60
custom-header: any value
etag: "324ce9104e113743300a847331bb942ab7ace81a"
date: Fri, 23 Sep 2022 14:11:42 GMT
server: envoy
x-envoy-upstream-service-time: 1

This response will stay fresh for one minute

Response generated at: Fri, 23 Sep 2022 14:11:42 GMT
$ curl $(glooctl proxy url)/service/1/valid-for-minute -i -H "Cache-Control: max-age=60"
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 99
cache-control: max-age=60
custom-header: any value
etag: "324ce9104e113743300a847331bb942ab7ace81a"
date: Fri, 23 Sep 2022 14:11:44 GMT
server: envoy
x-envoy-upstream-service-time: 1

This response will stay fresh for one minute

Response generated at: Fri, 23 Sep 2022 14:11:44 GMT
$
```
6. Always get new response with new time as seen above. No Age header generated and also cache entry is udpated in redis with every request.
7. Logs from backend service pods when going through gloo: 
```
10.101.0.45 - - [23/Sep/2022 15:28:38] "GET /service/1/valid-for-minute HTTP/1.1" 200 -
10.101.0.45 - - [23/Sep/2022 15:28:39] "GET /service/1/valid-for-minute HTTP/1.1" 200 -
10.101.0.45 - - [23/Sep/2022 15:28:40] "GET /service/1/valid-for-minute HTTP/1.1" 200 -
10.101.0.45 - - [23/Sep/2022 15:28:41] "GET /service/1/valid-for-minute HTTP/1.1" 200 -
10.101.0.45 - - [23/Sep/2022 15:28:42] "GET /service/1/valid-for-minute HTTP/1.1" 200 -
10.101.0.45 - - [23/Sep/2022 15:28:43] "GET /service/1/valid-for-minute HTTP/1.1" 200 -
```

### Expected Behavior

When `max-age=60` header is returned, I expect the cached response to be returned. `date` header to stay the same for next 60s. and Age header available in response. This works as expected when trying basic [exmaple](https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/cache) with envoy sandbox, which uses the same backend service: 

```
$ curl localhost:8000/service/1/valid-for-minute -i
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 99
cache-control: max-age=60
custom-header: any value
etag: "324ce9104e113743300a847331bb942ab7ace81a"
date: Fri, 23 Sep 2022 15:18:56 GMT
server: envoy
x-envoy-upstream-service-time: 2

This response will stay fresh for one minute

Response generated at: Fri, 23 Sep 2022 15:18:56 GMT
$ curl localhost:8000/service/1/valid-for-minute -i
HTTP/1.1 200 OK
content-type: text/html; charset=utf-8
content-length: 99
cache-control: max-age=60
custom-header: any value
etag: "324ce9104e113743300a847331bb942ab7ace81a"
date: Fri, 23 Sep 2022 15:18:56 GMT
server: envoy
x-envoy-upstream-service-time: 2
age: 12

This response will stay fresh for one minute

Response generated at: Fri, 23 Sep 2022 15:18:56 GMT
$ curl localhost:8000/service/1/valid-for-minute -i
HTTP/1.1 200 OK
cache-control: max-age=60
custom-header: any value
etag: "324ce9104e113743300a847331bb942ab7ace81a"
date: Fri, 23 Sep 2022 15:20:05 GMT
server: envoy
x-envoy-upstream-service-time: 2
content-length: 99
content-type: text/html; charset=utf-8

This response will stay fresh for one minute

Response generated at: Fri, 23 Sep 2022 15:18:56 GMT
$ curl localhost:8000/service/1/valid-for-minute -i
HTTP/1.1 200 OK
content-length: 99
etag: "324ce9104e113743300a847331bb942ab7ace81a"
cache-control: max-age=60
custom-header: any value
date: Fri, 23 Sep 2022 15:20:05 GMT
server: envoy
x-envoy-upstream-service-time: 2
content-type: text/html; charset=utf-8
age: 11

This response will stay fresh for one minute

Response generated at: Fri, 23 Sep 2022 15:18:56 GMT
$
```
Logs from backend service pod in the envoy sandbox scenario:
```
172.20.0.2 - - [23/Sep/2022 15:18:56] "GET /service/1/valid-for-minute HTTP/1.1" 200 -
172.20.0.2 - - [23/Sep/2022 15:20:05] "GET /service/1/valid-for-minute HTTP/1.1" 304 -
172.20.0.2 - - [23/Sep/2022 15:28:24] "GET /service/1/valid-for-minute HTTP/1.1" 304 -
```
