### ISSUE TITLE
Allow additional containers and initContainers on gateway-proxy deployments

### ISSUE THREAD

**Issue by TheMakboul** [solo-io/gloo#7247]
### Version

1.11.x

### Is your feature request related to a problem? Please describe.

We have a need to run gloo edge with additional containers and initContainers on the pods, and specifying these containers as part of the gloo config is not straight forward. A similar feature request is captured [here](https://github.com/solo-io/gloo/issues/5187), and this request expands upon this idea.

### Describe the solution you'd like

Solving for `initContainers`, a list would be specified as part of the values passed to the helm chart
```
gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        extraInitContainers:
          - command:
            - sh
            - -c
            - iptables -t nat -A OUTPUT -p tcp -d 127.0.0.1 --dport 8126 -j DNAT --to $DD_AGENT_HOST:8126
            env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            image: registry/iptables:1.0.0
            imagePullPolicy: IfNotPresent
            name: gloo-proxy-iptables
            resources: {}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                - NET_ADMIN
              runAsUser: 0
```

The helm template for the gateway-proxy deployment would be modified to read these values 
```
      {{- if $spec.podTemplate.extraInitContainers }}
      {{ toYaml $spec.podTemplate.extraInitContainers | indent 6}}
      {{- end }}
```

Similarly solving for `containers`, a list would be specified as part of the values passed to the helm chart
```
gloo:
  gatewayProxies:
    gatewayProxy:
      podTemplate:
        extraContainers:
          - name: extra-container 
            env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  key: address
                  name: vault-info
            image: IMAGE_PATH
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 200m
                memory: 256Mi
            startupProbe:
              failureThreshold: 10
              httpGet:
                path: /healthz
                port: 3001
              initialDelaySeconds: 10
              periodSeconds: 5
```

The helm template for the gateway-proxy deployment would be modified to read these values 
```
      {{- if $spec.podTemplate.extraContainers }}
      {{ toYaml $spec.podTemplate.extraContainers | indent 6}}
      {{- end }}
```

### Describe alternatives you've considered

We've tried specifying a `extraInitContainersHelper` or `extraContainersHelper` which required unpacking the helm chart and adding a helper file with named templates, and variable interpolation would still require the use of a post-renderer. Both of these are issues that I am trying to avoid. 

We've tried adding the desired containers via a post-renderer and Kustomize.
