### ISSUE TITLE
Istio Integration: Traffic Routed on Wrong Port resulting in 503 when Service Target Port is Different

### ISSUE THREAD

**Issue by murphye** [solo-io/gloo#7298]
### Gloo Edge Version

1.12.x (latest stable)

### Describe the bug

There seems to be a bug with the changes for https://github.com/solo-io/gloo/issues/6195 that only happens when the upstream `Service` definition has a `targetPort` (such as 8080) different than the `port` (such as 80). 

I believe the bug may be in this region of code, but I am not for sure: https://github.com/solo-io/gloo/pull/6441/files#diff-34a26dd6e5aa3b257ff21ab1575da112448f84063d4cbcfc01cc8e85a0b512bdR327

### Steps to reproduce the bug

1. Install Istio and Gloo Edge with the Istio sidecar enabled
2. Enable Access logging on both Gloo Edge and Istio
3. Create an upstream `Service` definition that has a `targetPort` (such as 8080) different than the `port` (such as 80). 
4. Create Gloo Edge VirtualService to route traffic to the upstream
5. Observe that a 503 error occurs
6. Observe the access logs

Workaround:
7. Add another `port` (such as 8080) that matches the `targetPort` (such as 8080) to the `Service`
8. No more 503 errors

Here is an example request that was failing from the Access logs:

```
[2022-10-05T18:03:39.662Z] "POST /authentication/refresh HTTP/2" 302 - 17 0 16 13 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0" "12b137ac-3d60-465d-9a90-26ed790dfb1f" "rp-ch-gateway.fg-rp-ch" "172.20.33.151:8080"
```
```
{"x_forwarded_for":null,"bytes_sent":91,"route_name":"allow_any","connection_termination_details":null,"response_code_details":"upstream_reset_before_response_started{connection_failure}","response_flags":"UF","authority":"rp-ch-gateway.fg-rp-ch","method":"GET","upstream_local_address":null,"duration":10004,"upstream_transport_failure_reason":null,"request_id":"d4493b58-fb44-43a7-9eb0-46bca8e7aa62","upstream_host":"172.20.33.151:8080","downstream_local_address":"172.20.33.151:8080","protocol":"HTTP/1.1","start_time":"2022-10-05T17:48:34.043Z","upstream_service_time":null,"response_code":503,"downstream_remote_address":"10.132.69.99:39622","path":"/","requested_server_name":null,"user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0","upstream_cluster":"PassthroughCluster","bytes_received":0}
```

In this case, `"upstream_host":"172.20.33.151:8080"` is the address of the service port. But for the `Service`, `8080` is the `targetPort` not the `port`. Therefore the request fails.

### Expected Behavior

Using services with a different `targetPort` should be supported. Our code may just be pulling the wrong port information or assuming they are always the same.

**Comment by ky-rafaels** [comment]
For reproducing, here is my Edge config (note gateway with sidecar injected):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitch-edge-enterprise
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gloo-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'http://storage.googleapis.com/gloo-ee-helm'
    targetRevision: 1.12.26
    helm:
      values: >
        global:
          istioIntegration:
            enableIstioSidecarOnGateway: true
            istioSidecarRevTag: 1-13
            disableAutoinjection: false
        create_license_secret: true

        license_key: '<license-key>'
        
        gloo:
          gateway:
            readGatewaysFromAllNamespaces: true
          license_secret_name: license
          gatewayProxies:
            aPrivateGw: # Proxy name for private access (intranet facing)
              namespace: corpgw
              disabled: false # overwrite the "default" value in the merge step
              service:
                httpPort: 80
                httpsFirst: false
                httpsPort: 443
                type: LoadBalancer
              gatewaySettings:
                accessLoggingService:
                  accessLog:
                  - fileSink:
                      path: /dev/stdout
                      stringFormat: ""
                customHttpGateway: # using the default HTTP Gateway
                  virtualServiceSelector:
                    gateway-type: private # label set on the VirtualService
                customHttpsGateway: # using the default HTTPS Gateway
                  virtualServiceSelector:
                    gateway-type: private # label set on the VirtualService
                disableHttpGateway: false # disable the default HTTP Gateway    
                disableHttpsGateway: false # disable the default HTTPS Gateway
            gatewayProxy:
              disabled: true # disable the default gateway-proxy deployment and its 2 default Gateway CRs
        observability:
          enabled: false
        prometheus:
          enabled: false
        gloo-fed:
          enabled: false
          create_license_secret: false
          glooFedApiserver:
            enable: false
    chart: gloo-ee
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
 ```
After also then deploying gloo mesh mgmt plane and registering a worker cluster, I have httpbin with a sidecar running on worker cluster. After exposing httpbin via virtualservice, viewing the istio-proxy logs on httpbin shows calls being made to k8s service IP with pod port. Changing svc to have matching targetPort and Port values resolves this
