### ISSUE TITLE
upstream healthcheck config causes SIGSEGV and gloo pod crash

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7302]
### Gloo Edge Version

1.12.x (latest stable)

### Describe the bug

upstream w/healthchecks below causes error below. Occurred when path was removed from the global healthcheck config:

```
spec:
  healthChecks:
  - alwaysLogHealthCheckFailures: true
    healthyThreshold: 1
    interval: 10s
    timeout: 5s
    unhealthyThreshold: 1
  loadBalancerConfig:
    healthyPanicThreshold: 90
  static:
    hosts:
    - addr: 172.31.4.251
      healthCheckConfig:
        path: /get
      port: 8080
    - addr: 172.31.16.225
      healthCheckConfig:
        path: /get
      port: 8080
    - addr: 172.31.5.244
      healthCheckConfig:
        path: /bogus
      port: 8080
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x33c0abb]

goroutine 692 [running]:
github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/advanced_http.convertEnvoyToGloo(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/workspace/solo-projects/projects/gloo/pkg/plugins/advanced_http/plugin.go:198 +0xbb
github.com/solo-io/solo-projects/projects/gloo/pkg/plugins/advanced_http.(*plugin).ProcessUpstream(0x6982bc0, 0x4e65a20, 0xc0033b4ff0, 0xc001474780, 0xc002519960, 0xc0033bf400, 0x0, 0x0)
	/workspace/solo-projects/projects/gloo/pkg/plugins/advanced_http/plugin.go:95 +0x31d
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeCluster(0xc002798f08, 0x4e65a20, 0xc0033b4ff0, 0xc001474780, 0xc002519960, 0xc002d2e0c0, 0xc002d19f50, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/translator/clusters.go:65 +0x22f
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).computeClusters(0xc002798f08, 0x4e65a20, 0xc002d2e270, 0xc001474780, 0xc002d19f50, 0xc002d2e0c0, 0xc0015c7c20, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/translator/clusters.go:47 +0x39f
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).translateClusterSubsystemComponents(0xc002798f08, 0x4e65a20, 0xc002d19a10, 0xc001474780, 0xc0015c7c20, 0xc002d19f50, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/translator/translator.go:166 +0x436
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorInstance).Translate(0xc002798f08, 0x4e65a20, 0xc002d19a10, 0xc001474780, 0xc0015c7c20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/translator/translator.go:122 +0x4f6
github.com/solo-io/gloo/projects/gloo/pkg/translator.(*translatorFactory).Translate(0xc0024aa660, 0x4e65a20, 0xc002d19530, 0xc001474780, 0xc0015c7c20, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/translator/translator.go:82 +0x27f
github.com/solo-io/gloo/projects/gloo/pkg/syncer.(*translatorSyncer).syncEnvoy(0xc0024d0c00, 0x4e65a20, 0xc0029b01e0, 0xc001474780, 0xc0029b0030, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/syncer/envoy_translator_syncer.go:132 +0xe02
github.com/solo-io/gloo/projects/gloo/pkg/syncer.(*translatorSyncer).Sync(0xc0024d0c00, 0x4e65978, 0xc002605b40, 0xc001474780, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/syncer/translator_syncer.go:94 +0xbf
github.com/solo-io/gloo/projects/gloo/pkg/api/v1/gloosnapshot.ApiSyncers.Sync(0xc0023d5a20, 0x2, 0x2, 0x4e65978, 0xc002605b40, 0xc001474780, 0x0, 0x0)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/api/v1/gloosnapshot/api_event_loop.sk.go:28 +0xf9
github.com/solo-io/gloo/projects/gloo/pkg/api/v1/gloosnapshot.(*apiEventLoop).Run.func1(0xc0009ac5a0, 0x4e65a20, 0xc0024abe90, 0x0, 0x0, 0x0, 0xdf8475800, 0x0, 0x0, 0xc0024abe60, ...)
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/api/v1/gloosnapshot/api_event_loop.sk.go:84 +0x375
created by github.com/solo-io/gloo/projects/gloo/pkg/api/v1/gloosnapshot.(*apiEventLoop).Run
	/go/pkg/mod/github.com/solo-io/gloo@v1.11.24/projects/gloo/pkg/api/v1/gloosnapshot/api_event_loop.sk.go:66 +0x42c
```

### Steps to reproduce the bug

Apply upstream described above

### Expected Behavior

Upstream is rejected or doesn't cause a crash
