### ISSUE TITLE
Unable to pull information on Gloo Instances when navigating the gloo fed ui

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#7388]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Gloo Fed UI through a javascript exception when navigating to the `Gloo Instances` Link.  Any subsequent links will fail with the same error
![Screen Shot 2022-10-28 at 12 01 40 PM](https://user-images.githubusercontent.com/10437147/198682263-0969824c-9fd6-440b-a795-9dab0ad7b9dd.png)
![Screen Shot 2022-10-28 at 12 04 00 PM](https://user-images.githubusercontent.com/10437147/198682322-55e69fa2-5421-47b1-957e-d719421787e1.png)

```
TypeError: t is undefined
    Ap gloo-instance-helpers.ts:30
    Ap gloo-instance-helpers.ts:25
    Pu GlooInstancesLanding.tsx:234
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    s index.esm.js:541
    g index.esm.js:701
    G index.esm.js:833
    a index.esm.js:50
    a index.esm.js:31
    s index.esm.js:21
    promise callback*l index.esm.js:23
    Fr index.esm.js:24
    Fr index.esm.js:20
    G index.esm.js:668
    Er index.esm.js:932
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    s index.esm.js:541
    g index.esm.js:701
    G index.esm.js:833
    a index.esm.js:50
    a index.esm.js:31
    s index.esm.js:21
    promise callback*l index.esm.js:23
    Fr index.esm.js:24
    Fr index.esm.js:20
    G index.esm.js:668
    Er index.esm.js:932
    React 2
    unstable_runWithPriority scheduler.production.min.js:18
    React 9
    <anonymous> index.tsx:7
    <anonymous> serviceWorker.ts:143
    <anonymous> serviceWorker.ts:143
react-dom.production.min.js:216:199
```

### Steps to reproduce the bug

1. Install 1.12.32
2. Deploy a sample vs:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs-httpbin
  namespace: gloo-system
spec:
# ---------------- SSL config ---------------------------
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
# -------------------------------------------------------
  virtualHost:
    domains:
      - '*'
    routes:
      - matchers:
          - prefix: /httpbin
        routeAction:
          single:
            upstream:
              name: httpbin-httpbin-8000
              namespace: gloo-system
        options:
          prefixRewrite: /
```
2.  Ensure glooctl is at the same version as the gloo install and then run `glooctl cluster register --cluster-name local`
3. Navigate to the Fed UI and select `Gloo Instances`

### Expected Behavior

Shouldn't throw an exception and show the local instance.
