### ISSUE TITLE
Extauth OAuth2 config does not put refresh token in cookie header

### ISSUE THREAD

**Issue by ky-rafaels** [solo-io/gloo#7393]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.21.x

### Describe the bug

In using an OAuth2 authconfig an access token is placed in the cookie header after the oauth callback to application but is missing a refresh token in cookie. Using an authconfig such as:
```yaml
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: corporatehub-oauth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oauth2:
        scopes:
        - trust
        appUrl: "https://{{ appURL }}.com"
        callbackPath: /callback
        clientId: {{ clientId }} 
        clientSecretRef:
          name: oauth-client-secret
          namespace: gloo-system
        authEndpoint: https://{{ oauthLogin }}/oauth/authorize
        tokenEndpoint: https://{{ oauthLogin }}/oauth/token
```
No validation or handling needs to be done to refresh token from extauth, this will be handled by the client app. It just needs to exist in the header similar to how access token is set in browser cookie.

### Steps to reproduce the bug

1. Create an OAuth2 (non-OIDC) authconfig and reference in a virtualservice for say httpbin.
2. Open developer tools in browser window to view OAuth2 exchange 
3. After redirected to OAuth login page, submit credentials and view cookie after redirect back to application
4. See only access_token in cookie and no refresh_token

<img width="1237" alt="Screen Shot 2022-10-31 at 3 15 19 PM" src="https://user-images.githubusercontent.com/56878501/199101945-08096a80-02c5-4584-a067-9d1dbe7ea86d.png">

### Expected Behavior

Refresh token should also exist in cookie for browser session after successful OAuth login

### Additional Context

Relevant go code: https://github.com/solo-io/ext-auth-service/blob/e8861b51167cd864fcbdabd1e404836dbd657582/pkg/config/oauth2/oauth2_request.go#L532

**Comment by inFocus7** [comment]
Waiting on update, looks like the issue _could_ be due to missing configuration (`allowRefreshing`) to store the refresh token (which allows refreshing). 

This should look something like
```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: corporatehub-oauth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oauth2:
        session:
          cookie:
            allowRefreshing: true
        scopes:
        - trust
        appUrl: "https://{{ appURL }}.com"
        callbackPath: /callback
        clientId: {{ clientId }} 
        clientSecretRef:
          name: oauth-client-secret
          namespace: gloo-system
        authEndpoint: https://{{ oauthLogin }}/oauth/authorize
        tokenEndpoint: https://{{ oauthLogin }}/oauth/token
```
