### ISSUE TITLE
OAuth2 support the use of unique token names in cookie 

### ISSUE THREAD

**Issue by ky-rafaels** [solo-io/gloo#7418]
### Is your feature request related to a problem? Please describe.

A customer has several apps that expect an access_token and refresh_token returned from OAuth2 callback with a unique name in browser cookie other than `access_token=` or `refresh_token=`.
 

### Describe the solution you'd like

during callback in the response, set-cookie is set twice, once for access_token and then for refresh_token with their respective values. 

Customer would like to have a unique name in the set-cookie response for both tokens. 

### Describe alternatives you've considered

Currently working on a set of transformations in virtualservice to accomplish this but unsuccessful thus far. Recent transformation attempted:

```yaml
      stagedTransformations:
        regular:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                extractors:
                  accessToken:
                    header: cookie
                    regex: .*access_token=([^;]*).*
                    subgroup: 1
                  refreshtoken:
                    header: cookie
                    regex: .*refresh_token=([^;]*).*
                    subgroup: 1
                headers:
                  fcauth:
                    text: '{{ accessToken }}' 
                  refresh:
                    text: '{{ refreshtoken }}'
          responseTransforms:
            - responseTransformation:
                transformationTemplate:
                  headersToAppend:
                    - key: set-cookie
                      value: 
                        text: 'fc_auth={{ request_header("fcauth") }}'
                    - key: set-cookie
                      value: 
                        text: 'refresh={{ request_header("refresh") }}'
```

**Comment by ky-rafaels** [comment]
Attempted another transformation to do this:
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: gloo-system
  labels:
    gateway-type: private
spec:
  sslConfig:
    secretRef:
      name: upstream-tls
      namespace: gloo-system
    sniDomains:
    - httpbin.kyle.gl00.net
  virtualHost:
    domains:
      - 'httpbin.kyle.gl00.net'
    routes:
      - matchers:
        - prefix: /callback
        routeAction: 
          single:
            upstream:
              namespace: gloo-system
              name: httpbin-httpbin-8000
        options:
          stagedTransformations:
            early: # working
              responseTransforms:
              - responseTransformation:
                  transformationTemplate:
                    extractors:
                      accesstoken:
                        header: set-cookie
                        regex: .*access_token=([^$].*)
                        subgroup: 1
                    headersToAppend:
                    - key: set-cookie
                      value:
                        text: fc_auth={{ accesstoken }}
            regular:
              responseTransforms:
              - responseTransformation:
                  transformationTemplate:
                    extractors:
                      refreshtoken:
                        header: set-cookie
                        regex: .*refresh_token=([^$].*)
                        subgroup: 1
                    headersToAppend:
                    - key: set-cookie
                      value:
                        text: refresh={{ refreshtoken }}
      - matchers:
        - prefix: /get
        routeAction: 
          single:
            upstream:
              namespace: gloo-system
              name: httpbin-httpbin-8000
        options:
          stagedTransformations:
            early:
              requestTransforms:
              - requestTransformation:
                  transformationTemplate:
                    extractors:
                      refreshtoken:
                        header: cookie
                        regex: .*refresh_token=([^;]*).*
                        subgroup: 1
                    headers:
                      refresh:
                        text: '{{ refreshtoken }}'
          transformations:
            responseTransformation:
              transformationTemplate:
                headersToAppend:
                  - key: set-cookie
                    value:
                      text: refresh="{{ request_header("refresh") }}"
      - matchers:
        - prefix: /
        routeAction: 
          single:
            upstream:
              namespace: gloo-system
              name: httpbin-httpbin-8000
    options:
      extauth:
        configRef:
          name: httpbin-oauth 
          namespace: gloo-system
```

To note we were unable to properly perform a response transformation on `/` receiving and error in browser: `bad request: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value... etc` new bug filed [here](https://github.com/solo-io/gloo/issues/7419) for this bug. 

The transformation above gives the ability to change the access_token name in cookie in browser on callback however unable to change the name of `refresh_token` at callback so transformation happens later, after redirect to application. On consecutive calls to app, refresh_token with new name will then appear in request cookie for browser.
