### ISSUE TITLE
Response Transformations on Root Break Root Path

### ISSUE THREAD

**Issue by bgottfried91** [solo-io/gloo#7419]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

A `responseTransformation` that affects a `route` where the `matchers` will target the root path `/` will result in an error like 
```
bad request: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'F'.
```
 No other paths appear to be affected besides the root path. We encountered this at a customer while trying to use the response transformation logic to modify the `set-cookie` header on the root prefix path and on further investigation, found that it affects practically any response transformation modifying headers on a route to the root path.

### Steps to reproduce the bug

Follow [this page for injecting a response header](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/transformations/inject_response_header/).

Create the VS with the transformation in it. 
`curl -H "x-solo-hdr1: val1" $(glooctl proxy url)/get -i`
results in 
```
HTTP/1.1 200 OK
date: Thu, 10 Nov 2022 23:22:24 GMT
content-type: application/json; charset=utf-8
content-length: 349
etag: W/"15d-0MQsGxg5EccM8ExTIHhvSOe6nXU"
vary: Accept-Encoding
set-cookie: sails.sid=s%3ArT-zDT6_54O665aJuq0qdiNSMvri69Fg.Z1pxx%2FBl9NqbsZ2sxgmHaBCIK3q98xb2SDL6XP2K%2FIw; Path=/; HttpOnly
x-envoy-upstream-service-time: 6
x-solo-resp-hdr1: val1
server: envoy

{"args":{},"headers":{"x-forwarded-proto":"http","x-forwarded-port":"80","host":"20.120.67.173","x-amzn-trace-id":"Root=1-636d87b0-4ea9d3eb77e4f55f02deabbf","user-agent":"curl/7.58.0","accept":"*/*","x-solo-hdr1":"val1","x-request-id":"585b22c0-1715-4d9b-8437-4e91e9c48dca","x-envoy-expected-rq-timeout-ms":"15000"},"url":"http://20.120.67.173/get"}
```
like the document shows.
However,
`curl -H "x-solo-hdr1: val1" $(glooctl proxy url) -i`
results in
```
HTTP/1.1 400 Bad Request
date: Thu, 10 Nov 2022 23:23:03 GMT
content-length: 145
location: https://docs.postman-echo.com
vary: Accept, Accept-Encoding
set-cookie: sails.sid=s%3AzfkUv_ILIrObFe8kXycZ9XsL9g4lCPPw.%2BfKLnWcbgMxjQIey5efOmTkgwfgULtDxx%2BRZzeka8B8; Path=/; HttpOnly
x-envoy-upstream-service-time: 9
server: envoy

bad request: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - invalid literal; last read: 'F'
```
despite the root path being a valid endpoint for the Postman Echo service.

We can validate this by modifying the VS to look like this instead:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: inject-response-header
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
       - prefix: /get
      routeAction:
        single:
          upstream:
            name: postman-echo
            namespace: gloo-system
      options:
        transformations:
          responseTransformation:
            transformationTemplate:
              headers:
                x-solo-resp-hdr1:
                  text: '{{ request_header("x-solo-hdr1") }}'
    - matchers:
       - prefix: /
      routeAction:
        single:
          upstream:
            name: postman-echo
            namespace: gloo-system
```
Note that the transformation block is now underneath the `/get` path route and the root path route has no response transformation.

` curl -H "x-solo-hdr1: val1" $(glooctl proxy url) -i`
now results in
```
HTTP/1.1 302 Found
date: Thu, 10 Nov 2022 23:25:50 GMT
content-type: text/plain; charset=utf-8
content-length: 51
location: https://docs.postman-echo.com
vary: Accept, Accept-Encoding
set-cookie: sails.sid=s%3ANjdg-N7lsD5UR346D9__rhYu9UAZgaI-.1lpDc5CVcgnckXAM16Y%2BClIdXpPiZP4HIMHrK6%2Ff7iM; Path=/; HttpOnly
x-envoy-upstream-service-time: 5
server: envoy

Found. Redirecting to https://docs.postman-echo.com 
```
and we still get the transformation behavior we want if we hit the `/get` path:
`curl -H "x-solo-hdr1: val1" $(glooctl proxy url)/get -i`
results in
```
HTTP/1.1 200 OK
date: Thu, 10 Nov 2022 23:26:29 GMT
content-type: application/json; charset=utf-8
content-length: 349
etag: W/"15d-otpK5gRpyKkTcmIZYyFLheBbzVw"
vary: Accept-Encoding
set-cookie: sails.sid=s%3AZFd9cM_1jGyugmAdEiduYT1STW8O7gVQ.9iDRb6A68LfJYgqakBFfcg69%2FkpblTlNkHaHVaAjQH4; Path=/; HttpOnly
x-envoy-upstream-service-time: 6
x-solo-resp-hdr1: val1
server: envoy

{"args":{},"headers":{"x-forwarded-proto":"http","x-forwarded-port":"80","host":"20.120.67.173","x-amzn-trace-id":"Root=1-636d88a5-222e6e753c8d4f0c7ca721fb","user-agent":"curl/7.58.0","accept":"*/*","x-solo-hdr1":"val1","x-request-id":"e4b89a3f-f0ce-404e-8ed7-6c59f70a6523","x-envoy-expected-rq-timeout-ms":"15000"},"url":"http://20.120.67.173/get"}
```
with the appropriate added header `x-solo-resp-hdr1`.

The bad behavior will also occur on the root path route if the transformation is applied at the VS level (i.e. not on a specific route like in the docs example), but no other paths appear to be affected. Whether the matcher for the root path route is `prefix` or `exact` seems to have no effect on whether the bad behavior occurs.

This bug does not seem to affect `requestTransformation`s on a route to the root path, only `responseTransformation`s.

### Expected Behavior

When a `responseTransformation` is performed on a request to the root path, the transformation should occur and the response should come back normally.

**Comment by ky-rafaels** [comment]
This particular issue was discovered during the investigation of changing the name of an access or refresh token in browser cookie (relevant feature filed [here](https://github.com/solo-io/gloo/issues/7418))

**Comment by bgottfried91** [comment]
I'm attaching a dump of the gateway proxy config from replicating this issue (it'll also have some other config in it unrelated to the issue, you want to focus on traffic going to `postman-echo` through the `response-transformation` VS) to this comment.
[7419-Proxy-Config-Dump.txt](https://github.com/solo-io/gloo/files/10059083/7419-Proxy-Config-Dump.txt)

**Comment by chrisgaun** [comment]
We can either do this one or https://github.com/solo-io/gloo/issues/7418

**Comment by bgottfried91** [comment]
Spoke to the customer this morning - they would prefer #7418 if the timescale is roughly the same for them.

**Comment by ben-taussig-solo** [comment]
I was able to clarify that this is caused by an assumption in the transformation filter that response bodies will be formatted as JSON. This error occurs at any endpoint which returns non-JSON data, which happens to occur at the root path for `postman-echo`. I put up a failing end-to-end test here, which replicates the bug on a non-root endpoint using httpbin: https://github.com/solo-io/gloo/commit/6ac42950dc0804504bef232acdcd7bdd762c820e#diff-469976683ea4c5afbe29efd238be341cf8766a5be763e459089120665bf20ce9R309-R356

In order to resolve this, I'll need to make some changes in envoy-gloo to our transformation filter.

**Comment by ben-taussig-solo** [comment]
Looks like at some level we expect this behavior: https://github.com/solo-io/envoy-gloo/blob/master/test/extensions/filters/http/transformation/transformation_filter_test.cc#L629-L647

Still, shouldn't be an issue to resolve

**Comment by ben-taussig-solo** [comment]
Update: you can prevent envoy from attempting to parse the response body as JSON by setting the `parseBodyBehavior` field in your TransformationTemplate to `DontParse` (reference [here](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/extensions/transformation/transformation.proto.sk/#transformationtemplate))

E.G.,
```yaml
            transformationTemplate:
              headers:
                x-solo-resp-hdr1:
                  text: '{{ request_header("x-solo-hdr1") }}'
              parseBodyBehavior: DontParse
```
