### ISSUE TITLE
 query params not being translated to the grpc request object

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#7487]
### Gloo Edge Version

1.12.x (latest stable)

### Kubernetes Version

1.22.x

### Describe the bug

Query parameters are not being passed through to the grpc upstream

### Steps to reproduce the bug

Follow the example : https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest/ to create a GRPC upstream.

Expose that upstream in the virtual service:
https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest/#create-a-rest-to-grpc-translation

Hit the endpoint with with query parameters in the request.

### Expected Behavior

Expected the query parameters to be passed to the grpc upstream

**Comment by kdorosh** [comment]
I suspect this works with advanced transcoding https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest_advanced/ and proper instrumentation of query params to proto fields e.g. https://stackoverflow.com/questions/72118020/envoy-grpc-json-transcoder-with-special-characters-in-query-param-names did we try that?

also note that envoy query param config on the filter (what to do with invalid or missing query params) may also be at play here https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/grpc_json_transcoder/v3/transcoder.proto

**Comment by nfuden** [comment]
Given the initiating event for this had logs saying that it could not map to a grpc service there is definitely something wrong with how the query params are being consumed. Likely due to configuration as stated in the first links from the above comment.

**Comment by kdorosh** [comment]
this is an RFE for FDS discovered grpc to rest https://github.com/solo-io/gloo/blob/v1.13.0-rc1/projects/gloo/pkg/plugins/grpc/plugin.go#L189

this can be worked around with manual and advanced grpc to rest https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/grpc_to_rest_advanced/

**Comment by pszeto** [comment]
There seems to be limited support for query parameters.  Using the following routetable:

```
      - matchers:
        - methods:
          - GET
          prefix: /items
          queryParameters:
          - name: itemname
          - name: test
        routeAction:
          single:
            destinationSpec:
              grpc:
                function: GetItem
                package: solo.examples.v1
                parameters:
                  path: /items?itemname={name}&test={test}
                service: StoreService
            upstream:
              name: default-grpcstore-demo-80
              namespace: gloo-system
```

When curling the ` http://34.139.54.17/items\?itemname\=item2\&test\=a` , the mapping works and I get a response from the upstream:

```> GET /items?itemname=item2&test=a HTTP/1.1
> Host: 34.139.54.17
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json
< x-envoy-upstream-service-time: 0
< grpc-status: 0
< grpc-message:
< content-length: 25
< date: Fri, 02 Dec 2022 19:43:30 GMT
< server: envoy
<
* Connection #0 to host 34.139.54.17 left intact
{"item":{"name":"item2"}}
```

however, i switch the order of the query parameters... to 
`http://34.139.54.17/items\?test\=a\&itemname\=item2`

The grpc upstream doesn't have the correct value and fails the lookup:

```
* Connected to 34.139.54.17 (34.139.54.17) port 80 (#0)
> GET /items?test=a&itemname=item2 HTTP/1.1
> Host: 34.139.54.17
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-type: application/grpc
< grpc-status: 5
< grpc-message: item was not found
< x-envoy-upstream-service-time: 0
< content-length: 0
< date: Fri, 02 Dec 2022 19:43:59 GMT
< server: envoy
<
* Connection #0 to host 34.139.54.17 left intact
```

It would be nice to support the same features as https://docs.solo.io/gloo-edge/1.11.42/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc_json/grpc_json.proto.sk/#grpcjsontranscoder

https://github.com/solo-io/gloo/issues/7480
