### ISSUE TITLE
Upstreams not updating with new cert-manager ingresses and services

### ISSUE THREAD

**Issue by danieltharp** [solo-io/gloo#7519]
### Gloo Edge Version

1.11.x

### Kubernetes Version

1.22.x

### Describe the bug

Cert-manager is failing to renew certs because the new upstreams do not appear to be registering in Gloo. The initial `cm-acme-http-solver-` services are present, but new ones generated for renewals are not appearing (and the old ones are not being cleaned out). Thus, requests to the challenge service are returning 404 directly from Gloo instead of a 200 from a cert-manager pod.

### Steps to reproduce the bug

1. Be unskilled at Gloo and many, _many_ other things.
2. Create an alpn01 certificate via cert-manager
3. Kill off the associated `cm-acme-http-solver-` ingress
4. Initiate a renewal after a sufficient amount of time

### Expected Behavior

Gloo automatically updates the upstreams table and the renewal is successful.

### Additional Context

Helm chart values:

```yaml
gloo:
  gateway:
    deployment:
      replicas: 1
    validation:
      alwaysAcceptResources: false
ingress:
  enabled: true  # I have tried this both true and false
```

Cert-Manager Route Table:
```yaml
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  name: 'cert-manager-routes'
  namespace: 'gloo-system'
spec:
  routes:
    - matchers:
        - prefix: /.well-known/acme-challenge/
      routeAction:
        single:
          kube:
            ref:
              name: acme-solver
              namespace: cert-manager
            port: 8089
```

Application Route Table:
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: makoto-http-routes
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - makoto.tharp.io
    routes:
      - matchers:
          - prefix: /.well-known/acme-challenge/
        delegateAction:
          ref:
            name: cert-manager-routes
            namespace: gloo-system
      - matchers:
        - prefix: /  # Everything else.
        redirectAction:
            hostRedirect: makoto.tharp.io
            httpsRedirect: true
```
