### ISSUE TITLE
dynamicForwardProxy not working with replaceInvalidRoutes enabled

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#7668]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

Hi,

We have been hitting an issue in which if we have dynamicForwardProxy enabled in the gateway:
```
kubectl -n gloo-system patch gw/gateway-proxy --type merge -p "
spec:            
  httpGateway:
    options:
      dynamicForwardProxy: {}
"
```

And we set replaceInvalidRoutes to true in Gloo Edge settings:
```
apiVersion: gloo.solo.io/v1
kind: Settings
metadata:
  annotations:
    meta.helm.sh/release-name: gloo
    meta.helm.sh/release-namespace: gloo-system
  labels:
    app: gloo
    app.kubernetes.io/managed-by: Helm
    gloo: settings
  name: default
  namespace: gloo-system
spec:
  discovery:
    fdsMode: WHITELIST
  discoveryNamespace: gloo-system
  gateway:
    enableGatewayController: true
    isolateVirtualHostsBySslConfig: false
    readGatewaysFromAllNamespaces: false
    validation:
      allowWarnings: false
      alwaysAccept: true
      disableTransformationValidation: false
      proxyValidationServerAddr: gloo:9988
      serverEnabled: true
      validationServerGrpcMaxSizeBytes: 104857600
      warnRouteShortCircuiting: false
  gloo:
    disableKubernetesDestinations: false
    disableProxyGarbageCollection: false
    enableRestEds: false
    invalidConfigPolicy:
      invalidRouteResponseBody: Gloo Gateway has invalid configuration. Administrators
        should run `glooctl check` to find and fix config errors.
      invalidRouteResponseCode: 404
      replaceInvalidRoutes: true
    proxyDebugBindAddr: 0.0.0.0:9966
    restXdsBindAddr: 0.0.0.0:9976
    xdsBindAddr: 0.0.0.0:9977
  refreshRate: 60s
```

If you create a VirutalService that uses this dynamicProxyConfiguration:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-static
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - httpbin.test
    routes:
    - matchers:
      - prefix: /service
      options:
        regexRewrite:
          pattern:
            regex: ^/service/.*
          substitution: /get
        stagedTransformations:
          early:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    destination:
                      header: :path
                      regex: /service/(.*)
                      subgroup: 1
                  headers:
                    x-destination:
                      text: '{{ destination }}'
      routeAction:
        dynamicForwardProxy:
          autoHostRewriteHeader: x-destination
```

You will get the following error when trying to curl the VS:
```
curl http://httpbin.test/service/52.200.117.68 -vvv  -k
*   Trying 52.89.23.178:80...
* Connected to wadtfy-sample-backend.api-i.bmwgroup.net (52.89.23.178) port 80 (#0)
> GET /service/52.200.117.68 HTTP/1.1
> Host: wadtfy-sample-backend.api-i.bmwgroup.net
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-length: 112
< content-type: text/plain
< date: Fri, 13 Jan 2023 10:29:15 GMT
< server: envoy
< x-envoy-upstream-service-time: 0
< 
* Connection #0 to host wadtfy-sample-backend.api-i.bmwgroup.net left intact
Gloo Gateway has invalid configuration. Administrators should run `glooctl check` to find and fix config errors.%
```

If you set replaceInvalidRoutes: false in Settings, the VirtualService will work again.

We can see this error in config_dump.json:
```
{
  "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
  "name": "fallback_cluster_for_invalid_routes",
  "connect_timeout": "5s",
  "load_assignment": {
    "cluster_name": "fallback_cluster_for_invalid_routes",
    "endpoints": [
      {
        "lb_endpoints": [
          {
            "endpoint": {
              "address": {
                "pipe": {
                  "path": "@fallback_listener_for_invalid_routes"
                }
              }
            }
          }
        ]
      }
    ]
  }
}
```

### Steps to reproduce the bug

Already indicated

### Expected Behavior

The VirtualService should work independently of the value of replaceInvalidRoutes
