### ISSUE TITLE
Allow setting x-forwarded-host and x-forwarded-port

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#7683]
### Version

1.12.x

### Is your feature request related to a problem? Please describe.

Customer requires exposing `x-forwarded-host` and `x-forwarded-port` to their upstream.  

Although Envoy has this ability, it is not currently exposed via the Gloo Edge API.

### Describe the solution you'd like

A simple way to do this via the Gloo Edge API

### Describe alternatives you've considered

As discussed here: https://solo-io-corp.slack.com/archives/C02LQ0JCNLF/p1638181079038900?thread_ts=1637688318.011000&cid=C02LQ0JCNLF

It may be possible to define via allowedHeaders e.g.
```
global:
  extensions:
    extAuth:
      enabled: false
gloo:
  settings:
    kubeResourceOverride:
      spec:
        extauth:
          extauthzServerRef:
            name: external-auth-server
            namespace: kube-gloo-system
          httpService:
            pathPrefix: /envoy/verify-params-header
            request:
              allowedHeaders:
              - cookie
              - x-forwarded-host
              - x-forwarded-method
              - x-forwarded-proto
              - x-forwarded-uri
              - x-ostenan
```
