### ISSUE TITLE
Implement clientSideTls with using Dynamic Forward Proxy in Gloo Edge

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#7693]
### Version

None

### Is your feature request related to a problem? Please describe.

We have a client reporting that when you have Gloo Edge with dynamicForwardProxy enabled, you always reach the client target with HTTP even if you specify https port.

So imagine we have the following VirtualService:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: test-static
  namespace: my-namespace
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /service
      options:
        regexRewrite:
          pattern:
            regex: ^/service/.*
          substitution: /get
        stagedTransformations:
          early:
            requestTransforms:
            - requestTransformation:
                transformationTemplate:
                  extractors:
                    destination:
                      header: :path
                      regex: /service/(.*)
                      subgroup: 1
                  headers:
                    x-destination:
                      text: '{{ destination }}'
      routeAction:
        dynamicForwardProxy:
          autoHostRewriteHeader: x-destination
```

If we make a curl to httpbin and try to reach https://httpbin.org for example (52.1.93.201 coincides with public httpbin IP), you will always reach http://httpbin.org

```
curl https://httpbin/service/52.1.93.201:443
{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.79.1", 
    "X-Amzn-Trace-Id": "Root=1-63c81172-0295d0ca16096dc2530f0d2c"
  }, 
  "origin": "79.146.83.15", 
  "url": "http://httpbin.org/get"
}
```

### Describe the solution you'd like

I think we should have something like this:
`clientSideTls: true`

So an option for making the call in HTTPS instead of HTTP
