### ISSUE TITLE
Inja validation of invalid Inja has incorrect behavior 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#7697]
### Gloo Edge Version

1.12.x

### Kubernetes Version

None

### Describe the bug

When the Inja is invalid there is the following entry in the gloo pod logs

`{"level":"debug","ts":"2023-01-18T20:01:05.854Z","logger":"gloo-ee.v1.event_loop.gloo.reporter","caller":"reporter/reporter.go:309","msg":"wrote report for name:\"grpc\" namespace:\"gloo-system\" : state:Accepted reported_by:\"gloo\" subresource_statuses:{key:\"*v1.Proxy.gateway-proxy_gloo-system\" value:{state:Rejected reason:\"1 error occurred:\\n\\t* Route Error: ProcessingError. Reason: *transformer.plugin: envoy validation mode output: error initializing configuration '': Failed to parse response template: Failed to parse body template [inja.exception.parser_error] else without matching if\\n, error: exit status 1. Route Name: gloo-system_default-route-3-matcher-0\\n\\n\" reported_by:\"gloo\"}}","version":"1.12.33"} `

but Envoy is updated WITHOUT the transform filter configuration. Also, the gloo log entry above is debug and should be an error or warning. 

### Steps to reproduce the bug

Create a route with valid Inja. 

```
    - matchers:
      - prefix: /postmanecho/
      options:
        prefixRewrite: /
        transformations:
          responseTransformation:
            transformationTemplate:
              body:
                text: '{% if int(header("content-length")) > 2000 %} {"error" : "Too
                  Damn Big!!"} {% else %} {{ body() }} {% endif %}'
              headers:
                :status:
                  text: '{% if int(header("content-length")) > 2000 %}401{% else %}{{header(":status")
                    }}{% endif %}'
              parseBodyBehavior: DontParse
      routeAction:
        single:
          upstream:
            name: postman-echo.com
            namespace: gloo-system
```

All good. VS is accepted and Envoy is correctly updated. VS status is:

```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system': {}
```

Remove the { at the beginning of the body.text Inja to create invalid Inja:

```
    - matchers:
      - prefix: /postmanecho/
      options:
        prefixRewrite: /
        transformations:
          responseTransformation:
            transformationTemplate:
              body:
                text: '% if int(header("content-length")) > 2000 %} {"error" : "Too
                  Damn Big!!"} {% else %} {{ body() }} {% endif %}'
              headers:
                :status:
                  text: '{% if int(header("content-length")) > 2000 %}401{% else %}{{header(":status")
                    }}{% endif %}'
              parseBodyBehavior: DontParse
      routeAction:
        single:
          upstream:
            name: postman-echo.com
            namespace: gloo-system
```

VS status is:

```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *transformer.plugin:
            envoy validation mode output: error initializing configuration '': Failed
            to parse response template: Failed to parse body template [inja.exception.parser_error]
            else without matching if\n, error: exit status 1. Route Name: gloo-system_default-route-4-matcher-0\n\n"
          reportedBy: gloo
          state: Rejected
```

This creates the gloo log entry above

### Expected Behavior

Envoy should not be updated when there is invalid config

The gloo log entry should be a warning or error
