### ISSUE TITLE
gracefulShutdown does not work as expected

### ISSUE THREAD

**Issue by Ati59** [solo-io/gloo#7743]
### Gloo Edge Version

1.12.x

### Kubernetes Version

1.22.x

### Describe the bug

Deploying GE using those settings (https://docs.solo.io/gloo-edge/latest/operations/advanced/zero-downtime-gateway-rollout/) :
```yaml
      podTemplate:
        terminationGracePeriodSeconds: 7
        gracefulShutdown:
          enabled: true
          sleepTimeSeconds: 5
```
will add a `preStop` hook on the deployment to make envoy graceful feature trying to drain the in-flights connections :
```yaml
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - wget --post-data "" -O /dev/null 127.0.0.1:19000/healthcheck/fail; sleep 5
```

The problem is that when we do a rollout/scale-in, k8s will do 2 things **at the same time** (as describe here : https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination): 
- Launch the `preHook`
- Get the pod out of the service `endpoints`

The second action actually means that no **new** request will be send to envoy as soon as the rollout/scale-in is launched.
This configuration will then results on : 
- envoy will be in draining/fail mode, answering the established connections only
- the ELB HC requests would be failed if the ELB open new connections (whereas using existing ones), meaning that ELB will hit timeout whereas get the envoy 503 (`service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout`)
- the ELB will consider the node healthy during 20 to 30sec min sending new connection request to this node as normal
- we get some timeout(s)/error(s)

You will see on the video the endpoint disappearing : 
https://user-images.githubusercontent.com/35342300/215067889-e7e53bd7-0d44-4918-a524-65325ab24a61.mov

### Steps to reproduce the bug

1. Launch an EKS cluster with some nodes (at least 4 with the configuration file)
2. Deploy GE with this configuration :
```yaml
gloo:
  gatewayProxies:
    gatewayProxy:
      deployment:
        replicas: 4

      podDisruptionBudget:
        maxUnavailable: 0
        maxSurge: 1

      service:
        httpPort: 80
        httpsFirst: true
        httpsPort: 443
        type: LoadBalancer
        externalTrafficPolicy: Local
        extraAnnotations:
          # LB
          service.beta.kubernetes.io/aws-load-balancer-type: "external"
          service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
          
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "x-via-lb-type=external"
          service.beta.kubernetes.io/aws-load-balancer-ip-address-type: "ipv4"

          # LB attributes
          service.beta.kubernetes.io/aws-load-balancer-attributes: "load_balancing.cross_zone.enabled=true"
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'

          # Target group attributes
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: "deregistration_delay.connection_termination.enabled=true,deregistration_delay.timeout_seconds=120,proxy_protocol_v2.enabled=true"

          # Backend
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "ssl"

          # Health checks
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"   # 2-20
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2" # 2-10
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"           # 10 or 30
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/envoy-hc" 
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTPS"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "2"             # 2 is the minimum

      antiAffinity: true

      podTemplate:
        extraLabels:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: gloo
                    operator: In
                    values:
                    - gateway-proxy
                topologyKey: "kubernetes.io/hostname"

        probes: true
        customReadinessProbe:
          httpGet:
            scheme: HTTPS
            port: 8443
            path: /envoy-hc
          failureThreshold: 2
          periodSeconds: 5

      gatewaySettings:
        customHttpsGateway:
          options:
            healthCheck:
              path: /envoy-hc
            httpConnectionManagerSettings:
              useRemoteAddress: true
              skipXffAppend: false

        accessLoggingService:
          accessLog:
            - fileSink:
                path: /dev/stdout
```
3. Launch some curl to create traffic (I give you mine for example)

GET:
```bash
for i in $(seq 1 5000); do d=$(date "+%H:%M:%S"); res=$(curl -k -o /dev/null -w "%{http_code}" --connect-timeout 20 https://k8s-gloosyst-gatewayp-57561faeb0-56dc82ef86a40051.elb.us-east-1.amazonaws.com/ 2>/dev/null); if [[ "$res" != "200" ]] then; printf "\n$res - begin at ${d} - ended at $(date +%H:%M:%S)\n"; else; printf "$res ";fi; done
```

POST:
```bash
for i in $(seq 1 5000); do d=$(date "+%H:%M:%S"); res=$(curl -k -o /dev/null -w "%{http_code}" --limit-rate 200k --form "fileupload=@output.dat" https://k8s-gloosyst-gatewayp-57561faeb0-56dc82ef86a40051.elb.us-east-1.amazonaws.com/post 2>/dev/null| tail -n 1); printf "$res - begin at ${d} - ended at $(date +%H:%M:%S)\n"; done
```

Hey command:
```bash
hey -c 10 --cpus 4 -z 3m -m POST -t 5 https://k8s-gloosyst-gatewayp-57561faeb0-56dc82ef86a40051.elb.us-east-1.amazonaws.com/post
```
4. Reduce the number of replica or launch a rollout and keep an eyes on `gateway-proxy` logs and list of `endpoints`
5. See the curl response codes

### Expected Behavior

We are more in a near zero downtime mode as we will always loose some requests. We expect to loose zero request.

The zero-downtime-gateway-rollout documentation should be reviewed.

### Additional Context

The problem is related to this issue if you use `externalTrafficPolicy: Local`: https://github.com/kubernetes/kubernetes/issues/85643

Using `externalTrafficPolicy: Cluster` will workaround the problem because active connections will be sent to the terminating pod and the new one to another healthy endpoints.

This should be fixed by the feature gate options `ProxyTerminatingEndpoints` in alpha from k8s 1.22 to 1.25 and become beta and will be active by default on k8s 1.26 : https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

In customer case and AWS/EKS in general, it won't be available because feature gate options cannot be enabled : https://github.com/aws/containers-roadmap/issues/512
