### ISSUE TITLE
[Gloo Federation] - Gloo Federation gives-up on cluster reconciliation

### ISSUE THREAD

**Issue by Ido-Itz** [solo-io/gloo#7814]
### Gloo Edge Version

1.12.x

### Kubernetes Version

1.23.x

### Describe the bug

When Gloo Federation fails to reconcile (or to reach) a specific edge cluster, it looks like it stops retrying after a certain amount of time.  
As a Kubernetes controller, I would expect Gloo Fed to continue retrying indefinitely, as long as it (Gloo-Fed) is running. 
Exponential backoff sounds like a good idea here, as long as there is a maximal interval for the backoff (e.g. max interval cannot exceed 5 minutes), which would still allow it to retry from time to time.

Without this functionality, we are forced to restart the Gloo Federation pod in order to pick-up any cluster that was unavailable for some time.

### Steps to reproduce the bug

1. Edge cluster is unavailable for some time
2. Cluster becomes available again
3. Gloo Fed is no longer trying to reconcile the cluster (no matter how long you waint)
4. Restart Gloo-Fed
5. Cluster was reconciled

### Expected Behavior

I expect Gloo-Fed to reconcile a cluster when it becomes available again, within a reasonable amount of time

**Comment by jenshu** [comment]
Per discussion, we need to make _at least_ the following configurable in gloo-fed (possibly through helm values that configure env variables)
- initial retry delay
- max number of retries (up to infinite)
- max delay between retries

**Comment by jenshu** [comment]
Available in GlooEE v1.14.0-beta10 and v1.13.12

In the gloo fed chart, these can be configured as follows (below are the default values):
```
glooFed:
  retries:
    # this is likely the one you care about, which will retry manager creation when the remote cluster can't be reached
    clusterWatcherRemote:
      type: backoff  # can be either backoff or fixed
      delay: 1s  # delay between retries
      maxDelay: 0  # if 0, there is no max delay
      maxJitter: 100ms  # if 0, then no delay randomness will be added
      attempts: 0  # 0 means unlimited attempts/retry forever
    # below options are to retry status updates on management cluster when a remote cluster is added/removed
    clusterWatcherLocal:
      type: backoff
      delay: 100ms
      maxDelay: 0
      maxJitter: 100ms
      attempts: 5
```
