### ISSUE TITLE
gateway objects not cleaned up after disabling it from helm

### ISSUE THREAD

**Issue by pszeto** [solo-io/gloo#7827]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

1.23.x

### Describe the bug

gateway objects not cleaned up after disabling it from helm

### Steps to reproduce the bug

Deploy multiple gateways using helm:

```
gloo:
  gateway:
    persistProxySpec: true
    validation:
      allowWarnings: false
      alwaysAccept: false
      warnRouteShortCircuiting: true
  gatewayProxies:
    gatewayProxy:
      disabled: true
    firstGW:
      disabled: false 
      gatewaySettings:
        disableHttpGateway: false
    secondGatewayProxy:
      disabled: false
      gatewaySettings:
        disableHttpGateway: false

```
This will generate a gateway object for `first-gw` and `second-gateway-proxy`

```
k get gateways.gateway.solo.io -n gloo-system                                                                                                                    
NAME                       AGE
first-gw                   22s
first-gw-ssl               22s
second-gateway-proxy       2m8s
second-gateway-proxy-ssl   2m8s
```

There would be deployments and services for both the gateways and VirtualServices will have status from both gateways:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.solo.io/v1","kind":"VirtualService","metadata":{"annotations":{},"name":"vs-httpbin","namespace":"gloo-system"},"spec":{"virtualHost":{"domains":["*"],"routes":[{"matchers":[{"prefix":"/"}],"options":{"prefixRewrite":"/"},"routeAction":{"single":{"upstream":{"name":"gloo-mesh-gloo-mesh-ui-8090","namespace":"gloo-system"}}}}]}}}
  creationTimestamp: "2023-02-09T20:19:43Z"
  generation: 6
  name: vs-httpbin
  namespace: gloo-system
  resourceVersion: "730789"
  uid: 0538b125-09e7-43f8-bee5-f2c48836470e
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      options:
        prefixRewrite: /
      routeAction:
        single:
          upstream:
            name: gloo-mesh-gloo-mesh-ui-8090
            namespace: gloo-system
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.first-gw_gloo-system':
          reportedBy: gloo
          state: Accepted
        '*v1.Proxy.second-gateway-proxy_gloo-system':
          reportedBy: gloo
          state: Accepted
```

Now disable the `first-gw` with by changing the helm values `gloo.gatewayProxies.firstGW.disabled=true`

```
gloo:
  gateway:
    persistProxySpec: true
    validation:
      allowWarnings: false
      alwaysAccept: false
      warnRouteShortCircuiting: true
  gatewayProxies:
    gatewayProxy:
      disabled: true
    firstGW:
      disabled: true  # disable first gateway
      gatewaySettings:
        disableHttpGateway: false
    secondGatewayProxy:
      disabled: false
      gatewaySettings:
        disableHttpGateway: false
```

The `first-gw` service and deployment will be gone, but the gateway object will still remain:

```
k get svc -n gloo-system                                                                                                  
NAME                                  TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                AGE
gloo                                  ClusterIP      10.71.243.109   <none>          9977/TCP,9976/TCP,9988/TCP,9966/TCP,9979/TCP,443/TCP   6m49s
gloo-fed-console                      ClusterIP      10.71.242.251   <none>          10101/TCP,8090/TCP,8081/TCP                            6m49s
glooe-grafana                         ClusterIP      10.71.253.178   <none>          80/TCP                                                 6m49s
glooe-prometheus-kube-state-metrics   ClusterIP      10.71.240.207   <none>          8080/TCP                                               6m49s
glooe-prometheus-server               ClusterIP      10.71.246.141   <none>          80/TCP                                                 6m49s
second-gateway-proxy                  LoadBalancer   10.71.244.42    34.75.148.175   80:30188/TCP,443:31794/TCP                             6m49s
```

```
 k get deployment -n gloo-system                                                                                         
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
discovery                             1/1     1            1           7m9s
gloo                                  1/1     1            1           7m9s
gloo-fed                              1/1     1            1           7m9s
gloo-fed-console                      1/1     1            1           7m9s
glooe-grafana                         1/1     1            1           7m9s
glooe-prometheus-kube-state-metrics   1/1     1            1           7m9s
glooe-prometheus-server               1/1     1            1           7m9s
observability                         1/1     1            1           7m9s
second-gateway-proxy                  1/1     1            1           7m9s
```

```
 k get gateways.gateway.solo.io -n gloo-system                                                                     
NAME                       AGE
first-gw                   5m25s
first-gw-ssl               5m25s
second-gateway-proxy       7m11s
second-gateway-proxy-ssl   7m11s
```

```
k get proxy -A                                                                                                             
NAMESPACE     NAME                   AGE
gloo-system   first-gw               5m41s
gloo-system   second-gateway-proxy   6m57s
```

and VirtualService will still have the old gateway status.

```
status:
  statuses:
    gloo-system:
      reportedBy: gloo
      state: Accepted
      subresourceStatuses:
        '*v1.Proxy.first-gw_gloo-system':
          reportedBy: gloo
          state: Accepted
        '*v1.Proxy.second-gateway-proxy_gloo-system':
          reportedBy: gloo
          state: Accepted
```

### Expected Behavior

The gateway object and proxy object for the removed gateway should removed.  The VS should have the statuses updated for the removed gateway.
