### ISSUE TITLE
headerSecretRef doesn't work with Opaque type secret

### ISSUE THREAD

**Issue by AkshayAdsul** [solo-io/gloo#7963]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

When using headerSecretRef to add headers in a route as explained in doco 
https://docs.solo.io/gloo-edge/v1.10.x/guides/traffic_management/request_processing/append_remove_headers/.
The doco says 
The type of the secret must be gloo.solo.io/header or Opaque
But in reality this works only for type gloo.solo.io/header. The routetable is not accepted by Gloo if we use Opaque secret. It gets accepted as soon as we switch to gloo header type.

### Steps to reproduce the bug

1. Create secret of type opaque `kubectl create secret generic my-secret --from-literal=my-header=somevalue`
2. Update VS with headerManipulation struct which uses the headerSecretRef
    ```yaml
   options:
      headerManipulation:
          requestHeadersToAdd:
          - headerSecretRef:
              name: my-secret
              namespace: gloo-system
    ```
3. This fails with below error
reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *headers.plugin:
            list did not find secret gloo-system.my-secret. Route Name: gloo-system_test-service-vs-route-0-matcher-0\n\n"
          reportedBy: gloo
          state: Rejected

4. But when we switch the secret type to  gloo header.

### Expected Behavior

This should work when the type of the secret is Opaque.

### Additional Context

Refer https://solo-io.zendesk.com/agent/tickets/1548
