### ISSUE TITLE
Unable to get cross account lambda working in 1.12.x

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#7965]
### Gloo Edge Version

1.12.x

### Kubernetes Version

None

### Describe the bug

Cross account lambda doesnt seem to be working in 1.12.x We have had multiple calls with the customer + engineering and we are unable to get things working.

### Steps to reproduce the bug

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: consumer-api-test
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: gloo-tls-secret
      namespace: gloo-system
  virtualHost:
    domains:
      - '*'
    options:
    routes:
      routeAction:
        single:
          destinationSpec:
            aws:
              logicalName: abcdefg
              requestTransformation: true
              unwrapAsApiGateway: true
          upstream:
            name: gloo-lambda-integration
            namespace: gloo-system
        matchers:
          - prefix: /
```

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: gloo-lambda-integration
  namespace: gloo-system
spec:
  aws:
    awsAccountId: '123456789'
    lambdaFunctions:
      - logicalName: abcdefg
```

### Expected Behavior

cross account should work

### Additional Context

https://solo-io.slack.com/archives/GLHNC87RN/p1677099399978709
