### ISSUE TITLE
Support for REDIS_URL passed as customEnv

### ISSUE THREAD

**Issue by adamwalach** [solo-io/gloo#7992]
### Version

1.13.x (latest stable)

### Is your feature request related to a problem? Please describe.

In the `gloo-ee` chart, in `templates/2-rate-limit-deployment.yaml` I need to provide value for `REDIS_URL` taken from a secret. I use customEnv section but I end up with two definitions of the same variable. With the current implementation there is no possibility to disable `REDIS_URL` in the chart.

### Describe the solution you'd like

In the `gloo-ee/templates/2-rate-limit-deployment.yaml` I added new `else if` condition that uses new `disableBuiltinUrl` flag:

```
....
              value: /var/run/envoy/ratelimit.sock
            - name: REDIS_SOCKET_TYPE
              value: unix
            {{- else if .Values.redis.disableBuiltinUrl }}{{/* end .Values.redis.clientSideShardingEnabled */}}
            {{- /* REDIS_URL generation is disabled, instead it can be provided by customEnv */ -}}
            {{- else }}
            - name: REDIS_URL
              value: {{ printf "%s:%v" $redisName .Values.redis.service.port }}
...
```

This flag needs to be also added to `values.yaml`
```
    runAsGroup: 999
    runAsUser: 999
    staticPort: 6379
    disableBuiltinUrl: false
```

**Comment by Bslabe123** [comment]
Looked into it a bit more and given that the customer uses ArgoCI could they implement this kustomize patch?

```
cat > redis-url-patch.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limit
  namespace: gloo-system
spec:
  template:
    spec:
      containers:
        - \$patch: merge
          name: rate-limit
          env:
            - \$patch: merge
              name: REDIS_URL
              value: "some-value"
EOF
```

```
cat > kustomize.sh <<EOF
#!/bin/sh
cat > base.yaml
# you can also use "kustomize build ." if you have it installed.
exec kubectl kustomize
EOF
chmod +x ./kustomize.sh
```

```
cat > kustomization.yaml <<EOF
resources:
- base.yaml
patchesStrategicMerge:
- sysctl-patch.yaml
EOF
```

```
helm template glooe _test/gloo-ee --namespace gloo-system --set license_key="some-license-key" --post-renderer ./kustomize.sh
```
