### ISSUE TITLE
Only RSA public key is supported in PEM format 

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#7993]
### Version

1.13.x (latest stable)

### Is your feature request related to a problem? Please describe.

Yes, my feature is related to a problem.

If you create a VirtualService with jet validation but you are using ECDSA P256 algorithm it doesn't work and you get the following error message:
```
"1 error occurred:\n\t* VirtualHost Error: ProcessingError. Reason:
        invalid virtual host [gloo-system_default]: Error translating provider for
        gloo-system_default: failed to parse inline jwks: cannot parse local jwks:
        3 errors occurred:\n\t* PEM: unsupported public key. only RSA public key is
        supported in PEM format\n\t* JWKS: invalid character '-' in numeric literal\n\t*
        JWK: invalid character '-' in numeric literal\n\n\n\n"
```

Steps to reproduce:

Create a Virtual Service with ECDSA P256 algorithm generated PEM:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      jwtStaged:
        beforeExtAuth:
          providers:
            inline:
              issuer: de.telekom.tsms.tokenservice
              jwks:
                local:
                  key: |
                    -----BEGIN PUBLIC KEY-----
                    ECDSA P256 algorithm Cert
                    -----END PUBLIC KEY-----
              tokenSource:
                headers:
                - header: authorization
                  prefix: 'Bearer '
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
status:
  statuses:
    gloo-system:
      reason: "1 error occurred:\n\t* VirtualHost Error: ProcessingError. Reason:
        invalid virtual host [gloo-system_default]: Error translating provider for
        gloo-system_default: failed to parse inline jwks: cannot parse local jwks:
        3 errors occurred:\n\t* PEM: unsupported public key. only RSA public key is
        supported in PEM format\n\t* JWKS: invalid character '-' in numeric literal\n\t*
        JWK: invalid character '-' in numeric literal\n\n\n\n"
      reportedBy: gloo
      state: Rejected
      subresourceStatuses:
        '*v1.Proxy.gateway-proxy_gloo-system':
          reportedBy: gloo
          state: Accepted
```
