### ISSUE TITLE
gloo-ee chart renders invalid yaml when default gw proxy disabled and kubeResourceOverride is used

### ISSUE THREAD

**Issue by jenshu** [solo-io/gloo#8025]
### Gloo Edge Version

1.12.x

### Kubernetes Version

None

### Describe the bug

Trying to install GlooEE with these values
```
gloo:
  gatewayProxies:
    gatewayProxy:
      disabled: true
    otherProxy:
      disabled: false
      kubeResourceOverride:
        spec:
          template:
            metadata:
              labels:
                foo: bar
license_key: foobar
```
results in an error `Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error parsing : invalid Yaml document separator: apiVersion: apps/v1` due to the `---` separator not being on its own line:
```
# Source: gloo-ee/charts/gloo/templates/7-gateway-proxy-deployment.yaml
---apiVersion: apps/v1
kind: Deployment
```

This seems to only occur when all the following are true:
- using the gloo-ee chart (couldn't reproduce in the gloo chart, but we should double check that)
- when the default gatewayProxy is disabled
- the enabled proxy comes alphabetically _after_ `gatewayProxy` (i.e. couldn't reproduce with a proxy named `aProxy`)
- the enabled proxy uses a kubeResourceOverride

Might be fixed by moving [the divider](https://github.com/solo-io/gloo/blob/c4fb0d7b2aba7c6cd7232a9b796c664ac19448fb/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L528) to right after [this line](https://github.com/solo-io/gloo/blob/c4fb0d7b2aba7c6cd7232a9b796c664ac19448fb/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L27)

We should add testing to ensure we're not making the same mistake in other templates too.

### Steps to reproduce the bug

see above

### Expected Behavior

render valid yaml
