### ISSUE TITLE
Unable to Modify RLC with Validating Webhook Enabled

### ISSUE THREAD

**Issue by kevin-shelaga** [solo-io/gloo#8042]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

With the validating webhook enabled, changing the `requestsPerUnit` on a RLC and applying the change causes the config to be rejected with errors.

```sh
failed to process RateLimitConfig resource with name [global-limit] in namespace [production]: unknown rate limit config type <nil> 
```

### Steps to reproduce the bug

1. enabled validating webhook
2. apply the following config and reference it to a VS
```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: global-limit
  namespace: staging
spec:
  raw:
    descriptors:
    - key: generic_key
      value: counter
      rateLimit:
        requestsPerUnit: 450
        unit: MINUTE
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counter
```
3. Update the `requestsPerUnit`
```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: global-limit
  namespace: staging
spec:
  raw:
    descriptors:
    - key: generic_key
      value: counter
      rateLimit:
        requestsPerUnit: 15000
        unit: MINUTE
    rateLimits:
    - actions:
      - genericKey:
          descriptorValue: counter
```

### Expected Behavior

- [ ] No errors
- [ ] All related issues (see below) are confirmed to be resolved as well

### Additional Context

Workaround: Remove the RLC from being referenced by the VS, make the change and apply, then reference again. Or simply disable the validating webhook and make your change, then enable again.

### Related Issues
There are a few issues which are either duplicates of this, or very similar, so we have closed them, and expect them to be solved by this work:
- https://github.com/solo-io/gloo/issues/8238
- https://github.com/solo-io/gloo/issues/8239
