### ISSUE TITLE
Extauth does not consider x-forwarded-* headers for OIDC redirects

### ISSUE THREAD

**Issue by anessi** [solo-io/gloo#8069]
### Gloo Edge Version

1.11.x

### Kubernetes Version

1.24.x

### Describe the bug

Extauth does not consider `x-forwarded-*` headers for OIDC redirects. When having a setup where there's an external WAF or other reverse proxy in front of Gloo this would update the `host` to the hostname of the WAF/reverse proxy header but set `x-forwarded-host` to the value of the initial entry point (e.g. the WAF). When `extauth` does a redirect to the `appUrl` after successful authentication with OIDC it's expected to redirect to the WAF/reverse proxy host set in the `x-forwarded-host`. However, currently only the `host` header is considered.

### Steps to reproduce the bug

1. Setup OIDC
2. Set a `x-forwarded-host` header
3. Check that the redirect is not going to the host set in the `x-forwarded-host` header. You can see this in the extauth logs.

### Expected Behavior

It is expected that all `x-forwarded-*` headers are considered as this is a very common setup to have a WAF/reverse-proxy in front of the a cluster/Gloo.

### Additional Context

Confirmed with Solo field engineers.

Workaround: use a transformation to set the host header statically:
```yaml
      stagedTransformations:
        early:
          requestTransforms:
          - requestTransformation:
              transformationTemplate:
                headers:
                  :host:
                    text: myhost
```
or rewrite the `location` header in case `x-forwarded-host` is set:
```yaml
      stagedTransformations:
        inheritTransformation: true
        regular:
          responseTransforms:
          - responseTransformation:
              transformationTemplate:
                extractors:
                  host:
                    header: location
                    regex: ^https?://([^/]+)(.*)$
                    subgroup: 1
                  path:
                    header: location
                    regex: ^https?://([^/]+)(.*)$
                    subgroup: 2
                headers:
                  location:
                    text: '{% if header("location") != "" and request_header("x-forwarded-host")
                      != "" %}https://{{ request_header("x-forwarded-host") }}{{ path
                      }}{% else %}{{ header("location") }}{% endif %}'
                passthrough: {}
```
