### ISSUE TITLE
Unable to override route cors allowCredentials without allowOrigin or allowOriginRegex

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8115]
### Gloo Edge Version

1.13.x (latest stable)

### Kubernetes Version

None

### Describe the bug

The RouteOptions documentation states that _**Defines a CORS policy for the route If a CORS policy is also defined on the route’s virtual host, the policies are merged**._

However, if I try to override `allowCredentials` without also defining `allowOrigin` or `allowOriginRegex` in the override then the `allowCredentials` override is ignored. 

### Steps to reproduce the bug

Add CORS config to at the VirtualHost level. For example:

```
  virtualHost:
    domains:
    - foo.com
    options:
      cors:
        allowCredentials: false
        allowOrigin:
        - foo.com
```

Add an override at the RouteOptions level. For example:

```
    - matchers:
      - prefix: /foo
      options:
        cors:
          allowCredentials: true
```

Note that the `allow_credentials: true` is never set in Envoy. The following will generate an override on the Route:

```
    - matchers:
      - prefix: /foo
      options:
        cors:
          allowCredentials: true
          allowOrigin:
          - foo.com
```

### Expected Behavior

`allowCredentials` override at the Route level does not require `allowOrigin` or `allowOriginRegex` to work
