### ISSUE TITLE
Docs: Clarify How Policies Can Be Applied to Resources

### ISSUE THREAD

**Issue by sam-heilbron** [solo-io/gloo#8116]
### Version

master

### Describe the requested changes

Some of our APIs in Gloo Edge contain configuration that is large and potentially used in a number of places. For example, a VirtualService that defines WAF configuration. In the first iteration of our API, these policies were defined inline. This led to resources being large, and needing to be updated frequently. For example, everytime the WAF policy needs to be updated, all VirtualServices that use it (could be 1000's) need to also be updated.

We built a mechanism to externalize policy definitions in VirtualServices and Routes. This feature is extremely useful and something that we should document to users.

This feature was introduced here: https://github.com/solo-io/gloo/pull/4863

The benefit, is that now a policy can be defined in one place (WAF config for virtual hosts) and any resources that use it, can reference that policy by name/namespace. Any update to that policy does not require updates to the resource.

### Link to any relevant existing docs

I'm not aware of any.

### Additional Context

Internal Slack context: https://solo-io-corp.slack.com/archives/CEDCS8TAP/p1682019868832699

**Comment by bdecoste** [comment]
### Describe the requested changes

The doc here: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/external_options.proto.sk/#virtualhostoption

Should be:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: http
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      headerManipulation:
        requestHeadersToRemove: "header-from-vhost"
    optionsConfigRefs:    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      delegateOptions:
      - name: virtualhost-external-options-1
        namespace: opt-namespace
      - name: virtualhost-external-options-2
        namespace: opt-namespace
```

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/external_options.proto.sk/#virtualhostoption
