### ISSUE TITLE
VirtualHostOption doc missing optionsConfigRefs for delegateOptions

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8128]
### Version

master

### Describe the requested changes

The doc here: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/external_options.proto.sk/#virtualhostoption

Should be:

```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: http
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      headerManipulation:
        requestHeadersToRemove: "header-from-vhost"
    optionsConfigRefs:    <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      delegateOptions:
      - name: virtualhost-external-options-1
        namespace: opt-namespace
      - name: virtualhost-external-options-2
        namespace: opt-namespace
```

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gateway/api/v1/external_options.proto.sk/#virtualhostoption
