### ISSUE TITLE
Documentation of floatingUserId out of date

### ISSUE THREAD

**Issue by jbohanon** [solo-io/gloo#8163]
### Version

master

### Describe the requested changes

The example in the docs for using `floatingUserId` when installing via helm is missing some fields that may be required. 

The example yaml for gloo Open Source should show the options 
```
gateway:
    rolloutJob:
        floatingUserId: true
    cleanupJob:
        floatingUserId: true
```
The example yaml for gloo Enterprise should show the options
```
gloo:
    gateway:
        rolloutJob:
            floatingUserId: true
        cleanupJob:
            floatingUserId: true
```

### Link to any relevant existing docs

https://docs.solo.io/gloo-edge/latest/installation/platform_configuration/cluster_setup/#openshift

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208024847164552) by [Unito](https://www.unito.io)
