### ISSUE TITLE
directResponseAction with missing status field passes validation and causes outofsync RDS

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8210]
### Gloo Edge Version

1.13.x

### Kubernetes Version

None

### Describe the bug

If a directResponseAction is missing the status field (see below) then the invalid config passes Gloo validation and leaks to Envoy where is causes an RDS rejection and the Envoys to become outofsync

### Steps to reproduce the bug

```
    - directResponseAction:
        body: foo
      matchers:
      - prefix: /direct
```

### Expected Behavior

Missing status field fails Gloo validation and is not leaked to Envoy
