### ISSUE TITLE
rateLimitConfig with Nested Descriptors fail 

### ISSUE THREAD

**Issue by afro-coder** [solo-io/gloo#8238]
### Gloo Edge Version

1.13.x

### Kubernetes Version

None

### Describe the bug

When using rateLimitConfig with Nested Descriptors the  generated config doesn't have the action created for Rate limiting. Gloo Edge 1.13.16 is the version in use.

### Steps to reproduce the bug

1. Create a Ratelimit config as such and Virtual Service
```yaml
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: global
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: generic_key
      value: per-minute
      descriptors:
      - key: remote_address
        rateLimit:
          requestsPerUnit: 10
          unit: MINUTE
    rateLimits:
    - actions:
      - genericKey:
        descriptorValue: per-minute
      - remoteAddress: {}
```
Virtual Service
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  annotations:
  creationTimestamp: "2023-05-17T09:04:53Z"
  generation: 45
  name: default
  namespace: gloo-system
  resourceVersion: "23594"
  uid: bd75b3fb-47d5-4874-b3fb-7319e833009e
spec:
  virtualHost:
    domains:
    - '*'
    options:
      rateLimitConfigs:
        refs:
        - name: global
          namespace: gloo-system
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```
2. Apply this config | If you have Strict Validation enabled for config you see the following error.
```bash
Resource: "ratelimit.solo.io/v1alpha1, Resource=ratelimitconfigs", GroupVersionKind: "ratelimit.solo.io/v1alpha1, Kind=RateLimitConfig"
Name: "global", Namespace: "gloo-system"
for: "ratelimit-nested.yaml": error when patching "ratelimit-nested.yaml": admission webhook "gloo.gloo-system.svc" denied the request: resource incompatible with current Gloo snapshot: [Validating *v1alpha1.RateLimitConfig failed: 1 error occurred:
        * Validating *v1alpha1.RateLimitConfig failed: validating *v1alpha1.RateLimitConfig name:"global" namespace:"gloo-system": failed to validate Proxy [namespace: gloo-system, name: gateway-proxy] with gloo validation: VirtualHost Error: ProcessingError. Reason: invalid virtual host [gloo-system_default]: 1 error occurred:
        * failed to process RateLimitConfig resource with name [global] in namespace [gloo-system]: unknown rate limit config type <nil>

; failed extension resource reports: 3 errors occurred:
        * invalid resource gloo-system.gateway-proxy
        * unknown rate limit config type <nil>
        * unknown rate limit config type <nil>
```
3. Check the Gloo Pod logs, and you will see this error continously
```
[2023-05-17 12:11:33.330][7][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.RateLimits[0]: embedded message failed validation | caused by RateLimitValidationError.Actions[1]: embedded message failed validation | caused by field: "action_specifier", reason: is required): name: "listener-::-8080-routes"
virtual_hosts {
  name: "gloo-system_default"
  domains: "*"
  routes {
    match {
      prefix: "/"
    }
    route {
      cluster: "default-petstore-8080_gloo-system"
    }
    name: "gloo-system_default-route-0-matcher-0"
  }
  rate_limits {
    stage {
      value: 2
    }
    actions {
      generic_key {
        descriptor_value: "gloo-system.global"
      }
    }
    actions {
    }
    actions {
    }
  }
  typed_per_filter_config {
    key: "envoy.filters.http.ext_authz"
    value {
      [type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute] {
        disabled: true
      }
    }
  }
}
```
The served config shows the following
```
#rds
name: listener-::-8080-routes
virtualHosts:
- domains:
  - '*'
  name: gloo-system_default
  rateLimits:
  - actions:
    - genericKey:
        descriptorValue: gloo-system.global
    - {}
    - remoteAddress: {}
    stage: 2
  routes:
  - match:
      prefix: /
    name: gloo-system_default-route-0-matcher-0
    route:
      cluster: default-petstore-8080_gloo-system
  typedPerFilterConfig:
    envoy.filters.http.ext_authz:
      '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
      disabled: true
```
There is no change in the envoy dump since gloo doesn't push this config.

### Expected Behavior

The Actions from the nested descriptors should be added in gloo
