### ISSUE TITLE
rateLimitConfig doesn't allow quotes in the value for key: type

### ISSUE THREAD

**Issue by afro-coder** [solo-io/gloo#8239]
### Gloo Edge Version

1.14.x (latest stable)

### Kubernetes Version

None

### Describe the bug

When specifying a value with quotes in `key: type`  Go fails to parse it with the following error
```bash
Error: 2 errors occurred:
        * converting output crd: unmarshalling crd spec on custom resource global in namespace gloo-system into v1alpha1RateLimitConfig: json: cannot unmarshal number into Go value of type string
        * Virtual service references unknown rate limit config:
  Virtual service: default test-service-vs
  Rate Limit Config: gloo-system global
```

### Steps to reproduce the bug

1. Create RatelimitConfig as such
```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: global
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: type
      value: "example"
      descriptors:
        - key: number
          value: 10
          rateLimit:
            requestsPerUnit: 3
            unit: MINUTE
    rateLimits:
      - actions:
        - requestHeaders:
            descriptorKey: type
            headerName: x-type
        - requestHeaders:
            descriptorKey: number
            headerName: x-number
```
Apply this config and reference it in a VirtualService
```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  annotations:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      rateLimitConfigs:
        refs:
        - name: global
          namespace: gloo-system
    routes:
    - matchers:
      - prefix: /
      routeAction:
        single:
          upstream:
            name: default-petstore-8080
            namespace: gloo-system
```
You should see the following
```
Error: 2 errors occurred:
        * converting output crd: unmarshalling crd spec on custom resource global in namespace gloo-system into v1alpha1RateLimitConfig: json: cannot unmarshal number into Go value of type string
        * Virtual service references unknown rate limit config:
  Virtual service: default test-service-vs
  Rate Limit Config: gloo-system global
```
If strict validation is enabled
```
Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"ratelimit.solo.io/v1alpha1\",\"kind\":\"RateLimitConfig\",\"metadata\":{\"annotations\":{},\"n
ame\":\"global\",\"namespace\":\"gloo-system\"},\"spec\":{\"raw\":{\"descriptors\":[{\"descriptors\":[{\"key\":\"number\",\"rateLimit\":{\"requestsPerUnit\":3,\"unit\":\"MINUTE\"},\"value\":10
}],\"key\":\"type\",\"value\":\"example\"}],\"rateLimits\":[{\"actions\":[{\"requestHeaders\":{\"descriptorKey\":\"type\",\"headerName\":\"x-type\"}},{\"requestHeaders\":{\"descriptorKey\":\"n
umber\",\"headerName\":\"x-number\"}}]}]}}}\n"}},"spec":{"raw":{"descriptors":[{"descriptors":[{"key":"number","rateLimit":{"requestsPerUnit":3,"unit":"MINUTE"},"value":10}],"key":"type","valu
e":"example"}],"rateLimits":[{"actions":[{"requestHeaders":{"descriptorKey":"type","headerName":"x-type"}},{"requestHeaders":{"descriptorKey":"number","headerName":"x-number"}}]}]}}}
to:
Resource: "ratelimit.solo.io/v1alpha1, Resource=ratelimitconfigs", GroupVersionKind: "ratelimit.solo.io/v1alpha1, Kind=RateLimitConfig"
Name: "global", Namespace: "gloo-system"
for: "ratelimit.yaml-broken": error when patching "ratelimit.yaml-broken": admission webhook "gloo.gloo-system.svc" denied the request: resource incompatible with current Gloo snapshot: [Valid
ating *v1alpha1.RateLimitConfig failed: 1 error occurred:
        * Validating *v1alpha1.RateLimitConfig failed: validating *v1alpha1.RateLimitConfig name:"global"  namespace:"gloo-system": failed to validate Proxy [namespace: gloo-system, name: gate
way-proxy] with gloo validation: VirtualHost Error: ProcessingError. Reason: invalid virtual host [default_test-service-vs]: 1 error occurred:
        * failed to process RateLimitConfig resource with name [global] in namespace [gloo-system]: unknown rate limit config type <nil>

; failed extension resource reports: 3 errors occurred:
        * invalid resource gloo-system.global
        * unknown rate limit config type <nil>
        * unknown rate limit config type <nil>
]
```
However this doesn't help with understanding what went wrong, it can only be seen when strict validation is disabled.

### Expected Behavior

The string should be parsed as a string.
