### ISSUE TITLE
Modifying a pseudo-header passes Gloo validation but is rejected by Envoy 

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8254]
### Gloo Edge Version

1.13.x

### Kubernetes Version

None

### Describe the bug

I configured a VirtualService to add a pseudo-header (e.g. :schema) which was passed by Gloo validation but was rejected by Envoy causing a bad route and Envoy to become outofsync with the control plane. 

### Steps to reproduce the bug

Create a VS with the following

```
    options:
      headerManipulation:
        responseHeadersToAdd:
          - header:
              key: ":scheme"
              value: "https"
            append: false
```

That passes the validating webhook, VS status is accepted, and passes `glooctl check` except for RDS outofsync) but causes:

`[2023-05-19 14:01:29.817][7][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.route.v3.RouteConfiguration rejected: :-prefixed or host headers may not be modified`

### Expected Behavior

Pseudo-header manipulation is rejected by Gloo validation
