### ISSUE TITLE
Incorrect RunAsUser/floatingUserId logic in gateway-proxy-deployment Helm chart

### ISSUE THREAD

**Issue by sheidkamp** [solo-io/gloo#8387]
### Gloo Edge Version

1.14.x

### Kubernetes Version

None

### Describe the bug

In this section of the Helm template:
https://github.com/solo-io/gloo/blob/5b16328f4dc1a35912f689ca309e2f74ebf65fcd/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L221

`runAsUser` is getting incorrectly set to 0.

We should be using an approach similar to here: https://github.com/solo-io/gloo/blob/5b16328f4dc1a35912f689ca309e2f74ebf65fcd/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L112

which would look something like:
```
{{- $securityDefaults := dict "runAsNonRoot" $spec.podTemplate.runUnprivileged "capabilities" $capabilities "readOnlyRootFilesystem" true "allowPrivilegeEscalation" false }}
{{- if not $spec.podTemplate.floatingUserId -}}
  {{- $_ := set $securityDefaults "runAsUser" $spec.podTemplate.runAsUser }}
{{- end -}}
```
(the above is untested)

### Steps to reproduce the bug

`helm template install/helm/gloo --set-string gatewayProxies.gatewayProxy.podTemplate.floatingUserId=true --debug`

produces:
```
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 0
 ```
 
 When `runAsUser` should be omitted
(also investigate why this produces invalid YAML)

### Expected Behavior

`runAsUser` should be omitted in the reproduction scenario
