### ISSUE TITLE
Creating a custom gateway proxy with VS selector not configures the proxy correctly: no listening ports

### ISSUE THREAD

**Issue by mtenrero** [solo-io/gloo#8403]
### Gloo Edge Version

1.14.x (latest stable)

### Kubernetes Version

1.24.x

### Describe the bug

When defining several gatewayProxies using the Helm Chart, it's required to define the virtualService selector for properly routing traffic.

This works fine for proxies with just one port, (HTTP or HTTPS) But when configuring both HTTP and HTTPS ports, the proxy deployed is not able to open any port.

Helm config:

```yaml
gatewayProxies:
  default: # Proxy name for public access (Internet facing)
    envoyLogLevel: debug
    disabled: false # overwrite the "default" value in the merge step
    kind:
      deployment:
        replicas: 1
    service:
      httpPort: 80
      httpsFirst: false
      httpsPort: 443
      type: LoadBalancer
    gatewaySettings:
      customHttpsGateway: # using the default HTTPS Gateway
        virtualServiceSelector:
          gateway-type: default # label set on the VirtualService
      customHttpGateway: # using the default HTTPS Gateway
        virtualServiceSelector:
          gateway-type: default # label set on the VirtualService
```
Generated GW Resources:
```yaml
apiVersion: gateway.solo.io/v1
    kind: Gateway
    metadata:
      name: default
      namespace: default
      labels:
        app: gloo
    spec:
      bindAddress: "::"
      bindPort: 8080
      httpGateway:
        virtualServiceSelector:
          gateway-type: default
      useProxyProto: false
      ssl: false
      proxyNames:
      - default
    ---
    apiVersion: gateway.solo.io/v1
    kind: Gateway
    metadata:
      name: default-ssl
      namespace: default
      labels:
        app: gloo
    spec:
      bindAddress: "::"
      bindPort: 8443
      httpGateway:
        virtualServiceSelector:
          gateway-type: default
      useProxyProto: false
      ssl: true
      proxyNames:
      - default
```

Proxy listening ports:

```bash
/ $ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      7/envoy
tcp        0      0 127.0.0.1:19000         0.0.0.0:*               LISTEN      7/envoy
```

### Steps to reproduce the bug

1. configure Helm Chart for deploying some gatewayProxies
2. Configure at least one of them with customHttpsGateway and customHttpGateway (just one works fine)
3. Deploy solution
4. No Ports will be open by the proxy

### Expected Behavior

Both Ports will be listening together
