### ISSUE TITLE
Creating several GatewayProxies with Helm doesn't generate SSL Gateways

### ISSUE THREAD

**Issue by mtenrero** [solo-io/gloo#8404]
### Gloo Edge Version

1.14.x (latest stable)

### Kubernetes Version

1.24.x

### Describe the bug

Due an error in the Helm template, when defining GatewayProxies with SSL support, those are not properly generated in some scenarios:

```yaml
---
    apiVersion: gateway.solo.io/v1
    kind: Gateway
    metadata:
      name: default
      namespace: default
      labels:
        app: gloo
    spec:
      bindAddress: "::"
      bindPort: 8080
      httpGateway:
        virtualServiceSelector:
          gateway-type: default
      useProxyProto: false
      ssl: false
      proxyNames:
      - default
    ---
    apiVersion: gateway.solo.io/v1
    kind: Gateway
    metadata:
      name: default-ssl
      namespace: default
      labels:
        app: gloo
    spec:
      bindAddress: "::"
      bindPort: 8443
      httpGateway:
        virtualServiceSelector:
          gateway-type: default
      useProxyProto: false
      ssl: true
      proxyNames:
      - default---
```

### Steps to reproduce the bug

1. Define several Gateway Proxies in Helm values
2. Install/Template Chart
3. SSL Gateways are not generated due to a missing newline char

### Expected Behavior

SSL Gateways should be correctly generated
