### ISSUE TITLE
Improved observability for HTTP parser issue

### ISSUE THREAD

**Issue by guydc** [solo-io/gloo#8439]
### Version

1.14.x (latest stable)

### Is your feature request related to a problem? Please describe.

The envoy HTTP parser can fail to parse requests for various reasons. The [failure reason](https://github.com/nodejs/http-parser/blob/main/http_parser.h#L242) is only [reported](https://github.com/envoyproxy/envoy/blob/main/source/common/http/conn_manager_impl.cc#L397) when the http module log level is set debug. 

EDIT: permalink for the log line in question: https://github.com/envoyproxy/envoy/blob/b4f37553d6887447f942a1aedbc8c2dacae45537/source/common/http/conn_manager_impl.cc#L397

### Describe the solution you'd like

The parser error should be available as an HTTP access log [command operator](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators). 

### Describe alternatives you've considered

- Setting the log level to debug is not a viable option for live environments 
- TCP dumps or taps are not a viable option for live environments
- Request Shadowing and HTTP tap do not work when a parser error is encountered 
- Some parser errors appear to have a dedicated metric in the HCM's [HTTP1 details](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/response_code_details#http1-details). However, not all errors are covered, and metrics do not provide the request context (client IP, requested server name, etc.) that is necessary to investigate such issues. 

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207721058759246) by [Unito](https://www.unito.io)

**Comment by idogoren** [comment]
+1 for the feature request.

**Comment by nrjpoddar** [comment]
@nfuden to look at this issue for scope/estimation.

**Comment by ashishb-solo** [comment]
I've done some investigation into this. Envoy already has a [command operator](https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log/usage#command-operators) called `%RESPONSE_CODE_DETAILS%`, which should, in theory, print the reason why the parsing failed.

I configured Envoy with the configuration at the bottom of this message and crafted a few of my own HTTP requests to send to the server and understand how it this operator printed. It works for quite a few errors; for example, `http1.too_many_headers`, `http1.unexpected_underscore`, or `http1.content_length_and_chunked_not_allowed`. However, sometimes the only printed message is `http1.codec_error` when more descriptive messages could (ideally) be provided.

I provide some examples below. Note that I did my best to try crafting HTTP messages that would result in the correspondingly listed parse error messages; but the fact that these messages did not result the errors that we had hoped for may simply be because I did not craft these errors correctly.

You can run these examples by simply running `nc localhost 10000 < filename.http` - make sure when saving these to a file that DOS-style line-endings are used (ie. \r\n instead of just \n) [in accordance with the HTTP specification](https://www.rfc-editor.org/rfc/rfc2616#page-16).

### Invalid URL 

```
GET \ HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.88.1
Accept: */*
```

Results in this output:

```
[2024-07-31 15:50:15.429][65051][info][http] [source/common/http/conn_manager_impl.cc:431] [Tags: "ConnectionId":"0"] dispatch error: http/1.1 protocol error: HPE_INVALID_URL
RESPONSE CODE DETAILS: http1.codec_error
```

Note how the log reports `HPE_INVALID_URL` but the response code details prints a generic error.

### Invalid HTTP Version

```
GET / HTTP/xxx
Host: localhost:8080
User-Agent: curl/7.88.1
Accept: */*
```

```
[2024-07-31 15:51:59.468][65049][info][http] [source/common/http/conn_manager_impl.cc:431] [Tags: "ConnectionId":"1"] dispatch error: http/1.1 protocol error: HPE_INVALID_VERSION
RESPONSE CODE DETAILS: http1.codec_error
```

Same as above

### Invalid Header Name Characters

```
GET / HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.88.1
Accept: */*
\❌-header1: va\999lu:e❌1
```

```
[2024-07-31 15:52:33.245][65051][info][http] [source/common/http/conn_manager_impl.cc:431] [Tags: "ConnectionId":"2"] dispatch error: http/1.1 protocol error: INVALID_HEADER_NAME_CHARACTER
RESPONSE CODE DETAILS: http1.codec_error
```

### Envoy config

```
# required for toggling runtime reloadable features
layered_runtime:
  layers:
  - name: admin
    admin_layer: {}

# taken from https://www.envoyproxy.io/docs/envoy/latest/start/quick-start/configuration-static
# or view-source:https://www.envoyproxy.io/docs/envoy/latest/_downloads/92dcb9714fb6bc288d042029b34c0de4/envoy-demo.yaml
admin:
  address:
    socket_address: { address: 127.0.0.1, port_value: 9901 }

static_resources:

  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          common_http_protocol_options:
            headers_with_underscores_action: REJECT_REQUEST
            max_headers_count: 10
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.stdout
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
              log_format:
                text_format_source:
                  inline_string: |
                    RESPONSE CODE DETAILS: %RESPONSE_CODE_DETAILS%



                    .
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "direct response\\n"
                # route:
                #   host_rewrite_literal: www.envoyproxy.io
                #   cluster: service_envoyproxy_io

  clusters:
  - name: service_envoyproxy_io
    type: LOGICAL_DNS
    # Comment out the following line to test on v6 networks
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: service_envoyproxy_io
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: www.envoyproxy.io
                port_value: 443
    transport_socket:
      name: envoy.transport_sockets.tls
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
        sni: www.envoyproxy.io
```
