### ISSUE TITLE
Expose capability to overwrite matching header in passThroughAuth

### ISSUE THREAD

**Issue by jaymiracola** [solo-io/gloo#8477]
### Version

1.14.x (latest stable)

### Is your feature request related to a problem? Please describe.

Currently, only appending to a matching header is supported in passThroughAuth. When a matching header is in the request and response, we dont have a way to work around overwriting that header in the response.

```
    - passThroughAuth:
        http:
          url: https://solo.io/auth
          connectionTimeout: 30s
          request:
            allowedHeaders:
              - authorization
          response:
            allowedUpstreamHeaders:
              - authorization
```

In the above, the `authorization` header needs to be overwritten in the `response`. Currently `allowedUpstreamHeaders` only supports appending.

### Describe the solution you'd like

- [ ] All related Issues (see below) are addressed and confirmed to be resolved

### Additional Context

- https://github.com/solo-io/gloo/issues/8391 can/should be tackled at the same time (by the same person) because the domain is very similar 

### Related Issues
- https://github.com/solo-io/gloo/issues/6205
