### ISSUE TITLE
append: false not working for headerManipulation

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#8525]
### Gloo Edge Version

1.15.x (beta)

### Kubernetes Version

None

### Describe the bug

It seems that [append](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-field-config-core-v3-headervalueoption-append) field is deprecated in envoy, I have a headerManipulation in my VirtualService and the same headerManipulation in my child RouteTable with append false, but they are getting appended any way, the header never gets overwritten, so it seems with the deprecation of this field this stopped working.

### Steps to reproduce the bug

Steps to reproduce:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      headerManipulation:
        responseHeadersToAdd:
        - header:
            key: X-Frame-Options
            value: SAMEORIGIN
    routes:
    - delegateAction:
        selector:
          labels:
            delegate: true
      matchers:
      - prefix: /
 --------
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    delegate: true
  name: child
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - prefix: /get
    options:
      headerManipulation:
        responseHeadersToAdd:
        - append: false
          header:
            key: X-Frame-Options
            value: NEWORIGIN
    routeAction:
      single:
        upstream:
          name: default-httpbin-8000
          namespace: gloo-system
```

### Expected Behavior

Regarding the above VS and RT, X-Frame-Options header should be overwritten with value NEWORIGIN as I have append: true in the RouteTable, however it gets added to the previous header so in the response I am able to see both NEWORIGIN and SAMEORIGIN.
