### ISSUE TITLE
Gloo installation fails when providing a values-overrides file to helm for charts: 0.17.2 0.17.3

### ISSUE THREAD

**Issue by alfredo** [solo-io/gloo#857]
While trying to install gloo providing a custom set of values. .e.g. 

```
$ helm install gloo/gloo --name gloo --namespace gloo-system --version 0.17.3 -f values.yaml
```
Where values.yaml is:
```
rbac:
  create: true

gatewayProxies:
  gateway-proxy:
    service:
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

it fails while generating the chart:

```
Error: render error in "gloo/templates/9-gateway-proxy-configmap.yaml": template: gloo/templates/9-gateway-proxy-configmap.yaml:14:18: executing "gloo/templates/9-gateway-proxy-configmap.yaml" at <$spec.configMap.data>: nil pointer evaluating interface {}.data
```

I have tried modifying the values.yaml structure for the `gatewayProxies` key as per https://github.com/solo-io/gloo/blob/master/install/helm/gloo/values-gateway-template.yaml#L47-L68 but it would still fail.

My testing indicates that the charts affected are:
- gloo-0.17.2
- gloo-0.17.3

As far as I can tell 0.17.1 doesn't present this issue.

Thank you!

**Comment by rickducott** [comment]
Hi, sorry about that. The problem is due to a refactor we made in #839 to adhere to Helm style recommendations. The values structure now should look like:

```
gatewayProxies:
  - name: gateway-proxy
    service:
      extraAnnotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

Where gateway proxies is now a yaml list, and each entry in the list now has a name property. Can you try that?

**Comment by earlsioson** [comment]
@rickducott I gave your suggestion a try and I'm still receiving the same error as the OP. This is the contents of the values file I'm using.
```
gatewayProxies:
  - name: gateway-proxy
    service:
      loadBalancerIP: <myip>
```

**Comment by EItanya** [comment]
@earlsioson I think i know the problem, could you possibly try this 

```
gatewayProxies:
  - name: gateway-proxy
    kind:
        deployment:
            replicas: 1
    service:
      loadBalancerIP: <myip>
```
