### ISSUE TITLE
Rate limit translation does not enforce all required fields. 

### ISSUE THREAD

**Issue by elcasteel** [solo-io/gloo#8573]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.15.0-rc2

### Kubernetes Version

v1.24

### Describe the bug

Gloo will accept this config without a `descriptorValue` in the `genericKey`
```
apiVersion: ratelimit.solo.io/v1alpha1
kind: RateLimitConfig
metadata:
  name: rlc
  namespace: gloo-system
spec:
  raw:
    descriptors:
    - key: generic_key
      value: counter
      rateLimit:
        requestsPerUnit: 2
        unit: MINUTE
    rateLimits:
    - actions:
      - genericKey:
    ```
Envoy will fail with this configuration and output logs like:
```
[2023-08-09 21:37:41.236][14][debug][misc] [external/envoy/source/common/protobuf/utility.cc:213] Proto validation error; throwing Proto constraint validation failed (RouteConfigurationValidationError.VirtualHosts[0]: embedded message failed validation | caused by VirtualHostValidationError.RateLimits[0]: embedded message failed validation | caused by RateLimitValidationError.Actions[1]: embedded message failed validation | caused by field: "action_specifier", reason: is required): name: "listener-::-8080-routes"
virtual_hosts {
  name: "gloo-system_default"
  domains: "*"
  routes {
    match {
      prefix: "/"
    }
    route {
      cluster: "default-petclinic-80_gloo-system"
    }
    name: "gloo-system_default-route-0-matcher-0"
  }
  rate_limits {
    stage {
      value: 2
    }
    actions {
      generic_key {
        descriptor_value: "gloo-system.rlc"
      }
    }
    actions {
    }
  }
  typed_per_filter_config {
    key: "envoy.filters.http.ext_authz"
    value {
      [type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute] {
        disabled: true
      }
    }
  }
}
```

### Expected Behavior

Gloo should reject config before sending it to Envoy. We can use this document to find all the fields that are required in ratelimit actions https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-ratelimit-action-request-headers

### Steps to reproduce the bug

Apply the above RLC, add it to a VS. Resources will be accepted by gloo and envoy will be in an error state. 

### Additional Context

Found while reproducing: https://github.com/solo-io/gloo/issues/8042
The work was big enough to create a new issue as the original issue is already fixed.
