### ISSUE TITLE
Ability to append a value to a set of headers

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#8634]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.14.x

### Kubernetes Version

1.25

### Describe the bug

According to the [docs](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/append_remove_headers/), if I set append: true in a HeaderManipulation:
```
if the header HEADER_NAME is already present, append the value
```

### Expected Behavior

What I understand with this, is that if I have the following headerManipulation in place:
```
      options:
        headerManipulation:
          responseHeadersToAdd:
          - header:
              key: x-version
              value: fake version
            append: true
```

And I receive a request with the responseHeader x-version: 5, the expected outcome would be that the value get happened to the existing header:
```
x-version: 5 fake version
```

However, what is happening, is that a new header with the same name gets created:
```
x-version: 5
x-version: fake version
```

We have a client that wants to append a string to a set of "set-cookie" headers, so if I have two response headers set-cookie, and I want to append a string, for example "; Partitioned", I should be able to do that:
Response headers before HeaderManipulation:
```
set-cookie: TOKEN=eyJhbGciO...8; Version=1; Path=/blah/blah/; Secure; HttpOnly
set-cookie: AUTH_SESSION_ID=ec90fdc7-6f16-4ab1-bdfa-6a2478a1f25b; Version=1
```
Response headers after headerManipulation:
```
set-cookie: TOKEN=eyJhbGciO...8; Version=1; Path=/blah/blah/; Secure; HttpOnly; Partitioned
set-cookie: AUTH_SESSION_ID=ec90fdc7-6f16-4ab1-bdfa-6a2478a1f25b; Version=1; Partitioned
```
However, what I am getting is the following:
```
set-cookie: TOKEN=eyJhbGciO...8; Version=1; Path=/blah/blah/; Secure; HttpOnly
set-cookie: AUTH_SESSION_ID=ec90fdc7-6f16-4ab1-bdfa-6a2478a1f25b; Version=1; Path=/blah/blah/; SameSite=None; Secure; HttpOnly
set-cookie: ; Partitioned
```

### Steps to reproduce the bug

Create a VS with the following headerManipulation:
```
      options:
        headerManipulation:
          responseHeadersToAdd:
          - header:
              key: x-version
              value: fake version
            append: true
```

Check that a new response header is created instead of being appended

### Additional Context

It might be related to append field deprecated in envoy: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/base.proto#envoy-v3-api-field-config-core-v3-headervalueoption-append

Also related to https://github.com/solo-io/gloo/issues/8525

**Comment by inFocus7** [comment]
Haven't looked into this specific issue, but from my work on the append field deprecation issue, it looks like it won't address this.

From my local verification which uses Envoy's `append_action`, I see that with the following setup I still get multiple headers for the **responseHeaderToAdd**. For **requestHeaderToAdd** it looks like it acts as expected(?)

**RouteTable**
```yaml
[...]
      headerManipulation:
        requestHeadersToAdd:
        - append: true
          header:
            key: test-request-header
            value: b
        responseHeadersToAdd:
        - append: false
          header:
            key: X-Frame-Options
            value: RTORIGIN
[...]
```

**VirtualService**
```
[...]
      headerManipulation:
        requestHeadersToAdd:
        - append: true
          header:
            key: test-request-header
            value: a
        responseHeadersToAdd:
        - append: true
          header:
            key: X-Frame-Options
            value: VSORIGIN
[...]
```

Result:
```
[...]
< x-frame-options: RTORIGIN
< x-frame-options: VSORIGIN
< 
{
  [...]
  "headers": {
    [...]
    "Test-Request-Header": "b,a", 
    [...]
  }, 
  [...]
}
[...]
```

**Comment by edubonifs** [comment]
Hi @inFocus7 ,

Do you think we can implement this behavior with any other envoy field that we could expose with Gloo Edge?

As it seems we cannot have this working with the current exposed fields

**Comment by pandino** [comment]
Hi @inFocus7, @edubonifs pointed me to this ticket. We also have a similar problem, however our case is a little more complex than the reported one: on top of adding lines to the `set-cookie` header we also need some logic attached. For example we would like to add the `SameSite=Strict` attribute only if the `SameSite` is not already defined. This is a simplified version of what we are currently doing:

    [...]
              transformationTemplate:
                extractors:        
                  secure:
                    header: "set-cookie"
                    regex: '^(.*[Ss]ecure)(.*)$'
                  sameSite:
                    header: "set-cookie"
                    regex: '^(.*[Ss]ame[Ss]ite=)(.*)$'
                headersToAppend:        
                  - key: set-cookie
                    value:
                      text: "{% if header(\"set-cookie\") != \"\" %}{{ header(\"set-cookie\") }}{% if default(secure, \"\") == \"\" %}; Secure{% endif %}{% if default(sameSite, \"\") == \"\" %}; SameSite=Strict{% endif %}{% endif %}"
    [...]

Our main problem here is that this works only for one header, there is no looping among multiple `set-cookie` headers.

I think the append action is meant to be used to append a new header to an existing header with the same name, folding the two together. In your test above, the request headers has been properly folded by combining the two header values in the same header name with a comma. So this may be not intended to add arbitrary strings to an header.

I do believe that arbitrary headers manipulation can be done in Envoy with a Lua script, but I can't see any way to pass a Lua filter in Gloo to the proxy. Probably this can be also done with a WASM filter, but again I don't understand if the filter can be applied to single routes (instead of adding it globally to the gateway proxy linked in the example) and the solution seems a little bit overcomplicated, aside not being ready for production....

**Comment by edubonifs** [comment]
Hi, another customer is now hitting this issue with jwt claimToHeader:
```
     jwtStaged:
        beforeExtAuth:
          providers:
            idp:
              keepToken: true
              claimsToHeaders:
                - claim: claim1
                  header: options
                - claim: claim2
                  header: options
                  append: true  
                - claim: claim3
                  header: options
                  append: true
```

Where the application is receiving the headers, not appended, but several headers with the same name and different values:
```
"options": "apple, banana"
"options": "orange"
"options": "kumquat"
```

**Comment by edubonifs** [comment]
It would be good if we could control both behaviors:
- if we want all the values to be on the same header
- if we want to have different headers named the same with different values
So users can choose between them

**Comment by anessi** [comment]
This is still an issue for us, so please keep it open, thanks.

**Comment by anessi** [comment]
Adding more details to the comment https://github.com/solo-io/gloo/issues/8634#issuecomment-1727674731 above

According to the HTTP spec https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie it is possible to set multiple **Set-Cookie headers** in a single response:
> To send multiple cookies, multiple Set-Cookie headers should be sent in the same response. 

We are receiving a list of **Set-Cookie headers** like shown in the example below **on a single response**:

```
'set-cookie', 'AL_CONTROL=REMOVE_HEADERS%3DPERSONID; Domain=*; Path=/; HttpOnly'
'set-cookie', 'AL_CONTROL=SET_CREDENTIALS=mobile:300; Domain=*; Path=/; HttpOnly'
'set-cookie', 'AL_CONTROL=SESSION=NEWID&SESSION_TIMEOUT=300; Domain=*; Path=/; HttpOnly'
'set-cookie', 'CLX_EB_LOGIN_INFO=customer=mycustomer:contractType=1; Expires=Thu, 12 Dec 2024 09:03:46 GMT; Domain=*; Path=/; HttpOnly'
'set-cookie', 'CONSENT_SESSION_TICKET=QkNfTk89NzgxLHBlcnN; Domain=*; Path=/; HttpOnly'
'set-cookie', 'ATTORNEY_SESSION_TICKET=QkNfTk89NzgxLHBlcn; Domain=*; Path=/; HttpOnly'
```

and want to add a transformation that modifies the headers as shown below (note the added **Secure** and **SameSite=Strict** values):

```
'set-cookie', 'AL_CONTROL=REMOVE_HEADERS%3DPERSONID; Domain=*; Path=/; HttpOnly'; Secure; SameSite=Strict
'set-cookie', 'AL_CONTROL=SET_CREDENTIALS=mobile:300; Domain=*; Path=/; HttpOnly'; Secure; SameSite=Strict
'set-cookie', 'AL_CONTROL=SESSION=NEWID&SESSION_TIMEOUT=300; Domain=*; Path=/; HttpOnly'; Secure; SameSite=Strict
'set-cookie', 'CLX_EB_LOGIN_INFO=customer=mycustomer:contractType=1; Expires=Thu, 12 Dec 2024 09:03:46 GMT; Domain=*; Path=/; HttpOnly'; Secure; SameSite=Strict
'set-cookie', 'CONSENT_SESSION_TICKET=QkNfTk89NzgxLHBlcnN; Domain=*; Path=/; HttpOnly'; Secure; SameSite=Strict
'set-cookie', 'ATTORNEY_SESSION_TICKET=QkNfTk89NzgxLHBlcn; Domain=*; Path=/; HttpOnly'; Secure; SameSite=Strict
```

For the currently used transformation and problems with this transformation see the linked comment above.
We have been in contact with Solo support and they mentioned that this is not possible to the the limitation described in this issue.

**Comment by anessi** [comment]
I got the following information from support: As this is currently not supported out of the box, one possible workaround is to do header manipulation using ext-proc https://docs.solo.io/gloo-edge/main/guides/traffic_management/extproc/header-manipulation/

However, this requires an additional POD so adding considerable complexity for such a 'simple' use-case.

**Comment by nfuden** [comment]
Another thing to do here is to use transformations like in https://docs.solo.io/gloo-edge/latest/guides/traffic_management/request_processing/transformations/update_request_uri/


something like 

      options:
        transformations:
          requestTransformation:
            transformationTemplate:
              headers:
                # set the x-version header to the template value below
                "x-version":
                  text: '{{ header(":x-version") }}, fake version'

**Comment by anessi** [comment]
@nfuden : unfortunately that does not work as expected when having **multiple** (e.g. set-cookie) headers which is allowed according to the HTTP specification.

1. If we use `transformationTemplate.headers` only one single (set-cookie) header is kept and the other headers with the same name (set-cookie) are removed
2. If we use `transformationTemplate.headersToAppend` only the first (set-cookie) header is modified and appended (duplicated), but the other are **not** processed

The requirement is to have a transformation that:
* Loops over **all** and modifies *all* headers with the given name (e.g. set-cookie)

Please see https://github.com/k8sgateway/k8sgateway/issues/8634#issuecomment-2472836373 for the full example including the headers.

Below the transformation templates I have used for testing the use-cases above:
1. `transformationTemplate.headers`
```
    options:
      stagedTransformations:
        inheritTransformation: true
        regular:
          responseTransforms:
          - responseTransformation:
              transformationTemplate:
                extractors:
                  httpOnly:
                    header: set-cookie
                    regex: ^(.*[Hh]ttp[Oo]nly)(.*)$
                  sameSite:
                    header: set-cookie
                    regex: ^(.*[Ss]ame[Ss]ite=)(.*)$
                  secure:
                    header: set-cookie
                    regex: ^(.*[Ss]ecure)(.*)$
                headers:
                  set-cookie:
                    text: '{% if header("set-cookie") != "" %}{{ header("set-cookie")
                      }}{% if default(sameSite, "") == "" %}; SameSite=Strict{% endif
                      %}{% if default(secure, "") == "" %}; Secure{% endif %}{% if
                      default(httpOnly, "") == "" %}; HttpOnly{% endif %}{% endif
                      %}'
                passthrough: {}
```

2. `transformationTemplate.headersToAppend`:
```
    options:
      stagedTransformations:
        inheritTransformation: true
        regular:
          responseTransforms:
          - responseTransformation:
              transformationTemplate:
                extractors:
                  httpOnly:
                    header: set-cookie
                    regex: ^(.*[Hh]ttp[Oo]nly)(.*)$
                  sameSite:
                    header: set-cookie
                    regex: ^(.*[Ss]ame[Ss]ite=)(.*)$
                  secure:
                    header: set-cookie
                    regex: ^(.*[Ss]ecure)(.*)$
                headersToAppend:
                - key: set-cookie
                  value:
                    text: '{% if header("set-cookie") != "" %}{{ header("set-cookie")
                      }}{% if default(sameSite, "") == "" %}; SameSite=Strict{% endif
                      %}{% if default(secure, "") == "" %}; Secure{% endif %}{% if
                      default(httpOnly, "") == "" %}; HttpOnly{% endif %}{% endif
                      %}'
                passthrough: {}
```
