### ISSUE TITLE
Subsets functionality is not working on Gloo Edge 1.14.x and 1.15.x

### ISSUE THREAD

**Issue by PanOS1** [solo-io/gloo#8679]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.14.12

### Kubernetes Version

v1.25.12

### Describe the bug

Subsets functionality as described[ here](https://docs.solo.io/gloo-edge/latest/guides/traffic_management/destination_types/subsets/)  is not working. curl requests return responses from all pods.

### Expected Behavior

Responses should originate only from the pods with the label defined in `subset.values`

### Steps to reproduce the bug

1. create 2 deployments with the following labels:

### deploy 1
```
labels:
  app: myApp
  process: web
  release: nonCanary
```

### deploy 2
```
labels:
  app: myApp
  process: web
  release: canary
```

The upstream defined will have something like:
```
  kube:
    selector:
      app: myApp
      process: web
    serviceName: myApp
    serviceNamespace: default
    servicePort: 80
    subsetSpec:
      selectors:
      - keys:
        - release
```

And the virtual service
```
    routes:
    - matchers:
      - prefix: /
      options:
        timeout: 60s
      routeAction:
        single:
          subset:
            values:
              release: nonCanary
          upstream:
            name: default-myApp-80
            namespace: default
```

When i curl myApp i get responses from both the `release: canary` and `release: nonCanary` pods

### Additional Context

NOTE: that my setup with subsets works OK on latest v1.13.x of gloo-edge , but the functionality breaks on 1.14.x and 1.15.x
