### ISSUE TITLE
Expose Envoy's most_specific_header_mutation_wins field

### ISSUE THREAD

**Issue by inFocus7** [solo-io/gloo#8690]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.16

### Is your feature request related to a problem? Please describe.

The order of header mutations being evaluated goes from most specific to least specific, meaning setting mutations (such as `header_responses_to_add`, and `append` options) on least specific fields take priority over the most specific fields.

> Headers are appended to requests/responses in the following order: weighted cluster level headers, route level headers, virtual host level headers and finally global level headers.
> - [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#custom-request-response-headers)

Relevant Issue: #8525 

In the case of
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    options:
      headerManipulation:
        responseHeadersToAdd:
        - header:
            key: X-Frame-Options
            value: SAMEORIGIN
    routes:
    - delegateAction:
        selector:
          labels:
            delegate: true
      matchers:
      - prefix: /
 --------
apiVersion: gateway.solo.io/v1
kind: RouteTable
metadata:
  labels:
    delegate: true
  name: child
  namespace: gloo-system
spec:
  routes:
  - matchers:
    - prefix: /get
    options:
      headerManipulation:
        responseHeadersToAdd:
        - append: false
          header:
            key: X-Frame-Options
            value: NEWORIGIN
    routeAction:
      single:
        upstream:
          name: default-httpbin-8000
          namespace: gloo-system
```

Since the VirtualHost's header manipulation gets evaluated **after** the Route's, the Route's `append` does not affect the VirtualHost.

### Describe the solution you'd like

We should expose Envoy's [most_specific_mutation_wins](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#config-route-v3-routeconfiguration) in RouteConfiguration. This would reverse the order of evaluation, meaning that a more specific header would be able to overwrite a less specific one.
