### ISSUE TITLE
AuthConfig using k8sSecretApikeyStorage gets rejected.  

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#8709]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.15.2

### Kubernetes Version

v1.27.2-gke.1200

### Describe the bug
> Edited to reflect that neither `labelSelector` nor `apiKeySecretRefs` work under `K8sSecretApiKeyStorage`

AuthConfig using k8sSecretApikeyStorage gets rejected.  

- Following our documentation here https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/apikey_auth/
works fine with `labelSelector`.  This field is described as "DEPRECATED: use K8sSecretApiKeyStorage" 
- When replacing with `k8sSecretAPIKeyStorage` the authConfig resource is rejected

```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"enterprise.gloo.solo.io/v1","kind":"AuthConfig","metadata":{"annotations":{},"name":"apikey-auth","namespace":"gloo-system"},"spec":{"configs":[{"apiKeyAuth":{"headerName":"api-key","k8sSecretApikeyStorage":{"labelSelector":{"team":"infrastructure"}}}}]}}
  creationTimestamp: "2023-09-29T15:32:10Z"
  generation: 2
  name: apikey-auth
  namespace: gloo-system
  resourceVersion: "50662339"
  uid: d1beed5d-e0bc-4519-b468-e21a4b012330
spec:
  configs:
  - apiKeyAuth:
      headerName: api-key
      k8sSecretApikeyStorage:
        labelSelector:
          team: infrastructure
status:
  statuses:
    gloo-system:
      reason: "1 error occurred:\n\t* Invalid configurations for apikey auth config
        apikey-auth.gloo-system\n\n"
      reportedBy: gloo
      state: Rejected
```

### Expected Behavior

API allows for specifying a secret by list of references or a label selector.  Both should work.  

Given a set of resources, it would be useful to see this rejected state immediately in status.
```
kubectl get authconfig -o wide
NAME             AGE
apikey-auth      95m
token-api-auth   10m
```

Once it's discovered that it's not working, it would be useful to understand where this is going wrong and how it can be fixed.  

### Steps to reproduce the bug
Following the [API Keys](https://docs.solo.io/gloo-edge/latest/guides/security/auth/extauth/apikey_auth/) tutorial placing the `labelSelector` under `k8sSecretApikeyStorage` 
```
glooctl create secret apikey infra-apikey \
    --apikey N2YwMDIxZTEtNGUzNS1jNzgzLTRkYjAtYjE2YzRkZGVmNjcy \
    --apikey-labels team=infrastructure

kubectl apply -f - << EOF
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: apikey-auth
  namespace: gloo-system
spec:
  configs:
  - apiKeyAuth:
      headerName: api-key
      k8sSecretApikeyStorage:
        labelSelector:
          team: infrastructure
EOF
```

### Additional Environment Detail

Simple Gloo Edge install with GLOO_EDGE_VERSION=1.15.2
```
install_gloo_edge () {
	glooVersion=${GLOO_EDGE_VERSION:-1.13.12} 
	glooValues=${1:-https://raw.githubusercontent.com/solo-io/gloo-edge-use-cases/main/production-helm-values/values.yaml} 
	helm upgrade --install glooe glooe/gloo-ee --namespace gloo-system --create-namespace -f ~/Work/gloo-edge-use-cases/production-helm-values/istioIntegration.yaml --version $glooVersion --set-string license_key=$GLOO_EDGE_LICENSE_KEY --set "gloo.discovery.enabled=true" --set "observability.enabled=false" --set "grafana.defaultInstallationEnabled=false" --set "prometheus.enabled=false" --set "gloo-fed.enabled=false" --set "gloo.settings.disableKubernetesDestinations=true" --set "gloo.gateway.validation.enabled=true" --set "gloo.gateway.validation.alwaysAcceptResources=false" --set "gloo.gateway.validation.warnRouteShortCircuiting=true" --set "gloo.gateway.validation.failurePolicy='Fail'" --set "gloo.gateway.validation.allowWarnings=true"
}
```
