### ISSUE TITLE
failover.policy.overprovisioningFactor is ignored

### ISSUE THREAD

**Issue by bdecoste** [solo-io/gloo#8720]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.13.24

### Kubernetes Version

1.23

### Describe the bug

Upstream `failover.policy.overprovisioningFactor` is ignored

### Expected Behavior

Upstream `failover.policy.overprovisioningFactor` should result in Envoy config with `cluster.load_assignment.policy.overprovisioning_factor`

### Steps to reproduce the bug

Upstream:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: failover
  namespace: gloo-system
spec:
  failover:
    policy:
      overprovisioningFactor: 600
    prioritizedLocalities:
    - localityEndpoints:
      - lbEndpoints:
        - address: echo-service.default.svc.cluster.local
          healthCheckConfig:
            path: /status/200
          port: 8080
  healthChecks:
  - healthyThreshold: 1
    httpHealthCheck:
      expectedStatuses:
      - end: 201
        start: 200
      path: /status/200
    interval: 10s
    timeout: 5s
    unhealthyThreshold: 1
  loadBalancerConfig:
    healthyPanicThreshold: 50
  static:
    hosts:
    - addr: httpbin.default.svc.cluster.local
      healthCheckConfig:
        path: /status/500
      port: 8000

```
Route in VirtualService:

```
    - matchers:
      - prefix: /failover/
      options:
        prefixRewrite: /
      routeAction:
        single:
          upstream:
            name: failover
            namespace: gloo-system
```

Resulting Envoy Cluster config:

```
    {
     "version_info": "8162297227039708371",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "failover_gloo-system",
      "type": "STRICT_DNS",
      "connect_timeout": "5s",
      "health_checks": [
       {
        "timeout": "5s",
        "interval": "10s",
        "unhealthy_threshold": 1,
        "healthy_threshold": 1,
        "custom_health_check": {
         "name": "io.solo.health_checkers.advanced_http",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.config.health_checker.advanced_http.v2.AdvancedHttp",
          "http_health_check": {
           "path": "/status/500",
           "expected_statuses": [
            {
             "start": "200",
             "end": "201"
            }
           ]
          }
         }
        }
       }
      ],
      "dns_lookup_family": "V4_ONLY",
      "metadata": {},
      "common_lb_config": {
       "healthy_panic_threshold": {
        "value": 50
       }
      },
      "load_assignment": {
       "cluster_name": "failover_gloo-system",
       "endpoints": [
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "httpbin.default.svc.cluster.local",
              "port_value": 8000
             }
            },
            "health_check_config": {
             "hostname": "httpbin.default.svc.cluster.local"
            },
            "hostname": "httpbin.default.svc.cluster.local"
           },
           "metadata": {
            "filter_metadata": {
             "envoy.transport_socket_match": {
              "httpbin.default.svc.cluster.local;httpbin.default.svc.cluster.local:8000": true
             },
             "io.solo.health_checkers.advanced_http": {
              "path": "/status/500"
             }
            }
           }
          }
         ]
        },
        {
         "lb_endpoints": [
          {
           "endpoint": {
            "address": {
             "socket_address": {
              "address": "echo-service.default.svc.cluster.local",
              "port_value": 8080
             }
            },
            "health_check_config": {},
            "hostname": "echo-service.default.svc.cluster.local"
           },
           "metadata": {
            "filter_metadata": {
             "io.solo.health_checkers.advanced_http": {
              "path": "/status/200"
             }
            }
           }
          }
         ],
         "priority": 1
        }
       ]
      }
     },
     "last_updated": "2023-09-27T13:17:26.234Z"
    },
```
