### ISSUE TITLE
ValidationError: unknown field "networkLocalRatelimit" in io.solo.gateway.v1.Gateway.spec.httpGateway.options

### ISSUE THREAD

**Issue by evsasha** [solo-io/gloo#8899]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.15.16

### Kubernetes Version

v1.27.3

### Describe the bug

When trying to follow the official [documentation](https://docs.solo.io/gloo-edge/latest/guides/security/local_rate_limiting/http/) for creating local rate limits, I encounter an error at [Apply local rate limit settings to Layer 4 traffic](https://docs.solo.io/gloo-edge/latest/guides/security/local_rate_limiting/http/#layer4):

```shell
error: error validating "STDIN": error validating data: ValidationError(Gateway.spec.httpGateway.options): unknown field "networkLocalRatelimit" in io.solo.gateway.v1.Gateway.spec.httpGateway.options; if you choose to ignore these errors, turn validation off with --validate=false
```

### Expected Behavior

Validation has been successful. Local rate limits have been added to the configuration.

### Steps to reproduce the bug

Follow the example from the [documentation](https://docs.solo.io/gloo-edge/latest/guides/security/local_rate_limiting/http/) :

1. Deploy the httpbin sample app
2. Apply local rate limit settings to Layer 4 traffic

**Comment by davidjumani** [comment]
Hi @evsasha I just tested the steps and they work as expected. I suspect that there might be older versions of CRDs installed. How did you install / upgrade gloo edge ?

**Comment by evsasha** [comment]
Hello. I upgraded my previous installation from version 1.15.2 using the helm update command.

I haven't tested a clean installation, as version 1.15.2 is currently deployed in a production environment. The standard installation pipeline in a testing environment involves an update.

**Comment by davidjumani** [comment]
Could you get the gateway CRD and check if it has the networkLocalRatelimit field ?
```
kubectl get crd gateways.gateway.solo.io -o yaml
```
You should see something like this in the result
```
                      networkLocalRatelimit:
                        properties:
                          fillInterval:
                            type: string
                          maxTokens:
                            format: int32
                            type: integer
                          tokensPerFill:
                            maximum: 4294967295
                            minimum: 0
                            nullable: true
                            type: integer
```
