### ISSUE TITLE
Tutorial #2 doesn't fail as expected

### ISSUE THREAD

**Issue by drnic** [solo-io/gloo#89]
In https://github.com/solo-io/gloo/blob/master/docs/getting_started/kubernetes/2.md#steps the instructions state:

```
 curl ${GATEWAY_URL}/petstore/findPet

 bad request: Did not found json element: id
```

But it no longer errors like this.

I believe the function definitions have changed. The tutorial expects them to be:

```
glooctl upstream get default-petstore-8080 -o yaml
```

```yaml
functions:
     ...
     - name: findPetById
       spec:
         body: ""
         headers:
           :method: GET
         path: /api/pets/{{id}}
```

But instead they are now:

```yaml
functions:
...
- name: findPetById
  spec:
    body: ""
    headers:
      :method: GET
    passthrough_body: false
    path: /api/pets/{{ default(id, "") }}
```
