### ISSUE TITLE
Check the subject DN of client certificates

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#8924]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

Hi Sam,
We have a requirement from one of our customers:
They try to find the optimal solution about checking the subject DN of client certificates:
Validate client certificates that are presented to them in the context of mTLS
Only allow those client certs to pass through where the subject DN matches a list of predefined values
Scenario largly resmebles the on being described in https://www.solo.io/blog/tutorial-advanced-mtls-with-gloo-edge/
The following questions arise:
The above article suggests that in order to achieve the goal one has to develop custom code and deploy it to GlooEdge. In this blog, we show them how to do it with custom plugin using ExtAuth.
According to them, out mtls is not complete because we are missing checking the CN of the presented mTls certificates.
Do you think it would be possible doing this using Passthrough Auth? Is it worth for a Feature Request?
Thanks

**Comment by sam-heilbron** [comment]
In our API, we defined [verify_subject_alt_name](https://github.com/solo-io/gloo/blob/3f40e5bf1481121dc5400211cbfdedc8e1a24616/projects/gloo/api/v1/ssl/ssl.proto#L31), which, per the API:
```
verifies that the Subject Alternative Name in the peer certificate is one of the specified values.
```

This would be defined on a VirtualService definition, like:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: default
  namespace: gloo-system
spec:
  sslConfig:
    secretRef:
      name: tls
      namespace: gloo-system
    verifySubjectAltName:
    - httpbin.solo.io
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - exact: /route
      routeAction:
        single:
          upstream:
            name: default-httpbin-8080
            namespace: gloo-system
```

@edubonifs could you confirm that this is the field you're looking for?

If not, could you help me understand how this field does not solve the problem you are hitting, and the steps I could take to reproduce it myself?

If so, do you think there are any improvements we can make to our public API or user-facing docs to make this field more discoverable?
