### ISSUE TITLE
Path matcher produces invalid Envoy Config

### ISSUE THREAD

**Issue by SantoDE** [solo-io/gloo#8950]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v2.0.0-beta1

### Kubernetes Version

v1.27.3 (kind)

### Describe the bug

Once I have an `HTTPRoute` that looks like that:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: whoami
  namespace: whoami
  labels:
    example: whoami-route
spec:
  parentRefs:
    - name: http
      namespace: gloo-system
  hostnames:
    - "www.example.com"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /foobar
    - backendRefs:
        - name: whoami-service
          namespace: whoami
          port: 80
``` 

There is an envoy config where the `/foobar` results in a 500 direct response, while `/` serves the app just fine. 
```
  "dynamic_route_configs": [
    {
     "version_info": "4624349018333159854",
     "route_config": {
      "@type": "type.googleapis.com/envoy.config.route.v3.RouteConfiguration",
      "name": "http-routes-17976600636774254599",
      "virtual_hosts": [
       {
        "name": "http~www_example_com",
        "domains": [
         "www.example.com"
        ],
        "routes": [
         {
          "match": {
           "path_separated_prefix": "/foobar"
          },
          "direct_response": {
           "status": 500,
           "body": {
            "inline_string": ""
           }
          },
          "name": "http~www_example_com-route-0-matcher-0"
         },
         {
          "match": {
           "prefix": "/"
          },
          "route": {
           "cluster": "whoami-whoami-service-80_whoami",
           "cluster_not_found_response_code": "INTERNAL_SERVER_ERROR"
          },
          "name": "http~www_example_com-route-1-matcher-0"
         }
        ]
       }
      ],
      "ignore_port_in_host_matching": true
     },
     "last_updated": "2023-12-04T16:11:01.263Z"
    }
```

### Expected Behavior

I should be able to access the app on `www.example.com/foobar` 

### Steps to reproduce the bug

1. Create kind Cluster
2. Install GG v2 `glooctl install -g`
3. Create whoami
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  namespace: whoami
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: whoami    
```
4. Create HTTPRoute from above
5. curl -v www.example.com:8080/foobar
