### ISSUE TITLE
support rate-limit with built in Redis when using multiple dataplanes

### ISSUE THREAD

**Issue by totallyGreg** [solo-io/gloo#8967]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

v1.14.8

### Kubernetes Version

unknown

### Describe the bug

When using the feature `dataPlanePerProxy`, rate-limit pods cannot talk to the respected redis instances since the redis config map generated is set for a single control and data plane solution and it is referencing the wrong redis service

### Expected Behavior

rate-limit should be configured to use an existing redis instance for their respective data plane. 

### Steps to reproduce the bug

Gloo EE version: 1.14.8

Our Structure:
• 1 gloo instance (control plane)
• 2 gateway-proxies, extauth, ratelimit, and redis instances (data plane)
The name of the redis and rate-limit instances:
• rate-limit-internal-proxy should talk to redis-internal-proxy
• and rate-limit-gateway-proxy should talk to redis-gateway-proxy
It looks like the issue is the rate-limit-sidecar-config which is being used by both rate-limit instances, which referenced this service:
```
          endpoints:
          - lbendpoints:
            - endpoint:
                address:
                  socketaddress:
                    address: redis   <---- this does not exists
                    port_value: 6379
```
