### ISSUE TITLE
Gloo fails after upgrade from 1.14.27 to 1.15.x

### ISSUE THREAD

**Issue by ndtmdsma** [solo-io/gloo#8968]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.15.x

### Kubernetes Version

v1.24

### Describe the bug

Upgrading from Gloo 1.14.x to 1.15.x causes Gloo to fail entirely. Everything starts, glooctl check says everything is OK, but Gloo doesn't route anything. I get warning as below for **all** upstreams:

```
[warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:128] gRPC config for type.googleapis.com/envoy.config.cluster.v3.Cluster rejected: Error adding/updating cluster(s) app1_gloo-system: Didn't find a registered config subscription factory implementation for name: 'envoy.config_subscription.rest', kube-svc:app2-0-80_ns2: Didn't find a registered config subscription factory implementation for name: 'envoy.config_subscription.rest', consul-svc:app3_gloo-system: Didn't find a registered config subscription factory implementation for name: 'envoy.config_subscription.rest'
```

It's a very long list.

### Expected Behavior

Gloo working after upgrade

### Steps to reproduce the bug

Upgrade Gloo from 1.14.27 to 1.15.x (I tried all patch versions). 

### Additional Environment Detail

Using consul upstreams discovery (but gloo fails for both consul and kube upstreams). 

Running in EKS.

Helm values: 
```  
    crds:
      create: true
    discovery:
      deployment:
        floatingUserId: false
        fsGroup: 10101
        image:
          extended: false
          repository: discovery
          tag: 1.15.17
        replicas: 1
        runAsUser: 10101
        stats:
          enabled: true
          serviceMonitorEnabled: true
          podMonitorEnabled: true
      enabled: true
      fdsMode: WHITELIST
      serviceAccount:
        disableAutomount: false
      logLevel: "info"
      udsOptions:
        enabled: true
    gateway:
      enabled: true
      certGenJob:
        enabled: true
        image:
          repository: certgen
        restartPolicy: OnFailure
        setTtlAfterFinished: true
        ttlSecondsAfterFinished: 60
        runAsUser: 10101
        cron:
          enabled: false
          schedule: "* * * * *"
        runOnUpdate: false
      rolloutJob:
        enabled: true
        image:
          repository: kubectl
        restartPolicy: OnFailure
        runAsUser: 10101
        ttlSecondsAfterFinished: 60
      cleanupJob:
        enabled: true
        image:
          repository: kubectl
        restartPolicy: OnFailure
        runAsUser: 10101
        ttlSecondsAfterFinished: 60
      proxyServiceAccount:
        disableAutomount: false
      readGatewaysFromAllNamespaces: false
      isolateVirtualHostsBySslConfig: false
      serviceAccount:
        disableAutomount: false
      updateValues: false
      validation:
        enabled: true
        failurePolicy: "Ignore"
        secretName: gateway-validation-certs
        alwaysAcceptResources: true
        allowWarnings: true
        serverEnabled: true
        disableTransformationValidation: false
        warnRouteShortCircuiting: false
        validationServerGrpcMaxSizeBytes: 104857600
        webhook:
          enabled: true
          disableHelmHook: false
          extraAnnotations: {}
      persistProxySpec: true
    gatewayProxies:
      gatewayProxy:
        antiAffinity: false
        configMap:
          data: null
        envoyApiVersion: V3
        envoyBootstrapExtensions: null
        envoyStaticClusters: null
        failover:
          enabled: false
        gatewaySettings:
          disableGeneratedGateways: false
          options: {}
          useProxyProto: false
        globalDownstreamMaxConnections: 250000
        healthyPanicThreshold: 50
        kind:
          deployment:
            replicas: 1
        loopBackAddress: 127.0.0.1
        podTemplate:
          customReadinessProbe: {}
          disableNetBind: true
          floatingUserId: false
          fsGroup: 10101
          gracefulShutdown:
            enabled: false
            sleepTimeSeconds: 25
          httpPort: 8080
          httpsPort: 8443
          image:
            extended: false
            repository: gloo-envoy-wrapper
            tag: 1.15.17
          probes: false
          runAsUser: 10101
          runUnprivileged: true
          terminationGracePeriodSeconds: 0
          tolerations: null
        readConfig: false
        readConfigMulticluster: false
        service:
          httpPort: 80
          httpsFirst: false
          httpsPort: 443
          type: LoadBalancer
    global:
      glooRbac:
        create: true
        nameSuffix: ""
        namespaced: false
      glooStats:
        enabled: true
        routePrefixRewrite: /stats/prometheus
      image:
        extended: false
        pullPolicy: IfNotPresent
        registry: quay.io/solo-io
      istioSDS: {}
    gloo:
      deployment:
        disableUsageStatistics: false
        floatingUserId: false
        image:
          extended: false
          repository: gloo
          tag: 1.15.17
        replicas: 1
        restXdsPort: 9976
        runAsUser: 10101
        validationPort: 9988
        xdsPort: 9977
      serviceAccount:
        disableAutomount: false
    k8s:
      clusterName: cluster.local
    namespace:
      create: false
    settings:
      aws:
        enableCredentialsDiscovery: false
        enableServiceAccountCredentials: false
        stsCredentialsRegion: ""
      create: true
      disableKubernetesDestinations: false
      disableProxyGarbageCollection: false
      enableRestEds: true
      integrations:
        consul:
          insecureSkipVerify: true
          httpAddress: https://consul-server.consul.svc.cluster.local:8501
          serviceDiscovery: {}
        consulUpstreamDiscovery: null
        knative:
          enabled: false
      invalidConfigPolicy:
        invalidRouteResponseBody: Gateway has invalid configuration.
        invalidRouteResponseCode: 404
      regexMaxProgramSize: 150
      linkerd: false
      singleNamespace: false
```
