### ISSUE TITLE
gatewayProxies deployment's `.kind.deployment.priorityClassName` is not implemented

### ISSUE THREAD

**Issue by zelig81** [solo-io/gloo#9010]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.14.21

### Kubernetes Version

v1.26.8

### Describe the bug

when I set priorityClassName in values of helm chart for gatewayProxy (in `gatewayProxies.NAME.kind.deployment.priorityClassName`) it is not set on the resulting `NAME` deployment. The proxies are created though.

example of values:
```yaml
...
gatewayProxies:
  gatewayProxy:
    kind:
      deployment:
        priorityClassName: cluster-critical-priority-preempting
...
  internalProxy:
    kind:
      deployment:
        priorityClassName: cluster-critical-priority-preempting
...
```

### Expected Behavior

resulting deployments for `gateway-proxy` and `internal-proxy` should contain priorityClassName

### Steps to reproduce the bug

helm install ...

### Additional Context

after having a look on gateway proxy template, I see that `.kind.deployment` is in use only for configuration of replicas, customEnv and affinity specifically. Could you please add the absent values per documentation for gatewayProxies.NAME.kind.deployment.XXXXXX to be set in the resulting deployments? 

(most important for me are `nodeSelector` and `priorityClassName`)

As possible solution - `kubeResourceOverride` can be used (to be merged with deployment spec), but after multiple tries I did not find any working formula with this key :sad

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208134060199527) by [Unito](https://www.unito.io)
