### ISSUE TITLE
Having the possibility of storing redis secret externally

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#9097]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Is your feature request related to a problem? Please describe.

Hi, 

One of our customers need to externalize secrets outside of k8s to meet our security & compliance posture. Some possible options are:

- Use AWS ElasticCache with IAM (most preferred, no credentials)
- Retrieve a secret from Hashicorp Vault
- Retrieve a secret from AWS Secrets Manager

**Comment by nfuden** [comment]
@edubonifs is this not possible with the vault secret backend?

**Comment by edubonifs** [comment]
Hi @nfuden , as fr as I understood in this doc: https://docs.solo.io/gloo-edge/latest/installation/advanced_configuration/vault_secrets/
This is for Gloo Edge settings, and for secrets being referenced on RouteTables with this format:
```
glooctl create secret tls \
    --certchain /path/to/cert.pem \
    --privatekey /path/to/key.pem
    --name tls-secret \
    --use-vault \
    --vault-address http://vault:8200/ \
    --vault-token "$VAULT_TOKEN"
```

But now I am checking this other doc: https://docs.solo.io/gloo-edge/latest/guides/integrations/vault/aws-irsa-auth/ which suggests the following:
```
gloo:
  serviceAccount:
    extraAnnotations: 
      eks.amazonaws.com/role-arn: ${VAULT_AUTH_ROLE_ARN}
discovery:
  serviceAccount:
    extraAnnotations:
      eks.amazonaws.com/role-arn: ${VAULT_AUTH_ROLE_ARN}
```

So maybe adding an annotation to redis deployment could work

**Comment by edubonifs** [comment]
Hi @nfuden , I just deployed Gloo Edge and Vault following this doc: https://docs.solo.io/gloo-edge/latest/guides/integrations/vault/aws-irsa-auth/

It seems that the only two pods that tries to connect to vault are the ones specified on the docs, gloo and discovery.
Extauth and ratelimit pods, which are the ones that mount this redis secret, don't even try to connect to vault with this setup.

Also, this secret is specified on the deployment:
```
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
```

From my tests, it seems that gloo is only looking in vault the secret that we make reference in the RouteTable using sslConfig.

I connected discovery pod to vault, tried to get that redis secret which I previously created in vault, but the pod was crashing
