### ISSUE TITLE
glooctl version 

### ISSUE THREAD

**Issue by nmnellis** [solo-io/gloo#9224]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.1, client 1.15.19

### Kubernetes Version

1.27

### Describe the bug

I installed gloo but glooctl version does not reflect the version i installed 1.16.1. 

```sh
# gloo
image: quay.io/solo-io/gloo-ee:1.16.1@sha256:4c294535cd5ca05169887c20ff7b6102db675877643aef2beaaacf187970d017
# rate limit
image: quay.io/solo-io/rate-limit-ee:1.16.1@sha256:0924ce50d921a9b0458fb6db92b3c7cf385755b6618bc2cb33e79aa07298b042
#extauth
image: quay.io/solo-io/extauth-ee:1.16.2-bredirect-in-oauth-d16079d@sha256:223445e3798878acb00611c81c250d5e4b4d8c2fb70944e3959a393c177f93d7
```

```sh
▶ glooctl version -o table
----------
glooctl binary version (1.15.19) differs from server components (v1.16.3) by at least a minor version.
Consider running:
glooctl upgrade --release=v1.16.3
----------

Client: version: 1.15.19
Server:
+-------------+--------------------+-----------------------+
|  NAMESPACE  |  DEPLOYMENT-TYPE   |      CONTAINERS       |
+-------------+--------------------+-----------------------+
| gloo-system | Gateway Enterprise | redis: 7.0.11         |
|             |                    | discovery-ee: latest  |
|             |                    | gloo-ee: latest       |
|             |                    | extauth-ee: latest    |
|             |                    | rate-limit-ee: latest |
+-------------+--------------------+-----------------------+
```

### Expected Behavior

the correct image versions would be displayed

### Steps to reproduce the bug

Install Argocd
```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

kubectl wait deployment argocd-server --for condition=Available=True -n argocd

argoPass=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
echo $argoPass
```

* Install gloo

```
kubectl apply -f -<<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fis-gloo-edge-enterprise-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://storage.googleapis.com/gloo-ee-helm'
    targetRevision: 1.16.1
    helm:
      values: >
        global:
          glooStats:
            routePrefixRewrite: /stats
          istioIntegration:
            enableIstioSidecarOnGateway: true
            istioSidecarRevTag: 1-17
            disableAutoinjection: false
          extensions:
            extAuth:
              deployment:
                image:
                  pullPolicy: IfNotPresent
                  repository: extauth-ee
                  tag: 1.16.2-bredirect-in-oauth-d16079d
        create_license_secret: true
        gloo:
          gateway:
            readGatewaysFromAllNamespaces: true
          license_secret_name: license
          extauth:
            extauthzServerRef:
              name: extauth
              namespace: gloo-system
          gatewayProxies:
            aPublicGw: # Proxy name for public access (Internet facing)
              namespace: public-dis-gw
              disabled: false # overwrite the "default" value in the merge step
              kind:
                deployment:
                  replicas: 1
              service:
                httpPort: 80
                httpsFirst: false
                httpsPort: 443
                type: NodePort
                httpNodePort: 30379
                httpsNodePort: 30378
              gatewaySettings:
                accessLoggingService:
                  accessLog:
                  - fileSink:
                      path: /dev/stdout
                      stringFormat: ""
                customHttpGateway: # using the default HTTP Gateway
                  virtualServiceSelector:
                    gateway-type: public # label set on the VirtualService
                customHttpsGateway: # using the default HTTPS Gateway
                  virtualServiceSelector:
                    gateway-type: public # label set on the VirtualService
                disableHttpGateway: false # disable the default HTTP Gateway
                disableHttpsGateway: false # disable the default HTTPS Gateway
            aPrivateGw: # Proxy name for private access (intranet facing)
              namespace: private-dis-gw
              disabled: false # overwrite the "default" value in the merge step
              podTemplate:
                httpPort: 8080
                httpsPort: 8443
              kind:
                deployment:
                  replicas: 1
              service:
                httpPort: 80
                httpsFirst: false
                httpsPort: 443
                type: LoadBalancer
                httpNodePort: 31400
                httpsNodePort: 31145
              gatewaySettings:
                accessLoggingService:
                  accessLog:
                  - fileSink:
                      path: /dev/stdout
                      stringFormat: ""
                customHttpGateway: # using the default HTTP Gateway
                  virtualServiceSelector:
                    gateway-type: private # label set on the VirtualService
                customHttpsGateway: # using the default HTTPS Gateway
                  virtualServiceSelector:
                    gateway-type: private # label set on the VirtualService
                disableHttpGateway: false # disable the default HTTP Gateway
                disableHttpsGateway: false # disable the default HTTPS Gateway
            gatewayProxy:
              disabled: true # disable the default gateway-proxy deployment and its 2 default Gateway CRs
        prometheus:
          enabled: true
          server:
            retention: 3d
        gloo-fed:
          enabled: false
          create_license_secret: false
          glooFedApiserver:
            enable: false
        observability:
          enabled: false
    chart: gloo-ee
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
EOF
```
