### ISSUE TITLE
proxy_latency_response_out is always equal to DURATION time of the request

### ISSUE THREAD

**Issue by edubonifs** [solo-io/gloo#9317]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.15.x

### Kubernetes Version

1.26

### Describe the bug

Testing with proxyLatency response_out, I observed that 
```
proxy_latency_response_out: '%DYNAMIC_METADATA(io.solo.filters.http.proxy_latency:response_out)%'
```
Is always equal to:
```
DURATION: '%DURATION%'
```

### Expected Behavior

For me, latency for response_out should only measure the latency on response time, not having the same value as duration of the total request.

### Steps to reproduce the bug

Gateway object:
```
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  annotations:
  labels:
    app: gloo
  name: gateway-proxy
  namespace: gloo-system
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      proxyLatency:
        measureRequestInternally: true
        request: LAST_INCOMING_LAST_OUTGOING
        response: LAST_INCOMING_LAST_OUTGOING
  options:
    accessLoggingService:
      accessLog:
      - fileSink:
          jsonFormat:
            DURATION: '%DURATION%'
            proxy_latency_response_out: '%DYNAMIC_METADATA(io.solo.filters.http.proxy_latency:response_out)%'
          path: /dev/stdout
  proxyNames:
  - gateway-proxy
  ssl: false
  useProxyProto: false
```

Inject some fault injection on request:
```
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: vs
  namespace: gloo-system
spec:
  virtualHost:
    domains:
    - '*'
    routes:
    - matchers:
      - prefix: /
      options:
        faults:
          delay:
            fixedDelay: 2s
            percentage: 100
      routeAction:
        single:
          upstream:
            name: httpbin-httpbin-8000
            namespace: gloo-system
```

As you see, I have a delay of 2s on the request, however, if I check my logs:
```
{"DURATION":2006,"proxy_latency_response_out":2006}
```

proxy_latency_response_out is always taking the total response time

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1206768562311555/1207064976581486) by [Unito](https://www.unito.io)
