### ISSUE TITLE
glooe/gloo-ee 1.16.4 InvalidImageName for gloo-fed-apiserver

### ISSUE THREAD

**Issue by ably77** [solo-io/gloo#9320]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.4

### Kubernetes Version

v1.28.5

### Describe the bug

when deploying gloo ee 1.16.4 with the legacy ui:
```
gloo-fed:
  glooFedApiserver:
    enable: true
```

the result is an InvalidImageName for the gloo-fed-console pod
```
% k get pods -n gloo-system
gloo-fed-console-7b5467977c-dw6zm                        2/3     InvalidImageName    0          2m22s
```

Looking further, it seems like in 1.16.4 we are not templating the SHA of the gloo-fed-apiserver correctly which is resulting in this error
```
% k get pods -n gloo-system gloo-fed-console-7b5467977c-sn4nf -oyaml | grep image:
    image: quay.io/solo-io/gloo-fed-apiserver:1.16.4@
```

Workaround:
I was able to override this in helm with the following values which pins the right version, tag and SHA
```
glooFedApiserver:
  enable: true
  image:
    digest: sha256:e829026a1ec736b8c979551a17a9ce8fd5b348423a254b5e579dd8214a253679
    tag: 1.16.4
    registry: quay.io/solo-io
    repository: gloo-fed-apiserver
```

### Expected Behavior

the helm chart should properly render these values by default

### Steps to reproduce the bug

```
helm upgrade --install gloo glooe/gloo-ee \
-n gloo-system \
--version=1.16.4 \
-f -<<EOF
license_key: ""
gloo-fed:
  enabled: false
  glooFedApiserver:
    enable: true
EOF
```
