### ISSUE TITLE
Allow customizing the command in the lifecycle preStop hook via helm chart 

### ISSUE THREAD

**Issue by sadieleob** [solo-io/gloo#9344]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.3

### Is your feature request related to a problem? Please describe.

To enable the lifecycle hook in GE helm-chart we have gracefulShudown , enabling it in the helmCharts configures the following in the gateway-proxy deployment:
```
lifecycle:                                                                                                                                                                                                                        
    preStop:                                                                                                                                                                                                                         
        exec:                                                                                                                                                                                                                         
            command:                                                                                                                                                                                                                    
            - /bin/sh                                                                                                                                                                                                                   
            - -c                                                                                                                                                                                                                         
            - wget --post-data "" -O /dev/null 127.0.0.1:19000/healthcheck/fail; sleep                                                                                                                                                  
               15
 ```
 The ask is to be able to customize the command via helm values. 
 

### Describe the solution you'd like

Allowing the customization of the command in the lifecycle preStop hook

### Describe alternatives you've considered

The alternative is to use Kustomize or edit the deployment directly

### Additional Context

_No response_
