### ISSUE TITLE
GE UI unable to retrieve Envoy configuration when gateway-proxies not in default `gloo-system` namespace

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#9378]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.6

### Kubernetes Version

1.27.8

### Describe the bug

When you deploy your gateway proxies in any other namespace than `gloo-system`, the GE UI will be not be able to recognize and display the Envoy configuration.

Using the following configuration, in which we only deploy the default gateway in `gloo-system` and the other 2 gateway-proxies in `gloo-external` and `gloo-internal`, the UI will only be able to display the Envoy config of the GW in `gloo-system` namespace:

```
gloo:
  settings:
    disableKubernetesDestinations: true
  discovery:
    enabled: true
  gateway:
    persistProxySpec: true
    readGatewaysFromAllNamespaces: true
  gatewayProxies:      
    gatewayProxy:
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: default
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: default
    publicGw:
      namespace: gloo-external
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      kind:
        deployment:
          replicas: 1
      service:
        httpPort: 81
        httpsFirst: true
        httpsPort: 444
        type: LoadBalancer
      tcpKeepaliveTimeSeconds: 5
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: public
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: public
    corpGw:
      namespace: gloo-internal
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      kind:
        deployment:
          replicas: 1
      service:
        httpPort: 8080
        httpsFirst: true
        httpsPort: 8443
        type: LoadBalancer
      tcpKeepaliveTimeSeconds: 5
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: private
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: private
```
<img width="1310" alt="Screenshot 2024-04-16 at 20 03 45" src="https://github.com/solo-io/gloo/assets/875822/2de37bde-4597-466e-bdd2-3277b5e3ca28">

When you deploy all 3 gateway-proxies in the `gloo-system` namespace, the UI will see all of them:

```
gloo:
  settings:
    disableKubernetesDestinations: true
  discovery:
    enabled: true
  gateway:
    persistProxySpec: true
    readGatewaysFromAllNamespaces: true
  gatewayProxies:      
    gatewayProxy:
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: default
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: default
    publicGw:
      # namespace: gloo-external
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      kind:
        deployment:
          replicas: 1
      service:
        httpPort: 81
        httpsFirst: true
        httpsPort: 444
        type: LoadBalancer
      tcpKeepaliveTimeSeconds: 5
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: public
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: public
    corpGw:
      # namespace: gloo-internal
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      kind:
        deployment:
          replicas: 1
      service:
        httpPort: 8080
        httpsFirst: true
        httpsPort: 8443
        type: LoadBalancer
      tcpKeepaliveTimeSeconds: 5
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: private
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: private
```
<img width="1307" alt="Screenshot 2024-04-16 at 19 40 39" src="https://github.com/solo-io/gloo/assets/875822/093d7b5e-5f73-451e-8a41-bdc3fb482a3e">

When you change the `writeNamespace` of GE to another namespace than `gloo-system`, the `Proxy` CRs get written to a namespace that is different from `gloo-system`.  The dataplane works fine, but the UI can't see any Envoy config with this setting.

```
gloo:
  settings:
    disableKubernetesDestinations: true
    writeNamespace: gloo-external
  discovery:
    enabled: true
  gateway:
    persistProxySpec: true
    readGatewaysFromAllNamespaces: true
  gatewayProxies:      
    gatewayProxy:
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: default
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: default
    publicGw:
      # namespace: gloo-external
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      kind:
        deployment:
          replicas: 1
      service:
        httpPort: 81
        httpsFirst: true
        httpsPort: 444
        type: LoadBalancer
      tcpKeepaliveTimeSeconds: 5
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: public
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: public
    corpGw:
      # namespace: gloo-internal
      disabled: false
      readConfig: true
      readConfigMulticluster: true
      kind:
        deployment:
          replicas: 1
      service:
        httpPort: 8080
        httpsFirst: true
        httpsPort: 8443
        type: LoadBalancer
      tcpKeepaliveTimeSeconds: 5
      gatewaySettings:
        customHttpGateway:
          virtualServiceSelector:
            gateway-type: private
        customHttpsGateway:
          virtualServiceSelector:
            gateway-type: private
```

<img width="1317" alt="Screenshot 2024-04-16 at 19 52 47" src="https://github.com/solo-io/gloo/assets/875822/1fbac2a5-b1ed-4f37-9e3b-d330fee7f4b2">

### Expected Behavior

GE UI is able to display the Envoy configuration of all my gateway-proxies, regardless of the namespace they are deployed in.

### Steps to reproduce the bug

Use the Helm values provided in the description to deploy the different scenarios.
