### ISSUE TITLE
"conflicting matcher" message for VS 

### ISSUE THREAD

**Issue by htech7x** [solo-io/gloo#9462]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.8

### Kubernetes Version

1.28.5

### Describe the bug

After creating VS,  "gloo check" complains about  "conflicting matcher"

```
glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... 1 Errors!
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
Error: 1 error occurred:
	* Found virtual service with warnings by 'gloo-system': gloo-portal reproenv (Reason: warning:
  virtual host [gloo-portal.reproenv] has conflicting matcher: regex:"/org/[^/]+?"  methods:"GET"  methods:"OPTIONS"
virtual host [gloo-portal.reproenv] has conflicting matcher: regex:"/org/[^/]+?/children"  methods:"GET"  methods:"OPTIONS"
virtual host [gloo-portal.reproenv] has conflicting matcher: regex:"/org/[^/]+?/parents"  methods:"GET"  methods:"OPTIONS")
```

### Expected Behavior

Validation works as expected

### Steps to reproduce the bug

1. Deploy Gloo EE and Gloo Portal
```
$ helm list -A
NAME       	NAMESPACE  	REVISION	UPDATED                             	STATUS  	CHART            	APP VERSION
gloo       	gloo-system	1       	2024-05-06 12:13:32.154175 -0500 CDT	deployed	gloo-ee-1.16.8
gloo-portal	gloo-portal	1       	2024-05-06 12:15:07.705303 -0500 CDT	deployed	gloo-portal-1.4.0
```
2. Edit settings for Gloo EE
```
   kubectl edit settings default -n gloo-system
   ...
   gateway:
     validation:
       allowWarnings: false                                       # <-- change this line
       alwaysAccept: false                                        # <-- change this line
       disableTransformationValidation: false
       warnRouteShortCircuiting: true                     # <-- change this line
```

3. Create API Doc  according to the [documentation](https://docs.solo.io/gloo-portal/latest/guides/admin_dashboard/create_apidoc/) using the following "swagger.json"
[swagger.json](https://github.com/solo-io/gloo/files/15252418/swagger.json)
4. Create API Product and API Environment according to the [documentation](https://docs.solo.io/gloo-portal/latest/guides/admin_dashboard/create_apiproduct/) 
5. Run "gloo check" and check the message
```
glooctl check
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... 1 Errors!
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
Error: 1 error occurred:
	* Found virtual service with warnings by 'gloo-system': gloo-portal reproenv (Reason: warning:
  virtual host [gloo-portal.reproenv] has conflicting matcher: regex:"/org/[^/]+?"  methods:"GET"  methods:"OPTIONS"
virtual host [gloo-portal.reproenv] has conflicting matcher: regex:"/org/[^/]+?/children"  methods:"GET"  methods:"OPTIONS"
virtual host [gloo-portal.reproenv] has conflicting matcher: regex:"/org/[^/]+?/parents"  methods:"GET"  methods:"OPTIONS")
```
