### ISSUE TITLE
Add "Front-Channel Logout" support to Gloo

### ISSUE THREAD

**Issue by htech7x** [solo-io/gloo#9510]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.8

# Context

Gloo Edge currently does not support OIDC [Front Channel Logout](https://openid.net/specs/openid-connect-frontchannel-1_0-final.html), a specification that in an SSO environment that includes multiple applications, allows the user to logout of all these applications by simply logging out of their current SSO session.

In the past, we've advised users to use the `afterLogoutUrl` as a workaround, by implementing the logout functionality of all the applications in an iFrame in that `afterLogoutUrl`. This is very much a "poor man's solution" to a problem for which there is a solution defined in the OIDC specification.

# Requirements

An implementation of the OIDC [Front Channel Logout](https://openid.net/specs/openid-connect-frontchannel-1_0-final.html) specification.

## Job Stories

TODO

### Additional Context

Currently we advise users to use the "afterLogoutUrl" as a workaround since Gloo doesn't support front-channel logout.
Example of using "afterLogoutUrl":

```
apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: oauth
  namespace: gloo-system
spec:
  configs:
  - oauth2:
      oidcAuthorizationCode:
        afterLogoutUrl: https://httpbin.solo.io/prompt
        appUrl: https://httpbin.solo.io
        callbackPath: /callback
        clientId: b036d586-983f-4568-a882-5a9f499aa60e
        clientSecretRef:
          name: oauth
          namespace: gloo-system
        issuerUrl: http://ae6ce2927b9b445a6a84f7cf3a0b5878-122919987.us-east-2.elb.amazonaws.com:8080/auth/realms/master/
        logoutPath: /logout
        scopes:
        - email
        session:
          failOnFetchFailure: true
          redis:
            cookieName: keycloak-session
            options:
              host: redis.gloo-system.svc.cluster.local:6379
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208180411863300) by [Unito](https://www.unito.io)
