### ISSUE TITLE
Headers to add keys are not validated

### ISSUE THREAD

**Issue by davidjumani** [solo-io/gloo#9622]
### Gloo Edge Product

Open Source

### Gloo Edge Version

All

### Kubernetes Version

All

### Describe the bug

`vs.yaml`
```
        headerManipulation:
          requestHeadersToAdd:
          - header:
              key: "head(er)"
              value: random
```

Previously
```
$ kg apply -f vs.yaml 

virtualservice.gateway.solo.io/default created

$ curl localhost:8080/get
invalid header name: head(er)
```

### Expected Behavior

It should not accept invalid header keys

### Steps to reproduce the bug

As above
