### ISSUE TITLE
Gloo Gateway v2 Upstream gives InvalidKind error

### ISSUE THREAD

**Issue by fooeysadly** [solo-io/gloo#9667]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v2.0.0-beta1

### Kubernetes Version

v1.28.10

### Describe the bug

The HTTPRoute with an Upstream does not work with an InvalidKind error.
![Schermafbeelding 2024-06-23 113217](https://github.com/solo-io/gloo/assets/173602197/82021e1d-d2a1-495b-8c9e-b3435f0b1791)

### Expected Behavior

The HTTPRoute should be successfully created.

### Steps to reproduce the bug

- Install the v2.0.0-beta1 version of the gloo gateway
- Perform the Get Started tutorial [link](https://docs.solo.io/gateway/latest/quickstart/)
- Install the CRDs for Upstream
`kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v2.0.x/install/helm/gloo/crds/gateway.solo.io_v1_RouteOption.yaml`
`kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v2.0.x/install/helm/gloo/crds/gloo.solo.io_v1_Upstream.yaml `
`kubectl apply -f https://raw.githubusercontent.com/solo-io/gloo/v2.0.x/install/helm/gloo/crds/gloo.solo.io_v1_UpstreamGroup.yaml`
- Add the Upstream like on the documentation [link](https://docs.solo.io/gateway/latest/traffic-management/destination-types/upstreams/static/)
- Verify the HTTPRoute

**Comment by DuncanDoyle** [comment]
@fooeysadly: Can you share the content of your `HTTPRoute` and the `Upstream` CR you are referencing from that `HTTPRoute`. I'd like to verify your configuration and see if I can reproduce.

**Comment by fooeysadly** [comment]
@DuncanDoyle 
I have a `Gateway` instance from performing this command:
`kubectl -n httpbin apply -f https://raw.githubusercontent.com/solo-io/gloo/v2.0.x/projects/gateway2/examples/httpbin.yaml`

I made this `Upstream`:
```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: httpbin-static
  namespace: httpbin
spec:
  static:
    hosts:
      - addr: jsonplaceholder.typicode.com
        port: 80

```
Then I made this `RouteOption`:
```
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: rewrite
  namespace: httpbin
spec:
  options:
    hostRewrite: 'jsonplaceholder.typicode.com'

```
And I made this `HTTPRoute`:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-static
  namespace: httpbin
spec:
  parentRefs:
  - name: http
    namespace: httpbin
  hostnames:
    - "static.example"
  rules:
    - backendRefs:
      - name: json-upstream
        kind: Upstream
        group: gloo.solo.io
      filters:
      - type: ExtensionRef
        extensionRef:
          group: gateway.solo.io
          kind: RouteOption
          name: rewrite

```
