### ISSUE TITLE
No way to expose metrics endpoint's port from Helm variables

### ISSUE THREAD

**Issue by luismiguelsaez-steercrm** [solo-io/gloo#9711]
### Gloo Edge Product

Open Source

### Gloo Edge Version

v1.17.0-rc8

### Is your feature request related to a problem? Please describe.

We want to scrape Prometheus metrics, but there's no way to add the port mapping to the `gateway-proxy` pods. Here is the current `podTemplate` from the Helm values

```yaml
    podTemplate:
      customLivenessProbe: {}
      customReadinessProbe: {}
      disableNetBind: true
      enablePodSecurityContext: true
      fsGroup: 10101
      gracefulShutdown:
        enabled: false
        sleepTimeSeconds: 25
      httpPort: 8080
      httpsPort: 8443
```

Without a proper port specification in the pod, the Prometheus `PodMonitor` or `ServiceMonitor` doesn't work, as it is required.

### Describe the solution you'd like

The solution would be to add the stats port to the `podTemplate`, like this:

```yaml
    podTemplate:
      customLivenessProbe: {}
      customReadinessProbe: {}
      disableNetBind: true
      enablePodSecurityContext: true
      fsGroup: 10101
      gracefulShutdown:
        enabled: false
        sleepTimeSeconds: 25
      httpPort: 8080
      httpsPort: 8443
      statsPort: 19000
```

and add it to the `Pod` specification in the corresponding Helm template, so it is rendered as:

```yaml
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 8443
      name: https
      protocol: TCP
    - containerPort: 19000
      name: stats
```

That way, the port can be referenced from a `PodMonitor` or a `Service`, which later can be used from a `ServiceMonitor`.
