### ISSUE TITLE
Multi-param DestinationSpec for K8S Gateway API HTTPRoutes

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#9712]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.17.0

### Is your feature request related to a problem? Please describe.

# Context

In our current implementation to support function parameters for Function Upstreams in K8S Gateway API, we use an ExtensionRef to a virtual `Parameter` resource to pass in, for example, the logical name of the Lambda function to call. See [this GitHub issue comment](https://github.com/solo-io/solo-projects/issues/6160#issuecomment-2161397367), which contains the following example:

```
backendRefs:
    - name: lambda
      namespace: gloo-system
      group: gloo.solo.io
      kind: Upstream
      filters:
        - type: ExtensionRef
          extensionRef:
            group: "gloo.solo.io"
            kind: Parameter
            name: echo
```

Since this is an unnamed parament, we only support on Function Upstream parameter to be specified. There are however `destinationSpec` in the Gloo Edge API that support multiple parameters: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk/#destinationspec

The `aws` `destinationSpec` for example supports fiels like `wrapAsApiGateway`, `unwrapAsApiGateway`, `invocationStyle`, etc.: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/aws/aws.proto.sk/

With the current K8S Gateway API implementation, we can't/don't support these additional parameters.

# Requirement

Provide support for multiple `destinationSpec` parameters in the K8S Gateway API for Function Upstreams. We must support these parameters for the following Function Upstream (https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk/#destinationspec):
- aws
- azure
- rest

Since the `grpc destinationSpec` is deprecated (see: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options/grpc/grpc.proto.sk/#destinationspec), we should not add support for it in our K8S Gateway API implementation.

**Comment by nrjpoddar** [comment]
@sam-heilbron to look at this issue for scope/estimation.

**Comment by DuncanDoyle** [comment]
It seems that you can use `destinationOverrides` on the `Upstream` to add additional configuration logic, at least for AWS Lambda Upstream, in a K8S Gatewat API use-case. I.e. with the following `HttpRoute`:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: lambda-example-com-route
  namespace: default
  labels:
    app: apis
spec:
  parentRefs:
    - name: gw
      namespace: ingress-gw
  hostnames:
    - "lambda.example.com"
  rules:
    - matches:  
      - path:
          type: Exact
          value: /
      backendRefs:
      - name: my-aws-lambda-upstream
        namespace: gloo-system
        group: gloo.solo.io
        kind: Upstream
        filters:
        - type: ExtensionRef
          extensionRef:
            group: "gloo.solo.io"
            kind: Parameter
            name: QuarkusLambdaDdoyle
````

I can set the `unwrapAsApiGateway` parameter as follows on the `Upstream`:

```
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: my-aws-lambda-upstream
  namespace: gloo-system
spec:
  aws:
    region: eu-central-1
    secretRef:
      name: aws-creds
      namespace: gloo-system
    destinationOverrides:
      unwrapAsApiGateway: true
```

So there seems to be somewhat of a workaround to support these additional parameters for AWS Lambda Upstreams, but the UX is questionable (in particular because we are defining that we're overriding a `destinationSpec` that does not really exist.
