### ISSUE TITLE
ApiProduct image in DevPortal UI configurable via ApiProduct metadata

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#9729]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.17

### Is your feature request related to a problem? Please describe.

In the current DevPortal Starter UI, the image we show for ApiProducts is always a plate of tacos. Although tacos are nice and delicious, it would be good if can make this image configurable via the metadata of an ApiProduct.

The `ApiProduct` CR allows us to specify `customMetadata`. We should add support to DevPortal UI to fetch a URL from the `customMetadata.image` field and display the image that that URL points to in the UI.

Here is an example of an `ApiProduct` with such a `customMetadata.image` field:

```
apiVersion: portal.gloo.solo.io/v1
kind: ApiProduct
metadata:
  name: pets-api-product
  namespace: pets
spec:
  id: pets-tracks
  displayName: "Pets + Tracks (MultiRoute)"
  customMetadata:
      image: <url>
  versions:
    - apiVersion: v1
      targetRefs:
        - name: pets-route
          namespace: pets
          group: gateway.networking.k8s.io
          kind: HTTPRoute
      openapiMetadata:
          title:  "openapi spec title"
      customMetadata:
          phase: supported
          type: multi
```

### Describe the solution you'd like

Allow users to specify an image URL in the `customMetadata.image` field, and show that image as the ApiProduct's image in the DevPortal UI.

### Describe alternatives you've considered

n.a

### Additional Context

n.a.

**Comment by Charlesthebird** [comment]
I opened a duplicate issue [here](https://github.com/solo-io/gloo-mesh-enterprise/issues/17623#issuecomment-2218481451), which is resolved now (in https://github.com/solo-io/dev-portal-starter/pull/74). The image with this update is: `gcr.io/solo-public/docs/portal-frontend:v0.0.29`. 


I used the following `APIProduct` to test out the `imageURL` property (the linked issue and PR includes some more info):

```yaml
apiVersion: portal.gloo.solo.io/v1
kind: ApiProduct
metadata:
  labels:
    app: pets-rest-api
  name: pets-api-product
  namespace: petstore
spec:
  customMetadata:
    imageURL: https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg
  displayName: Petstore API
  id: pets
  versions:
  - apiVersion: v1
    customMetadata:
      imageURL: https://cdn.create.vista.com/api/media/medium/212586574/stock-photo-cat-dog-lying-plaid-sofa
    openapiMetadata:
      title: openapi spec title
    targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: petstore-api
      namespace: petstore
```
