### ISSUE TITLE
Custom metadata display and filtering support in Dev Portal UI

### ISSUE THREAD

**Issue by DuncanDoyle** [solo-io/gloo#9730]
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.17

### Is your feature request related to a problem? Please describe.

The `ApiProduct` CR of our Portal allows us to specify "custom metadata" on the ApiProduct and version levels. See example CR below:

```
apiVersion: portal.gloo.solo.io/v1
kind: ApiProduct
metadata:
  name: pets-tracks-multi-route-api-product
  namespace: pets-tracks
spec:
  id: pets-tracks
  displayName: "Pets + Tracks (MultiRoute)"
  customMetadata:
      image: <url>
  versions:
    - apiVersion: v1
      targetRefs:
        - name: pets-route
          namespace: pets
          group: gateway.networking.k8s.io
          kind: HTTPRoute
        - name: tracks-route
          namespace: tracks
          group: gateway.networking.k8s.io
          kind: HTTPRoute
      openapiMetadata:
          title:  "openapi spec title"
      customMetadata:
          phase: supported
          type: multi
    - apiVersion: v2
      targetRefs:
        - name: pets-route-2
          namespace: pets
          group: gateway.networking.k8s.io
          kind: HTTPRoute
      customMetadata:
          phase: supported
          type: multi
```

Currently, the Dev Portal UI does neither display this metadata, nor provide any filtering capabilities on this metadata.

### Describe the solution you'd like

Dev Portal UI should display the ApiProduct's "custom metadata", so this information is available for end users consumption. This allows ApiProduct owners to provide additional data and information about the ApiProduct to the API clients and consumers.

Second, the Dev Portal UI should provide filtering capabilities for this metadata, so the metadata information can be used to filter the ApiProducts that the end user, clients and consumers are interested in.

### Describe alternatives you've considered

n.a.

### Additional Context

n.a.
