### ISSUE TITLE
Missing include in gateway- proxy yaml

### ISSUE THREAD

**Issue by AlfredoFausto** [solo-io/gloo#9731]
### Gloo Edge Product

Enterprise

### Gloo Edge Version

1.16.9

### Kubernetes Version

1.27

### Describe the bug

Trying to configure the priorityClassName with helm values didn't reflect the changes in the chart.
Example: 

This is the values file used
```

gloo:
  gatewayProxies:
    gatewayProxy:
      kind:
        deployment:
          kubeResourceOverride:
            spec:
              template:
                spec:
                  priorityClassName:

```
The docs specify how should used:
gloo.gatewayProxies.gatewayProxy.kind.deployment.kubeResourceOverride.NAME
https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/enterprise_helm_chart_values/#helm-chart-kuberesourceoverrides

In the helpers, we should have 
```
https://github.com/solo-io/gloo/blob/ed1dbf08542b51888cbb66a7f134dad8be94b05c/install/helm/gloo/templates/_helpers.tpl#L68

{{- define "gloo.podSpecStandardFields" -}}

```
But this include is missing in the template install/helm/gloo/templates/7-gateway-proxy-deployment.yaml

### Expected Behavior

I would expect using the values we have in the docs should work as-is.
Delete the include was removed by accident or deprecation without notice.

### Steps to reproduce the bug

Template the chart with the values file above and a verify the rendered yaml

### Additional Environment Detail

Kind 1.27
Helm 3.15.1
Gloo we 1.16.9
