### ISSUE TITLE
overriding ingress image registry overrides gloo's as well

### ISSUE THREAD

**Issue by ilackarms** [solo-io/gloo#988]
when using `values.yaml` to override the image regsitry for an individual deployment (seem with `ingress`) seems to override that of `gloo`.

steps to reproduce:

using values file:

```yaml
crds:
  create: true
discovery:
  fdsMode: WHITELIST
gateway:
  enabled: false
ingress:
  deployment:
    image:
      registry: docker.io/ilackarms
      repository: ingress
      tag: test-ilackarms
#      repository: quay.io/solo-io/ingress
#      tag: 0.18.9
      pullPolicy: Always
    replicas: 1
    stats: false
  enabled: false
k8s:
  clusterName: cluster.local
namespace:
  create: true
rbac:
  create: true
settings:
  create: true
  integrations:
    knative:
      enabled: true
      version: 0.8.0
      installKnative: true
      proxy:
        httpPort: "80"
        httpsPort: "443"
        image:
          pullPolicy: Always
          registry: quay.io/solo-io
          repository: gloo-envoy-wrapper
          tag: 0.18.9
        replicas: 1
        stats: true
global:
  pullPolicy: Always
```

run:

```
make GCLOUD_PROJECT_ID=solo-public BUILD_ID=ilackarms clean build-test-assets
helm template _test/gloo-test-ilackarms.tgz -f value-overrides.yaml --namespace gloo-system
```

produces:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gloo
  name: gloo
  namespace: gloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: gloo
  template:
    metadata:
      labels:
        gloo: gloo
    spec:
      containers:
      - image: docker.io/ilackarms/gloo:test-ilackarms
        imagePullPolicy: Always
```

where
`spec.containers.image` is expected equal `gcr.io/solo-gloo-knative-e2e/gloo:test-ilackarms`

this bug was not seen with the `discovery` deployment's image
